git clone iluwatar/java-design-patterns
git clone reactivex/rxjava
git clone elastic/elasticsearch
git clone square/retrofit
git clone square/okhttp
git clone spring-projects/spring-boot
git clone google/guava
git clone kdn251/interviews
git clone philjay/mpandroidchart
git clone bumptech/glide
git clone spring-projects/spring-framework
git clone airbnb/lottie-android
git clone jakewharton/butterknife
git clone apache/incubator-dubbo
git clone square/leakcanary
git clone zxing/zxing
git clone Blankj/AndroidUtilCode
git clone greenrobot/EventBus
git clone ReactiveX/RxAndroid
git clone nostra13/Android-Universal-Image-Loader
git clone square/picasso
git clone google/iosched
git clone skylot/jadx
git clone netty/netty
git clone facebook/fresco
git clone alibaba/fastjson
git clone CymChad/BaseRecyclerViewAdapterHelper
git clone Netflix/Hystrix
git clone libgdx/libgdx
git clone afollestad/material-dialogs
