cd butterknife ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd Android-CleanArchitecture ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd Luban ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd zheng ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd glide ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd SlidingMenu ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd HomeMirror ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd Java-Interview ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd CircleImageView ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd retrofit ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd Android-PickerView ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd material-dialogs ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd guava ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd cheesesquare ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd Android-PullToRefresh ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd incubator-dubbo ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd HikariCP ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd fresco ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd MaterialViewPager ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd proxyee-down ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd storm ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd java8-tutorial ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd AndroidUtilCode ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd zxing ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd RxAndroid ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd vert.x ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd logger ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd leakcanary ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd Calligraphy ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd tinker ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd RxBinding ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd MaterialDrawer ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd Material-Animations ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd spring-boot ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd Android-ObservableScrollView ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd HanLP ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd disruptor ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd plaid ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd Android-Universal-Image-Loader ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd kafka ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd PermissionsDispatcher ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd interviews ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd deeplearning4j ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd Signal-Android ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd uCrop ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd SmartRefreshLayout ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd android-async-http ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd netty ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd stetho ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd libgdx ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd EventBus ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd iosched ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd selenium ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd fastjson ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd incubator-weex ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd FizzBuzzEnterpriseEdition ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd ExoPlayer ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd AndroidViewAnimations ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd react-native-navigation ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd recyclerview-animators ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd java-design-patterns ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd Telegram ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd bytecode-viewer ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd PocketHub ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd AndroidSlidingUpPanel ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd PhotoView ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd druid ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd AVLoadingIndicatorView ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd jenkins ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd lottie-android ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd RxJava ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd jadx ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd androidannotations ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd zipkin ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd bazel ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd okhttp ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd okhttp-OkGo ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd mybatis-3 ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd VasSonic ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd platform_frameworks_base ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd MaterialDesignLibrary ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd greenDAO ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd presto ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd BaseRecyclerViewAdapterHelper ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd MPAndroidChart ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd gson ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd Matisse ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd spark ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd elasticsearch ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd spring-framework ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd vlayout ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd hadoop ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd BottomBar ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd realm-java ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd Hystrix ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd AndroidSwipeLayout ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd ViewPagerIndicator ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd AppIntro ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd android-Ultra-Pull-To-Refresh ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
cd picasso ;git fetch origin '+refs/pull/*/head:refs/pull/*';cd ../
