./get_msg.sh repo100/java-design-patterns > corpus/iluwatar/java-design-patterns/hash_msg.txt
./get_msg.sh repo100/RxJava > corpus/ReactiveX/RxJava/hash_msg.txt
./get_msg.sh repo100/elasticsearch > corpus/elastic/elasticsearch/hash_msg.txt
./get_msg.sh repo100/retrofit > corpus/square/retrofit/hash_msg.txt
./get_msg.sh repo100/okhttp > corpus/square/okhttp/hash_msg.txt
./get_msg.sh repo100/spring-boot > corpus/spring-projects/spring-boot/hash_msg.txt
./get_msg.sh repo100/guava > corpus/google/guava/hash_msg.txt
./get_msg.sh repo100/interviews > corpus/kdn251/interviews/hash_msg.txt
./get_msg.sh repo100/MPAndroidChart > corpus/PhilJay/MPAndroidChart/hash_msg.txt
./get_msg.sh repo100/glide > corpus/bumptech/glide/hash_msg.txt
./get_msg.sh repo100/spring-framework > corpus/spring-projects/spring-framework/hash_msg.txt
./get_msg.sh repo100/lottie-android > corpus/airbnb/lottie-android/hash_msg.txt
./get_msg.sh repo100/butterknife > corpus/JakeWharton/butterknife/hash_msg.txt
./get_msg.sh repo100/incubator-dubbo > corpus/apache/incubator-dubbo/hash_msg.txt
./get_msg.sh repo100/leakcanary > corpus/square/leakcanary/hash_msg.txt
./get_msg.sh repo100/zxing > corpus/zxing/zxing/hash_msg.txt
./get_msg.sh repo100/AndroidUtilCode > corpus/Blankj/AndroidUtilCode/hash_msg.txt
./get_msg.sh repo100/EventBus > corpus/greenrobot/EventBus/hash_msg.txt
./get_msg.sh repo100/RxAndroid > corpus/ReactiveX/RxAndroid/hash_msg.txt
./get_msg.sh repo100/Android-Universal-Image-Loader > corpus/nostra13/Android-Universal-Image-Loader/hash_msg.txt
./get_msg.sh repo100/picasso > corpus/square/picasso/hash_msg.txt
./get_msg.sh repo100/iosched > corpus/google/iosched/hash_msg.txt
./get_msg.sh repo100/jadx > corpus/skylot/jadx/hash_msg.txt
./get_msg.sh repo100/netty > corpus/netty/netty/hash_msg.txt
./get_msg.sh repo100/fresco > corpus/facebook/fresco/hash_msg.txt
./get_msg.sh repo100/fastjson > corpus/alibaba/fastjson/hash_msg.txt
./get_msg.sh repo100/BaseRecyclerViewAdapterHelper > corpus/CymChad/BaseRecyclerViewAdapterHelper/hash_msg.txt
./get_msg.sh repo100/Hystrix > corpus/Netflix/Hystrix/hash_msg.txt
./get_msg.sh repo100/libgdx > corpus/libgdx/libgdx/hash_msg.txt
./get_msg.sh repo100/material-dialogs > corpus/afollestad/material-dialogs/hash_msg.txt
./get_msg.sh repo100/PhotoView > corpus/chrisbanes/PhotoView/hash_msg.txt
./get_msg.sh repo100/SmartRefreshLayout > corpus/scwang90/SmartRefreshLayout/hash_msg.txt
./get_msg.sh repo100/gson > corpus/google/gson/hash_msg.txt
./get_msg.sh repo100/druid > corpus/alibaba/druid/hash_msg.txt
./get_msg.sh repo100/tinker > corpus/Tencent/tinker/hash_msg.txt
./get_msg.sh repo100/proxyee-down > corpus/proxyee-down-org/proxyee-down/hash_msg.txt
./get_msg.sh repo100/Android-CleanArchitecture > corpus/android10/Android-CleanArchitecture/hash_msg.txt
./get_msg.sh repo100/Material-Animations > corpus/lgvalle/Material-Animations/hash_msg.txt
./get_msg.sh repo100/plaid > corpus/nickbutcher/plaid/hash_msg.txt
./get_msg.sh repo100/selenium > corpus/SeleniumHQ/selenium/hash_msg.txt
./get_msg.sh repo100/SlidingMenu > corpus/jfeinstein10/SlidingMenu/hash_msg.txt
./get_msg.sh repo100/zheng > corpus/shuzheng/zheng/hash_msg.txt
./get_msg.sh repo100/jenkins > corpus/jenkinsci/jenkins/hash_msg.txt
./get_msg.sh repo100/ExoPlayer > corpus/google/ExoPlayer/hash_msg.txt
./get_msg.sh repo100/androidannotations > corpus/androidannotations/androidannotations/hash_msg.txt
./get_msg.sh repo100/greenDAO > corpus/greenrobot/greenDAO/hash_msg.txt
./get_msg.sh repo100/AndroidSwipeLayout > corpus/daimajia/AndroidSwipeLayout/hash_msg.txt
./get_msg.sh repo100/android-async-http > corpus/loopj/android-async-http/hash_msg.txt
./get_msg.sh repo100/Telegram > corpus/DrKLO/Telegram/hash_msg.txt
./get_msg.sh repo100/CircleImageView > corpus/hdodenhof/CircleImageView/hash_msg.txt
./get_msg.sh repo100/incubator-weex > corpus/apache/incubator-weex/hash_msg.txt
./get_msg.sh repo100/stetho > corpus/facebook/stetho/hash_msg.txt
./get_msg.sh repo100/Signal-Android > corpus/signalapp/Signal-Android/hash_msg.txt
./get_msg.sh repo100/ViewPagerIndicator > corpus/JakeWharton/ViewPagerIndicator/hash_msg.txt
./get_msg.sh repo100/realm-java > corpus/realm/realm-java/hash_msg.txt
./get_msg.sh repo100/AndroidViewAnimations > corpus/daimajia/AndroidViewAnimations/hash_msg.txt
./get_msg.sh repo100/java8-tutorial > corpus/winterbe/java8-tutorial/hash_msg.txt
./get_msg.sh repo100/bazel > corpus/bazelbuild/bazel/hash_msg.txt
./get_msg.sh repo100/logger > corpus/orhanobut/logger/hash_msg.txt
./get_msg.sh repo100/bytecode-viewer > corpus/Konloch/bytecode-viewer/hash_msg.txt
./get_msg.sh repo100/MaterialDrawer > corpus/mikepenz/MaterialDrawer/hash_msg.txt
./get_msg.sh repo100/FizzBuzzEnterpriseEdition > corpus/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/hash_msg.txt
./get_msg.sh repo100/deeplearning4j > corpus/deeplearning4j/deeplearning4j/hash_msg.txt
./get_msg.sh repo100/PocketHub > corpus/pockethub/PocketHub/hash_msg.txt
./get_msg.sh repo100/android-Ultra-Pull-To-Refresh > corpus/liaohuqiu/android-Ultra-Pull-To-Refresh/hash_msg.txt
./get_msg.sh repo100/zipkin > corpus/openzipkin/zipkin/hash_msg.txt
./get_msg.sh repo100/storm > corpus/nathanmarz/storm/hash_msg.txt
./get_msg.sh repo100/kafka > corpus/apache/kafka/hash_msg.txt
./get_msg.sh repo100/Android-ObservableScrollView > corpus/ksoichiro/Android-ObservableScrollView/hash_msg.txt
./get_msg.sh repo100/MaterialDesignLibrary > corpus/navasmdc/MaterialDesignLibrary/hash_msg.txt
./get_msg.sh repo100/Android-PullToRefresh > corpus/chrisbanes/Android-PullToRefresh/hash_msg.txt
./get_msg.sh repo100/vlayout > corpus/alibaba/vlayout/hash_msg.txt
./get_msg.sh repo100/recyclerview-animators > corpus/wasabeef/recyclerview-animators/hash_msg.txt
./get_msg.sh repo100/VasSonic > corpus/Tencent/VasSonic/hash_msg.txt
./get_msg.sh repo100/vert.x > corpus/eclipse/vert.x/hash_msg.txt
./get_msg.sh repo100/HanLP > corpus/hankcs/HanLP/hash_msg.txt
./get_msg.sh repo100/react-native-navigation > corpus/wix/react-native-navigation/hash_msg.txt
./get_msg.sh repo100/disruptor > corpus/LMAX-Exchange/disruptor/hash_msg.txt
./get_msg.sh repo100/Luban > corpus/Curzibn/Luban/hash_msg.txt
./get_msg.sh repo100/mybatis-3 > corpus/mybatis/mybatis-3/hash_msg.txt
./get_msg.sh repo100/Java-Interview > corpus/crossoverJie/Java-Interview/hash_msg.txt
./get_msg.sh repo100/BottomBar > corpus/roughike/BottomBar/hash_msg.txt
./get_msg.sh repo100/okhttp-OkGo > corpus/jeasonlzy/okhttp-OkGo/hash_msg.txt
./get_msg.sh repo100/Android-PickerView > corpus/Bigkoo/Android-PickerView/hash_msg.txt
./get_msg.sh repo100/AppIntro > corpus/apl-devs/AppIntro/hash_msg.txt
./get_msg.sh repo100/Calligraphy > corpus/chrisjenx/Calligraphy/hash_msg.txt
./get_msg.sh repo100/presto > corpus/prestodb/presto/hash_msg.txt
./get_msg.sh repo100/HomeMirror > corpus/HannahMitt/HomeMirror/hash_msg.txt
./get_msg.sh repo100/AndroidSlidingUpPanel > corpus/umano/AndroidSlidingUpPanel/hash_msg.txt
./get_msg.sh repo100/platform_frameworks_base > corpus/aosp-mirror/platform_frameworks_base/hash_msg.txt
./get_msg.sh repo100/RxBinding > corpus/JakeWharton/RxBinding/hash_msg.txt
./get_msg.sh repo100/hadoop > corpus/apache/hadoop/hash_msg.txt
./get_msg.sh repo100/AVLoadingIndicatorView > corpus/81813780/AVLoadingIndicatorView/hash_msg.txt
./get_msg.sh repo100/PermissionsDispatcher > corpus/permissions-dispatcher/PermissionsDispatcher/hash_msg.txt
./get_msg.sh repo100/spark > corpus/perwendel/spark/hash_msg.txt
./get_msg.sh repo100/cheesesquare > corpus/chrisbanes/cheesesquare/hash_msg.txt
./get_msg.sh repo100/MaterialViewPager > corpus/florent37/MaterialViewPager/hash_msg.txt
./get_msg.sh repo100/Matisse > corpus/zhihu/Matisse/hash_msg.txt
./get_msg.sh repo100/HikariCP > corpus/brettwooldridge/HikariCP/hash_msg.txt
./get_msg.sh repo100/uCrop > corpus/Yalantis/uCrop/hash_msg.txt
