./get_issue_list.py chrisjenx/Calligraphy > corpus/chrisjenx/Calligraphy/api.json
./get_issue_list.py vondear/RxTool > corpus/vondear/RxTool/api.json
./get_issue_list.py mockito/mockito > corpus/mockito/mockito/api.json
./get_issue_list.py perwendel/spark > corpus/perwendel/spark/api.json
./get_issue_list.py Yalantis/uCrop > corpus/Yalantis/uCrop/api.json
./get_issue_list.py HannahMitt/HomeMirror > corpus/HannahMitt/HomeMirror/api.json
./get_issue_list.py YoKeyword/Fragmentation > corpus/YoKeyword/Fragmentation/api.json
./get_issue_list.py H07000223/FlycoTabLayout > corpus/H07000223/FlycoTabLayout/api.json
./get_issue_list.py florent37/MaterialViewPager > corpus/florent37/MaterialViewPager/api.json
./get_issue_list.py lingochamp/FileDownloader > corpus/lingochamp/FileDownloader/api.json
./get_issue_list.py naver/pinpoint > corpus/naver/pinpoint/api.json
./get_issue_list.py chrisbanes/cheesesquare > corpus/chrisbanes/cheesesquare/api.json
./get_issue_list.py tbruyelle/RxPermissions > corpus/tbruyelle/RxPermissions/api.json
./get_issue_list.py Freelander/Android_Data > corpus/Freelander/Android_Data/api.json
./get_issue_list.py clojure/clojure > corpus/clojure/clojure/api.json
./get_issue_list.py google/guice > corpus/google/guice/api.json
./get_issue_list.py youth5201314/banner > corpus/youth5201314/banner/api.json
./get_issue_list.py Bilibili/DanmakuFlameMaster > corpus/Bilibili/DanmakuFlameMaster/api.json
./get_issue_list.py xetorthio/jedis > corpus/xetorthio/jedis/api.json
./get_issue_list.py code4craft/webmagic > corpus/code4craft/webmagic/api.json
./get_issue_list.py apache/incubator-druid > corpus/apache/incubator-druid/api.json
./get_issue_list.py JeffLi1993/springboot-learning-example > corpus/JeffLi1993/springboot-learning-example/api.json
./get_issue_list.py google/agera > corpus/google/agera/api.json
./get_issue_list.py JakeWharton/ActionBarSherlock > corpus/JakeWharton/ActionBarSherlock/api.json
./get_issue_list.py google/auto > corpus/google/auto/api.json
./get_issue_list.py junit-team/junit4 > corpus/junit-team/junit4/api.json
./get_issue_list.py oracle/graal > corpus/oracle/graal/api.json
./get_issue_list.py iBotPeaches/Apktool > corpus/iBotPeaches/Apktool/api.json
./get_issue_list.py JessYanCoding/MVPArms > corpus/JessYanCoding/MVPArms/api.json
./get_issue_list.py redisson/redisson > corpus/redisson/redisson/api.json
./get_issue_list.py wasabeef/glide-transformations > corpus/wasabeef/glide-transformations/api.json
./get_issue_list.py rzwitserloot/lombok > corpus/rzwitserloot/lombok/api.json
./get_issue_list.py square/dagger > corpus/square/dagger/api.json
./get_issue_list.py dropwizard/dropwizard > corpus/dropwizard/dropwizard/api.json
./get_issue_list.py Netflix/SimianArmy > corpus/Netflix/SimianArmy/api.json
./get_issue_list.py alibaba/arthas > corpus/alibaba/arthas/api.json
./get_issue_list.py cymcsg/UltimateRecyclerView > corpus/cymcsg/UltimateRecyclerView/api.json
./get_issue_list.py Bearded-Hen/Android-Bootstrap > corpus/Bearded-Hen/Android-Bootstrap/api.json
./get_issue_list.py koral--/android-gif-drawable > corpus/koral--/android-gif-drawable/api.json
./get_issue_list.py ityouknow/spring-boot-examples > corpus/ityouknow/spring-boot-examples/api.json
./get_issue_list.py kaushikgopal/RxJava-Android-Samples > corpus/kaushikgopal/RxJava-Android-Samples/api.json
./get_issue_list.py Netflix/eureka > corpus/Netflix/eureka/api.json
./get_issue_list.py dbeaver/dbeaver > corpus/dbeaver/dbeaver/api.json
./get_issue_list.py google/tink > corpus/google/tink/api.json
./get_issue_list.py googlesamples/easypermissions > corpus/googlesamples/easypermissions/api.json
./get_issue_list.py astuetz/PagerSlidingTabStrip > corpus/astuetz/PagerSlidingTabStrip/api.json
./get_issue_list.py alibaba/canal > corpus/alibaba/canal/api.json
./get_issue_list.py alibaba/atlas > corpus/alibaba/atlas/api.json
./get_issue_list.py jhy/jsoup > corpus/jhy/jsoup/api.json
./get_issue_list.py laobie/StatusBarUtil > corpus/laobie/StatusBarUtil/api.json
./get_issue_list.py ChrisRM/material-theme-jetbrains > corpus/ChrisRM/material-theme-jetbrains/api.json
./get_issue_list.py Netflix/zuul > corpus/Netflix/zuul/api.json
./get_issue_list.py GcsSloop/AndroidNote > corpus/GcsSloop/AndroidNote/api.json
./get_issue_list.py hongyangAndroid/okhttputils > corpus/hongyangAndroid/okhttputils/api.json
./get_issue_list.py hongyangAndroid/AndroidAutoLayout > corpus/hongyangAndroid/AndroidAutoLayout/api.json
./get_issue_list.py aritraroy/UltimateAndroidReference > corpus/aritraroy/UltimateAndroidReference/api.json
./get_issue_list.py didi/VirtualAPK > corpus/didi/VirtualAPK/api.json
./get_issue_list.py JakeWharton/hugo > corpus/JakeWharton/hugo/api.json
./get_issue_list.py trello/RxLifecycle > corpus/trello/RxLifecycle/api.json
./get_issue_list.py react-native-community/react-native-camera > corpus/react-native-community/react-native-camera/api.json
./get_issue_list.py JakeWharton/timber > corpus/JakeWharton/timber/api.json
./get_issue_list.py geeeeeeeeek/WeChatLuckyMoney > corpus/geeeeeeeeek/WeChatLuckyMoney/api.json
./get_issue_list.py facebook/buck > corpus/facebook/buck/api.json
./get_issue_list.py pedant/sweet-alert-dialog > corpus/pedant/sweet-alert-dialog/api.json
./get_issue_list.py lecho/hellocharts-android > corpus/lecho/hellocharts-android/api.json
./get_issue_list.py square/javapoet > corpus/square/javapoet/api.json
./get_issue_list.py dropwizard/metrics > corpus/dropwizard/metrics/api.json
./get_issue_list.py xuxueli/xxl-job > corpus/xuxueli/xxl-job/api.json
./get_issue_list.py google/physical-web > corpus/google/physical-web/api.json
./get_issue_list.py sharding-sphere/sharding-sphere > corpus/sharding-sphere/sharding-sphere/api.json
./get_issue_list.py apache/rocketmq > corpus/apache/rocketmq/api.json
./get_issue_list.py daniulive/SmarterStreaming > corpus/daniulive/SmarterStreaming/api.json
./get_issue_list.py codecentric/spring-boot-admin > corpus/codecentric/spring-boot-admin/api.json
./get_issue_list.py DroidPluginTeam/DroidPlugin > corpus/DroidPluginTeam/DroidPlugin/api.json
./get_issue_list.py googlesamples/android-testing > corpus/googlesamples/android-testing/api.json
./get_issue_list.py mission-peace/interview > corpus/mission-peace/interview/api.json
./get_issue_list.py QMUI/QMUI_Android > corpus/QMUI/QMUI_Android/api.json
./get_issue_list.py koush/ion > corpus/koush/ion/api.json
./get_issue_list.py pedrovgs/EffectiveAndroidUI > corpus/pedrovgs/EffectiveAndroidUI/api.json
./get_issue_list.py pagehelper/Mybatis-PageHelper > corpus/pagehelper/Mybatis-PageHelper/api.json
./get_issue_list.py futuresimple/android-floating-action-button > corpus/futuresimple/android-floating-action-button/api.json
./get_issue_list.py nhaarman/ListViewAnimations > corpus/nhaarman/ListViewAnimations/api.json
./get_issue_list.py rey5137/material > corpus/rey5137/material/api.json
./get_issue_list.py medcl/elasticsearch-analysis-ik > corpus/medcl/elasticsearch-analysis-ik/api.json
./get_issue_list.py LitePalFramework/LitePal > corpus/LitePalFramework/LitePal/api.json
./get_issue_list.py material-components/material-components-android > corpus/material-components/material-components-android/api.json
./get_issue_list.py cats-oss/android-gpuimage > corpus/cats-oss/android-gpuimage/api.json
./get_issue_list.py stanfordnlp/CoreNLP > corpus/stanfordnlp/CoreNLP/api.json
./get_issue_list.py JakeWharton/u2020 > corpus/JakeWharton/u2020/api.json
./get_issue_list.py antoniolg/androidmvp > corpus/antoniolg/androidmvp/api.json
./get_issue_list.py singwhatiwanna/dynamic-load-apk > corpus/singwhatiwanna/dynamic-load-apk/api.json
./get_issue_list.py ybq/Android-SpinKit > corpus/ybq/Android-SpinKit/api.json
./get_issue_list.py facebook/litho > corpus/facebook/litho/api.json
./get_issue_list.py springside/springside4 > corpus/springside/springside4/api.json
./get_issue_list.py ikew0ng/SwipeBackLayout > corpus/ikew0ng/SwipeBackLayout/api.json
./get_issue_list.py rengwuxian/MaterialEditText > corpus/rengwuxian/MaterialEditText/api.json
./get_issue_list.py apache/zookeeper > corpus/apache/zookeeper/api.json
./get_issue_list.py amitshekhariitbhu/Android-Debug-Database > corpus/amitshekhariitbhu/Android-Debug-Database/api.json
./get_issue_list.py apache/storm > corpus/apache/storm/api.json
./get_issue_list.py leolin310148/ShortcutBadger > corpus/leolin310148/ShortcutBadger/api.json
./get_issue_list.py forezp/SpringCloudLearning > corpus/forezp/SpringCloudLearning/api.json
./get_issue_list.py amlcurran/ShowcaseView > corpus/amlcurran/ShowcaseView/api.json
./get_issue_list.py swagger-api/swagger-core > corpus/swagger-api/swagger-core/api.json
./get_issue_list.py MyCATApache/Mycat-Server > corpus/MyCATApache/Mycat-Server/api.json
./get_issue_list.py emilsjolander/StickyListHeaders > corpus/emilsjolander/StickyListHeaders/api.json
./get_issue_list.py pxb1988/dex2jar > corpus/pxb1988/dex2jar/api.json
./get_issue_list.py hackware1993/MagicIndicator > corpus/hackware1993/MagicIndicator/api.json
./get_issue_list.py naman14/Timber > corpus/naman14/Timber/api.json
./get_issue_list.py evant/gradle-retrolambda > corpus/evant/gradle-retrolambda/api.json
./get_issue_list.py google/j2objc > corpus/google/j2objc/api.json
./get_issue_list.py MyCATApache/Mycat-Server > corpus/MyCATApache/Mycat-Server/api.json
./get_issue_list.py emilsjolander/StickyListHeaders > corpus/emilsjolander/StickyListHeaders/api.json
./get_issue_list.py pxb1988/dex2jar > corpus/pxb1988/dex2jar/api.json
./get_issue_list.py hackware1993/MagicIndicator > corpus/hackware1993/MagicIndicator/api.json
./get_issue_list.py naman14/Timber > corpus/naman14/Timber/api.json
./get_issue_list.py evant/gradle-retrolambda > corpus/evant/gradle-retrolambda/api.json
./get_issue_list.py google/j2objc > corpus/google/j2objc/api.json
./get_issue_list.py google/android-classyshark > corpus/google/android-classyshark/api.json
./get_issue_list.py shwenzhang/AndResGuard > corpus/shwenzhang/AndResGuard/api.json
./get_issue_list.py LuckSiege/PictureSelector > corpus/LuckSiege/PictureSelector/api.json
./get_issue_list.py daimajia/AndroidImageSlider > corpus/daimajia/AndroidImageSlider/api.json
./get_issue_list.py lucasr/twoway-view > corpus/lucasr/twoway-view/api.json
./get_issue_list.py daimajia/NumberProgressBar > corpus/daimajia/NumberProgressBar/api.json
./get_issue_list.py Qihoo360/RePlugin > corpus/Qihoo360/RePlugin/api.json
./get_issue_list.py facebook/rebound > corpus/facebook/rebound/api.json
./get_issue_list.py wyouflf/xUtils3 > corpus/wyouflf/xUtils3/api.json
./get_issue_list.py apereo/cas > corpus/apereo/cas/api.json
./get_issue_list.py square/otto > corpus/square/otto/api.json
./get_issue_list.py eclipse/che > corpus/eclipse/che/api.json
./get_issue_list.py vinc3m1/RoundedImageView > corpus/vinc3m1/RoundedImageView/api.json
./get_issue_list.py apache/flink > corpus/apache/flink/api.json
./get_issue_list.py grpc/grpc-java > corpus/grpc/grpc-java/api.json
./get_issue_list.py Devlight/InfiniteCycleViewPager > corpus/Devlight/InfiniteCycleViewPager/api.json
./get_issue_list.py dyc87112/SpringBoot-Learning > corpus/dyc87112/SpringBoot-Learning/api.json
./get_issue_list.py android-hacker/VirtualXposed > corpus/android-hacker/VirtualXposed/api.json
./get_issue_list.py apache/incubator-skywalking > corpus/apache/incubator-skywalking/api.json
./get_issue_list.py Nightonke/BoomMenu > corpus/Nightonke/BoomMenu/api.json
./get_issue_list.py jgilfelt/SystemBarTint > corpus/jgilfelt/SystemBarTint/api.json
./get_issue_list.py dmytrodanylyk/circular-progress-button > corpus/dmytrodanylyk/circular-progress-button/api.json
./get_issue_list.py GoogleContainerTools/jib > corpus/GoogleContainerTools/jib/api.json
./get_issue_list.py kickstarter/android-oss > corpus/kickstarter/android-oss/api.json
./get_issue_list.py wyouflf/xUtils > corpus/wyouflf/xUtils/api.json
./get_issue_list.py asLody/VirtualApp > corpus/asLody/VirtualApp/api.json
./get_issue_list.py sparklemotion/nokogiri > corpus/sparklemotion/nokogiri/api.json
./get_issue_list.py sockeqwe/mosby > corpus/sockeqwe/mosby/api.json
./get_issue_list.py JessYanCoding/AndroidAutoSize > corpus/JessYanCoding/AndroidAutoSize/api.json
./get_issue_list.py Justson/AgentWeb > corpus/Justson/AgentWeb/api.json
./get_issue_list.py ben-manes/caffeine > corpus/ben-manes/caffeine/api.json
./get_issue_list.py airbnb/epoxy > corpus/airbnb/epoxy/api.json
./get_issue_list.py evernote/android-job > corpus/evernote/android-job/api.json
./get_issue_list.py frogermcs/InstaMaterial > corpus/frogermcs/InstaMaterial/api.json
./get_issue_list.py davemorrissey/subsampling-scale-image-view > corpus/davemorrissey/subsampling-scale-image-view/api.json
./get_issue_list.py Blankj/awesome-java-leetcode > corpus/Blankj/awesome-java-leetcode/api.json
./get_issue_list.py gyf-dev/ImmersionBar > corpus/gyf-dev/ImmersionBar/api.json
./get_issue_list.py claritylab/lucida > corpus/claritylab/lucida/api.json
./get_issue_list.py firebase/quickstart-android > corpus/firebase/quickstart-android/api.json
./get_issue_list.py Trinea/android-common > corpus/Trinea/android-common/api.json
./get_issue_list.py yixia/VitamioBundle > corpus/yixia/VitamioBundle/api.json
./get_issue_list.py hs-web/hsweb-framework > corpus/hs-web/hsweb-framework/api.json
./get_issue_list.py GrenderG/Toasty > corpus/GrenderG/Toasty/api.json
./get_issue_list.py aa112901/remusic > corpus/aa112901/remusic/api.json
./get_issue_list.py zaproxy/zaproxy > corpus/zaproxy/zaproxy/api.json
./get_issue_list.py thinkaurelius/titan > corpus/thinkaurelius/titan/api.json
./get_issue_list.py apache/cassandra > corpus/apache/cassandra/api.json
./get_issue_list.py alibaba/freeline > corpus/alibaba/freeline/api.json
./get_issue_list.py vipshop/vjtools > corpus/vipshop/vjtools/api.json
./get_issue_list.py Yalantis/Side-Menu.Android > corpus/Yalantis/Side-Menu.Android/api.json
./get_issue_list.py antlr/antlr4 > corpus/antlr/antlr4/api.json
./get_issue_list.py izzyleung/ZhihuDailyPurify > corpus/izzyleung/ZhihuDailyPurify/api.json
./get_issue_list.py gabrielemariotti/cardslib > corpus/gabrielemariotti/cardslib/api.json
./get_issue_list.py traex/RippleEffect > corpus/traex/RippleEffect/api.json
./get_issue_list.py prolificinteractive/material-calendarview > corpus/prolificinteractive/material-calendarview/api.json
./get_issue_list.py yanzhenjie/AndPermission > corpus/yanzhenjie/AndPermission/api.json
./get_issue_list.py AsyncHttpClient/async-http-client > corpus/AsyncHttpClient/async-http-client/api.json
./get_issue_list.py weibocom/motan > corpus/weibocom/motan/api.json
./get_issue_list.py JakeWharton/DiskLruCache > corpus/JakeWharton/DiskLruCache/api.json
./get_issue_list.py commonsguy/cw-omnibus > corpus/commonsguy/cw-omnibus/api.json
./get_issue_list.py etsy/AndroidStaggeredGrid > corpus/etsy/AndroidStaggeredGrid/api.json
./get_issue_list.py TooTallNate/Java-WebSocket > corpus/TooTallNate/Java-WebSocket/api.json
./get_issue_list.py smuyyh/BookReader > corpus/smuyyh/BookReader/api.json
./get_issue_list.py square/sqlbrite > corpus/square/sqlbrite/api.json
./get_issue_list.py TeamNewPipe/NewPipe > corpus/TeamNewPipe/NewPipe/api.json
./get_issue_list.py gitpitch/gitpitch > corpus/gitpitch/gitpitch/api.json
./get_issue_list.py ACRA/acra > corpus/ACRA/acra/api.json
./get_issue_list.py facebook/facebook-android-sdk > corpus/facebook/facebook-android-sdk/api.json
./get_issue_list.py guardianproject/haven > corpus/guardianproject/haven/api.json
./get_issue_list.py scribejava/scribejava > corpus/scribejava/scribejava/api.json
./get_issue_list.py react-community/react-native-image-picker > corpus/react-community/react-native-image-picker/api.json
./get_issue_list.py pardom-zz/ActiveAndroid > corpus/pardom-zz/ActiveAndroid/api.json
./get_issue_list.py NLPchina/ansj_seg > corpus/NLPchina/ansj_seg/api.json
./get_issue_list.py motianhuo/wechat > corpus/motianhuo/wechat/api.json
./get_issue_list.py markzhai/AndroidPerformanceMonitor > corpus/markzhai/AndroidPerformanceMonitor/api.json
./get_issue_list.py XRecyclerView/XRecyclerView > corpus/XRecyclerView/XRecyclerView/api.json
./get_issue_list.py square/moshi > corpus/square/moshi/api.json
./get_issue_list.py Graylog2/graylog2-server > corpus/Graylog2/graylog2-server/api.json
./get_issue_list.py MindorksOpenSource/android-interview-questions > corpus/MindorksOpenSource/android-interview-questions/api.json
./get_issue_list.py sqshq/PiggyMetrics > corpus/sqshq/PiggyMetrics/api.json
./get_issue_list.py google/closure-compiler > corpus/google/closure-compiler/api.json
./get_issue_list.py janishar/mit-deep-learning-book-pdf > corpus/janishar/mit-deep-learning-book-pdf/api.json
./get_issue_list.py processing/processing > corpus/processing/processing/api.json
./get_issue_list.py go-lang-plugin-org/go-lang-idea-plugin > corpus/go-lang-plugin-org/go-lang-idea-plugin/api.json
./get_issue_list.py wequick/Small > corpus/wequick/Small/api.json
./get_issue_list.py gocd/gocd > corpus/gocd/gocd/api.json
./get_issue_list.py Clans/FloatingActionButton > corpus/Clans/FloatingActionButton/api.json
./get_issue_list.py hongyangAndroid/FlowLayout > corpus/hongyangAndroid/FlowLayout/api.json
./get_issue_list.py chentao0707/SimplifyReader > corpus/chentao0707/SimplifyReader/api.json
./get_issue_list.py mcxiaoke/android-volley > corpus/mcxiaoke/android-volley/api.json
./get_issue_list.py JakeWharton/NineOldAndroids > corpus/JakeWharton/NineOldAndroids/api.json
./get_issue_list.py java-native-access/jna > corpus/java-native-access/jna/api.json
./get_issue_list.py danielzeller/Depth-LIB-Android- > corpus/danielzeller/Depth-LIB-Android-/api.json
./get_issue_list.py knightliao/disconf > corpus/knightliao/disconf/api.json
./get_issue_list.py careercup/ctci > corpus/careercup/ctci/api.json
./get_issue_list.py elasticjob/elastic-job-lite > corpus/elasticjob/elastic-job-lite/api.json
./get_issue_list.py Devlight/NavigationTabBar > corpus/Devlight/NavigationTabBar/api.json
./get_issue_list.py dm77/barcodescanner > corpus/dm77/barcodescanner/api.json
./get_issue_list.py Activiti/Activiti > corpus/Activiti/Activiti/api.json
./get_issue_list.py lets-blade/blade > corpus/lets-blade/blade/api.json
./get_issue_list.py aporter/coursera-android > corpus/aporter/coursera-android/api.json
./get_issue_list.py NLPchina/elasticsearch-sql > corpus/NLPchina/elasticsearch-sql/api.json
./get_issue_list.py square/android-times-square > corpus/square/android-times-square/api.json
./get_issue_list.py AndroidBootstrap/android-bootstrap > corpus/AndroidBootstrap/android-bootstrap/api.json
./get_issue_list.py robolectric/robolectric > corpus/robolectric/robolectric/api.json
./get_issue_list.py hanks-zyh/HTextView > corpus/hanks-zyh/HTextView/api.json
./get_issue_list.py h6ah4i/android-advancedrecyclerview > corpus/h6ah4i/android-advancedrecyclerview/api.json
./get_issue_list.py wasabeef/richeditor-android > corpus/wasabeef/richeditor-android/api.json
./get_issue_list.py yarolegovich/DiscreteScrollView > corpus/yarolegovich/DiscreteScrollView/api.json
./get_issue_list.py NanoHttpd/nanohttpd > corpus/NanoHttpd/nanohttpd/api.json
./get_issue_list.py Ramotion/folding-cell-android > corpus/Ramotion/folding-cell-android/api.json
./get_issue_list.py google/error-prone > corpus/google/error-prone/api.json
./get_issue_list.py andkulikov/Transitions-Everywhere > corpus/andkulikov/Transitions-Everywhere/api.json
./get_issue_list.py jdamcd/android-crop > corpus/jdamcd/android-crop/api.json
./get_issue_list.py spring-projects/spring-mvc-showcase > corpus/spring-projects/spring-mvc-showcase/api.json
./get_issue_list.py orhanobut/dialogplus > corpus/orhanobut/dialogplus/api.json
./get_issue_list.py joelittlejohn/jsonschema2pojo > corpus/joelittlejohn/jsonschema2pojo/api.json
./get_issue_list.py gzu-liyujiang/AndroidPicker > corpus/gzu-liyujiang/AndroidPicker/api.json
./get_issue_list.py castorflex/SmoothProgressBar > corpus/castorflex/SmoothProgressBar/api.json
./get_issue_list.py KeepSafe/TapTargetView > corpus/KeepSafe/TapTargetView/api.json
./get_issue_list.py alibaba/UltraViewPager > corpus/alibaba/UltraViewPager/api.json
./get_issue_list.py careercup/CtCI-6th-Edition > corpus/careercup/CtCI-6th-Edition/api.json
./get_issue_list.py barteksc/AndroidPdfViewer > corpus/barteksc/AndroidPdfViewer/api.json
./get_issue_list.py k9mail/k-9 > corpus/k9mail/k-9/api.json
./get_issue_list.py Vedenin/useful-java-links > corpus/Vedenin/useful-java-links/api.json
./get_issue_list.py hongyangAndroid/baseAdapter > corpus/hongyangAndroid/baseAdapter/api.json
./get_issue_list.py haifengl/smile > corpus/haifengl/smile/api.json
./get_issue_list.py checkstyle/checkstyle > corpus/checkstyle/checkstyle/api.json
./get_issue_list.py Flipboard/bottomsheet > corpus/Flipboard/bottomsheet/api.json
./get_issue_list.py google/cameraview > corpus/google/cameraview/api.json
./get_issue_list.py DreaminginCodeZH/Douya > corpus/DreaminginCodeZH/Douya/api.json
./get_issue_list.py uber/RIBs > corpus/uber/RIBs/api.json
./get_issue_list.py mikepenz/Android-Iconics > corpus/mikepenz/Android-Iconics/api.json
./get_issue_list.py Bigkoo/Android-ConvenientBanner > corpus/Bigkoo/Android-ConvenientBanner/api.json
./get_issue_list.py ArthurHub/Android-Image-Cropper > corpus/ArthurHub/Android-Image-Cropper/api.json
./get_issue_list.py TommyLemon/APIJSON > corpus/TommyLemon/APIJSON/api.json
./get_issue_list.py makovkastar/FloatingActionButton > corpus/makovkastar/FloatingActionButton/api.json
./get_issue_list.py alibaba/dexposed > corpus/alibaba/dexposed/api.json
./get_issue_list.py diogobernardino/WilliamChart > corpus/diogobernardino/WilliamChart/api.json
./get_issue_list.py jpush/aurora-imui > corpus/jpush/aurora-imui/api.json
./get_issue_list.py jwtk/jjwt > corpus/jwtk/jjwt/api.json
./get_issue_list.py zetbaitsu/Compressor > corpus/zetbaitsu/Compressor/api.json
./get_issue_list.py amitshekhariitbhu/RxJava2-Android-Samples > corpus/amitshekhariitbhu/RxJava2-Android-Samples/api.json
./get_issue_list.py amitshekhariitbhu/Fast-Android-Networking > corpus/amitshekhariitbhu/Fast-Android-Networking/api.json
./get_issue_list.py real-logic/aeron > corpus/real-logic/aeron/api.json
./get_issue_list.py lightbend/config > corpus/lightbend/config/api.json
./get_issue_list.py mcxiaoke/packer-ng-plugin > corpus/mcxiaoke/packer-ng-plugin/api.json
./get_issue_list.py Meituan-Dianping/walle > corpus/Meituan-Dianping/walle/api.json
./get_issue_list.py Yalantis/Phoenix > corpus/Yalantis/Phoenix/api.json
./get_issue_list.py lihengming/spring-boot-api-project-seed > corpus/lihengming/spring-boot-api-project-seed/api.json
./get_issue_list.py kyleduo/SwitchButton > corpus/kyleduo/SwitchButton/api.json
./get_issue_list.py apache/zeppelin > corpus/apache/zeppelin/api.json
./get_issue_list.py roboguice/roboguice > corpus/roboguice/roboguice/api.json
./get_issue_list.py alibaba/otter > corpus/alibaba/otter/api.json
./get_issue_list.py JodaOrg/joda-time > corpus/JodaOrg/joda-time/api.json
./get_issue_list.py HotBitmapGG/bilibili-android-client > corpus/HotBitmapGG/bilibili-android-client/api.json
./get_issue_list.py huanghaibin-dev/CalendarView > corpus/huanghaibin-dev/CalendarView/api.json
./get_issue_list.py Angel-ML/angel > corpus/Angel-ML/angel/api.json
./get_issue_list.py bingoogolapple/BGARefreshLayout-Android > corpus/bingoogolapple/BGARefreshLayout-Android/api.json
./get_issue_list.py pedrovgs/AndroidWiFiADB > corpus/pedrovgs/AndroidWiFiADB/api.json
./get_issue_list.py k0shk0sh/FastHub > corpus/k0shk0sh/FastHub/api.json
./get_issue_list.py rubensousa/RecyclerViewSnap > corpus/rubensousa/RecyclerViewSnap/api.json
./get_issue_list.py alibaba/Sentinel > corpus/alibaba/Sentinel/api.json
./get_issue_list.py wuhaoyu1990/MagicCamera > corpus/wuhaoyu1990/MagicCamera/api.json
./get_issue_list.py wdullaer/MaterialDateTimePicker > corpus/wdullaer/MaterialDateTimePicker/api.json
./get_issue_list.py Alluxio/alluxio > corpus/Alluxio/alluxio/api.json
./get_issue_list.py drakeet/MultiType > corpus/drakeet/MultiType/api.json
./get_issue_list.py MindorksOpenSource/from-java-to-kotlin > corpus/MindorksOpenSource/from-java-to-kotlin/api.json
./get_issue_list.py liyifeng1994/ssm > corpus/liyifeng1994/ssm/api.json
./get_issue_list.py yipianfengye/android-zxingLibrary > corpus/yipianfengye/android-zxingLibrary/api.json
./get_issue_list.py OpenFeign/feign > corpus/OpenFeign/feign/api.json
./get_issue_list.py grantland/android-autofittextview > corpus/grantland/android-autofittextview/api.json
./get_issue_list.py nisrulz/android-tips-tricks > corpus/nisrulz/android-tips-tricks/api.json
./get_issue_list.py orientechnologies/orientdb > corpus/orientechnologies/orientdb/api.json
./get_issue_list.py rengwuxian/RxJavaSamples > corpus/rengwuxian/RxJavaSamples/api.json
./get_issue_list.py wasabeef/Blurry > corpus/wasabeef/Blurry/api.json
./get_issue_list.py JoanZapata/android-iconify > corpus/JoanZapata/android-iconify/api.json
./get_issue_list.py alibaba/jstorm > corpus/alibaba/jstorm/api.json
./get_issue_list.py h2oai/h2o-3 > corpus/h2oai/h2o-3/api.json
./get_issue_list.py yanzhenjie/SwipeRecyclerView > corpus/yanzhenjie/SwipeRecyclerView/api.json
./get_issue_list.py pili-engineering/PLDroidPlayer > corpus/pili-engineering/PLDroidPlayer/api.json
./get_issue_list.py BoltsFramework/Bolts-Android > corpus/BoltsFramework/Bolts-Android/api.json
./get_issue_list.py sohutv/cachecloud > corpus/sohutv/cachecloud/api.json
./get_issue_list.py Ashok-Varma/BottomNavigation > corpus/Ashok-Varma/BottomNavigation/api.json
./get_issue_list.py JetBrains/ideavim > corpus/JetBrains/ideavim/api.json
./get_issue_list.py flyway/flyway > corpus/flyway/flyway/api.json
./get_issue_list.py hugeterry/CoordinatorTabLayout > corpus/hugeterry/CoordinatorTabLayout/api.json
./get_issue_list.py Karumi/Dexter > corpus/Karumi/Dexter/api.json
./get_issue_list.py react-native-community/react-native-video > corpus/react-native-community/react-native-video/api.json
./get_issue_list.py yanzhenjie/NoHttp > corpus/yanzhenjie/NoHttp/api.json
./get_issue_list.py ximsfei/Android-skin-support > corpus/ximsfei/Android-skin-support/api.json
./get_issue_list.py jgilfelt/chuck > corpus/jgilfelt/chuck/api.json
./get_issue_list.py baoyachi/StepView > corpus/baoyachi/StepView/api.json
./get_issue_list.py zo0r/react-native-push-notification > corpus/zo0r/react-native-push-notification/api.json
./get_issue_list.py hibernate/hibernate-orm > corpus/hibernate/hibernate-orm/api.json
./get_issue_list.py kevin-wayne/algs4 > corpus/kevin-wayne/algs4/api.json
./get_issue_list.py rubensousa/ViewPagerCards > corpus/rubensousa/ViewPagerCards/api.json
./get_issue_list.py rest-assured/rest-assured > corpus/rest-assured/rest-assured/api.json
./get_issue_list.py dinuscxj/LoadingDrawable > corpus/dinuscxj/LoadingDrawable/api.json
./get_issue_list.py ChadCSong/ShineButton > corpus/ChadCSong/ShineButton/api.json
./get_issue_list.py openhab/openhab1-addons > corpus/openhab/openhab1-addons/api.json
./get_issue_list.py luontola/retrolambda > corpus/luontola/retrolambda/api.json
./get_issue_list.py Yalantis/Context-Menu.Android > corpus/Yalantis/Context-Menu.Android/api.json
./get_issue_list.py aurelhubert/ahbottomnavigation > corpus/aurelhubert/ahbottomnavigation/api.json
./get_issue_list.py lcodecorex/TwinklingRefreshLayout > corpus/lcodecorex/TwinklingRefreshLayout/api.json
./get_issue_list.py romandanylyk/PageIndicatorView > corpus/romandanylyk/PageIndicatorView/api.json
./get_issue_list.py NYTimes/Store > corpus/NYTimes/Store/api.json
./get_issue_list.py socketio/socket.io-client-java > corpus/socketio/socket.io-client-java/api.json
./get_issue_list.py topjohnwu/Magisk > corpus/topjohnwu/Magisk/api.json
./get_issue_list.py baoyongzhang/SwipeMenuListView > corpus/baoyongzhang/SwipeMenuListView/api.json
./get_issue_list.py amirzaidi/Launcher3 > corpus/amirzaidi/Launcher3/api.json
./get_issue_list.py avast/android-butterknife-zelezny > corpus/avast/android-butterknife-zelezny/api.json
./get_issue_list.py PipelineAI/pipeline > corpus/PipelineAI/pipeline/api.json
./get_issue_list.py OpenTSDB/opentsdb > corpus/OpenTSDB/opentsdb/api.json
./get_issue_list.py puniverse/quasar > corpus/puniverse/quasar/api.json
./get_issue_list.py baomidou/mybatis-plus > corpus/baomidou/mybatis-plus/api.json
./get_issue_list.py CellularPrivacy/Android-IMSI-Catcher-Detector > corpus/CellularPrivacy/Android-IMSI-Catcher-Detector/api.json
./get_issue_list.py google/google-authenticator > corpus/google/google-authenticator/api.json
./get_issue_list.py mrniko/netty-socketio > corpus/mrniko/netty-socketio/api.json
./get_issue_list.py MiguelCatalan/MaterialSearchView > corpus/MiguelCatalan/MaterialSearchView/api.json
./get_issue_list.py xcc3641/SeeWeather > corpus/xcc3641/SeeWeather/api.json
./get_issue_list.py youlookwhat/CloudReader > corpus/youlookwhat/CloudReader/api.json
./get_issue_list.py Manabu-GT/ExpandableTextView > corpus/Manabu-GT/ExpandableTextView/api.json
./get_issue_list.py ryanhoo/StylishMusicPlayer > corpus/ryanhoo/StylishMusicPlayer/api.json
./get_issue_list.py jfoenixadmin/JFoenix > corpus/jfoenixadmin/JFoenix/api.json
./get_issue_list.py tyrantgit/ExplosionField > corpus/tyrantgit/ExplosionField/api.json
./get_issue_list.py apache/incubator-heron > corpus/apache/incubator-heron/api.json
./get_issue_list.py yigit/android-priority-jobqueue > corpus/yigit/android-priority-jobqueue/api.json
./get_issue_list.py bluelinelabs/Conductor > corpus/bluelinelabs/Conductor/api.json
./get_issue_list.py chrisbanes/ActionBar-PullToRefresh > corpus/chrisbanes/ActionBar-PullToRefresh/api.json
./get_issue_list.py TommyLemon/Android-ZBLibrary > corpus/TommyLemon/Android-ZBLibrary/api.json
./get_issue_list.py actorapp/actor-platform > corpus/actorapp/actor-platform/api.json
./get_issue_list.py kikoso/android-stackblur > corpus/kikoso/android-stackblur/api.json
./get_issue_list.py tyrantgit/ExplosionField > corpus/tyrantgit/ExplosionField/api.json
./get_issue_list.py apache/incubator-heron > corpus/apache/incubator-heron/api.json
./get_issue_list.py yigit/android-priority-jobqueue > corpus/yigit/android-priority-jobqueue/api.json
./get_issue_list.py bluelinelabs/Conductor > corpus/bluelinelabs/Conductor/api.json
./get_issue_list.py chrisbanes/ActionBar-PullToRefresh > corpus/chrisbanes/ActionBar-PullToRefresh/api.json
./get_issue_list.py TommyLemon/Android-ZBLibrary > corpus/TommyLemon/Android-ZBLibrary/api.json
./get_issue_list.py actorapp/actor-platform > corpus/actorapp/actor-platform/api.json
./get_issue_list.py kikoso/android-stackblur > corpus/kikoso/android-stackblur/api.json
./get_issue_list.py json-path/JsonPath > corpus/json-path/JsonPath/api.json
./get_issue_list.py robinhood/ticker > corpus/robinhood/ticker/api.json
./get_issue_list.py Atmosphere/atmosphere > corpus/Atmosphere/atmosphere/api.json
./get_issue_list.py ivacf/archi > corpus/ivacf/archi/api.json
./get_issue_list.py Jacksgong/JKeyboardPanelSwitch > corpus/Jacksgong/JKeyboardPanelSwitch/api.json
./get_issue_list.py yasserg/crawler4j > corpus/yasserg/crawler4j/api.json
./get_issue_list.py yangfuhai/ASimpleCache > corpus/yangfuhai/ASimpleCache/api.json
./get_issue_list.py rabbitmq/rabbitmq-tutorials > corpus/rabbitmq/rabbitmq-tutorials/api.json
./get_issue_list.py lsjwzh/RecyclerViewPager > corpus/lsjwzh/RecyclerViewPager/api.json
./get_issue_list.py airbnb/DeepLinkDispatch > corpus/airbnb/DeepLinkDispatch/api.json
./get_issue_list.py litesuits/android-common > corpus/litesuits/android-common/api.json
./get_issue_list.py xcltapestry/XCL-Charts > corpus/xcltapestry/XCL-Charts/api.json
./get_issue_list.py dropbox/hackpad > corpus/dropbox/hackpad/api.json
./get_issue_list.py journeyapps/zxing-android-embedded > corpus/journeyapps/zxing-android-embedded/api.json
./get_issue_list.py codeestX/GeekNews > corpus/codeestX/GeekNews/api.json
./get_issue_list.py ongakuer/CircleIndicator > corpus/ongakuer/CircleIndicator/api.json
./get_issue_list.py bauerca/drag-sort-listview > corpus/bauerca/drag-sort-listview/api.json
./get_issue_list.py lzyzsd/CircleProgress > corpus/lzyzsd/CircleProgress/api.json
./get_issue_list.py zouzg/mybatis-generator-gui > corpus/zouzg/mybatis-generator-gui/api.json
./get_issue_list.py springfox/springfox > corpus/springfox/springfox/api.json
./get_issue_list.py JesusFreke/smali > corpus/JesusFreke/smali/api.json
./get_issue_list.py yangfuhai/afinal > corpus/yangfuhai/afinal/api.json
./get_issue_list.py bluelinelabs/LoganSquare > corpus/bluelinelabs/LoganSquare/api.json
./get_issue_list.py SonarSource/sonarqube > corpus/SonarSource/sonarqube/api.json
./get_issue_list.py orhanobut/hawk > corpus/orhanobut/hawk/api.json
./get_issue_list.py pengjianbo/GalleryFinal > corpus/pengjianbo/GalleryFinal/api.json
./get_issue_list.py spring-projects/spring-security-oauth > corpus/spring-projects/spring-security-oauth/api.json
./get_issue_list.py firebase/FirebaseUI-Android > corpus/firebase/FirebaseUI-Android/api.json
./get_issue_list.py facebook/shimmer-android > corpus/facebook/shimmer-android/api.json
./get_issue_list.py dyc87112/SpringCloud-Learning > corpus/dyc87112/SpringCloud-Learning/api.json
./get_issue_list.py react-native-community/react-native-svg > corpus/react-native-community/react-native-svg/api.json
./get_issue_list.py tangqi92/Android-Tips > corpus/tangqi92/Android-Tips/api.json
./get_issue_list.py dongjunkun/DropDownMenu > corpus/dongjunkun/DropDownMenu/api.json
./get_issue_list.py stleary/JSON-java > corpus/stleary/JSON-java/api.json
./get_issue_list.py bitcoinj/bitcoinj > corpus/bitcoinj/bitcoinj/api.json
./get_issue_list.py siacs/Conversations > corpus/siacs/Conversations/api.json
./get_issue_list.py arimorty/floatingsearchview > corpus/arimorty/floatingsearchview/api.json
./get_issue_list.py Microsoft/malmo > corpus/Microsoft/malmo/api.json
./get_issue_list.py airbnb/native-navigation > corpus/airbnb/native-navigation/api.json
./get_issue_list.py keycloak/keycloak > corpus/keycloak/keycloak/api.json
./get_issue_list.py bingoogolapple/BGABanner-Android > corpus/bingoogolapple/BGABanner-Android/api.json
./get_issue_list.py keyboardsurfer/Crouton > corpus/keyboardsurfer/Crouton/api.json
./get_issue_list.py andremion/Music-Player > corpus/andremion/Music-Player/api.json
./get_issue_list.py termux/termux-app > corpus/termux/termux-app/api.json
./get_issue_list.py stephanenicolas/robospice > corpus/stephanenicolas/robospice/api.json
./get_issue_list.py udacity/Sunshine-Version-2 > corpus/udacity/Sunshine-Version-2/api.json
./get_issue_list.py DingMouRen/LayoutManagerGroup > corpus/DingMouRen/LayoutManagerGroup/api.json
./get_issue_list.py hitherejoe/animate > corpus/hitherejoe/animate/api.json
./get_issue_list.py mybatis/generator > corpus/mybatis/generator/api.json
./get_issue_list.py spring-projects/spring-security > corpus/spring-projects/spring-security/api.json
./get_issue_list.py Bilibili/MagicaSakura > corpus/Bilibili/MagicaSakura/api.json
./get_issue_list.py nicolasgramlich/AndEngine > corpus/nicolasgramlich/AndEngine/api.json
./get_issue_list.py jgilfelt/android-viewbadger > corpus/jgilfelt/android-viewbadger/api.json
./get_issue_list.py gabrielemariotti/RecyclerViewItemAnimators > corpus/gabrielemariotti/RecyclerViewItemAnimators/api.json
./get_issue_list.py daimajia/AndroidViewHover > corpus/daimajia/AndroidViewHover/api.json
./get_issue_list.py alamkanak/Android-Week-View > corpus/alamkanak/Android-Week-View/api.json
./get_issue_list.py Meituan-Dianping/Robust > corpus/Meituan-Dianping/Robust/api.json
./get_issue_list.py cjlin1/libsvm > corpus/cjlin1/libsvm/api.json
./get_issue_list.py gephi/gephi > corpus/gephi/gephi/api.json
./get_issue_list.py qstumn/BadgeView > corpus/qstumn/BadgeView/api.json
./get_issue_list.py DuGuQiuBai/Java > corpus/DuGuQiuBai/Java/api.json
./get_issue_list.py willowtreeapps/spruce-android > corpus/willowtreeapps/spruce-android/api.json
./get_issue_list.py spring-cloud/spring-cloud-netflix > corpus/spring-cloud/spring-cloud-netflix/api.json
./get_issue_list.py ManuelPeinado/FadingActionBar > corpus/ManuelPeinado/FadingActionBar/api.json
./get_issue_list.py ragunathjawahar/android-saripaar > corpus/ragunathjawahar/android-saripaar/api.json
./get_issue_list.py yahoo/anthelion > corpus/yahoo/anthelion/api.json
./get_issue_list.py apache/groovy > corpus/apache/groovy/api.json
./get_issue_list.py pedrovgs/DraggablePanel > corpus/pedrovgs/DraggablePanel/api.json
./get_issue_list.py Piasy/BigImageViewer > corpus/Piasy/BigImageViewer/api.json
./get_issue_list.py saulmm/Android-Material-Examples > corpus/saulmm/Android-Material-Examples/api.json
./get_issue_list.py danikula/AndroidVideoCache > corpus/danikula/AndroidVideoCache/api.json
./get_issue_list.py race604/FlyRefresh > corpus/race604/FlyRefresh/api.json
./get_issue_list.py davideas/FlexibleAdapter > corpus/davideas/FlexibleAdapter/api.json
./get_issue_list.py shekhargulati/99-problems > corpus/shekhargulati/99-problems/api.json
./get_issue_list.py jasonross/Nuwa > corpus/jasonross/Nuwa/api.json
./get_issue_list.py Exrick/xmall > corpus/Exrick/xmall/api.json
./get_issue_list.py bytedeco/javacv > corpus/bytedeco/javacv/api.json
./get_issue_list.py hazelcast/hazelcast > corpus/hazelcast/hazelcast/api.json
./get_issue_list.py psaravan/JamsMusicPlayer > corpus/psaravan/JamsMusicPlayer/api.json
./get_issue_list.py Skykai521/StickerCamera > corpus/Skykai521/StickerCamera/api.json
./get_issue_list.py abel533/Mapper > corpus/abel533/Mapper/api.json
./get_issue_list.py dmytrodanylyk/android-process-button > corpus/dmytrodanylyk/android-process-button/api.json
./get_issue_list.py sherxon/AlgoDS > corpus/sherxon/AlgoDS/api.json
./get_issue_list.py lovetuzitong/MultiImageSelector > corpus/lovetuzitong/MultiImageSelector/api.json
./get_issue_list.py jersey/jersey > corpus/jersey/jersey/api.json
./get_issue_list.py amulyakhare/TextDrawable > corpus/amulyakhare/TextDrawable/api.json
./get_issue_list.py changmingxie/tcc-transaction > corpus/changmingxie/tcc-transaction/api.json
./get_issue_list.py JulienGenoud/android-percent-support-lib-sample > corpus/JulienGenoud/android-percent-support-lib-sample/api.json
./get_issue_list.py huangyanbin/smartTable > corpus/huangyanbin/smartTable/api.json
./get_issue_list.py vavr-io/vavr > corpus/vavr-io/vavr/api.json
./get_issue_list.py facebook/network-connection-class > corpus/facebook/network-connection-class/api.json
./get_issue_list.py paascloud/paascloud-master > corpus/paascloud/paascloud-master/api.json
./get_issue_list.py rubensousa/PreviewSeekBar > corpus/rubensousa/PreviewSeekBar/api.json
./get_issue_list.py objectbox/objectbox-java > corpus/objectbox/objectbox-java/api.json
./get_issue_list.py kevinsawicki/http-request > corpus/kevinsawicki/http-request/api.json
./get_issue_list.py zzz40500/GsonFormat > corpus/zzz40500/GsonFormat/api.json
./get_issue_list.py donglua/PhotoPicker > corpus/donglua/PhotoPicker/api.json
./get_issue_list.py crazycodeboy/react-native-splash-screen > corpus/crazycodeboy/react-native-splash-screen/api.json
./get_issue_list.py graphql-java/graphql-java > corpus/graphql-java/graphql-java/api.json
./get_issue_list.py aws/aws-sdk-java > corpus/aws/aws-sdk-java/api.json
./get_issue_list.py spring-projects/spring-petclinic > corpus/spring-projects/spring-petclinic/api.json
./get_issue_list.py reactive-streams/reactive-streams-jvm > corpus/reactive-streams/reactive-streams-jvm/api.json
./get_issue_list.py iammert/ScalingLayout > corpus/iammert/ScalingLayout/api.json
./get_issue_list.py openaphid/android-flip > corpus/openaphid/android-flip/api.json
./get_issue_list.py SpecialCyCi/AndroidResideMenu > corpus/SpecialCyCi/AndroidResideMenu/api.json
./get_issue_list.py apache/tomcat > corpus/apache/tomcat/api.json
./get_issue_list.py dragonflyoss/Dragonfly > corpus/dragonflyoss/Dragonfly/api.json
./get_issue_list.py alipay/sofa-jarslink > corpus/alipay/sofa-jarslink/api.json
./get_issue_list.py oblac/jodd > corpus/oblac/jodd/api.json
./get_issue_list.py linlinjava/litemall > corpus/linlinjava/litemall/api.json
./get_issue_list.py yipianfengye/android-adDialog > corpus/yipianfengye/android-adDialog/api.json
./get_issue_list.py code-troopers/android-betterpickers > corpus/code-troopers/android-betterpickers/api.json
./get_issue_list.py jOOQ/jOOQ > corpus/jOOQ/jOOQ/api.json
./get_issue_list.py HoraApps/LeafPic > corpus/HoraApps/LeafPic/api.json
./get_issue_list.py sunfusheng/MarqueeView > corpus/sunfusheng/MarqueeView/api.json
./get_issue_list.py apache/pulsar > corpus/apache/pulsar/api.json
./get_issue_list.py seven332/EhViewer > corpus/seven332/EhViewer/api.json
./get_issue_list.py databricks/learning-spark > corpus/databricks/learning-spark/api.json
./get_issue_list.py square/flow > corpus/square/flow/api.json
./get_issue_list.py Bilibili/boxing > corpus/Bilibili/boxing/api.json
./get_issue_list.py binIoter/GuideView > corpus/binIoter/GuideView/api.json
./get_issue_list.py jiangqqlmj/FastDev4Android > corpus/jiangqqlmj/FastDev4Android/api.json
./get_issue_list.py danylovolokh/VideoPlayerManager > corpus/danylovolokh/VideoPlayerManager/api.json
./get_issue_list.py yui/yuicompressor > corpus/yui/yuicompressor/api.json
./get_issue_list.py CalebFenton/simplify > corpus/CalebFenton/simplify/api.json
./get_issue_list.py CameraKit/blurkit-android > corpus/CameraKit/blurkit-android/api.json
./get_issue_list.py qii/weiciyuan > corpus/qii/weiciyuan/api.json
./get_issue_list.py jfinal/jfinal > corpus/jfinal/jfinal/api.json
./get_issue_list.py SimonVT/android-menudrawer > corpus/SimonVT/android-menudrawer/api.json
./get_issue_list.py edmodo/cropper > corpus/edmodo/cropper/api.json
./get_issue_list.py owncloud/android > corpus/owncloud/android/api.json
./get_issue_list.py hmkcode/Android > corpus/hmkcode/Android/api.json
./get_issue_list.py luojilab/DDComponentForAndroid > corpus/luojilab/DDComponentForAndroid/api.json
./get_issue_list.py jfeinstein10/JazzyViewPager > corpus/jfeinstein10/JazzyViewPager/api.json
./get_issue_list.py requery/requery > corpus/requery/requery/api.json
./get_issue_list.py googlemaps/android-maps-utils > corpus/googlemaps/android-maps-utils/api.json
./get_issue_list.py junit-team/junit5 > corpus/junit-team/junit5/api.json
./get_issue_list.py Yalantis/GuillotineMenu-Android > corpus/Yalantis/GuillotineMenu-Android/api.json
./get_issue_list.py lygttpod/SuperTextView > corpus/lygttpod/SuperTextView/api.json
./get_issue_list.py vespa-engine/vespa > corpus/vespa-engine/vespa/api.json
./get_issue_list.py sharish/ShimmerRecyclerView > corpus/sharish/ShimmerRecyclerView/api.json
./get_issue_list.py Ereza/CustomActivityOnCrash > corpus/Ereza/CustomActivityOnCrash/api.json
./get_issue_list.py hongyangAndroid/Highlight > corpus/hongyangAndroid/Highlight/api.json
./get_issue_list.py eirslett/frontend-maven-plugin > corpus/eirslett/frontend-maven-plugin/api.json
./get_issue_list.py pushtorefresh/storio > corpus/pushtorefresh/storio/api.json
./get_issue_list.py Malinskiy/SuperRecyclerView > corpus/Malinskiy/SuperRecyclerView/api.json
./get_issue_list.py cyrilmottier/GreenDroid > corpus/cyrilmottier/GreenDroid/api.json
./get_issue_list.py brianway/java-learning > corpus/brianway/java-learning/api.json
./get_issue_list.py xmuSistone/ViewpagerTransition > corpus/xmuSistone/ViewpagerTransition/api.json
./get_issue_list.py MinecraftForge/MinecraftForge > corpus/MinecraftForge/MinecraftForge/api.json
./get_issue_list.py bytedeco/javacpp > corpus/bytedeco/javacpp/api.json
./get_issue_list.py JakeWharton/scalpel > corpus/JakeWharton/scalpel/api.json
./get_issue_list.py knowm/XChange > corpus/knowm/XChange/api.json
./get_issue_list.py mzule/ActivityRouter > corpus/mzule/ActivityRouter/api.json
./get_issue_list.py beworker/pinned-section-listview > corpus/beworker/pinned-section-listview/api.json
./get_issue_list.py zzhoujay/RichText > corpus/zzhoujay/RichText/api.json
./get_issue_list.py sunfusheng/StickyHeaderListView > corpus/sunfusheng/StickyHeaderListView/api.json
./get_issue_list.py square/wire > corpus/square/wire/api.json
./get_issue_list.py Tencent/MSEC > corpus/Tencent/MSEC/api.json
./get_issue_list.py LyndonChin/MasteringAndroidDataBinding > corpus/LyndonChin/MasteringAndroidDataBinding/api.json
./get_issue_list.py awangdev/LintCode > corpus/awangdev/LintCode/api.json
./get_issue_list.py zwwill/yanxuan-weex-demo > corpus/zwwill/yanxuan-weex-demo/api.json
./get_issue_list.py JohnPersano/SuperToasts > corpus/JohnPersano/SuperToasts/api.json
./get_issue_list.py florent37/ExpectAnim > corpus/florent37/ExpectAnim/api.json
./get_issue_list.py Marswin/MarsDaemon > corpus/Marswin/MarsDaemon/api.json
./get_issue_list.py north2016/T-MVP > corpus/north2016/T-MVP/api.json
./get_issue_list.py pqpo/SmartCropper > corpus/pqpo/SmartCropper/api.json
./get_issue_list.py chennaione/sugar > corpus/chennaione/sugar/api.json
./get_issue_list.py w446108264/XhsEmoticonsKeyboard > corpus/w446108264/XhsEmoticonsKeyboard/api.json
./get_issue_list.py bisq-network/bisq > corpus/bisq-network/bisq/api.json
./get_issue_list.py Teevity/ice > corpus/Teevity/ice/api.json
./get_issue_list.py Jasonchenlijian/FastBle > corpus/Jasonchenlijian/FastBle/api.json
./get_issue_list.py Nightonke/WoWoViewPager > corpus/Nightonke/WoWoViewPager/api.json
./get_issue_list.py Todd-Davies/ProgressWheel > corpus/Todd-Davies/ProgressWheel/api.json
./get_issue_list.py yusugomori/DeepLearning > corpus/yusugomori/DeepLearning/api.json
./get_issue_list.py saulmm/CoordinatorBehaviorExample > corpus/saulmm/CoordinatorBehaviorExample/api.json
./get_issue_list.py Netflix/ribbon > corpus/Netflix/ribbon/api.json
./get_issue_list.py Freeyourgadget/Gadgetbridge > corpus/Freeyourgadget/Gadgetbridge/api.json
./get_issue_list.py oldmanpushcart/greys-anatomy > corpus/oldmanpushcart/greys-anatomy/api.json
./get_issue_list.py mcxtzhang/SwipeDelMenuLayout > corpus/mcxtzhang/SwipeDelMenuLayout/api.json
./get_issue_list.py jprante/elasticsearch-jdbc > corpus/jprante/elasticsearch-jdbc/api.json
./get_issue_list.py johannilsson/android-pulltorefresh > corpus/johannilsson/android-pulltorefresh/api.json
./get_issue_list.py rstudio/rstudio > corpus/rstudio/rstudio/api.json
./get_issue_list.py geftimov/android-pathview > corpus/geftimov/android-pathview/api.json
./get_issue_list.py BelooS/ChipsLayoutManager > corpus/BelooS/ChipsLayoutManager/api.json
./get_issue_list.py GitLqr/LQRWeChat > corpus/GitLqr/LQRWeChat/api.json
./get_issue_list.py eishay/jvm-serializers > corpus/eishay/jvm-serializers/api.json
./get_issue_list.py kbastani/spring-cloud-microservice-example > corpus/kbastani/spring-cloud-microservice-example/api.json
./get_issue_list.py JakeWharton/ThreeTenABP > corpus/JakeWharton/ThreeTenABP/api.json
./get_issue_list.py mihaip/dex-method-counts > corpus/mihaip/dex-method-counts/api.json
./get_issue_list.py cryptomator/cryptomator > corpus/cryptomator/cryptomator/api.json
./get_issue_list.py saulmm/Material-Movies > corpus/saulmm/Material-Movies/api.json
./get_issue_list.py crossoverJie/SSM > corpus/crossoverJie/SSM/api.json
./get_issue_list.py apache/cordova-android > corpus/apache/cordova-android/api.json
./get_issue_list.py JoanZapata/android-pdfview > corpus/JoanZapata/android-pdfview/api.json
./get_issue_list.py RobotiumTech/robotium > corpus/RobotiumTech/robotium/api.json
./get_issue_list.py oguzbilgener/CircularFloatingActionMenu > corpus/oguzbilgener/CircularFloatingActionMenu/api.json
./get_issue_list.py alibaba/easyexcel > corpus/alibaba/easyexcel/api.json
./get_issue_list.py ming1016/study > corpus/ming1016/study/api.json
./get_issue_list.py yhaolpz/FloatWindow > corpus/yhaolpz/FloatWindow/api.json
./get_issue_list.py mikepenz/FastAdapter > corpus/mikepenz/FastAdapter/api.json
./get_issue_list.py spring-projects/spring-data-examples > corpus/spring-projects/spring-data-examples/api.json
./get_issue_list.py phishman3579/java-algorithms-implementation > corpus/phishman3579/java-algorithms-implementation/api.json
./get_issue_list.py Comcast/FreeFlow > corpus/Comcast/FreeFlow/api.json
./get_issue_list.py TangoAgency/material-intro-screen > corpus/TangoAgency/material-intro-screen/api.json
./get_issue_list.py googlesamples/android-vision > corpus/googlesamples/android-vision/api.json
./get_issue_list.py pedrovgs/Algorithms > corpus/pedrovgs/Algorithms/api.json
./get_issue_list.py MovingBlocks/Terasology > corpus/MovingBlocks/Terasology/api.json
./get_issue_list.py path/android-priority-jobqueue > corpus/path/android-priority-jobqueue/api.json
./get_issue_list.py alibaba/cobar > corpus/alibaba/cobar/api.json
./get_issue_list.py jd-alexander/LikeButton > corpus/jd-alexander/LikeButton/api.json
./get_issue_list.py yarolegovich/SlidingRootNav > corpus/yarolegovich/SlidingRootNav/api.json
./get_issue_list.py balysv/material-menu > corpus/balysv/material-menu/api.json
./get_issue_list.py apache/jmeter > corpus/apache/jmeter/api.json
./get_issue_list.py cglib/cglib > corpus/cglib/cglib/api.json
./get_issue_list.py google/hover > corpus/google/hover/api.json
./get_issue_list.py google/binnavi > corpus/google/binnavi/api.json
./get_issue_list.py airbnb/airpal > corpus/airbnb/airpal/api.json
./get_issue_list.py jhalterman/failsafe > corpus/jhalterman/failsafe/api.json
./get_issue_list.py raphw/byte-buddy > corpus/raphw/byte-buddy/api.json
./get_issue_list.py romainguy/ViewServer > corpus/romainguy/ViewServer/api.json
./get_issue_list.py languagetool-org/languagetool > corpus/languagetool-org/languagetool/api.json
./get_issue_list.py apache/hbase > corpus/apache/hbase/api.json
./get_issue_list.py florent37/DiagonalLayout > corpus/florent37/DiagonalLayout/api.json
./get_issue_list.py DylanVann/react-native-fast-image > corpus/DylanVann/react-native-fast-image/api.json
./get_issue_list.py sd6352051/NiftyDialogEffects > corpus/sd6352051/NiftyDialogEffects/api.json
./get_issue_list.py bmelnychuk/AndroidTreeView > corpus/bmelnychuk/AndroidTreeView/api.json
./get_issue_list.py MagicMashRoom/SuperCalendar > corpus/MagicMashRoom/SuperCalendar/api.json
./get_issue_list.py ozodrukh/CircularReveal > corpus/ozodrukh/CircularReveal/api.json
./get_issue_list.py harjot-oberai/MusicDNA > corpus/harjot-oberai/MusicDNA/api.json
./get_issue_list.py fyhertz/libstreaming > corpus/fyhertz/libstreaming/api.json
./get_issue_list.py glomadrian/Grav > corpus/glomadrian/Grav/api.json
./get_issue_list.py wenmingvs/AndroidProcess > corpus/wenmingvs/AndroidProcess/api.json
./get_issue_list.py chewiebug/GCViewer > corpus/chewiebug/GCViewer/api.json
./get_issue_list.py pchmn/MaterialChipsInput > corpus/pchmn/MaterialChipsInput/api.json
./get_issue_list.py stfalcon-studio/ChatKit > corpus/stfalcon-studio/ChatKit/api.json
./get_issue_list.py uber/NullAway > corpus/uber/NullAway/api.json
./get_issue_list.py dreamhead/moco > corpus/dreamhead/moco/api.json
./get_issue_list.py pnikosis/materialish-progress > corpus/pnikosis/materialish-progress/api.json
./get_issue_list.py 500px/500px-android-blur > corpus/500px/500px-android-blur/api.json
./get_issue_list.py Screetsec/TheFatRat > corpus/Screetsec/TheFatRat/api.json
./get_issue_list.py nisrulz/sensey > corpus/nisrulz/sensey/api.json
./get_issue_list.py apache/beam > corpus/apache/beam/api.json
./get_issue_list.py flavioarfaria/KenBurnsView > corpus/flavioarfaria/KenBurnsView/api.json
./get_issue_list.py youtube/api-samples > corpus/youtube/api-samples/api.json
./get_issue_list.py ityouknow/spring-cloud-examples > corpus/ityouknow/spring-cloud-examples/api.json
./get_issue_list.py JakeWharton/Telecine > corpus/JakeWharton/Telecine/api.json
./get_issue_list.py githubwing/ZoomHeader > corpus/githubwing/ZoomHeader/api.json
./get_issue_list.py LawnchairLauncher/Lawnchair > corpus/LawnchairLauncher/Lawnchair/api.json
./get_issue_list.py googlesamples/google-services > corpus/googlesamples/google-services/api.json
./get_issue_list.py goldze/MVVMHabit > corpus/goldze/MVVMHabit/api.json
./get_issue_list.py looly/hutool > corpus/looly/hutool/api.json
./get_issue_list.py iwgang/CountdownView > corpus/iwgang/CountdownView/api.json
./get_issue_list.py spring-cloud-incubator/spring-cloud-alibaba > corpus/spring-cloud-incubator/spring-cloud-alibaba/api.json
./get_issue_list.py konifar/android-material-design-icon-generator-plugin > corpus/konifar/android-material-design-icon-generator-plugin/api.json
./get_issue_list.py auth0/java-jwt > corpus/auth0/java-jwt/api.json
./get_issue_list.py ronmamo/reflections > corpus/ronmamo/reflections/api.json
./get_issue_list.py iPaulPro/Android-ItemTouchHelper-Demo > corpus/iPaulPro/Android-ItemTouchHelper-Demo/api.json
./get_issue_list.py abel533/MyBatis-Spring-Boot > corpus/abel533/MyBatis-Spring-Boot/api.json
./get_issue_list.py luckybilly/CC > corpus/luckybilly/CC/api.json
./get_issue_list.py hussien89aa/AndroidTutorialForBeginners > corpus/hussien89aa/AndroidTutorialForBeginners/api.json
./get_issue_list.py rovo89/XposedInstaller > corpus/rovo89/XposedInstaller/api.json
./get_issue_list.py simple-android-framework/android_design_patterns_analysis > corpus/simple-android-framework/android_design_patterns_analysis/api.json
./get_issue_list.py dlew/joda-time-android > corpus/dlew/joda-time-android/api.json
./get_issue_list.py siyamed/android-shape-imageview > corpus/siyamed/android-shape-imageview/api.json
./get_issue_list.py mpusher/mpush > corpus/mpusher/mpush/api.json
./get_issue_list.py brianfrankcooper/YCSB > corpus/brianfrankcooper/YCSB/api.json
./get_issue_list.py ffay/lanproxy > corpus/ffay/lanproxy/api.json
./get_issue_list.py Nightonke/CoCoin > corpus/Nightonke/CoCoin/api.json
./get_issue_list.py Twitter4J/Twitter4J > corpus/Twitter4J/Twitter4J/api.json
./get_issue_list.py btraceio/btrace > corpus/btraceio/btrace/api.json
./get_issue_list.py JackyAndroid/AndroidChromium > corpus/JackyAndroid/AndroidChromium/api.json
./get_issue_list.py oracle/opengrok > corpus/oracle/opengrok/api.json
./get_issue_list.py thingsboard/thingsboard > corpus/thingsboard/thingsboard/api.json
./get_issue_list.py ZieIony/Carbon > corpus/ZieIony/Carbon/api.json
./get_issue_list.py h2oai/h2o-2 > corpus/h2oai/h2o-2/api.json
./get_issue_list.py eclipse/jetty.project > corpus/eclipse/jetty.project/api.json
./get_issue_list.py aritraroy/PatternLockView > corpus/aritraroy/PatternLockView/api.json
./get_issue_list.py theDazzler/droidicon > corpus/theDazzler/droidicon/api.json
./get_issue_list.py apache/incubator-dubbo-spring-boot-project > corpus/apache/incubator-dubbo-spring-boot-project/api.json
./get_issue_list.py apache/camel > corpus/apache/camel/api.json
./get_issue_list.py google/google-java-format > corpus/google/google-java-format/api.json
./get_issue_list.py vipulasri/Timeline-View > corpus/vipulasri/Timeline-View/api.json
./get_issue_list.py AriaLyy/Aria > corpus/AriaLyy/Aria/api.json
./get_issue_list.py TeamAmaze/AmazeFileManager > corpus/TeamAmaze/AmazeFileManager/api.json
./get_issue_list.py android-cjj/JJSearchViewAnim > corpus/android-cjj/JJSearchViewAnim/api.json
./get_issue_list.py markushi/android-ui > corpus/markushi/android-ui/api.json
./get_issue_list.py powermock/powermock > corpus/powermock/powermock/api.json
./get_issue_list.py twitter/distributedlog > corpus/twitter/distributedlog/api.json
./get_issue_list.py quartz-scheduler/quartz > corpus/quartz-scheduler/quartz/api.json
./get_issue_list.py qiujuer/Genius-Android > corpus/qiujuer/Genius-Android/api.json
./get_issue_list.py Prototik/HoloEverywhere > corpus/Prototik/HoloEverywhere/api.json
./get_issue_list.py bigbluebutton/bigbluebutton > corpus/bigbluebutton/bigbluebutton/api.json
./get_issue_list.py javaee-samples/javaee7-samples > corpus/javaee-samples/javaee7-samples/api.json
./get_issue_list.py deano2390/MaterialShowcaseView > corpus/deano2390/MaterialShowcaseView/api.json
./get_issue_list.py zhanglei-workspace/shopping-management-system > corpus/zhanglei-workspace/shopping-management-system/api.json
./get_issue_list.py xinghongfei/LookLook > corpus/xinghongfei/LookLook/api.json
./get_issue_list.py apache/hive > corpus/apache/hive/api.json
./get_issue_list.py mxn21/FlowingDrawer > corpus/mxn21/FlowingDrawer/api.json
./get_issue_list.py Frank-Zhu/PullZoomView > corpus/Frank-Zhu/PullZoomView/api.json
./get_issue_list.py LuckyJayce/ViewPagerIndicator > corpus/LuckyJayce/ViewPagerIndicator/api.json
./get_issue_list.py JackyAndroid/AndroidTVLauncher > corpus/JackyAndroid/AndroidTVLauncher/api.json
./get_issue_list.py mikepenz/AboutLibraries > corpus/mikepenz/AboutLibraries/api.json
./get_issue_list.py square/tape > corpus/square/tape/api.json
./get_issue_list.py chanjarster/weixin-java-tools > corpus/chanjarster/weixin-java-tools/api.json
./get_issue_list.py alibaba/Tangram-Android > corpus/alibaba/Tangram-Android/api.json
./get_issue_list.py react-native-community/react-native-blur > corpus/react-native-community/react-native-blur/api.json
./get_issue_list.py huazhiyuan2008/RecyclerViewCardGallery > corpus/huazhiyuan2008/RecyclerViewCardGallery/api.json
./get_issue_list.py 2dxgujun/AndroidTagGroup > corpus/2dxgujun/AndroidTagGroup/api.json
./get_issue_list.py chenupt/SpringIndicator > corpus/chenupt/SpringIndicator/api.json
./get_issue_list.py stormzhang/9GAG > corpus/stormzhang/9GAG/api.json
./get_issue_list.py WritingMinds/ffmpeg-android-java > corpus/WritingMinds/ffmpeg-android-java/api.json
./get_issue_list.py ata4/disunity > corpus/ata4/disunity/api.json
./get_issue_list.py r0adkll/Slidr > corpus/r0adkll/Slidr/api.json
./get_issue_list.py linkedin/databus > corpus/linkedin/databus/api.json
./get_issue_list.py immutables/immutables > corpus/immutables/immutables/api.json
./get_issue_list.py ldoublem/LoadingView > corpus/ldoublem/LoadingView/api.json
./get_issue_list.py moezbhatti/qksms > corpus/moezbhatti/qksms/api.json
./get_issue_list.py facebook/react-native-fbsdk > corpus/facebook/react-native-fbsdk/api.json
./get_issue_list.py esoxjem/MovieGuide > corpus/esoxjem/MovieGuide/api.json
./get_issue_list.py voldemort/voldemort > corpus/voldemort/voldemort/api.json
./get_issue_list.py google/data-transfer-project > corpus/google/data-transfer-project/api.json
./get_issue_list.py jjoe64/GraphView > corpus/jjoe64/GraphView/api.json
./get_issue_list.py mybatis/spring-boot-starter > corpus/mybatis/spring-boot-starter/api.json
./get_issue_list.py Yalantis/Euclid > corpus/Yalantis/Euclid/api.json
./get_issue_list.py pentaho/pentaho-kettle > corpus/pentaho/pentaho-kettle/api.json
./get_issue_list.py daimajia/AnimationEasingFunctions > corpus/daimajia/AnimationEasingFunctions/api.json
./get_issue_list.py xmuSistone/CardSlidePanel > corpus/xmuSistone/CardSlidePanel/api.json
./get_issue_list.py FinalTeam/RxGalleryFinal > corpus/FinalTeam/RxGalleryFinal/api.json
./get_issue_list.py bingoogolapple/BGABadgeView-Android > corpus/bingoogolapple/BGABadgeView-Android/api.json
./get_issue_list.py undertow-io/undertow > corpus/undertow-io/undertow/api.json
./get_issue_list.py bin456789/Unblock163MusicClient-Xposed > corpus/bin456789/Unblock163MusicClient-Xposed/api.json
./get_issue_list.py balysv/material-ripple > corpus/balysv/material-ripple/api.json
./get_issue_list.py square/mortar > corpus/square/mortar/api.json
./get_issue_list.py code-mc/material-icon-lib > corpus/code-mc/material-icon-lib/api.json
./get_issue_list.py iammert/MaterialIntroView > corpus/iammert/MaterialIntroView/api.json
./get_issue_list.py wildfly/wildfly > corpus/wildfly/wildfly/api.json
./get_issue_list.py android-cjj/BeautifulRefreshLayout > corpus/android-cjj/BeautifulRefreshLayout/api.json
./get_issue_list.py web3j/web3j > corpus/web3j/web3j/api.json
./get_issue_list.py iSoron/uhabits > corpus/iSoron/uhabits/api.json
./get_issue_list.py avast/android-styled-dialogs > corpus/avast/android-styled-dialogs/api.json
./get_issue_list.py azkaban/azkaban > corpus/azkaban/azkaban/api.json
./get_issue_list.py xfumihiro/ViewInspector > corpus/xfumihiro/ViewInspector/api.json
./get_issue_list.py woxingxiao/BubbleSeekBar > corpus/woxingxiao/BubbleSeekBar/api.json
./get_issue_list.py spockframework/spock > corpus/spockframework/spock/api.json
./get_issue_list.py eleme/UETool > corpus/eleme/UETool/api.json
./get_issue_list.py crate/crate > corpus/crate/crate/api.json
./get_issue_list.py ittianyu/BottomNavigationViewEx > corpus/ittianyu/BottomNavigationViewEx/api.json
./get_issue_list.py spring-projects/spring-loaded > corpus/spring-projects/spring-loaded/api.json
./get_issue_list.py zhouchaoyuan/excelPanel > corpus/zhouchaoyuan/excelPanel/api.json
./get_issue_list.py vikramkakkar/SublimePicker > corpus/vikramkakkar/SublimePicker/api.json
./get_issue_list.py jaydenxiao2016/AndroidFire > corpus/jaydenxiao2016/AndroidFire/api.json
./get_issue_list.py aragozin/jvm-tools > corpus/aragozin/jvm-tools/api.json
./get_issue_list.py CrawlScript/WebCollector > corpus/CrawlScript/WebCollector/api.json
./get_issue_list.py alipay/sofa-boot > corpus/alipay/sofa-boot/api.json
./get_issue_list.py code4craft/netty-learning > corpus/code4craft/netty-learning/api.json
./get_issue_list.py amitshekhariitbhu/awesome-android-complete-reference > corpus/amitshekhariitbhu/awesome-android-complete-reference/api.json
./get_issue_list.py AntennaPod/AntennaPod > corpus/AntennaPod/AntennaPod/api.json
./get_issue_list.py watabou/pixel-dungeon > corpus/watabou/pixel-dungeon/api.json
./get_issue_list.py soarcn/BottomSheet > corpus/soarcn/BottomSheet/api.json
./get_issue_list.py chrisbanes/philm > corpus/chrisbanes/philm/api.json
./get_issue_list.py apache/lucene-solr > corpus/apache/lucene-solr/api.json
./get_issue_list.py VictorAlbertos/RxCache > corpus/VictorAlbertos/RxCache/api.json
./get_issue_list.py apache/ignite > corpus/apache/ignite/api.json
./get_issue_list.py reark/reark > corpus/reark/reark/api.json
./get_issue_list.py resilience4j/resilience4j > corpus/resilience4j/resilience4j/api.json
./get_issue_list.py bm-x/PhotoView > corpus/bm-x/PhotoView/api.json
./get_issue_list.py nanchen2251/RxJava2Examples > corpus/nanchen2251/RxJava2Examples/api.json
./get_issue_list.py florent37/ViewAnimator > corpus/florent37/ViewAnimator/api.json
./get_issue_list.py yqritc/RecyclerView-FlexibleDivider > corpus/yqritc/RecyclerView-FlexibleDivider/api.json
./get_issue_list.py JZ-Darkal/AndroidHttpCapture > corpus/JZ-Darkal/AndroidHttpCapture/api.json
./get_issue_list.py javaparser/javaparser > corpus/javaparser/javaparser/api.json
./get_issue_list.py jdsjlzx/LRecyclerView > corpus/jdsjlzx/LRecyclerView/api.json
./get_issue_list.py mongodb/mongo-java-driver > corpus/mongodb/mongo-java-driver/api.json
./get_issue_list.py zaaach/CityPicker > corpus/zaaach/CityPicker/api.json
./get_issue_list.py zagum/Android-SwitchIcon > corpus/zagum/Android-SwitchIcon/api.json
./get_issue_list.py oasisfeng/condom > corpus/oasisfeng/condom/api.json
./get_issue_list.py Diolor/Swipecards > corpus/Diolor/Swipecards/api.json
./get_issue_list.py katzer/cordova-plugin-local-notifications > corpus/katzer/cordova-plugin-local-notifications/api.json
./get_issue_list.py AbrahamCaiJin/CommonUtilLibrary > corpus/AbrahamCaiJin/CommonUtilLibrary/api.json
./get_issue_list.py AltBeacon/android-beacon-library > corpus/AltBeacon/android-beacon-library/api.json
./get_issue_list.py android-cjj/Android-MaterialRefreshLayout > corpus/android-cjj/Android-MaterialRefreshLayout/api.json
./get_issue_list.py igreenwood/SimpleCropView > corpus/igreenwood/SimpleCropView/api.json
./get_issue_list.py Zomato/AndroidPhotoFilters > corpus/Zomato/AndroidPhotoFilters/api.json
./get_issue_list.py grandcentrix/tray > corpus/grandcentrix/tray/api.json
./get_issue_list.py hefuyicoder/ListenerMusicPlayer > corpus/hefuyicoder/ListenerMusicPlayer/api.json
./get_issue_list.py androidquery/androidquery > corpus/androidquery/androidquery/api.json
./get_issue_list.py facebook/device-year-class > corpus/facebook/device-year-class/api.json
./get_issue_list.py skavanagh/KeyBox > corpus/skavanagh/KeyBox/api.json
./get_issue_list.py zhou-you/RxEasyHttp > corpus/zhou-you/RxEasyHttp/api.json
./get_issue_list.py querydsl/querydsl > corpus/querydsl/querydsl/api.json
./get_issue_list.py Dimezis/BlurView > corpus/Dimezis/BlurView/api.json
./get_issue_list.py Rukey7/MvpApp > corpus/Rukey7/MvpApp/api.json
./get_issue_list.py AigeStudio/WheelPicker > corpus/AigeStudio/WheelPicker/api.json
./get_issue_list.py elye/loaderviewlibrary > corpus/elye/loaderviewlibrary/api.json
./get_issue_list.py ltsopensource/light-task-scheduler > corpus/ltsopensource/light-task-scheduler/api.json
./get_issue_list.py ToxicBakery/ViewPagerTransforms > corpus/ToxicBakery/ViewPagerTransforms/api.json
./get_issue_list.py apache/incubator-pinot > corpus/apache/incubator-pinot/api.json
./get_issue_list.py dmilicic/Android-Clean-Boilerplate > corpus/dmilicic/Android-Clean-Boilerplate/api.json
./get_issue_list.py sockeqwe/AdapterDelegates > corpus/sockeqwe/AdapterDelegates/api.json
./get_issue_list.py mcharmas/Android-ReactiveLocation > corpus/mcharmas/Android-ReactiveLocation/api.json
./get_issue_list.py florent37/CameraFragment > corpus/florent37/CameraFragment/api.json
./get_issue_list.py confluentinc/ksql > corpus/confluentinc/ksql/api.json
./get_issue_list.py cymcsg/UltimateAndroid > corpus/cymcsg/UltimateAndroid/api.json
./get_issue_list.py tronprotocol/java-tron > corpus/tronprotocol/java-tron/api.json
./get_issue_list.py tyzlmjj/PagerBottomTabStrip > corpus/tyzlmjj/PagerBottomTabStrip/api.json
./get_issue_list.py google/volley > corpus/google/volley/api.json
./get_issue_list.py fengjundev/Android-Skin-Loader > corpus/fengjundev/Android-Skin-Loader/api.json
./get_issue_list.py H07000223/FlycoDialog_Master > corpus/H07000223/FlycoDialog_Master/api.json
./get_issue_list.py jgilfelt/android-sqlite-asset-helper > corpus/jgilfelt/android-sqlite-asset-helper/api.json
./get_issue_list.py lingochamp/okdownload > corpus/lingochamp/okdownload/api.json
./get_issue_list.py apache/shiro > corpus/apache/shiro/api.json
./get_issue_list.py twosigma/beakerx > corpus/twosigma/beakerx/api.json
./get_issue_list.py pmd/pmd > corpus/pmd/pmd/api.json
./get_issue_list.py yingLanNull/ShadowImageView > corpus/yingLanNull/ShadowImageView/api.json
./get_issue_list.py Netflix/curator > corpus/Netflix/curator/api.json
./get_issue_list.py baoyongzhang/android-PullRefreshLayout > corpus/baoyongzhang/android-PullRefreshLayout/api.json
./get_issue_list.py JanusGraph/janusgraph > corpus/JanusGraph/janusgraph/api.json
./get_issue_list.py jiajunhui/PlayerBase > corpus/jiajunhui/PlayerBase/api.json
./get_issue_list.py guoxiaoxing/android-open-source-project-analysis > corpus/guoxiaoxing/android-open-source-project-analysis/api.json
./get_issue_list.py lapism/MaterialSearchView > corpus/lapism/MaterialSearchView/api.json
./get_issue_list.py AweiLoveAndroid/CommonDevKnowledge > corpus/AweiLoveAndroid/CommonDevKnowledge/api.json
./get_issue_list.py googlesamples/android-Camera2Basic > corpus/googlesamples/android-Camera2Basic/api.json
./get_issue_list.py evrencoskun/TableView > corpus/evrencoskun/TableView/api.json
./get_issue_list.py promeG/TinyPinyin > corpus/promeG/TinyPinyin/api.json
./get_issue_list.py ApmeM/android-flowlayout > corpus/ApmeM/android-flowlayout/api.json
./get_issue_list.py fqrouter/fqrouter > corpus/fqrouter/fqrouter/api.json
./get_issue_list.py wordpress-mobile/WordPress-Android > corpus/wordpress-mobile/WordPress-Android/api.json
./get_issue_list.py skyfishjy/android-ripple-background > corpus/skyfishjy/android-ripple-background/api.json
./get_issue_list.py tiann/understand-plugin-framework > corpus/tiann/understand-plugin-framework/api.json
./get_issue_list.py EverythingMe/overscroll-decor > corpus/EverythingMe/overscroll-decor/api.json
./get_issue_list.py Wizcorp/phonegap-facebook-plugin > corpus/Wizcorp/phonegap-facebook-plugin/api.json
./get_issue_list.py white-cat/ThinkAndroid > corpus/white-cat/ThinkAndroid/api.json
./get_issue_list.py rmtheis/android-ocr > corpus/rmtheis/android-ocr/api.json
./get_issue_list.py KieronQuinn/PersistentSearch > corpus/KieronQuinn/PersistentSearch/api.json
./get_issue_list.py Red5/red5-server > corpus/Red5/red5-server/api.json
./get_issue_list.py elevenetc/TextSurface > corpus/elevenetc/TextSurface/api.json
./get_issue_list.py lisawray/groupie > corpus/lisawray/groupie/api.json
./get_issue_list.py Yalantis/Horizon > corpus/Yalantis/Horizon/api.json
./get_issue_list.py jjdxmashl/jjdxm_ijkplayer > corpus/jjdxmashl/jjdxm_ijkplayer/api.json
./get_issue_list.py yanzhenjie/Album > corpus/yanzhenjie/Album/api.json
./get_issue_list.py jMonkeyEngine/jmonkeyengine > corpus/jMonkeyEngine/jmonkeyengine/api.json
./get_issue_list.py lettuce-io/lettuce-core > corpus/lettuce-io/lettuce-core/api.json
./get_issue_list.py MikeOrtiz/TouchImageView > corpus/MikeOrtiz/TouchImageView/api.json
./get_issue_list.py zhangkaitao/es > corpus/zhangkaitao/es/api.json
./get_issue_list.py Jude95/EasyRecyclerView > corpus/Jude95/EasyRecyclerView/api.json
./get_issue_list.py steelkiwi/cropiwa > corpus/steelkiwi/cropiwa/api.json
./get_issue_list.py zzz40500/AndroidSweetSheet > corpus/zzz40500/AndroidSweetSheet/api.json
./get_issue_list.py LWJGL/lwjgl3 > corpus/LWJGL/lwjgl3/api.json
./get_issue_list.py prontera/spring-cloud-rest-tcc > corpus/prontera/spring-cloud-rest-tcc/api.json
./get_issue_list.py kabouzeid/Phonograph > corpus/kabouzeid/Phonograph/api.json
./get_issue_list.py nutzam/nutz > corpus/nutzam/nutz/api.json
./get_issue_list.py kymjs/KJFrameForAndroid > corpus/kymjs/KJFrameForAndroid/api.json
./get_issue_list.py spotify/helios > corpus/spotify/helios/api.json
./get_issue_list.py mcxtzhang/ZLayoutManager > corpus/mcxtzhang/ZLayoutManager/api.json
./get_issue_list.py Devlight/NavigationTabStrip > corpus/Devlight/NavigationTabStrip/api.json
./get_issue_list.py Krupen/FabulousFilter > corpus/Krupen/FabulousFilter/api.json
./get_issue_list.py fython/MaterialStepperView > corpus/fython/MaterialStepperView/api.json
./get_issue_list.py twosigma/beakerx > corpus/twosigma/beakerx/api.json
./get_issue_list.py pmd/pmd > corpus/pmd/pmd/api.json
./get_issue_list.py yingLanNull/ShadowImageView > corpus/yingLanNull/ShadowImageView/api.json
./get_issue_list.py Netflix/curator > corpus/Netflix/curator/api.json
./get_issue_list.py baoyongzhang/android-PullRefreshLayout > corpus/baoyongzhang/android-PullRefreshLayout/api.json
./get_issue_list.py JanusGraph/janusgraph > corpus/JanusGraph/janusgraph/api.json
./get_issue_list.py jiajunhui/PlayerBase > corpus/jiajunhui/PlayerBase/api.json
./get_issue_list.py guoxiaoxing/android-open-source-project-analysis > corpus/guoxiaoxing/android-open-source-project-analysis/api.json
./get_issue_list.py lapism/MaterialSearchView > corpus/lapism/MaterialSearchView/api.json
./get_issue_list.py AweiLoveAndroid/CommonDevKnowledge > corpus/AweiLoveAndroid/CommonDevKnowledge/api.json
./get_issue_list.py googlesamples/android-Camera2Basic > corpus/googlesamples/android-Camera2Basic/api.json
./get_issue_list.py evrencoskun/TableView > corpus/evrencoskun/TableView/api.json
./get_issue_list.py promeG/TinyPinyin > corpus/promeG/TinyPinyin/api.json
./get_issue_list.py ApmeM/android-flowlayout > corpus/ApmeM/android-flowlayout/api.json
./get_issue_list.py fqrouter/fqrouter > corpus/fqrouter/fqrouter/api.json
./get_issue_list.py wordpress-mobile/WordPress-Android > corpus/wordpress-mobile/WordPress-Android/api.json
./get_issue_list.py skyfishjy/android-ripple-background > corpus/skyfishjy/android-ripple-background/api.json
./get_issue_list.py tiann/understand-plugin-framework > corpus/tiann/understand-plugin-framework/api.json
./get_issue_list.py EverythingMe/overscroll-decor > corpus/EverythingMe/overscroll-decor/api.json
./get_issue_list.py Wizcorp/phonegap-facebook-plugin > corpus/Wizcorp/phonegap-facebook-plugin/api.json
./get_issue_list.py white-cat/ThinkAndroid > corpus/white-cat/ThinkAndroid/api.json
./get_issue_list.py rmtheis/android-ocr > corpus/rmtheis/android-ocr/api.json
./get_issue_list.py KieronQuinn/PersistentSearch > corpus/KieronQuinn/PersistentSearch/api.json
./get_issue_list.py Red5/red5-server > corpus/Red5/red5-server/api.json
./get_issue_list.py elevenetc/TextSurface > corpus/elevenetc/TextSurface/api.json
./get_issue_list.py lisawray/groupie > corpus/lisawray/groupie/api.json
./get_issue_list.py Yalantis/Horizon > corpus/Yalantis/Horizon/api.json
./get_issue_list.py jjdxmashl/jjdxm_ijkplayer > corpus/jjdxmashl/jjdxm_ijkplayer/api.json
./get_issue_list.py yanzhenjie/Album > corpus/yanzhenjie/Album/api.json
./get_issue_list.py jMonkeyEngine/jmonkeyengine > corpus/jMonkeyEngine/jmonkeyengine/api.json
./get_issue_list.py JingYeoh/FragmentRigger > corpus/JingYeoh/FragmentRigger/api.json
./get_issue_list.py reactor/reactor-core > corpus/reactor/reactor-core/api.json
./get_issue_list.py nanchen2251/CompressHelper > corpus/nanchen2251/CompressHelper/api.json
./get_issue_list.py addthis/stream-lib > corpus/addthis/stream-lib/api.json
./get_issue_list.py jboss-javassist/javassist > corpus/jboss-javassist/javassist/api.json
./get_issue_list.py novoda/android-demos > corpus/novoda/android-demos/api.json
./get_issue_list.py FasterXML/jackson-databind > corpus/FasterXML/jackson-databind/api.json
./get_issue_list.py flavienlaurent/datetimepicker > corpus/flavienlaurent/datetimepicker/api.json
./get_issue_list.py fanrunqi/MaterialLogin > corpus/fanrunqi/MaterialLogin/api.json
./get_issue_list.py MindorksOpenSource/PRDownloader > corpus/MindorksOpenSource/PRDownloader/api.json
./get_issue_list.py RomainPiel/Shimmer-android > corpus/RomainPiel/Shimmer-android/api.json
./get_issue_list.py seaswalker/Spring > corpus/seaswalker/Spring/api.json
./get_issue_list.py gongwen/MarqueeViewLibrary > corpus/gongwen/MarqueeViewLibrary/api.json
./get_issue_list.py ethereum/ethereumj > corpus/ethereum/ethereumj/api.json
./get_issue_list.py AlexLiuSheng/CheckVersionLib > corpus/AlexLiuSheng/CheckVersionLib/api.json
./get_issue_list.py bingoogolapple/BGASwipeBackLayout-Android > corpus/bingoogolapple/BGASwipeBackLayout-Android/api.json
./get_issue_list.py KingJA/LoadSir > corpus/KingJA/LoadSir/api.json
./get_issue_list.py jcoleman/tomcat-redis-session-manager > corpus/jcoleman/tomcat-redis-session-manager/api.json
./get_issue_list.py googlesamples/android-play-location > corpus/googlesamples/android-play-location/api.json
./get_issue_list.py traccar/traccar > corpus/traccar/traccar/api.json
./get_issue_list.py ImmortalZ/StereoView > corpus/ImmortalZ/StereoView/api.json
./get_issue_list.py alibaba/DataX > corpus/alibaba/DataX/api.json
./get_issue_list.py apache/mahout > corpus/apache/mahout/api.json
./get_issue_list.py Athou/commafeed > corpus/Athou/commafeed/api.json
./get_issue_list.py MiCode/Notes > corpus/MiCode/Notes/api.json
./get_issue_list.py codingXiaxw/seckill > corpus/codingXiaxw/seckill/api.json
./get_issue_list.py anjlab/android-inapp-billing-v3 > corpus/anjlab/android-inapp-billing-v3/api.json
./get_issue_list.py Jungerr/GridPasswordView > corpus/Jungerr/GridPasswordView/api.json
./get_issue_list.py mancj/SlideUp-Android > corpus/mancj/SlideUp-Android/api.json
./get_issue_list.py medyo/Fancybuttons > corpus/medyo/Fancybuttons/api.json
./get_issue_list.py liyiorg/weixin-popular > corpus/liyiorg/weixin-popular/api.json
./get_issue_list.py nispok/snackbar > corpus/nispok/snackbar/api.json
./get_issue_list.py jokermonn/permissions4m > corpus/jokermonn/permissions4m/api.json
./get_issue_list.py qdrzwd/VideoRecorder > corpus/qdrzwd/VideoRecorder/api.json
./get_issue_list.py liuguangqiang/SwipeBack > corpus/liuguangqiang/SwipeBack/api.json
./get_issue_list.py harism/android-pagecurl > corpus/harism/android-pagecurl/api.json
./get_issue_list.py xmuSistone/VerticalSlideFragment > corpus/xmuSistone/VerticalSlideFragment/api.json
./get_issue_list.py dingjikerbo/BluetoothKit > corpus/dingjikerbo/BluetoothKit/api.json
./get_issue_list.py speedment/speedment > corpus/speedment/speedment/api.json
./get_issue_list.py google/truth > corpus/google/truth/api.json
./get_issue_list.py stephentuso/welcome-android > corpus/stephentuso/welcome-android/api.json
./get_issue_list.py parse-community/Parse-SDK-Android > corpus/parse-community/Parse-SDK-Android/api.json
./get_issue_list.py avjinder/Minimal-Todo > corpus/avjinder/Minimal-Todo/api.json
./get_issue_list.py mancj/MaterialSearchBar > corpus/mancj/MaterialSearchBar/api.json
./get_issue_list.py alibaba/jvm-sandbox > corpus/alibaba/jvm-sandbox/api.json
./get_issue_list.py Froussios/Intro-To-RxJava > corpus/Froussios/Intro-To-RxJava/api.json
./get_issue_list.py mthli/Knife > corpus/mthli/Knife/api.json
./get_issue_list.py pilgr/Paper > corpus/pilgr/Paper/api.json
./get_issue_list.py libgdx/packr > corpus/libgdx/packr/api.json
./get_issue_list.py java8/Java8InAction > corpus/java8/Java8InAction/api.json
./get_issue_list.py apache/nutch > corpus/apache/nutch/api.json
./get_issue_list.py testcontainers/testcontainers-java > corpus/testcontainers/testcontainers-java/api.json
./get_issue_list.py Netflix/archaius > corpus/Netflix/archaius/api.json
./get_issue_list.py FudanNLP/fnlp > corpus/FudanNLP/fnlp/api.json
