./get_msg_nom.sh repo100/java-design-patterns > corpus/iluwatar/java-design-patterns/msg_nom.txt
./get_msg_nom.sh repo100/RxJava > corpus/ReactiveX/RxJava/msg_nom.txt
./get_msg_nom.sh repo100/elasticsearch > corpus/elastic/elasticsearch/msg_nom.txt
./get_msg_nom.sh repo100/retrofit > corpus/square/retrofit/msg_nom.txt
./get_msg_nom.sh repo100/okhttp > corpus/square/okhttp/msg_nom.txt
./get_msg_nom.sh repo100/spring-boot > corpus/spring-projects/spring-boot/msg_nom.txt
./get_msg_nom.sh repo100/guava > corpus/google/guava/msg_nom.txt
./get_msg_nom.sh repo100/interviews > corpus/kdn251/interviews/msg_nom.txt
./get_msg_nom.sh repo100/MPAndroidChart > corpus/PhilJay/MPAndroidChart/msg_nom.txt
./get_msg_nom.sh repo100/glide > corpus/bumptech/glide/msg_nom.txt
./get_msg_nom.sh repo100/spring-framework > corpus/spring-projects/spring-framework/msg_nom.txt
./get_msg_nom.sh repo100/lottie-android > corpus/airbnb/lottie-android/msg_nom.txt
./get_msg_nom.sh repo100/butterknife > corpus/JakeWharton/butterknife/msg_nom.txt
./get_msg_nom.sh repo100/incubator-dubbo > corpus/apache/incubator-dubbo/msg_nom.txt
./get_msg_nom.sh repo100/leakcanary > corpus/square/leakcanary/msg_nom.txt
./get_msg_nom.sh repo100/zxing > corpus/zxing/zxing/msg_nom.txt
./get_msg_nom.sh repo100/AndroidUtilCode > corpus/Blankj/AndroidUtilCode/msg_nom.txt
./get_msg_nom.sh repo100/EventBus > corpus/greenrobot/EventBus/msg_nom.txt
./get_msg_nom.sh repo100/RxAndroid > corpus/ReactiveX/RxAndroid/msg_nom.txt
./get_msg_nom.sh repo100/Android-Universal-Image-Loader > corpus/nostra13/Android-Universal-Image-Loader/msg_nom.txt
./get_msg_nom.sh repo100/picasso > corpus/square/picasso/msg_nom.txt
./get_msg_nom.sh repo100/iosched > corpus/google/iosched/msg_nom.txt
./get_msg_nom.sh repo100/jadx > corpus/skylot/jadx/msg_nom.txt
./get_msg_nom.sh repo100/netty > corpus/netty/netty/msg_nom.txt
./get_msg_nom.sh repo100/fresco > corpus/facebook/fresco/msg_nom.txt
./get_msg_nom.sh repo100/fastjson > corpus/alibaba/fastjson/msg_nom.txt
./get_msg_nom.sh repo100/BaseRecyclerViewAdapterHelper > corpus/CymChad/BaseRecyclerViewAdapterHelper/msg_nom.txt
./get_msg_nom.sh repo100/Hystrix > corpus/Netflix/Hystrix/msg_nom.txt
./get_msg_nom.sh repo100/libgdx > corpus/libgdx/libgdx/msg_nom.txt
./get_msg_nom.sh repo100/material-dialogs > corpus/afollestad/material-dialogs/msg_nom.txt
./get_msg_nom.sh repo100/PhotoView > corpus/chrisbanes/PhotoView/msg_nom.txt
./get_msg_nom.sh repo100/SmartRefreshLayout > corpus/scwang90/SmartRefreshLayout/msg_nom.txt
./get_msg_nom.sh repo100/gson > corpus/google/gson/msg_nom.txt
./get_msg_nom.sh repo100/druid > corpus/alibaba/druid/msg_nom.txt
./get_msg_nom.sh repo100/tinker > corpus/Tencent/tinker/msg_nom.txt
./get_msg_nom.sh repo100/proxyee-down > corpus/proxyee-down-org/proxyee-down/msg_nom.txt
./get_msg_nom.sh repo100/Android-CleanArchitecture > corpus/android10/Android-CleanArchitecture/msg_nom.txt
./get_msg_nom.sh repo100/Material-Animations > corpus/lgvalle/Material-Animations/msg_nom.txt
./get_msg_nom.sh repo100/plaid > corpus/nickbutcher/plaid/msg_nom.txt
./get_msg_nom.sh repo100/selenium > corpus/SeleniumHQ/selenium/msg_nom.txt
./get_msg_nom.sh repo100/SlidingMenu > corpus/jfeinstein10/SlidingMenu/msg_nom.txt
./get_msg_nom.sh repo100/zheng > corpus/shuzheng/zheng/msg_nom.txt
./get_msg_nom.sh repo100/jenkins > corpus/jenkinsci/jenkins/msg_nom.txt
./get_msg_nom.sh repo100/ExoPlayer > corpus/google/ExoPlayer/msg_nom.txt
./get_msg_nom.sh repo100/androidannotations > corpus/androidannotations/androidannotations/msg_nom.txt
./get_msg_nom.sh repo100/greenDAO > corpus/greenrobot/greenDAO/msg_nom.txt
./get_msg_nom.sh repo100/AndroidSwipeLayout > corpus/daimajia/AndroidSwipeLayout/msg_nom.txt
./get_msg_nom.sh repo100/android-async-http > corpus/loopj/android-async-http/msg_nom.txt
./get_msg_nom.sh repo100/Telegram > corpus/DrKLO/Telegram/msg_nom.txt
./get_msg_nom.sh repo100/CircleImageView > corpus/hdodenhof/CircleImageView/msg_nom.txt
./get_msg_nom.sh repo100/incubator-weex > corpus/apache/incubator-weex/msg_nom.txt
./get_msg_nom.sh repo100/stetho > corpus/facebook/stetho/msg_nom.txt
./get_msg_nom.sh repo100/Signal-Android > corpus/signalapp/Signal-Android/msg_nom.txt
./get_msg_nom.sh repo100/ViewPagerIndicator > corpus/JakeWharton/ViewPagerIndicator/msg_nom.txt
./get_msg_nom.sh repo100/realm-java > corpus/realm/realm-java/msg_nom.txt
./get_msg_nom.sh repo100/AndroidViewAnimations > corpus/daimajia/AndroidViewAnimations/msg_nom.txt
./get_msg_nom.sh repo100/java8-tutorial > corpus/winterbe/java8-tutorial/msg_nom.txt
./get_msg_nom.sh repo100/bazel > corpus/bazelbuild/bazel/msg_nom.txt
./get_msg_nom.sh repo100/logger > corpus/orhanobut/logger/msg_nom.txt
./get_msg_nom.sh repo100/bytecode-viewer > corpus/Konloch/bytecode-viewer/msg_nom.txt
./get_msg_nom.sh repo100/MaterialDrawer > corpus/mikepenz/MaterialDrawer/msg_nom.txt
./get_msg_nom.sh repo100/FizzBuzzEnterpriseEdition > corpus/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/msg_nom.txt
./get_msg_nom.sh repo100/deeplearning4j > corpus/deeplearning4j/deeplearning4j/msg_nom.txt
./get_msg_nom.sh repo100/PocketHub > corpus/pockethub/PocketHub/msg_nom.txt
./get_msg_nom.sh repo100/android-Ultra-Pull-To-Refresh > corpus/liaohuqiu/android-Ultra-Pull-To-Refresh/msg_nom.txt
./get_msg_nom.sh repo100/zipkin > corpus/openzipkin/zipkin/msg_nom.txt
./get_msg_nom.sh repo100/storm > corpus/nathanmarz/storm/msg_nom.txt
./get_msg_nom.sh repo100/kafka > corpus/apache/kafka/msg_nom.txt
./get_msg_nom.sh repo100/Android-ObservableScrollView > corpus/ksoichiro/Android-ObservableScrollView/msg_nom.txt
./get_msg_nom.sh repo100/MaterialDesignLibrary > corpus/navasmdc/MaterialDesignLibrary/msg_nom.txt
./get_msg_nom.sh repo100/Android-PullToRefresh > corpus/chrisbanes/Android-PullToRefresh/msg_nom.txt
./get_msg_nom.sh repo100/vlayout > corpus/alibaba/vlayout/msg_nom.txt
./get_msg_nom.sh repo100/recyclerview-animators > corpus/wasabeef/recyclerview-animators/msg_nom.txt
./get_msg_nom.sh repo100/VasSonic > corpus/Tencent/VasSonic/msg_nom.txt
./get_msg_nom.sh repo100/vert.x > corpus/eclipse/vert.x/msg_nom.txt
./get_msg_nom.sh repo100/HanLP > corpus/hankcs/HanLP/msg_nom.txt
./get_msg_nom.sh repo100/react-native-navigation > corpus/wix/react-native-navigation/msg_nom.txt
./get_msg_nom.sh repo100/disruptor > corpus/LMAX-Exchange/disruptor/msg_nom.txt
./get_msg_nom.sh repo100/Luban > corpus/Curzibn/Luban/msg_nom.txt
./get_msg_nom.sh repo100/mybatis-3 > corpus/mybatis/mybatis-3/msg_nom.txt
./get_msg_nom.sh repo100/Java-Interview > corpus/crossoverJie/Java-Interview/msg_nom.txt
./get_msg_nom.sh repo100/BottomBar > corpus/roughike/BottomBar/msg_nom.txt
./get_msg_nom.sh repo100/okhttp-OkGo > corpus/jeasonlzy/okhttp-OkGo/msg_nom.txt
./get_msg_nom.sh repo100/Android-PickerView > corpus/Bigkoo/Android-PickerView/msg_nom.txt
./get_msg_nom.sh repo100/AppIntro > corpus/apl-devs/AppIntro/msg_nom.txt
./get_msg_nom.sh repo100/Calligraphy > corpus/chrisjenx/Calligraphy/msg_nom.txt
./get_msg_nom.sh repo100/presto > corpus/prestodb/presto/msg_nom.txt
./get_msg_nom.sh repo100/HomeMirror > corpus/HannahMitt/HomeMirror/msg_nom.txt
./get_msg_nom.sh repo100/AndroidSlidingUpPanel > corpus/umano/AndroidSlidingUpPanel/msg_nom.txt
./get_msg_nom.sh repo100/platform_frameworks_base > corpus/aosp-mirror/platform_frameworks_base/msg_nom.txt
./get_msg_nom.sh repo100/RxBinding > corpus/JakeWharton/RxBinding/msg_nom.txt
./get_msg_nom.sh repo100/hadoop > corpus/apache/hadoop/msg_nom.txt
./get_msg_nom.sh repo100/AVLoadingIndicatorView > corpus/81813780/AVLoadingIndicatorView/msg_nom.txt
./get_msg_nom.sh repo100/PermissionsDispatcher > corpus/permissions-dispatcher/PermissionsDispatcher/msg_nom.txt
./get_msg_nom.sh repo100/spark > corpus/perwendel/spark/msg_nom.txt
./get_msg_nom.sh repo100/cheesesquare > corpus/chrisbanes/cheesesquare/msg_nom.txt
./get_msg_nom.sh repo100/MaterialViewPager > corpus/florent37/MaterialViewPager/msg_nom.txt
./get_msg_nom.sh repo100/Matisse > corpus/zhihu/Matisse/msg_nom.txt
./get_msg_nom.sh repo100/HikariCP > corpus/brettwooldridge/HikariCP/msg_nom.txt
./get_msg_nom.sh repo100/uCrop > corpus/Yalantis/uCrop/msg_nom.txt
