./get_hash.py corpus2/youlookwhat/CloudReader/summary.json > corpus2/youlookwhat/CloudReader/hash.json
./get_hash.py corpus2/gzu-liyujiang/AndroidPicker/summary.json > corpus2/gzu-liyujiang/AndroidPicker/hash.json
./get_hash.py corpus2/ivacf/archi/summary.json > corpus2/ivacf/archi/hash.json
./get_hash.py corpus2/sunfusheng/MarqueeView/summary.json > corpus2/sunfusheng/MarqueeView/hash.json
./get_hash.py corpus2/sunfusheng/StickyHeaderListView/summary.json > corpus2/sunfusheng/StickyHeaderListView/hash.json
./get_hash.py corpus2/jcoleman/tomcat-redis-session-manager/summary.json > corpus2/jcoleman/tomcat-redis-session-manager/hash.json
./get_hash.py corpus2/HannahMitt/HomeMirror/summary.json > corpus2/HannahMitt/HomeMirror/hash.json
./get_hash.py corpus2/tangqi92/Android-Tips/summary.json > corpus2/tangqi92/Android-Tips/hash.json
./get_hash.py corpus2/dyc87112/SpringBoot-Learning/summary.json > corpus2/dyc87112/SpringBoot-Learning/hash.json
./get_hash.py corpus2/dyc87112/SpringCloud-Learning/summary.json > corpus2/dyc87112/SpringCloud-Learning/hash.json
./get_hash.py corpus2/AndroidBootstrap/android-bootstrap/summary.json > corpus2/AndroidBootstrap/android-bootstrap/hash.json
./get_hash.py corpus2/rest-assured/rest-assured/summary.json > corpus2/rest-assured/rest-assured/hash.json
./get_hash.py corpus2/xuxueli/xxl-job/summary.json > corpus2/xuxueli/xxl-job/hash.json
./get_hash.py corpus2/dm77/barcodescanner/summary.json > corpus2/dm77/barcodescanner/hash.json
./get_hash.py corpus2/r0adkll/Slidr/summary.json > corpus2/r0adkll/Slidr/hash.json
./get_hash.py corpus2/w446108264/XhsEmoticonsKeyboard/summary.json > corpus2/w446108264/XhsEmoticonsKeyboard/hash.json
./get_hash.py corpus2/voldemort/voldemort/summary.json > corpus2/voldemort/voldemort/hash.json
./get_hash.py corpus2/mancj/MaterialSearchBar/summary.json > corpus2/mancj/MaterialSearchBar/hash.json
./get_hash.py corpus2/mancj/SlideUp-Android/summary.json > corpus2/mancj/SlideUp-Android/hash.json
./get_hash.py corpus2/pxb1988/dex2jar/summary.json > corpus2/pxb1988/dex2jar/hash.json
./get_hash.py corpus2/roboguice/roboguice/summary.json > corpus2/roboguice/roboguice/hash.json
./get_hash.py corpus2/spring-projects/spring-loaded/summary.json > corpus2/spring-projects/spring-loaded/hash.json
./get_hash.py corpus2/spring-projects/spring-petclinic/summary.json > corpus2/spring-projects/spring-petclinic/hash.json
./get_hash.py corpus2/spring-projects/spring-data-examples/summary.json > corpus2/spring-projects/spring-data-examples/hash.json
./get_hash.py corpus2/spring-projects/spring-security/summary.json > corpus2/spring-projects/spring-security/hash.json
./get_hash.py corpus2/spring-projects/spring-security-oauth/summary.json > corpus2/spring-projects/spring-security-oauth/hash.json
./get_hash.py corpus2/spring-projects/spring-mvc-showcase/summary.json > corpus2/spring-projects/spring-mvc-showcase/hash.json
./get_hash.py corpus2/vinc3m1/RoundedImageView/summary.json > corpus2/vinc3m1/RoundedImageView/hash.json
./get_hash.py corpus2/chentao0707/SimplifyReader/summary.json > corpus2/chentao0707/SimplifyReader/hash.json
./get_hash.py corpus2/theDazzler/droidicon/summary.json > corpus2/theDazzler/droidicon/hash.json
./get_hash.py corpus2/ittianyu/BottomNavigationViewEx/summary.json > corpus2/ittianyu/BottomNavigationViewEx/hash.json
./get_hash.py corpus2/swagger-api/swagger-core/summary.json > corpus2/swagger-api/swagger-core/hash.json
./get_hash.py corpus2/emilsjolander/StickyListHeaders/summary.json > corpus2/emilsjolander/StickyListHeaders/hash.json
./get_hash.py corpus2/iPaulPro/Android-ItemTouchHelper-Demo/summary.json > corpus2/iPaulPro/Android-ItemTouchHelper-Demo/hash.json
./get_hash.py corpus2/lets-blade/blade/summary.json > corpus2/lets-blade/blade/hash.json
./get_hash.py corpus2/soarcn/BottomSheet/summary.json > corpus2/soarcn/BottomSheet/hash.json
./get_hash.py corpus2/NanoHttpd/nanohttpd/summary.json > corpus2/NanoHttpd/nanohttpd/hash.json
./get_hash.py corpus2/languagetool-org/languagetool/summary.json > corpus2/languagetool-org/languagetool/hash.json
./get_hash.py corpus2/aragozin/jvm-tools/summary.json > corpus2/aragozin/jvm-tools/hash.json
./get_hash.py corpus2/Teevity/ice/summary.json > corpus2/Teevity/ice/hash.json
./get_hash.py corpus2/huanghaibin-dev/CalendarView/summary.json > corpus2/huanghaibin-dev/CalendarView/hash.json
./get_hash.py corpus2/asLody/VirtualApp/summary.json > corpus2/asLody/VirtualApp/hash.json
./get_hash.py corpus2/seven332/EhViewer/summary.json > corpus2/seven332/EhViewer/hash.json
./get_hash.py corpus2/immutables/immutables/summary.json > corpus2/immutables/immutables/hash.json
./get_hash.py corpus2/TeamAmaze/AmazeFileManager/summary.json > corpus2/TeamAmaze/AmazeFileManager/hash.json
./get_hash.py corpus2/zzhoujay/RichText/summary.json > corpus2/zzhoujay/RichText/hash.json
./get_hash.py corpus2/mxn21/FlowingDrawer/summary.json > corpus2/mxn21/FlowingDrawer/hash.json
./get_hash.py corpus2/chanjarster/weixin-java-tools/summary.json > corpus2/chanjarster/weixin-java-tools/hash.json
./get_hash.py corpus2/bmelnychuk/AndroidTreeView/summary.json > corpus2/bmelnychuk/AndroidTreeView/hash.json
./get_hash.py corpus2/bytedeco/javacv/summary.json > corpus2/bytedeco/javacv/hash.json
./get_hash.py corpus2/bytedeco/javacpp/summary.json > corpus2/bytedeco/javacpp/hash.json
./get_hash.py corpus2/CameraKit/blurkit-android/summary.json > corpus2/CameraKit/blurkit-android/hash.json
./get_hash.py corpus2/jpush/aurora-imui/summary.json > corpus2/jpush/aurora-imui/hash.json
./get_hash.py corpus2/sockeqwe/AdapterDelegates/summary.json > corpus2/sockeqwe/AdapterDelegates/hash.json
./get_hash.py corpus2/sockeqwe/mosby/summary.json > corpus2/sockeqwe/mosby/hash.json
./get_hash.py corpus2/linkedin/databus/summary.json > corpus2/linkedin/databus/hash.json
./get_hash.py corpus2/spotify/helios/summary.json > corpus2/spotify/helios/hash.json
./get_hash.py corpus2/goldze/MVVMHabit/summary.json > corpus2/goldze/MVVMHabit/hash.json
./get_hash.py corpus2/yixia/VitamioBundle/summary.json > corpus2/yixia/VitamioBundle/hash.json
./get_hash.py corpus2/rey5137/material/summary.json > corpus2/rey5137/material/hash.json
./get_hash.py corpus2/romandanylyk/PageIndicatorView/summary.json > corpus2/romandanylyk/PageIndicatorView/hash.json
./get_hash.py corpus2/zhouchaoyuan/excelPanel/summary.json > corpus2/zhouchaoyuan/excelPanel/hash.json
./get_hash.py corpus2/FudanNLP/fnlp/summary.json > corpus2/FudanNLP/fnlp/hash.json
./get_hash.py corpus2/white-cat/ThinkAndroid/summary.json > corpus2/white-cat/ThinkAndroid/hash.json
./get_hash.py corpus2/gyf-dev/ImmersionBar/summary.json > corpus2/gyf-dev/ImmersionBar/hash.json
./get_hash.py corpus2/XRecyclerView/XRecyclerView/summary.json > corpus2/XRecyclerView/XRecyclerView/hash.json
./get_hash.py corpus2/Red5/red5-server/summary.json > corpus2/Red5/red5-server/hash.json
./get_hash.py corpus2/yasserg/crawler4j/summary.json > corpus2/yasserg/crawler4j/hash.json
./get_hash.py corpus2/RobotiumTech/robotium/summary.json > corpus2/RobotiumTech/robotium/hash.json
./get_hash.py corpus2/ethereum/ethereumj/summary.json > corpus2/ethereum/ethereumj/hash.json
./get_hash.py corpus2/igreenwood/SimpleCropView/summary.json > corpus2/igreenwood/SimpleCropView/hash.json
./get_hash.py corpus2/Jude95/EasyRecyclerView/summary.json > corpus2/Jude95/EasyRecyclerView/hash.json
./get_hash.py corpus2/antoniolg/androidmvp/summary.json > corpus2/antoniolg/androidmvp/hash.json
./get_hash.py corpus2/frogermcs/InstaMaterial/summary.json > corpus2/frogermcs/InstaMaterial/hash.json
./get_hash.py corpus2/phishman3579/java-algorithms-implementation/summary.json > corpus2/phishman3579/java-algorithms-implementation/hash.json
./get_hash.py corpus2/claritylab/lucida/summary.json > corpus2/claritylab/lucida/hash.json
./get_hash.py corpus2/owncloud/android/summary.json > corpus2/owncloud/android/hash.json
./get_hash.py corpus2/oblac/jodd/summary.json > corpus2/oblac/jodd/hash.json
./get_hash.py corpus2/ldoublem/LoadingView/summary.json > corpus2/ldoublem/LoadingView/hash.json
./get_hash.py corpus2/grpc/grpc-java/summary.json > corpus2/grpc/grpc-java/hash.json
./get_hash.py corpus2/youtube/api-samples/summary.json > corpus2/youtube/api-samples/hash.json
./get_hash.py corpus2/ben-manes/caffeine/summary.json > corpus2/ben-manes/caffeine/hash.json
./get_hash.py corpus2/tyrantgit/ExplosionField/summary.json > corpus2/tyrantgit/ExplosionField/hash.json
./get_hash.py corpus2/orientechnologies/orientdb/summary.json > corpus2/orientechnologies/orientdb/hash.json
./get_hash.py corpus2/liyiorg/weixin-popular/summary.json > corpus2/liyiorg/weixin-popular/hash.json
./get_hash.py corpus2/AsyncHttpClient/async-http-client/summary.json > corpus2/AsyncHttpClient/async-http-client/hash.json
./get_hash.py corpus2/wuhaoyu1990/MagicCamera/summary.json > corpus2/wuhaoyu1990/MagicCamera/hash.json
./get_hash.py corpus2/MyCATApache/Mycat-Server/summary.json > corpus2/MyCATApache/Mycat-Server/hash.json
./get_hash.py corpus2/moezbhatti/qksms/summary.json > corpus2/moezbhatti/qksms/hash.json
./get_hash.py corpus2/qiujuer/Genius-Android/summary.json > corpus2/qiujuer/Genius-Android/hash.json
./get_hash.py corpus2/dlew/joda-time-android/summary.json > corpus2/dlew/joda-time-android/hash.json
./get_hash.py corpus2/zwwill/yanxuan-weex-demo/summary.json > corpus2/zwwill/yanxuan-weex-demo/hash.json
./get_hash.py corpus2/aporter/coursera-android/summary.json > corpus2/aporter/coursera-android/hash.json
./get_hash.py corpus2/etsy/AndroidStaggeredGrid/summary.json > corpus2/etsy/AndroidStaggeredGrid/hash.json
./get_hash.py corpus2/real-logic/aeron/summary.json > corpus2/real-logic/aeron/hash.json
./get_hash.py corpus2/yhaolpz/FloatWindow/summary.json > corpus2/yhaolpz/FloatWindow/hash.json
./get_hash.py corpus2/huangyanbin/smartTable/summary.json > corpus2/huangyanbin/smartTable/hash.json
./get_hash.py corpus2/harism/android-pagecurl/summary.json > corpus2/harism/android-pagecurl/hash.json
./get_hash.py corpus2/johannilsson/android-pulltorefresh/summary.json > corpus2/johannilsson/android-pulltorefresh/hash.json
./get_hash.py corpus2/android-cjj/JJSearchViewAnim/summary.json > corpus2/android-cjj/JJSearchViewAnim/hash.json
./get_hash.py corpus2/android-cjj/BeautifulRefreshLayout/summary.json > corpus2/android-cjj/BeautifulRefreshLayout/hash.json
./get_hash.py corpus2/android-cjj/Android-MaterialRefreshLayout/summary.json > corpus2/android-cjj/Android-MaterialRefreshLayout/hash.json
./get_hash.py corpus2/checkstyle/checkstyle/summary.json > corpus2/checkstyle/checkstyle/hash.json
./get_hash.py corpus2/Manabu-GT/ExpandableTextView/summary.json > corpus2/Manabu-GT/ExpandableTextView/hash.json
./get_hash.py corpus2/CalebFenton/simplify/summary.json > corpus2/CalebFenton/simplify/hash.json
./get_hash.py corpus2/florent37/ViewAnimator/summary.json > corpus2/florent37/ViewAnimator/hash.json
./get_hash.py corpus2/florent37/CameraFragment/summary.json > corpus2/florent37/CameraFragment/hash.json
./get_hash.py corpus2/florent37/MaterialViewPager/summary.json > corpus2/florent37/MaterialViewPager/hash.json
./get_hash.py corpus2/florent37/DiagonalLayout/summary.json > corpus2/florent37/DiagonalLayout/hash.json
./get_hash.py corpus2/florent37/ExpectAnim/summary.json > corpus2/florent37/ExpectAnim/hash.json
./get_hash.py corpus2/jfoenixadmin/JFoenix/summary.json > corpus2/jfoenixadmin/JFoenix/hash.json
./get_hash.py corpus2/lygttpod/SuperTextView/summary.json > corpus2/lygttpod/SuperTextView/hash.json
./get_hash.py corpus2/iammert/ScalingLayout/summary.json > corpus2/iammert/ScalingLayout/hash.json
./get_hash.py corpus2/iammert/MaterialIntroView/summary.json > corpus2/iammert/MaterialIntroView/hash.json
./get_hash.py corpus2/wildfly/wildfly/summary.json > corpus2/wildfly/wildfly/hash.json
./get_hash.py corpus2/Activiti/Activiti/summary.json > corpus2/Activiti/Activiti/hash.json
./get_hash.py corpus2/yahoo/anthelion/summary.json > corpus2/yahoo/anthelion/hash.json
./get_hash.py corpus2/konifar/android-material-design-icon-generator-plugin/summary.json > corpus2/konifar/android-material-design-icon-generator-plugin/hash.json
./get_hash.py corpus2/chenupt/SpringIndicator/summary.json > corpus2/chenupt/SpringIndicator/hash.json
./get_hash.py corpus2/hazelcast/hazelcast/summary.json > corpus2/hazelcast/hazelcast/hash.json
./get_hash.py corpus2/andkulikov/Transitions-Everywhere/summary.json > corpus2/andkulikov/Transitions-Everywhere/hash.json
./get_hash.py corpus2/qii/weiciyuan/summary.json > corpus2/qii/weiciyuan/hash.json
./get_hash.py corpus2/pilgr/Paper/summary.json > corpus2/pilgr/Paper/hash.json
./get_hash.py corpus2/path/android-priority-jobqueue/summary.json > corpus2/path/android-priority-jobqueue/hash.json
./get_hash.py corpus2/psaravan/JamsMusicPlayer/summary.json > corpus2/psaravan/JamsMusicPlayer/hash.json
./get_hash.py corpus2/yqritc/RecyclerView-FlexibleDivider/summary.json > corpus2/yqritc/RecyclerView-FlexibleDivider/hash.json
./get_hash.py corpus2/AntennaPod/AntennaPod/summary.json > corpus2/AntennaPod/AntennaPod/hash.json
./get_hash.py corpus2/Nightonke/CoCoin/summary.json > corpus2/Nightonke/CoCoin/hash.json
./get_hash.py corpus2/Nightonke/BoomMenu/summary.json > corpus2/Nightonke/BoomMenu/hash.json
./get_hash.py corpus2/Nightonke/WoWoViewPager/summary.json > corpus2/Nightonke/WoWoViewPager/hash.json
./get_hash.py corpus2/careercup/CtCI-6th-Edition/summary.json > corpus2/careercup/CtCI-6th-Edition/hash.json
./get_hash.py corpus2/careercup/ctci/summary.json > corpus2/careercup/ctci/hash.json
./get_hash.py corpus2/GrenderG/Toasty/summary.json > corpus2/GrenderG/Toasty/hash.json
./get_hash.py corpus2/haifengl/smile/summary.json > corpus2/haifengl/smile/hash.json
./get_hash.py corpus2/katzer/cordova-plugin-local-notifications/summary.json > corpus2/katzer/cordova-plugin-local-notifications/hash.json
./get_hash.py corpus2/lzyzsd/CircleProgress/summary.json > corpus2/lzyzsd/CircleProgress/hash.json
./get_hash.py corpus2/jboss-javassist/javassist/summary.json > corpus2/jboss-javassist/javassist/hash.json
./get_hash.py corpus2/QMUI/QMUI_Android/summary.json > corpus2/QMUI/QMUI_Android/hash.json
./get_hash.py corpus2/dongjunkun/DropDownMenu/summary.json > corpus2/dongjunkun/DropDownMenu/hash.json
./get_hash.py corpus2/jjdxmashl/jjdxm_ijkplayer/summary.json > corpus2/jjdxmashl/jjdxm_ijkplayer/hash.json
./get_hash.py corpus2/jiangqqlmj/FastDev4Android/summary.json > corpus2/jiangqqlmj/FastDev4Android/hash.json
./get_hash.py corpus2/knightliao/disconf/summary.json > corpus2/knightliao/disconf/hash.json
./get_hash.py corpus2/oasisfeng/condom/summary.json > corpus2/oasisfeng/condom/hash.json
./get_hash.py corpus2/ragunathjawahar/android-saripaar/summary.json > corpus2/ragunathjawahar/android-saripaar/hash.json
./get_hash.py corpus2/bauerca/drag-sort-listview/summary.json > corpus2/bauerca/drag-sort-listview/hash.json
./get_hash.py corpus2/lapism/MaterialSearchView/summary.json > corpus2/lapism/MaterialSearchView/hash.json
./get_hash.py corpus2/topjohnwu/Magisk/summary.json > corpus2/topjohnwu/Magisk/hash.json
./get_hash.py corpus2/AweiLoveAndroid/CommonDevKnowledge/summary.json > corpus2/AweiLoveAndroid/CommonDevKnowledge/hash.json
./get_hash.py corpus2/Exrick/xmall/summary.json > corpus2/Exrick/xmall/hash.json
./get_hash.py corpus2/codingXiaxw/seckill/summary.json > corpus2/codingXiaxw/seckill/hash.json
./get_hash.py corpus2/evant/gradle-retrolambda/summary.json > corpus2/evant/gradle-retrolambda/hash.json
./get_hash.py corpus2/sherxon/AlgoDS/summary.json > corpus2/sherxon/AlgoDS/hash.json
./get_hash.py corpus2/javaee-samples/javaee7-samples/summary.json > corpus2/javaee-samples/javaee7-samples/hash.json
./get_hash.py corpus2/Diolor/Swipecards/summary.json > corpus2/Diolor/Swipecards/hash.json
./get_hash.py corpus2/zetbaitsu/Compressor/summary.json > corpus2/zetbaitsu/Compressor/hash.json
./get_hash.py corpus2/LitePalFramework/LitePal/summary.json > corpus2/LitePalFramework/LitePal/hash.json
./get_hash.py corpus2/hitherejoe/animate/summary.json > corpus2/hitherejoe/animate/hash.json
./get_hash.py corpus2/Freelander/Android_Data/summary.json > corpus2/Freelander/Android_Data/hash.json
./get_hash.py corpus2/wasabeef/Blurry/summary.json > corpus2/wasabeef/Blurry/hash.json
./get_hash.py corpus2/wasabeef/glide-transformations/summary.json > corpus2/wasabeef/glide-transformations/hash.json
./get_hash.py corpus2/wasabeef/richeditor-android/summary.json > corpus2/wasabeef/richeditor-android/hash.json
./get_hash.py corpus2/skavanagh/KeyBox/summary.json > corpus2/skavanagh/KeyBox/hash.json
./get_hash.py corpus2/RomainPiel/Shimmer-android/summary.json > corpus2/RomainPiel/Shimmer-android/hash.json
./get_hash.py corpus2/jhy/jsoup/summary.json > corpus2/jhy/jsoup/hash.json
./get_hash.py corpus2/BelooS/ChipsLayoutManager/summary.json > corpus2/BelooS/ChipsLayoutManager/hash.json
./get_hash.py corpus2/prontera/spring-cloud-rest-tcc/summary.json > corpus2/prontera/spring-cloud-rest-tcc/hash.json
./get_hash.py corpus2/beworker/pinned-section-listview/summary.json > corpus2/beworker/pinned-section-listview/hash.json
./get_hash.py corpus2/pushtorefresh/storio/summary.json > corpus2/pushtorefresh/storio/hash.json
./get_hash.py corpus2/jersey/jersey/summary.json > corpus2/jersey/jersey/hash.json
./get_hash.py corpus2/jwtk/jjwt/summary.json > corpus2/jwtk/jjwt/hash.json
./get_hash.py corpus2/aritraroy/UltimateAndroidReference/summary.json > corpus2/aritraroy/UltimateAndroidReference/hash.json
./get_hash.py corpus2/aritraroy/PatternLockView/summary.json > corpus2/aritraroy/PatternLockView/hash.json
./get_hash.py corpus2/elevenetc/TextSurface/summary.json > corpus2/elevenetc/TextSurface/hash.json
./get_hash.py corpus2/bingoogolapple/BGABanner-Android/summary.json > corpus2/bingoogolapple/BGABanner-Android/hash.json
./get_hash.py corpus2/bingoogolapple/BGABadgeView-Android/summary.json > corpus2/bingoogolapple/BGABadgeView-Android/hash.json
./get_hash.py corpus2/bingoogolapple/BGASwipeBackLayout-Android/summary.json > corpus2/bingoogolapple/BGASwipeBackLayout-Android/hash.json
./get_hash.py corpus2/bingoogolapple/BGARefreshLayout-Android/summary.json > corpus2/bingoogolapple/BGARefreshLayout-Android/hash.json
./get_hash.py corpus2/bin456789/Unblock163MusicClient-Xposed/summary.json > corpus2/bin456789/Unblock163MusicClient-Xposed/hash.json
./get_hash.py corpus2/testcontainers/testcontainers-java/summary.json > corpus2/testcontainers/testcontainers-java/hash.json
./get_hash.py corpus2/h2oai/h2o-2/summary.json > corpus2/h2oai/h2o-2/hash.json
./get_hash.py corpus2/h2oai/h2o-3/summary.json > corpus2/h2oai/h2o-3/hash.json
./get_hash.py corpus2/chewiebug/GCViewer/summary.json > corpus2/chewiebug/GCViewer/hash.json
./get_hash.py corpus2/ximsfei/Android-skin-support/summary.json > corpus2/ximsfei/Android-skin-support/hash.json
./get_hash.py corpus2/saulmm/Android-Material-Examples/summary.json > corpus2/saulmm/Android-Material-Examples/hash.json
./get_hash.py corpus2/saulmm/Material-Movies/summary.json > corpus2/saulmm/Material-Movies/hash.json
./get_hash.py corpus2/saulmm/CoordinatorBehaviorExample/summary.json > corpus2/saulmm/CoordinatorBehaviorExample/hash.json
./get_hash.py corpus2/danikula/AndroidVideoCache/summary.json > corpus2/danikula/AndroidVideoCache/hash.json
./get_hash.py corpus2/yanzhenjie/SwipeRecyclerView/summary.json > corpus2/yanzhenjie/SwipeRecyclerView/hash.json
./get_hash.py corpus2/yanzhenjie/NoHttp/summary.json > corpus2/yanzhenjie/NoHttp/hash.json
./get_hash.py corpus2/yanzhenjie/Album/summary.json > corpus2/yanzhenjie/Album/hash.json
./get_hash.py corpus2/yanzhenjie/AndPermission/summary.json > corpus2/yanzhenjie/AndPermission/hash.json
./get_hash.py corpus2/powermock/powermock/summary.json > corpus2/powermock/powermock/hash.json
./get_hash.py corpus2/wordpress-mobile/WordPress-Android/summary.json > corpus2/wordpress-mobile/WordPress-Android/hash.json
./get_hash.py corpus2/vikramkakkar/SublimePicker/summary.json > corpus2/vikramkakkar/SublimePicker/hash.json
./get_hash.py corpus2/nispok/snackbar/summary.json > corpus2/nispok/snackbar/hash.json
./get_hash.py corpus2/android-hacker/VirtualXposed/summary.json > corpus2/android-hacker/VirtualXposed/hash.json
./get_hash.py corpus2/castorflex/SmoothProgressBar/summary.json > corpus2/castorflex/SmoothProgressBar/hash.json
./get_hash.py corpus2/GcsSloop/AndroidNote/summary.json > corpus2/GcsSloop/AndroidNote/hash.json
./get_hash.py corpus2/AriaLyy/Aria/summary.json > corpus2/AriaLyy/Aria/hash.json
./get_hash.py corpus2/Athou/commafeed/summary.json > corpus2/Athou/commafeed/hash.json
./get_hash.py corpus2/xcc3641/SeeWeather/summary.json > corpus2/xcc3641/SeeWeather/hash.json
./get_hash.py corpus2/motianhuo/wechat/summary.json > corpus2/motianhuo/wechat/hash.json
./get_hash.py corpus2/zzz40500/AndroidSweetSheet/summary.json > corpus2/zzz40500/AndroidSweetSheet/hash.json
./get_hash.py corpus2/zzz40500/GsonFormat/summary.json > corpus2/zzz40500/GsonFormat/hash.json
./get_hash.py corpus2/TooTallNate/Java-WebSocket/summary.json > corpus2/TooTallNate/Java-WebSocket/hash.json
./get_hash.py corpus2/Flipboard/bottomsheet/summary.json > corpus2/Flipboard/bottomsheet/hash.json
./get_hash.py corpus2/NYTimes/Store/summary.json > corpus2/NYTimes/Store/hash.json
./get_hash.py corpus2/astuetz/PagerSlidingTabStrip/summary.json > corpus2/astuetz/PagerSlidingTabStrip/hash.json
./get_hash.py corpus2/H07000223/FlycoTabLayout/summary.json > corpus2/H07000223/FlycoTabLayout/hash.json
./get_hash.py corpus2/H07000223/FlycoDialog_Master/summary.json > corpus2/H07000223/FlycoDialog_Master/hash.json
./get_hash.py corpus2/SimonVT/android-menudrawer/summary.json > corpus2/SimonVT/android-menudrawer/hash.json
./get_hash.py corpus2/apereo/cas/summary.json > corpus2/apereo/cas/hash.json
./get_hash.py corpus2/gocd/gocd/summary.json > corpus2/gocd/gocd/hash.json
./get_hash.py corpus2/sqshq/PiggyMetrics/summary.json > corpus2/sqshq/PiggyMetrics/hash.json
./get_hash.py corpus2/koush/ion/summary.json > corpus2/koush/ion/hash.json
./get_hash.py corpus2/Microsoft/malmo/summary.json > corpus2/Microsoft/malmo/hash.json
./get_hash.py corpus2/PipelineAI/pipeline/summary.json > corpus2/PipelineAI/pipeline/hash.json
./get_hash.py corpus2/stephanenicolas/robospice/summary.json > corpus2/stephanenicolas/robospice/hash.json
./get_hash.py corpus2/Skykai521/StickerCamera/summary.json > corpus2/Skykai521/StickerCamera/hash.json
./get_hash.py corpus2/openaphid/android-flip/summary.json > corpus2/openaphid/android-flip/hash.json
./get_hash.py corpus2/zouzg/mybatis-generator-gui/summary.json > corpus2/zouzg/mybatis-generator-gui/hash.json
./get_hash.py corpus2/harjot-oberai/MusicDNA/summary.json > corpus2/harjot-oberai/MusicDNA/hash.json
./get_hash.py corpus2/go-lang-plugin-org/go-lang-idea-plugin/summary.json > corpus2/go-lang-plugin-org/go-lang-idea-plugin/hash.json
./get_hash.py corpus2/xcltapestry/XCL-Charts/summary.json > corpus2/xcltapestry/XCL-Charts/hash.json
./get_hash.py corpus2/redisson/redisson/summary.json > corpus2/redisson/redisson/hash.json
./get_hash.py corpus2/JetBrains/ideavim/summary.json > corpus2/JetBrains/ideavim/hash.json
./get_hash.py corpus2/java-native-access/jna/summary.json > corpus2/java-native-access/jna/hash.json
./get_hash.py corpus2/json-path/JsonPath/summary.json > corpus2/json-path/JsonPath/hash.json
./get_hash.py corpus2/markushi/android-ui/summary.json > corpus2/markushi/android-ui/hash.json
./get_hash.py corpus2/Dimezis/BlurView/summary.json > corpus2/Dimezis/BlurView/hash.json
./get_hash.py corpus2/geftimov/android-pathview/summary.json > corpus2/geftimov/android-pathview/hash.json
./get_hash.py corpus2/Screetsec/TheFatRat/summary.json > corpus2/Screetsec/TheFatRat/hash.json
./get_hash.py corpus2/hussien89aa/AndroidTutorialForBeginners/summary.json > corpus2/hussien89aa/AndroidTutorialForBeginners/hash.json
./get_hash.py corpus2/zaaach/CityPicker/summary.json > corpus2/zaaach/CityPicker/hash.json
./get_hash.py corpus2/sohutv/cachecloud/summary.json > corpus2/sohutv/cachecloud/hash.json
./get_hash.py corpus2/jasonross/Nuwa/summary.json > corpus2/jasonross/Nuwa/hash.json
./get_hash.py corpus2/lightbend/config/summary.json > corpus2/lightbend/config/hash.json
./get_hash.py corpus2/bitcoinj/bitcoinj/summary.json > corpus2/bitcoinj/bitcoinj/hash.json
./get_hash.py corpus2/uber/RIBs/summary.json > corpus2/uber/RIBs/hash.json
./get_hash.py corpus2/uber/NullAway/summary.json > corpus2/uber/NullAway/hash.json
./get_hash.py corpus2/Vedenin/useful-java-links/summary.json > corpus2/Vedenin/useful-java-links/hash.json
./get_hash.py corpus2/ityouknow/spring-boot-examples/summary.json > corpus2/ityouknow/spring-boot-examples/hash.json
./get_hash.py corpus2/ityouknow/spring-cloud-examples/summary.json > corpus2/ityouknow/spring-cloud-examples/hash.json
./get_hash.py corpus2/zo0r/react-native-push-notification/summary.json > corpus2/zo0r/react-native-push-notification/hash.json
./get_hash.py corpus2/Tencent/MSEC/summary.json > corpus2/Tencent/MSEC/hash.json
./get_hash.py corpus2/traccar/traccar/summary.json > corpus2/traccar/traccar/hash.json
./get_hash.py corpus2/futuresimple/android-floating-action-button/summary.json > corpus2/futuresimple/android-floating-action-button/hash.json
./get_hash.py corpus2/xfumihiro/ViewInspector/summary.json > corpus2/xfumihiro/ViewInspector/hash.json
./get_hash.py corpus2/dingjikerbo/BluetoothKit/summary.json > corpus2/dingjikerbo/BluetoothKit/hash.json
./get_hash.py corpus2/sharish/ShimmerRecyclerView/summary.json > corpus2/sharish/ShimmerRecyclerView/hash.json
./get_hash.py corpus2/Meituan-Dianping/Robust/summary.json > corpus2/Meituan-Dianping/Robust/hash.json
./get_hash.py corpus2/Meituan-Dianping/walle/summary.json > corpus2/Meituan-Dianping/walle/hash.json
./get_hash.py corpus2/yangfuhai/afinal/summary.json > corpus2/yangfuhai/afinal/hash.json
./get_hash.py corpus2/yangfuhai/ASimpleCache/summary.json > corpus2/yangfuhai/ASimpleCache/hash.json
./get_hash.py corpus2/andremion/Music-Player/summary.json > corpus2/andremion/Music-Player/hash.json
./get_hash.py corpus2/thingsboard/thingsboard/summary.json > corpus2/thingsboard/thingsboard/hash.json
./get_hash.py corpus2/SpecialCyCi/AndroidResideMenu/summary.json > corpus2/SpecialCyCi/AndroidResideMenu/hash.json
./get_hash.py corpus2/raphw/byte-buddy/summary.json > corpus2/raphw/byte-buddy/hash.json
./get_hash.py corpus2/ybq/Android-SpinKit/summary.json > corpus2/ybq/Android-SpinKit/hash.json
./get_hash.py corpus2/evrencoskun/TableView/summary.json > corpus2/evrencoskun/TableView/hash.json
./get_hash.py corpus2/stfalcon-studio/ChatKit/summary.json > corpus2/stfalcon-studio/ChatKit/hash.json
./get_hash.py corpus2/robinhood/ticker/summary.json > corpus2/robinhood/ticker/hash.json
./get_hash.py corpus2/hefuyicoder/ListenerMusicPlayer/summary.json > corpus2/hefuyicoder/ListenerMusicPlayer/hash.json
./get_hash.py corpus2/jd-alexander/LikeButton/summary.json > corpus2/jd-alexander/LikeButton/hash.json
./get_hash.py corpus2/ming1016/study/summary.json > corpus2/ming1016/study/hash.json
./get_hash.py corpus2/Atmosphere/atmosphere/summary.json > corpus2/Atmosphere/atmosphere/hash.json
./get_hash.py corpus2/material-components/material-components-android/summary.json > corpus2/material-components/material-components-android/hash.json
./get_hash.py corpus2/AbrahamCaiJin/CommonUtilLibrary/summary.json > corpus2/AbrahamCaiJin/CommonUtilLibrary/hash.json
./get_hash.py corpus2/YoKeyword/Fragmentation/summary.json > corpus2/YoKeyword/Fragmentation/hash.json
./get_hash.py corpus2/DylanVann/react-native-fast-image/summary.json > corpus2/DylanVann/react-native-fast-image/hash.json
./get_hash.py corpus2/crazycodeboy/react-native-splash-screen/summary.json > corpus2/crazycodeboy/react-native-splash-screen/hash.json
./get_hash.py corpus2/udacity/Sunshine-Version-2/summary.json > corpus2/udacity/Sunshine-Version-2/hash.json
./get_hash.py corpus2/vespa-engine/vespa/summary.json > corpus2/vespa-engine/vespa/hash.json
./get_hash.py corpus2/nisrulz/sensey/summary.json > corpus2/nisrulz/sensey/hash.json
./get_hash.py corpus2/nisrulz/android-tips-tricks/summary.json > corpus2/nisrulz/android-tips-tricks/hash.json
./get_hash.py corpus2/sd6352051/NiftyDialogEffects/summary.json > corpus2/sd6352051/NiftyDialogEffects/hash.json
./get_hash.py corpus2/firebase/quickstart-android/summary.json > corpus2/firebase/quickstart-android/hash.json
./get_hash.py corpus2/firebase/FirebaseUI-Android/summary.json > corpus2/firebase/FirebaseUI-Android/hash.json
./get_hash.py corpus2/ApmeM/android-flowlayout/summary.json > corpus2/ApmeM/android-flowlayout/hash.json
./get_hash.py corpus2/kaushikgopal/RxJava-Android-Samples/summary.json > corpus2/kaushikgopal/RxJava-Android-Samples/hash.json
./get_hash.py corpus2/willowtreeapps/spruce-android/summary.json > corpus2/willowtreeapps/spruce-android/hash.json
./get_hash.py corpus2/crossoverJie/SSM/summary.json > corpus2/crossoverJie/SSM/hash.json
./get_hash.py corpus2/Jacksgong/JKeyboardPanelSwitch/summary.json > corpus2/Jacksgong/JKeyboardPanelSwitch/hash.json
./get_hash.py corpus2/java8/Java8InAction/summary.json > corpus2/java8/Java8InAction/hash.json
./get_hash.py corpus2/JZ-Darkal/AndroidHttpCapture/summary.json > corpus2/JZ-Darkal/AndroidHttpCapture/hash.json
./get_hash.py corpus2/aws/aws-sdk-java/summary.json > corpus2/aws/aws-sdk-java/hash.json
./get_hash.py corpus2/baomidou/mybatis-plus/summary.json > corpus2/baomidou/mybatis-plus/hash.json
./get_hash.py corpus2/gongwen/MarqueeViewLibrary/summary.json > corpus2/gongwen/MarqueeViewLibrary/hash.json
./get_hash.py corpus2/jprante/elasticsearch-jdbc/summary.json > corpus2/jprante/elasticsearch-jdbc/hash.json
./get_hash.py corpus2/rzwitserloot/lombok/summary.json > corpus2/rzwitserloot/lombok/hash.json
./get_hash.py corpus2/web3j/web3j/summary.json > corpus2/web3j/web3j/hash.json
./get_hash.py corpus2/kymjs/KJFrameForAndroid/summary.json > corpus2/kymjs/KJFrameForAndroid/hash.json
./get_hash.py corpus2/lsjwzh/RecyclerViewPager/summary.json > corpus2/lsjwzh/RecyclerViewPager/hash.json
./get_hash.py corpus2/knowm/XChange/summary.json > corpus2/knowm/XChange/hash.json
./get_hash.py corpus2/jhalterman/failsafe/summary.json > corpus2/jhalterman/failsafe/hash.json
./get_hash.py corpus2/lecho/hellocharts-android/summary.json > corpus2/lecho/hellocharts-android/hash.json
./get_hash.py corpus2/KieronQuinn/PersistentSearch/summary.json > corpus2/KieronQuinn/PersistentSearch/hash.json
./get_hash.py corpus2/auth0/java-jwt/summary.json > corpus2/auth0/java-jwt/hash.json
./get_hash.py corpus2/socketio/socket.io-client-java/summary.json > corpus2/socketio/socket.io-client-java/hash.json
./get_hash.py corpus2/pagehelper/Mybatis-PageHelper/summary.json > corpus2/pagehelper/Mybatis-PageHelper/hash.json
./get_hash.py corpus2/Angel-ML/angel/summary.json > corpus2/Angel-ML/angel/hash.json
./get_hash.py corpus2/skyfishjy/android-ripple-background/summary.json > corpus2/skyfishjy/android-ripple-background/hash.json
./get_hash.py corpus2/cats-oss/android-gpuimage/summary.json > corpus2/cats-oss/android-gpuimage/hash.json
./get_hash.py corpus2/hs-web/hsweb-framework/summary.json > corpus2/hs-web/hsweb-framework/hash.json
./get_hash.py corpus2/iwgang/CountdownView/summary.json > corpus2/iwgang/CountdownView/hash.json
./get_hash.py corpus2/watabou/pixel-dungeon/summary.json > corpus2/watabou/pixel-dungeon/hash.json
./get_hash.py corpus2/nhaarman/ListViewAnimations/summary.json > corpus2/nhaarman/ListViewAnimations/hash.json
./get_hash.py corpus2/LuckSiege/PictureSelector/summary.json > corpus2/LuckSiege/PictureSelector/hash.json
./get_hash.py corpus2/grandcentrix/tray/summary.json > corpus2/grandcentrix/tray/hash.json
./get_hash.py corpus2/hibernate/hibernate-orm/summary.json > corpus2/hibernate/hibernate-orm/hash.json
./get_hash.py corpus2/xmuSistone/VerticalSlideFragment/summary.json > corpus2/xmuSistone/VerticalSlideFragment/hash.json
./get_hash.py corpus2/xmuSistone/ViewpagerTransition/summary.json > corpus2/xmuSistone/ViewpagerTransition/hash.json
./get_hash.py corpus2/xmuSistone/CardSlidePanel/summary.json > corpus2/xmuSistone/CardSlidePanel/hash.json
./get_hash.py corpus2/wyouflf/xUtils/summary.json > corpus2/wyouflf/xUtils/hash.json
./get_hash.py corpus2/wyouflf/xUtils3/summary.json > corpus2/wyouflf/xUtils3/hash.json
./get_hash.py corpus2/iBotPeaches/Apktool/summary.json > corpus2/iBotPeaches/Apktool/hash.json
./get_hash.py corpus2/NLPchina/ansj_seg/summary.json > corpus2/NLPchina/ansj_seg/hash.json
./get_hash.py corpus2/NLPchina/elasticsearch-sql/summary.json > corpus2/NLPchina/elasticsearch-sql/hash.json
./get_hash.py corpus2/code-troopers/android-betterpickers/summary.json > corpus2/code-troopers/android-betterpickers/hash.json
./get_hash.py corpus2/LyndonChin/MasteringAndroidDataBinding/summary.json > corpus2/LyndonChin/MasteringAndroidDataBinding/hash.json
./get_hash.py corpus2/wenmingvs/AndroidProcess/summary.json > corpus2/wenmingvs/AndroidProcess/hash.json
./get_hash.py corpus2/mcxiaoke/android-volley/summary.json > corpus2/mcxiaoke/android-volley/hash.json
./get_hash.py corpus2/mcxiaoke/packer-ng-plugin/summary.json > corpus2/mcxiaoke/packer-ng-plugin/hash.json
./get_hash.py corpus2/JodaOrg/joda-time/summary.json > corpus2/JodaOrg/joda-time/hash.json
./get_hash.py corpus2/mthli/Knife/summary.json > corpus2/mthli/Knife/hash.json
./get_hash.py corpus2/Frank-Zhu/PullZoomView/summary.json > corpus2/Frank-Zhu/PullZoomView/hash.json
./get_hash.py corpus2/MikeOrtiz/TouchImageView/summary.json > corpus2/MikeOrtiz/TouchImageView/hash.json
./get_hash.py corpus2/stleary/JSON-java/summary.json > corpus2/stleary/JSON-java/hash.json
./get_hash.py corpus2/azkaban/azkaban/summary.json > corpus2/azkaban/azkaban/hash.json
./get_hash.py corpus2/aa112901/remusic/summary.json > corpus2/aa112901/remusic/hash.json
./get_hash.py corpus2/KingJA/LoadSir/summary.json > corpus2/KingJA/LoadSir/hash.json
./get_hash.py corpus2/bm-x/PhotoView/summary.json > corpus2/bm-x/PhotoView/hash.json
./get_hash.py corpus2/amlcurran/ShowcaseView/summary.json > corpus2/amlcurran/ShowcaseView/hash.json
./get_hash.py corpus2/fengjundev/Android-Skin-Loader/summary.json > corpus2/fengjundev/Android-Skin-Loader/hash.json
./get_hash.py corpus2/Bigkoo/Android-ConvenientBanner/summary.json > corpus2/Bigkoo/Android-ConvenientBanner/hash.json
./get_hash.py corpus2/amirzaidi/Launcher3/summary.json > corpus2/amirzaidi/Launcher3/hash.json
./get_hash.py corpus2/romainguy/ViewServer/summary.json > corpus2/romainguy/ViewServer/hash.json
./get_hash.py corpus2/prolificinteractive/material-calendarview/summary.json > corpus2/prolificinteractive/material-calendarview/hash.json
./get_hash.py corpus2/danylovolokh/VideoPlayerManager/summary.json > corpus2/danylovolokh/VideoPlayerManager/hash.json
./get_hash.py corpus2/HoraApps/LeafPic/summary.json > corpus2/HoraApps/LeafPic/hash.json
./get_hash.py corpus2/eclipse/jetty.project/summary.json > corpus2/eclipse/jetty.project/hash.json
./get_hash.py corpus2/eclipse/che/summary.json > corpus2/eclipse/che/hash.json
./get_hash.py corpus2/Prototik/HoloEverywhere/summary.json > corpus2/Prototik/HoloEverywhere/hash.json
./get_hash.py corpus2/simple-android-framework/android_design_patterns_analysis/summary.json > corpus2/simple-android-framework/android_design_patterns_analysis/hash.json
./get_hash.py corpus2/arimorty/floatingsearchview/summary.json > corpus2/arimorty/floatingsearchview/hash.json
./get_hash.py corpus2/dropbox/hackpad/summary.json > corpus2/dropbox/hackpad/hash.json
./get_hash.py corpus2/bluelinelabs/Conductor/summary.json > corpus2/bluelinelabs/Conductor/hash.json
./get_hash.py corpus2/bluelinelabs/LoganSquare/summary.json > corpus2/bluelinelabs/LoganSquare/hash.json
./get_hash.py corpus2/yigit/android-priority-jobqueue/summary.json > corpus2/yigit/android-priority-jobqueue/hash.json
./get_hash.py corpus2/eleme/UETool/summary.json > corpus2/eleme/UETool/hash.json
./get_hash.py corpus2/FinalTeam/RxGalleryFinal/summary.json > corpus2/FinalTeam/RxGalleryFinal/hash.json
./get_hash.py corpus2/amulyakhare/TextDrawable/summary.json > corpus2/amulyakhare/TextDrawable/hash.json
./get_hash.py corpus2/rstudio/rstudio/summary.json > corpus2/rstudio/rstudio/hash.json
./get_hash.py corpus2/ryanhoo/StylishMusicPlayer/summary.json > corpus2/ryanhoo/StylishMusicPlayer/hash.json
./get_hash.py corpus2/spring-cloud/spring-cloud-netflix/summary.json > corpus2/spring-cloud/spring-cloud-netflix/hash.json
./get_hash.py corpus2/glomadrian/Grav/summary.json > corpus2/glomadrian/Grav/hash.json
./get_hash.py corpus2/resilience4j/resilience4j/summary.json > corpus2/resilience4j/resilience4j/hash.json
./get_hash.py corpus2/Alluxio/alluxio/summary.json > corpus2/Alluxio/alluxio/hash.json
./get_hash.py corpus2/kevinsawicki/http-request/summary.json > corpus2/kevinsawicki/http-request/hash.json
./get_hash.py corpus2/laobie/StatusBarUtil/summary.json > corpus2/laobie/StatusBarUtil/hash.json
./get_hash.py corpus2/ArthurHub/Android-Image-Cropper/summary.json > corpus2/ArthurHub/Android-Image-Cropper/hash.json
./get_hash.py corpus2/vipshop/vjtools/summary.json > corpus2/vipshop/vjtools/hash.json
./get_hash.py corpus2/reactive-streams/reactive-streams-jvm/summary.json > corpus2/reactive-streams/reactive-streams-jvm/hash.json
./get_hash.py corpus2/seaswalker/Spring/summary.json > corpus2/seaswalker/Spring/hash.json
./get_hash.py corpus2/code-mc/material-icon-lib/summary.json > corpus2/code-mc/material-icon-lib/hash.json
./get_hash.py corpus2/pedrovgs/EffectiveAndroidUI/summary.json > corpus2/pedrovgs/EffectiveAndroidUI/hash.json
./get_hash.py corpus2/pedrovgs/Algorithms/summary.json > corpus2/pedrovgs/Algorithms/hash.json
./get_hash.py corpus2/pedrovgs/DraggablePanel/summary.json > corpus2/pedrovgs/DraggablePanel/hash.json
./get_hash.py corpus2/pedrovgs/AndroidWiFiADB/summary.json > corpus2/pedrovgs/AndroidWiFiADB/hash.json
./get_hash.py corpus2/rengwuxian/RxJavaSamples/summary.json > corpus2/rengwuxian/RxJavaSamples/hash.json
./get_hash.py corpus2/rengwuxian/MaterialEditText/summary.json > corpus2/rengwuxian/MaterialEditText/hash.json
./get_hash.py corpus2/zhou-you/RxEasyHttp/summary.json > corpus2/zhou-you/RxEasyHttp/hash.json
./get_hash.py corpus2/Devlight/NavigationTabStrip/summary.json > corpus2/Devlight/NavigationTabStrip/hash.json
./get_hash.py corpus2/Devlight/NavigationTabBar/summary.json > corpus2/Devlight/NavigationTabBar/hash.json
./get_hash.py corpus2/Devlight/InfiniteCycleViewPager/summary.json > corpus2/Devlight/InfiniteCycleViewPager/hash.json
./get_hash.py corpus2/airbnb/DeepLinkDispatch/summary.json > corpus2/airbnb/DeepLinkDispatch/hash.json
./get_hash.py corpus2/airbnb/epoxy/summary.json > corpus2/airbnb/epoxy/hash.json
./get_hash.py corpus2/airbnb/airpal/summary.json > corpus2/airbnb/airpal/hash.json
./get_hash.py corpus2/airbnb/native-navigation/summary.json > corpus2/airbnb/native-navigation/hash.json
./get_hash.py corpus2/brianfrankcooper/YCSB/summary.json > corpus2/brianfrankcooper/YCSB/hash.json
./get_hash.py corpus2/quartz-scheduler/quartz/summary.json > corpus2/quartz-scheduler/quartz/hash.json
./get_hash.py corpus2/keyboardsurfer/Crouton/summary.json > corpus2/keyboardsurfer/Crouton/hash.json
./get_hash.py corpus2/CellularPrivacy/Android-IMSI-Catcher-Detector/summary.json > corpus2/CellularPrivacy/Android-IMSI-Catcher-Detector/hash.json
./get_hash.py corpus2/vondear/RxTool/summary.json > corpus2/vondear/RxTool/hash.json
./get_hash.py corpus2/elye/loaderviewlibrary/summary.json > corpus2/elye/loaderviewlibrary/hash.json
./get_hash.py corpus2/tiann/understand-plugin-framework/summary.json > corpus2/tiann/understand-plugin-framework/hash.json
./get_hash.py corpus2/TeamNewPipe/NewPipe/summary.json > corpus2/TeamNewPipe/NewPipe/hash.json
./get_hash.py corpus2/libgdx/packr/summary.json > corpus2/libgdx/packr/hash.json
./get_hash.py corpus2/donglua/PhotoPicker/summary.json > corpus2/donglua/PhotoPicker/hash.json
./get_hash.py corpus2/yusugomori/DeepLearning/summary.json > corpus2/yusugomori/DeepLearning/hash.json
./get_hash.py corpus2/Ereza/CustomActivityOnCrash/summary.json > corpus2/Ereza/CustomActivityOnCrash/hash.json
./get_hash.py corpus2/pnikosis/materialish-progress/summary.json > corpus2/pnikosis/materialish-progress/hash.json
./get_hash.py corpus2/mockito/mockito/summary.json > corpus2/mockito/mockito/hash.json
./get_hash.py corpus2/ManuelPeinado/FadingActionBar/summary.json > corpus2/ManuelPeinado/FadingActionBar/hash.json
./get_hash.py corpus2/youth5201314/banner/summary.json > corpus2/youth5201314/banner/hash.json
./get_hash.py corpus2/markzhai/AndroidPerformanceMonitor/summary.json > corpus2/markzhai/AndroidPerformanceMonitor/hash.json
./get_hash.py corpus2/Justson/AgentWeb/summary.json > corpus2/Justson/AgentWeb/hash.json
./get_hash.py corpus2/chrisbanes/cheesesquare/summary.json > corpus2/chrisbanes/cheesesquare/hash.json
./get_hash.py corpus2/chrisbanes/ActionBar-PullToRefresh/summary.json > corpus2/chrisbanes/ActionBar-PullToRefresh/hash.json
./get_hash.py corpus2/chrisbanes/philm/summary.json > corpus2/chrisbanes/philm/hash.json
./get_hash.py corpus2/nicolasgramlich/AndEngine/summary.json > corpus2/nicolasgramlich/AndEngine/hash.json
./get_hash.py corpus2/yarolegovich/SlidingRootNav/summary.json > corpus2/yarolegovich/SlidingRootNav/hash.json
./get_hash.py corpus2/yarolegovich/DiscreteScrollView/summary.json > corpus2/yarolegovich/DiscreteScrollView/hash.json
./get_hash.py corpus2/janishar/mit-deep-learning-book-pdf/summary.json > corpus2/janishar/mit-deep-learning-book-pdf/hash.json
./get_hash.py corpus2/promeG/TinyPinyin/summary.json > corpus2/promeG/TinyPinyin/hash.json
./get_hash.py corpus2/forezp/SpringCloudLearning/summary.json > corpus2/forezp/SpringCloudLearning/hash.json
./get_hash.py corpus2/baoyachi/StepView/summary.json > corpus2/baoyachi/StepView/hash.json
./get_hash.py corpus2/reactor/reactor-core/summary.json > corpus2/reactor/reactor-core/hash.json
./get_hash.py corpus2/Krupen/FabulousFilter/summary.json > corpus2/Krupen/FabulousFilter/hash.json
./get_hash.py corpus2/ZieIony/Carbon/summary.json > corpus2/ZieIony/Carbon/hash.json
./get_hash.py corpus2/addthis/stream-lib/summary.json > corpus2/addthis/stream-lib/hash.json
./get_hash.py corpus2/reark/reark/summary.json > corpus2/reark/reark/hash.json
./get_hash.py corpus2/alibaba/jvm-sandbox/summary.json > corpus2/alibaba/jvm-sandbox/hash.json
./get_hash.py corpus2/alibaba/dexposed/summary.json > corpus2/alibaba/dexposed/hash.json
./get_hash.py corpus2/alibaba/canal/summary.json > corpus2/alibaba/canal/hash.json
./get_hash.py corpus2/alibaba/arthas/summary.json > corpus2/alibaba/arthas/hash.json
./get_hash.py corpus2/alibaba/Tangram-Android/summary.json > corpus2/alibaba/Tangram-Android/hash.json
./get_hash.py corpus2/alibaba/freeline/summary.json > corpus2/alibaba/freeline/hash.json
./get_hash.py corpus2/alibaba/jstorm/summary.json > corpus2/alibaba/jstorm/hash.json
./get_hash.py corpus2/alibaba/cobar/summary.json > corpus2/alibaba/cobar/hash.json
./get_hash.py corpus2/alibaba/easyexcel/summary.json > corpus2/alibaba/easyexcel/hash.json
./get_hash.py corpus2/alibaba/UltraViewPager/summary.json > corpus2/alibaba/UltraViewPager/hash.json
./get_hash.py corpus2/alibaba/Sentinel/summary.json > corpus2/alibaba/Sentinel/hash.json
./get_hash.py corpus2/alibaba/atlas/summary.json > corpus2/alibaba/atlas/hash.json
./get_hash.py corpus2/alibaba/otter/summary.json > corpus2/alibaba/otter/hash.json
./get_hash.py corpus2/alibaba/DataX/summary.json > corpus2/alibaba/DataX/hash.json
./get_hash.py corpus2/objectbox/objectbox-java/summary.json > corpus2/objectbox/objectbox-java/hash.json
./get_hash.py corpus2/stephentuso/welcome-android/summary.json > corpus2/stephentuso/welcome-android/hash.json
./get_hash.py corpus2/twosigma/beakerx/summary.json > corpus2/twosigma/beakerx/hash.json
./get_hash.py corpus2/steelkiwi/cropiwa/summary.json > corpus2/steelkiwi/cropiwa/hash.json
./get_hash.py corpus2/jdamcd/android-crop/summary.json > corpus2/jdamcd/android-crop/hash.json
./get_hash.py corpus2/anjlab/android-inapp-billing-v3/summary.json > corpus2/anjlab/android-inapp-billing-v3/hash.json
./get_hash.py corpus2/DuGuQiuBai/Java/summary.json > corpus2/DuGuQiuBai/Java/hash.json
./get_hash.py corpus2/Freeyourgadget/Gadgetbridge/summary.json > corpus2/Freeyourgadget/Gadgetbridge/hash.json
./get_hash.py corpus2/zhanglei-workspace/shopping-management-system/summary.json > corpus2/zhanglei-workspace/shopping-management-system/hash.json
./get_hash.py corpus2/Ashok-Varma/BottomNavigation/summary.json > corpus2/Ashok-Varma/BottomNavigation/hash.json
./get_hash.py corpus2/oguzbilgener/CircularFloatingActionMenu/summary.json > corpus2/oguzbilgener/CircularFloatingActionMenu/hash.json
./get_hash.py corpus2/jjoe64/GraphView/summary.json > corpus2/jjoe64/GraphView/hash.json
./get_hash.py corpus2/amitshekhariitbhu/RxJava2-Android-Samples/summary.json > corpus2/amitshekhariitbhu/RxJava2-Android-Samples/hash.json
./get_hash.py corpus2/amitshekhariitbhu/Android-Debug-Database/summary.json > corpus2/amitshekhariitbhu/Android-Debug-Database/hash.json
./get_hash.py corpus2/amitshekhariitbhu/awesome-android-complete-reference/summary.json > corpus2/amitshekhariitbhu/awesome-android-complete-reference/hash.json
./get_hash.py corpus2/amitshekhariitbhu/Fast-Android-Networking/summary.json > corpus2/amitshekhariitbhu/Fast-Android-Networking/hash.json
./get_hash.py corpus2/izzyleung/ZhihuDailyPurify/summary.json > corpus2/izzyleung/ZhihuDailyPurify/hash.json
./get_hash.py corpus2/LawnchairLauncher/Lawnchair/summary.json > corpus2/LawnchairLauncher/Lawnchair/hash.json
./get_hash.py corpus2/GitLqr/LQRWeChat/summary.json > corpus2/GitLqr/LQRWeChat/hash.json
./get_hash.py corpus2/wdullaer/MaterialDateTimePicker/summary.json > corpus2/wdullaer/MaterialDateTimePicker/hash.json
./get_hash.py corpus2/scribejava/scribejava/summary.json > corpus2/scribejava/scribejava/hash.json
./get_hash.py corpus2/rmtheis/android-ocr/summary.json > corpus2/rmtheis/android-ocr/hash.json
./get_hash.py corpus2/aurelhubert/ahbottomnavigation/summary.json > corpus2/aurelhubert/ahbottomnavigation/hash.json
./get_hash.py corpus2/flavioarfaria/KenBurnsView/summary.json > corpus2/flavioarfaria/KenBurnsView/hash.json
./get_hash.py corpus2/JulienGenoud/android-percent-support-lib-sample/summary.json > corpus2/JulienGenoud/android-percent-support-lib-sample/hash.json
./get_hash.py corpus2/spring-cloud-incubator/spring-cloud-alibaba/summary.json > corpus2/spring-cloud-incubator/spring-cloud-alibaba/hash.json
./get_hash.py corpus2/zaproxy/zaproxy/summary.json > corpus2/zaproxy/zaproxy/hash.json
./get_hash.py corpus2/antlr/antlr4/summary.json > corpus2/antlr/antlr4/hash.json
./get_hash.py corpus2/Piasy/BigImageViewer/summary.json > corpus2/Piasy/BigImageViewer/hash.json
./get_hash.py corpus2/baoyongzhang/SwipeMenuListView/summary.json > corpus2/baoyongzhang/SwipeMenuListView/hash.json
./get_hash.py corpus2/baoyongzhang/android-PullRefreshLayout/summary.json > corpus2/baoyongzhang/android-PullRefreshLayout/hash.json
./get_hash.py corpus2/GoogleContainerTools/jib/summary.json > corpus2/GoogleContainerTools/jib/hash.json
./get_hash.py corpus2/perwendel/spark/summary.json > corpus2/perwendel/spark/hash.json
./get_hash.py corpus2/springside/springside4/summary.json > corpus2/springside/springside4/hash.json
./get_hash.py corpus2/hackware1993/MagicIndicator/summary.json > corpus2/hackware1993/MagicIndicator/hash.json
./get_hash.py corpus2/joelittlejohn/jsonschema2pojo/summary.json > corpus2/joelittlejohn/jsonschema2pojo/hash.json
./get_hash.py corpus2/springfox/springfox/summary.json > corpus2/springfox/springfox/hash.json
./get_hash.py corpus2/paascloud/paascloud-master/summary.json > corpus2/paascloud/paascloud-master/hash.json
./get_hash.py corpus2/gephi/gephi/summary.json > corpus2/gephi/gephi/hash.json
./get_hash.py corpus2/woxingxiao/BubbleSeekBar/summary.json > corpus2/woxingxiao/BubbleSeekBar/hash.json
./get_hash.py corpus2/lucasr/twoway-view/summary.json > corpus2/lucasr/twoway-view/hash.json
./get_hash.py corpus2/sharding-sphere/sharding-sphere/summary.json > corpus2/sharding-sphere/sharding-sphere/hash.json
./get_hash.py corpus2/sparklemotion/nokogiri/summary.json > corpus2/sparklemotion/nokogiri/hash.json
./get_hash.py corpus2/Marswin/MarsDaemon/summary.json > corpus2/Marswin/MarsDaemon/hash.json
./get_hash.py corpus2/Netflix/eureka/summary.json > corpus2/Netflix/eureka/hash.json
./get_hash.py corpus2/Netflix/ribbon/summary.json > corpus2/Netflix/ribbon/hash.json
./get_hash.py corpus2/Netflix/SimianArmy/summary.json > corpus2/Netflix/SimianArmy/hash.json
./get_hash.py corpus2/Netflix/curator/summary.json > corpus2/Netflix/curator/hash.json
./get_hash.py corpus2/Netflix/archaius/summary.json > corpus2/Netflix/archaius/hash.json
./get_hash.py corpus2/Netflix/zuul/summary.json > corpus2/Netflix/zuul/hash.json
./get_hash.py corpus2/Comcast/FreeFlow/summary.json > corpus2/Comcast/FreeFlow/hash.json
./get_hash.py corpus2/codeestX/GeekNews/summary.json > corpus2/codeestX/GeekNews/hash.json
./get_hash.py corpus2/makovkastar/FloatingActionButton/summary.json > corpus2/makovkastar/FloatingActionButton/hash.json
./get_hash.py corpus2/pengjianbo/GalleryFinal/summary.json > corpus2/pengjianbo/GalleryFinal/hash.json
./get_hash.py corpus2/LWJGL/lwjgl3/summary.json > corpus2/LWJGL/lwjgl3/hash.json
./get_hash.py corpus2/ToxicBakery/ViewPagerTransforms/summary.json > corpus2/ToxicBakery/ViewPagerTransforms/hash.json
./get_hash.py corpus2/AlexLiuSheng/CheckVersionLib/summary.json > corpus2/AlexLiuSheng/CheckVersionLib/hash.json
./get_hash.py corpus2/AltBeacon/android-beacon-library/summary.json > corpus2/AltBeacon/android-beacon-library/hash.json
./get_hash.py corpus2/ChadCSong/ShineButton/summary.json > corpus2/ChadCSong/ShineButton/hash.json
./get_hash.py corpus2/TangoAgency/material-intro-screen/summary.json > corpus2/TangoAgency/material-intro-screen/hash.json
./get_hash.py corpus2/pardom-zz/ActiveAndroid/summary.json > corpus2/pardom-zz/ActiveAndroid/hash.json
./get_hash.py corpus2/k0shk0sh/FastHub/summary.json > corpus2/k0shk0sh/FastHub/hash.json
./get_hash.py corpus2/lovetuzitong/MultiImageSelector/summary.json > corpus2/lovetuzitong/MultiImageSelector/hash.json
./get_hash.py corpus2/eishay/jvm-serializers/summary.json > corpus2/eishay/jvm-serializers/hash.json
./get_hash.py corpus2/north2016/T-MVP/summary.json > corpus2/north2016/T-MVP/hash.json
./get_hash.py corpus2/deano2390/MaterialShowcaseView/summary.json > corpus2/deano2390/MaterialShowcaseView/hash.json
./get_hash.py corpus2/google/j2objc/summary.json > corpus2/google/j2objc/hash.json
./get_hash.py corpus2/google/agera/summary.json > corpus2/google/agera/hash.json
./get_hash.py corpus2/google/hover/summary.json > corpus2/google/hover/hash.json
./get_hash.py corpus2/google/android-classyshark/summary.json > corpus2/google/android-classyshark/hash.json
./get_hash.py corpus2/google/truth/summary.json > corpus2/google/truth/hash.json
./get_hash.py corpus2/google/closure-compiler/summary.json > corpus2/google/closure-compiler/hash.json
./get_hash.py corpus2/google/cameraview/summary.json > corpus2/google/cameraview/hash.json
./get_hash.py corpus2/google/physical-web/summary.json > corpus2/google/physical-web/hash.json
./get_hash.py corpus2/google/binnavi/summary.json > corpus2/google/binnavi/hash.json
./get_hash.py corpus2/google/tink/summary.json > corpus2/google/tink/hash.json
./get_hash.py corpus2/google/volley/summary.json > corpus2/google/volley/hash.json
./get_hash.py corpus2/google/guice/summary.json > corpus2/google/guice/hash.json
./get_hash.py corpus2/google/data-transfer-project/summary.json > corpus2/google/data-transfer-project/hash.json
./get_hash.py corpus2/google/google-java-format/summary.json > corpus2/google/google-java-format/hash.json
./get_hash.py corpus2/google/google-authenticator/summary.json > corpus2/google/google-authenticator/hash.json
./get_hash.py corpus2/google/error-prone/summary.json > corpus2/google/error-prone/hash.json
./get_hash.py corpus2/google/auto/summary.json > corpus2/google/auto/hash.json
./get_hash.py corpus2/FasterXML/jackson-databind/summary.json > corpus2/FasterXML/jackson-databind/hash.json
./get_hash.py corpus2/DingMouRen/LayoutManagerGroup/summary.json > corpus2/DingMouRen/LayoutManagerGroup/hash.json
./get_hash.py corpus2/actorapp/actor-platform/summary.json > corpus2/actorapp/actor-platform/hash.json
./get_hash.py corpus2/react-native-community/react-native-video/summary.json > corpus2/react-native-community/react-native-video/hash.json
./get_hash.py corpus2/react-native-community/react-native-blur/summary.json > corpus2/react-native-community/react-native-blur/hash.json
./get_hash.py corpus2/react-native-community/react-native-svg/summary.json > corpus2/react-native-community/react-native-svg/hash.json
./get_hash.py corpus2/react-native-community/react-native-camera/summary.json > corpus2/react-native-community/react-native-camera/hash.json
./get_hash.py corpus2/kbastani/spring-cloud-microservice-example/summary.json > corpus2/kbastani/spring-cloud-microservice-example/hash.json
./get_hash.py corpus2/dragonflyoss/Dragonfly/summary.json > corpus2/dragonflyoss/Dragonfly/hash.json
./get_hash.py corpus2/ikew0ng/SwipeBackLayout/summary.json > corpus2/ikew0ng/SwipeBackLayout/hash.json
./get_hash.py corpus2/Clans/FloatingActionButton/summary.json > corpus2/Clans/FloatingActionButton/hash.json
./get_hash.py corpus2/xinghongfei/LookLook/summary.json > corpus2/xinghongfei/LookLook/hash.json
./get_hash.py corpus2/JoanZapata/android-iconify/summary.json > corpus2/JoanZapata/android-iconify/hash.json
./get_hash.py corpus2/JoanZapata/android-pdfview/summary.json > corpus2/JoanZapata/android-pdfview/hash.json
./get_hash.py corpus2/Froussios/Intro-To-RxJava/summary.json > corpus2/Froussios/Intro-To-RxJava/hash.json
./get_hash.py corpus2/hongyangAndroid/AndroidAutoLayout/summary.json > corpus2/hongyangAndroid/AndroidAutoLayout/hash.json
./get_hash.py corpus2/hongyangAndroid/Highlight/summary.json > corpus2/hongyangAndroid/Highlight/hash.json
./get_hash.py corpus2/hongyangAndroid/okhttputils/summary.json > corpus2/hongyangAndroid/okhttputils/hash.json
./get_hash.py corpus2/hongyangAndroid/baseAdapter/summary.json > corpus2/hongyangAndroid/baseAdapter/hash.json
./get_hash.py corpus2/hongyangAndroid/FlowLayout/summary.json > corpus2/hongyangAndroid/FlowLayout/hash.json
./get_hash.py corpus2/traex/RippleEffect/summary.json > corpus2/traex/RippleEffect/hash.json
./get_hash.py corpus2/jaydenxiao2016/AndroidFire/summary.json > corpus2/jaydenxiao2016/AndroidFire/hash.json
./get_hash.py corpus2/qdrzwd/VideoRecorder/summary.json > corpus2/qdrzwd/VideoRecorder/hash.json
./get_hash.py corpus2/cryptomator/cryptomator/summary.json > corpus2/cryptomator/cryptomator/hash.json
./get_hash.py corpus2/oldmanpushcart/greys-anatomy/summary.json > corpus2/oldmanpushcart/greys-anatomy/hash.json
./get_hash.py corpus2/luckybilly/CC/summary.json > corpus2/luckybilly/CC/hash.json
./get_hash.py corpus2/Bearded-Hen/Android-Bootstrap/summary.json > corpus2/Bearded-Hen/Android-Bootstrap/hash.json
./get_hash.py corpus2/javaparser/javaparser/summary.json > corpus2/javaparser/javaparser/hash.json
./get_hash.py corpus2/cjlin1/libsvm/summary.json > corpus2/cjlin1/libsvm/hash.json
./get_hash.py corpus2/mihaip/dex-method-counts/summary.json > corpus2/mihaip/dex-method-counts/hash.json
./get_hash.py corpus2/kevin-wayne/algs4/summary.json > corpus2/kevin-wayne/algs4/hash.json
./get_hash.py corpus2/Bilibili/MagicaSakura/summary.json > corpus2/Bilibili/MagicaSakura/hash.json
./get_hash.py corpus2/Bilibili/DanmakuFlameMaster/summary.json > corpus2/Bilibili/DanmakuFlameMaster/hash.json
./get_hash.py corpus2/Bilibili/boxing/summary.json > corpus2/Bilibili/boxing/hash.json
./get_hash.py corpus2/mzule/ActivityRouter/summary.json > corpus2/mzule/ActivityRouter/hash.json
./get_hash.py corpus2/esoxjem/MovieGuide/summary.json > corpus2/esoxjem/MovieGuide/hash.json
./get_hash.py corpus2/shekhargulati/99-problems/summary.json > corpus2/shekhargulati/99-problems/hash.json
./get_hash.py corpus2/mikepenz/AboutLibraries/summary.json > corpus2/mikepenz/AboutLibraries/hash.json
./get_hash.py corpus2/mikepenz/Android-Iconics/summary.json > corpus2/mikepenz/Android-Iconics/hash.json
./get_hash.py corpus2/mikepenz/FastAdapter/summary.json > corpus2/mikepenz/FastAdapter/hash.json
./get_hash.py corpus2/didi/VirtualAPK/summary.json > corpus2/didi/VirtualAPK/hash.json
./get_hash.py corpus2/daimajia/NumberProgressBar/summary.json > corpus2/daimajia/NumberProgressBar/hash.json
./get_hash.py corpus2/daimajia/AnimationEasingFunctions/summary.json > corpus2/daimajia/AnimationEasingFunctions/hash.json
./get_hash.py corpus2/daimajia/AndroidImageSlider/summary.json > corpus2/daimajia/AndroidImageSlider/hash.json
./get_hash.py corpus2/daimajia/AndroidViewHover/summary.json > corpus2/daimajia/AndroidViewHover/hash.json
./get_hash.py corpus2/medyo/Fancybuttons/summary.json > corpus2/medyo/Fancybuttons/hash.json
./get_hash.py corpus2/zagum/Android-SwitchIcon/summary.json > corpus2/zagum/Android-SwitchIcon/hash.json
./get_hash.py corpus2/KeepSafe/TapTargetView/summary.json > corpus2/KeepSafe/TapTargetView/hash.json
./get_hash.py corpus2/jiajunhui/PlayerBase/summary.json > corpus2/jiajunhui/PlayerBase/hash.json
./get_hash.py corpus2/weibocom/motan/summary.json > corpus2/weibocom/motan/hash.json
./get_hash.py corpus2/rubensousa/ViewPagerCards/summary.json > corpus2/rubensousa/ViewPagerCards/hash.json
./get_hash.py corpus2/rubensousa/PreviewSeekBar/summary.json > corpus2/rubensousa/PreviewSeekBar/hash.json
./get_hash.py corpus2/rubensousa/RecyclerViewSnap/summary.json > corpus2/rubensousa/RecyclerViewSnap/hash.json
./get_hash.py corpus2/kickstarter/android-oss/summary.json > corpus2/kickstarter/android-oss/hash.json
./get_hash.py corpus2/chrisjenx/Calligraphy/summary.json > corpus2/chrisjenx/Calligraphy/hash.json
./get_hash.py corpus2/JanusGraph/janusgraph/summary.json > corpus2/JanusGraph/janusgraph/hash.json
./get_hash.py corpus2/MovingBlocks/Terasology/summary.json > corpus2/MovingBlocks/Terasology/hash.json
./get_hash.py corpus2/mcharmas/Android-ReactiveLocation/summary.json > corpus2/mcharmas/Android-ReactiveLocation/hash.json
./get_hash.py corpus2/Blankj/awesome-java-leetcode/summary.json > corpus2/Blankj/awesome-java-leetcode/hash.json
./get_hash.py corpus2/flyway/flyway/summary.json > corpus2/flyway/flyway/hash.json
./get_hash.py corpus2/2dxgujun/AndroidTagGroup/summary.json > corpus2/2dxgujun/AndroidTagGroup/hash.json
./get_hash.py corpus2/Yalantis/Side-Menu.Android/summary.json > corpus2/Yalantis/Side-Menu.Android/hash.json
./get_hash.py corpus2/Yalantis/Euclid/summary.json > corpus2/Yalantis/Euclid/hash.json
./get_hash.py corpus2/Yalantis/uCrop/summary.json > corpus2/Yalantis/uCrop/hash.json
./get_hash.py corpus2/Yalantis/Phoenix/summary.json > corpus2/Yalantis/Phoenix/hash.json
./get_hash.py corpus2/Yalantis/GuillotineMenu-Android/summary.json > corpus2/Yalantis/GuillotineMenu-Android/hash.json
./get_hash.py corpus2/Yalantis/Context-Menu.Android/summary.json > corpus2/Yalantis/Context-Menu.Android/hash.json
./get_hash.py corpus2/Yalantis/Horizon/summary.json > corpus2/Yalantis/Horizon/hash.json
./get_hash.py corpus2/lcodecorex/TwinklingRefreshLayout/summary.json > corpus2/lcodecorex/TwinklingRefreshLayout/hash.json
./get_hash.py corpus2/alamkanak/Android-Week-View/summary.json > corpus2/alamkanak/Android-Week-View/hash.json
./get_hash.py corpus2/ChrisRM/material-theme-jetbrains/summary.json > corpus2/ChrisRM/material-theme-jetbrains/hash.json
./get_hash.py corpus2/rabbitmq/rabbitmq-tutorials/summary.json > corpus2/rabbitmq/rabbitmq-tutorials/hash.json
./get_hash.py corpus2/requery/requery/summary.json > corpus2/requery/requery/hash.json
./get_hash.py corpus2/MinecraftForge/MinecraftForge/summary.json > corpus2/MinecraftForge/MinecraftForge/hash.json
./get_hash.py corpus2/oracle/opengrok/summary.json > corpus2/oracle/opengrok/hash.json
./get_hash.py corpus2/oracle/graal/summary.json > corpus2/oracle/graal/hash.json
./get_hash.py corpus2/googlesamples/android-testing/summary.json > corpus2/googlesamples/android-testing/hash.json
./get_hash.py corpus2/googlesamples/google-services/summary.json > corpus2/googlesamples/google-services/hash.json
./get_hash.py corpus2/googlesamples/easypermissions/summary.json > corpus2/googlesamples/easypermissions/hash.json
./get_hash.py corpus2/googlesamples/android-vision/summary.json > corpus2/googlesamples/android-vision/hash.json
./get_hash.py corpus2/googlesamples/android-play-location/summary.json > corpus2/googlesamples/android-play-location/hash.json
./get_hash.py corpus2/googlesamples/android-Camera2Basic/summary.json > corpus2/googlesamples/android-Camera2Basic/hash.json
./get_hash.py corpus2/MagicMashRoom/SuperCalendar/summary.json > corpus2/MagicMashRoom/SuperCalendar/hash.json
./get_hash.py corpus2/hugeterry/CoordinatorTabLayout/summary.json > corpus2/hugeterry/CoordinatorTabLayout/hash.json
./get_hash.py corpus2/JakeWharton/timber/summary.json > corpus2/JakeWharton/timber/hash.json
./get_hash.py corpus2/JakeWharton/NineOldAndroids/summary.json > corpus2/JakeWharton/NineOldAndroids/hash.json
./get_hash.py corpus2/JakeWharton/ActionBarSherlock/summary.json > corpus2/JakeWharton/ActionBarSherlock/hash.json
./get_hash.py corpus2/JakeWharton/hugo/summary.json > corpus2/JakeWharton/hugo/hash.json
./get_hash.py corpus2/JakeWharton/DiskLruCache/summary.json > corpus2/JakeWharton/DiskLruCache/hash.json
./get_hash.py corpus2/JakeWharton/ThreeTenABP/summary.json > corpus2/JakeWharton/ThreeTenABP/hash.json
./get_hash.py corpus2/JakeWharton/Telecine/summary.json > corpus2/JakeWharton/Telecine/hash.json
./get_hash.py corpus2/JakeWharton/u2020/summary.json > corpus2/JakeWharton/u2020/hash.json
./get_hash.py corpus2/JakeWharton/scalpel/summary.json > corpus2/JakeWharton/scalpel/hash.json
./get_hash.py corpus2/code4craft/netty-learning/summary.json > corpus2/code4craft/netty-learning/hash.json
./get_hash.py corpus2/code4craft/webmagic/summary.json > corpus2/code4craft/webmagic/hash.json
./get_hash.py corpus2/jfeinstein10/JazzyViewPager/summary.json > corpus2/jfeinstein10/JazzyViewPager/hash.json
./get_hash.py corpus2/Karumi/Dexter/summary.json > corpus2/Karumi/Dexter/hash.json
./get_hash.py corpus2/qstumn/BadgeView/summary.json > corpus2/qstumn/BadgeView/hash.json
./get_hash.py corpus2/fqrouter/fqrouter/summary.json > corpus2/fqrouter/fqrouter/hash.json
./get_hash.py corpus2/SonarSource/sonarqube/summary.json > corpus2/SonarSource/sonarqube/hash.json
./get_hash.py corpus2/looly/hutool/summary.json > corpus2/looly/hutool/hash.json
./get_hash.py corpus2/bigbluebutton/bigbluebutton/summary.json > corpus2/bigbluebutton/bigbluebutton/hash.json
./get_hash.py corpus2/fython/MaterialStepperView/summary.json > corpus2/fython/MaterialStepperView/hash.json
./get_hash.py corpus2/dreamhead/moco/summary.json > corpus2/dreamhead/moco/hash.json
./get_hash.py corpus2/speedment/speedment/summary.json > corpus2/speedment/speedment/hash.json
./get_hash.py corpus2/Jasonchenlijian/FastBle/summary.json > corpus2/Jasonchenlijian/FastBle/hash.json
./get_hash.py corpus2/cyrilmottier/GreenDroid/summary.json > corpus2/cyrilmottier/GreenDroid/hash.json
./get_hash.py corpus2/cymcsg/UltimateAndroid/summary.json > corpus2/cymcsg/UltimateAndroid/hash.json
./get_hash.py corpus2/cymcsg/UltimateRecyclerView/summary.json > corpus2/cymcsg/UltimateRecyclerView/hash.json
./get_hash.py corpus2/twitter/distributedlog/summary.json > corpus2/twitter/distributedlog/hash.json
./get_hash.py corpus2/ltsopensource/light-task-scheduler/summary.json > corpus2/ltsopensource/light-task-scheduler/hash.json
./get_hash.py corpus2/robolectric/robolectric/summary.json > corpus2/robolectric/robolectric/hash.json
./get_hash.py corpus2/btraceio/btrace/summary.json > corpus2/btraceio/btrace/hash.json
./get_hash.py corpus2/naver/pinpoint/summary.json > corpus2/naver/pinpoint/hash.json
./get_hash.py corpus2/Ramotion/folding-cell-android/summary.json > corpus2/Ramotion/folding-cell-android/hash.json
./get_hash.py corpus2/binIoter/GuideView/summary.json > corpus2/binIoter/GuideView/hash.json
./get_hash.py corpus2/mongodb/mongo-java-driver/summary.json > corpus2/mongodb/mongo-java-driver/hash.json
./get_hash.py corpus2/pchmn/MaterialChipsInput/summary.json > corpus2/pchmn/MaterialChipsInput/hash.json
./get_hash.py corpus2/500px/500px-android-blur/summary.json > corpus2/500px/500px-android-blur/hash.json
./get_hash.py corpus2/Rukey7/MvpApp/summary.json > corpus2/Rukey7/MvpApp/hash.json
./get_hash.py corpus2/wequick/Small/summary.json > corpus2/wequick/Small/hash.json
./get_hash.py corpus2/gitpitch/gitpitch/summary.json > corpus2/gitpitch/gitpitch/hash.json
./get_hash.py corpus2/k9mail/k-9/summary.json > corpus2/k9mail/k-9/hash.json
./get_hash.py corpus2/jMonkeyEngine/jmonkeyengine/summary.json > corpus2/jMonkeyEngine/jmonkeyengine/hash.json
./get_hash.py corpus2/MiCode/Notes/summary.json > corpus2/MiCode/Notes/hash.json
./get_hash.py corpus2/ronmamo/reflections/summary.json > corpus2/ronmamo/reflections/hash.json
./get_hash.py corpus2/dropwizard/metrics/summary.json > corpus2/dropwizard/metrics/hash.json
./get_hash.py corpus2/dropwizard/dropwizard/summary.json > corpus2/dropwizard/dropwizard/hash.json
./get_hash.py corpus2/linlinjava/litemall/summary.json > corpus2/linlinjava/litemall/hash.json
./get_hash.py corpus2/race604/FlyRefresh/summary.json > corpus2/race604/FlyRefresh/hash.json
./get_hash.py corpus2/leolin310148/ShortcutBadger/summary.json > corpus2/leolin310148/ShortcutBadger/hash.json
./get_hash.py corpus2/danielzeller/Depth-LIB-Android-/summary.json > corpus2/danielzeller/Depth-LIB-Android-/hash.json
./get_hash.py corpus2/AigeStudio/WheelPicker/summary.json > corpus2/AigeStudio/WheelPicker/hash.json
./get_hash.py corpus2/barteksc/AndroidPdfViewer/summary.json > corpus2/barteksc/AndroidPdfViewer/hash.json
./get_hash.py corpus2/changmingxie/tcc-transaction/summary.json > corpus2/changmingxie/tcc-transaction/hash.json
./get_hash.py corpus2/flavienlaurent/datetimepicker/summary.json > corpus2/flavienlaurent/datetimepicker/hash.json
./get_hash.py corpus2/undertow-io/undertow/summary.json > corpus2/undertow-io/undertow/hash.json
./get_hash.py corpus2/medcl/elasticsearch-analysis-ik/summary.json > corpus2/medcl/elasticsearch-analysis-ik/hash.json
./get_hash.py corpus2/avast/android-styled-dialogs/summary.json > corpus2/avast/android-styled-dialogs/hash.json
./get_hash.py corpus2/avast/android-butterknife-zelezny/summary.json > corpus2/avast/android-butterknife-zelezny/hash.json
./get_hash.py corpus2/androidquery/androidquery/summary.json > corpus2/androidquery/androidquery/hash.json
./get_hash.py corpus2/liuguangqiang/SwipeBack/summary.json > corpus2/liuguangqiang/SwipeBack/hash.json
./get_hash.py corpus2/ffay/lanproxy/summary.json > corpus2/ffay/lanproxy/hash.json
./get_hash.py corpus2/rovo89/XposedInstaller/summary.json > corpus2/rovo89/XposedInstaller/hash.json
./get_hash.py corpus2/lisawray/groupie/summary.json > corpus2/lisawray/groupie/hash.json
./get_hash.py corpus2/mpusher/mpush/summary.json > corpus2/mpusher/mpush/hash.json
./get_hash.py corpus2/daniulive/SmarterStreaming/summary.json > corpus2/daniulive/SmarterStreaming/hash.json
./get_hash.py corpus2/pentaho/pentaho-kettle/summary.json > corpus2/pentaho/pentaho-kettle/hash.json
./get_hash.py corpus2/JeffLi1993/springboot-learning-example/summary.json > corpus2/JeffLi1993/springboot-learning-example/hash.json
./get_hash.py corpus2/kabouzeid/Phonograph/summary.json > corpus2/kabouzeid/Phonograph/hash.json
./get_hash.py corpus2/iSoron/uhabits/summary.json > corpus2/iSoron/uhabits/hash.json
./get_hash.py corpus2/BoltsFramework/Bolts-Android/summary.json > corpus2/BoltsFramework/Bolts-Android/hash.json
./get_hash.py corpus2/JingYeoh/FragmentRigger/summary.json > corpus2/JingYeoh/FragmentRigger/hash.json
./get_hash.py corpus2/stanfordnlp/CoreNLP/summary.json > corpus2/stanfordnlp/CoreNLP/hash.json
./get_hash.py corpus2/davideas/FlexibleAdapter/summary.json > corpus2/davideas/FlexibleAdapter/hash.json
./get_hash.py corpus2/confluentinc/ksql/summary.json > corpus2/confluentinc/ksql/hash.json
./get_hash.py corpus2/junit-team/junit5/summary.json > corpus2/junit-team/junit5/hash.json
./get_hash.py corpus2/junit-team/junit4/summary.json > corpus2/junit-team/junit4/hash.json
./get_hash.py corpus2/TommyLemon/Android-ZBLibrary/summary.json > corpus2/TommyLemon/Android-ZBLibrary/hash.json
./get_hash.py corpus2/TommyLemon/APIJSON/summary.json > corpus2/TommyLemon/APIJSON/hash.json
./get_hash.py corpus2/orhanobut/dialogplus/summary.json > corpus2/orhanobut/dialogplus/hash.json
./get_hash.py corpus2/orhanobut/hawk/summary.json > corpus2/orhanobut/hawk/hash.json
./get_hash.py corpus2/mrniko/netty-socketio/summary.json > corpus2/mrniko/netty-socketio/hash.json
./get_hash.py corpus2/huazhiyuan2008/RecyclerViewCardGallery/summary.json > corpus2/huazhiyuan2008/RecyclerViewCardGallery/hash.json
./get_hash.py corpus2/WritingMinds/ffmpeg-android-java/summary.json > corpus2/WritingMinds/ffmpeg-android-java/hash.json
./get_hash.py corpus2/vipulasri/Timeline-View/summary.json > corpus2/vipulasri/Timeline-View/hash.json
./get_hash.py corpus2/processing/processing/summary.json > corpus2/processing/processing/hash.json
./get_hash.py corpus2/databricks/learning-spark/summary.json > corpus2/databricks/learning-spark/hash.json
./get_hash.py corpus2/ongakuer/CircleIndicator/summary.json > corpus2/ongakuer/CircleIndicator/hash.json
./get_hash.py corpus2/pili-engineering/PLDroidPlayer/summary.json > corpus2/pili-engineering/PLDroidPlayer/hash.json
./get_hash.py corpus2/mission-peace/interview/summary.json > corpus2/mission-peace/interview/hash.json
./get_hash.py corpus2/jgilfelt/chuck/summary.json > corpus2/jgilfelt/chuck/hash.json
./get_hash.py corpus2/jgilfelt/android-viewbadger/summary.json > corpus2/jgilfelt/android-viewbadger/hash.json
./get_hash.py corpus2/jgilfelt/android-sqlite-asset-helper/summary.json > corpus2/jgilfelt/android-sqlite-asset-helper/hash.json
./get_hash.py corpus2/jgilfelt/SystemBarTint/summary.json > corpus2/jgilfelt/SystemBarTint/hash.json
./get_hash.py corpus2/brianway/java-learning/summary.json > corpus2/brianway/java-learning/hash.json
./get_hash.py corpus2/kyleduo/SwitchButton/summary.json > corpus2/kyleduo/SwitchButton/hash.json
./get_hash.py corpus2/chennaione/sugar/summary.json > corpus2/chennaione/sugar/hash.json
./get_hash.py corpus2/querydsl/querydsl/summary.json > corpus2/querydsl/querydsl/hash.json
./get_hash.py corpus2/avjinder/Minimal-Todo/summary.json > corpus2/avjinder/Minimal-Todo/hash.json
./get_hash.py corpus2/geeeeeeeeek/WeChatLuckyMoney/summary.json > corpus2/geeeeeeeeek/WeChatLuckyMoney/hash.json
./get_hash.py corpus2/pqpo/SmartCropper/summary.json > corpus2/pqpo/SmartCropper/hash.json
./get_hash.py corpus2/MiguelCatalan/MaterialSearchView/summary.json > corpus2/MiguelCatalan/MaterialSearchView/hash.json
./get_hash.py corpus2/JessYanCoding/MVPArms/summary.json > corpus2/JessYanCoding/MVPArms/hash.json
./get_hash.py corpus2/JessYanCoding/AndroidAutoSize/summary.json > corpus2/JessYanCoding/AndroidAutoSize/hash.json
./get_hash.py corpus2/lingochamp/okdownload/summary.json > corpus2/lingochamp/okdownload/hash.json
./get_hash.py corpus2/lingochamp/FileDownloader/summary.json > corpus2/lingochamp/FileDownloader/hash.json
./get_hash.py corpus2/liyifeng1994/ssm/summary.json > corpus2/liyifeng1994/ssm/hash.json
./get_hash.py corpus2/yipianfengye/android-zxingLibrary/summary.json > corpus2/yipianfengye/android-zxingLibrary/hash.json
./get_hash.py corpus2/yipianfengye/android-adDialog/summary.json > corpus2/yipianfengye/android-adDialog/hash.json
./get_hash.py corpus2/HotBitmapGG/bilibili-android-client/summary.json > corpus2/HotBitmapGG/bilibili-android-client/hash.json
./get_hash.py corpus2/Graylog2/graylog2-server/summary.json > corpus2/Graylog2/graylog2-server/hash.json
./get_hash.py corpus2/VictorAlbertos/RxCache/summary.json > corpus2/VictorAlbertos/RxCache/hash.json
./get_hash.py corpus2/guoxiaoxing/android-open-source-project-analysis/summary.json > corpus2/guoxiaoxing/android-open-source-project-analysis/hash.json
./get_hash.py corpus2/grantland/android-autofittextview/summary.json > corpus2/grantland/android-autofittextview/hash.json
./get_hash.py corpus2/spockframework/spock/summary.json > corpus2/spockframework/spock/hash.json
./get_hash.py corpus2/drakeet/MultiType/summary.json > corpus2/drakeet/MultiType/hash.json
./get_hash.py corpus2/alipay/sofa-boot/summary.json > corpus2/alipay/sofa-boot/hash.json
./get_hash.py corpus2/alipay/sofa-jarslink/summary.json > corpus2/alipay/sofa-jarslink/hash.json
./get_hash.py corpus2/hanks-zyh/HTextView/summary.json > corpus2/hanks-zyh/HTextView/hash.json
./get_hash.py corpus2/LuckyJayce/ViewPagerIndicator/summary.json > corpus2/LuckyJayce/ViewPagerIndicator/hash.json
./get_hash.py corpus2/keycloak/keycloak/summary.json > corpus2/keycloak/keycloak/hash.json
./get_hash.py corpus2/jfinal/jfinal/summary.json > corpus2/jfinal/jfinal/hash.json
./get_hash.py corpus2/eirslett/frontend-maven-plugin/summary.json > corpus2/eirslett/frontend-maven-plugin/hash.json
./get_hash.py corpus2/davemorrissey/subsampling-scale-image-view/summary.json > corpus2/davemorrissey/subsampling-scale-image-view/hash.json
./get_hash.py corpus2/yingLanNull/ShadowImageView/summary.json > corpus2/yingLanNull/ShadowImageView/hash.json
./get_hash.py corpus2/Jungerr/GridPasswordView/summary.json > corpus2/Jungerr/GridPasswordView/hash.json
./get_hash.py corpus2/dbeaver/dbeaver/summary.json > corpus2/dbeaver/dbeaver/hash.json
./get_hash.py corpus2/stormzhang/9GAG/summary.json > corpus2/stormzhang/9GAG/hash.json
./get_hash.py corpus2/awangdev/LintCode/summary.json > corpus2/awangdev/LintCode/hash.json
./get_hash.py corpus2/edmodo/cropper/summary.json > corpus2/edmodo/cropper/hash.json
./get_hash.py corpus2/EverythingMe/overscroll-decor/summary.json > corpus2/EverythingMe/overscroll-decor/hash.json
./get_hash.py corpus2/pmd/pmd/summary.json > corpus2/pmd/pmd/hash.json
./get_hash.py corpus2/DroidPluginTeam/DroidPlugin/summary.json > corpus2/DroidPluginTeam/DroidPlugin/hash.json
./get_hash.py corpus2/OpenTSDB/opentsdb/summary.json > corpus2/OpenTSDB/opentsdb/hash.json
./get_hash.py corpus2/JohnPersano/SuperToasts/summary.json > corpus2/JohnPersano/SuperToasts/hash.json
./get_hash.py corpus2/jokermonn/permissions4m/summary.json > corpus2/jokermonn/permissions4m/hash.json
./get_hash.py corpus2/DreaminginCodeZH/Douya/summary.json > corpus2/DreaminginCodeZH/Douya/hash.json
./get_hash.py corpus2/parse-community/Parse-SDK-Android/summary.json > corpus2/parse-community/Parse-SDK-Android/hash.json
./get_hash.py corpus2/diogobernardino/WilliamChart/summary.json > corpus2/diogobernardino/WilliamChart/hash.json
./get_hash.py corpus2/singwhatiwanna/dynamic-load-apk/summary.json > corpus2/singwhatiwanna/dynamic-load-apk/hash.json
./get_hash.py corpus2/xetorthio/jedis/summary.json > corpus2/xetorthio/jedis/hash.json
./get_hash.py corpus2/githubwing/ZoomHeader/summary.json > corpus2/githubwing/ZoomHeader/hash.json
./get_hash.py corpus2/balysv/material-menu/summary.json > corpus2/balysv/material-menu/hash.json
./get_hash.py corpus2/balysv/material-ripple/summary.json > corpus2/balysv/material-ripple/hash.json
./get_hash.py corpus2/openhab/openhab1-addons/summary.json > corpus2/openhab/openhab1-addons/hash.json
./get_hash.py corpus2/jOOQ/jOOQ/summary.json > corpus2/jOOQ/jOOQ/hash.json
./get_hash.py corpus2/evernote/android-job/summary.json > corpus2/evernote/android-job/hash.json
./get_hash.py corpus2/trello/RxLifecycle/summary.json > corpus2/trello/RxLifecycle/hash.json
./get_hash.py corpus2/Twitter4J/Twitter4J/summary.json > corpus2/Twitter4J/Twitter4J/hash.json
./get_hash.py corpus2/bisq-network/bisq/summary.json > corpus2/bisq-network/bisq/hash.json
./get_hash.py corpus2/termux/termux-app/summary.json > corpus2/termux/termux-app/hash.json
./get_hash.py corpus2/pedant/sweet-alert-dialog/summary.json > corpus2/pedant/sweet-alert-dialog/hash.json
./get_hash.py corpus2/siyamed/android-shape-imageview/summary.json > corpus2/siyamed/android-shape-imageview/hash.json
./get_hash.py corpus2/Trinea/android-common/summary.json > corpus2/Trinea/android-common/hash.json
./get_hash.py corpus2/novoda/android-demos/summary.json > corpus2/novoda/android-demos/hash.json
./get_hash.py corpus2/JackyAndroid/AndroidTVLauncher/summary.json > corpus2/JackyAndroid/AndroidTVLauncher/hash.json
./get_hash.py corpus2/JackyAndroid/AndroidChromium/summary.json > corpus2/JackyAndroid/AndroidChromium/hash.json
./get_hash.py corpus2/MindorksOpenSource/PRDownloader/summary.json > corpus2/MindorksOpenSource/PRDownloader/hash.json
./get_hash.py corpus2/MindorksOpenSource/from-java-to-kotlin/summary.json > corpus2/MindorksOpenSource/from-java-to-kotlin/hash.json
./get_hash.py corpus2/MindorksOpenSource/android-interview-questions/summary.json > corpus2/MindorksOpenSource/android-interview-questions/hash.json
./get_hash.py corpus2/gabrielemariotti/cardslib/summary.json > corpus2/gabrielemariotti/cardslib/hash.json
./get_hash.py corpus2/gabrielemariotti/RecyclerViewItemAnimators/summary.json > corpus2/gabrielemariotti/RecyclerViewItemAnimators/hash.json
./get_hash.py corpus2/ACRA/acra/summary.json > corpus2/ACRA/acra/hash.json
./get_hash.py corpus2/luojilab/DDComponentForAndroid/summary.json > corpus2/luojilab/DDComponentForAndroid/hash.json
./get_hash.py corpus2/nanchen2251/RxJava2Examples/summary.json > corpus2/nanchen2251/RxJava2Examples/hash.json
./get_hash.py corpus2/nanchen2251/CompressHelper/summary.json > corpus2/nanchen2251/CompressHelper/hash.json
./get_hash.py corpus2/graphql-java/graphql-java/summary.json > corpus2/graphql-java/graphql-java/hash.json
./get_hash.py corpus2/facebook/device-year-class/summary.json > corpus2/facebook/device-year-class/hash.json
./get_hash.py corpus2/facebook/litho/summary.json > corpus2/facebook/litho/hash.json
./get_hash.py corpus2/facebook/network-connection-class/summary.json > corpus2/facebook/network-connection-class/hash.json
./get_hash.py corpus2/facebook/react-native-fbsdk/summary.json > corpus2/facebook/react-native-fbsdk/hash.json
./get_hash.py corpus2/facebook/rebound/summary.json > corpus2/facebook/rebound/hash.json
./get_hash.py corpus2/facebook/buck/summary.json > corpus2/facebook/buck/hash.json
./get_hash.py corpus2/facebook/facebook-android-sdk/summary.json > corpus2/facebook/facebook-android-sdk/hash.json
./get_hash.py corpus2/facebook/shimmer-android/summary.json > corpus2/facebook/shimmer-android/hash.json
./get_hash.py corpus2/OpenFeign/feign/summary.json > corpus2/OpenFeign/feign/hash.json
./get_hash.py corpus2/jdsjlzx/LRecyclerView/summary.json > corpus2/jdsjlzx/LRecyclerView/hash.json
./get_hash.py corpus2/Wizcorp/phonegap-facebook-plugin/summary.json > corpus2/Wizcorp/phonegap-facebook-plugin/hash.json
./get_hash.py corpus2/litesuits/android-common/summary.json > corpus2/litesuits/android-common/hash.json
./get_hash.py corpus2/crate/crate/summary.json > corpus2/crate/crate/hash.json
./get_hash.py corpus2/ata4/disunity/summary.json > corpus2/ata4/disunity/hash.json
./get_hash.py corpus2/lettuce-io/lettuce-core/summary.json > corpus2/lettuce-io/lettuce-core/hash.json
./get_hash.py corpus2/dmytrodanylyk/android-process-button/summary.json > corpus2/dmytrodanylyk/android-process-button/hash.json
./get_hash.py corpus2/dmytrodanylyk/circular-progress-button/summary.json > corpus2/dmytrodanylyk/circular-progress-button/hash.json
./get_hash.py corpus2/Zomato/AndroidPhotoFilters/summary.json > corpus2/Zomato/AndroidPhotoFilters/hash.json
./get_hash.py corpus2/hmkcode/Android/summary.json > corpus2/hmkcode/Android/hash.json
./get_hash.py corpus2/naman14/Timber/summary.json > corpus2/naman14/Timber/hash.json
./get_hash.py corpus2/siacs/Conversations/summary.json > corpus2/siacs/Conversations/hash.json
./get_hash.py corpus2/Todd-Davies/ProgressWheel/summary.json > corpus2/Todd-Davies/ProgressWheel/hash.json
./get_hash.py corpus2/JesusFreke/smali/summary.json > corpus2/JesusFreke/smali/hash.json
./get_hash.py corpus2/Malinskiy/SuperRecyclerView/summary.json > corpus2/Malinskiy/SuperRecyclerView/hash.json
./get_hash.py corpus2/tbruyelle/RxPermissions/summary.json > corpus2/tbruyelle/RxPermissions/hash.json
./get_hash.py corpus2/kikoso/android-stackblur/summary.json > corpus2/kikoso/android-stackblur/hash.json
./get_hash.py corpus2/elasticjob/elastic-job-lite/summary.json > corpus2/elasticjob/elastic-job-lite/hash.json
./get_hash.py corpus2/mcxtzhang/ZLayoutManager/summary.json > corpus2/mcxtzhang/ZLayoutManager/hash.json
./get_hash.py corpus2/mcxtzhang/SwipeDelMenuLayout/summary.json > corpus2/mcxtzhang/SwipeDelMenuLayout/hash.json
./get_hash.py corpus2/smuyyh/BookReader/summary.json > corpus2/smuyyh/BookReader/hash.json
./get_hash.py corpus2/zhangkaitao/es/summary.json > corpus2/zhangkaitao/es/hash.json
./get_hash.py corpus2/ozodrukh/CircularReveal/summary.json > corpus2/ozodrukh/CircularReveal/hash.json
./get_hash.py corpus2/tronprotocol/java-tron/summary.json > corpus2/tronprotocol/java-tron/hash.json
./get_hash.py corpus2/CrawlScript/WebCollector/summary.json > corpus2/CrawlScript/WebCollector/hash.json
./get_hash.py corpus2/mybatis/generator/summary.json > corpus2/mybatis/generator/hash.json
./get_hash.py corpus2/mybatis/spring-boot-starter/summary.json > corpus2/mybatis/spring-boot-starter/hash.json
./get_hash.py corpus2/cglib/cglib/summary.json > corpus2/cglib/cglib/hash.json
./get_hash.py corpus2/dinuscxj/LoadingDrawable/summary.json > corpus2/dinuscxj/LoadingDrawable/hash.json
./get_hash.py corpus2/journeyapps/zxing-android-embedded/summary.json > corpus2/journeyapps/zxing-android-embedded/hash.json
./get_hash.py corpus2/yui/yuicompressor/summary.json > corpus2/yui/yuicompressor/hash.json
./get_hash.py corpus2/apache/flink/summary.json > corpus2/apache/flink/hash.json
./get_hash.py corpus2/apache/cassandra/summary.json > corpus2/apache/cassandra/hash.json
./get_hash.py corpus2/apache/groovy/summary.json > corpus2/apache/groovy/hash.json
./get_hash.py corpus2/apache/ignite/summary.json > corpus2/apache/ignite/hash.json
./get_hash.py corpus2/apache/camel/summary.json > corpus2/apache/camel/hash.json
./get_hash.py corpus2/apache/storm/summary.json > corpus2/apache/storm/hash.json
./get_hash.py corpus2/apache/incubator-druid/summary.json > corpus2/apache/incubator-druid/hash.json
./get_hash.py corpus2/apache/hive/summary.json > corpus2/apache/hive/hash.json
./get_hash.py corpus2/apache/rocketmq/summary.json > corpus2/apache/rocketmq/hash.json
./get_hash.py corpus2/apache/hbase/summary.json > corpus2/apache/hbase/hash.json
./get_hash.py corpus2/apache/pulsar/summary.json > corpus2/apache/pulsar/hash.json
./get_hash.py corpus2/apache/beam/summary.json > corpus2/apache/beam/hash.json
./get_hash.py corpus2/apache/lucene-solr/summary.json > corpus2/apache/lucene-solr/hash.json
./get_hash.py corpus2/apache/zookeeper/summary.json > corpus2/apache/zookeeper/hash.json
./get_hash.py corpus2/apache/mahout/summary.json > corpus2/apache/mahout/hash.json
./get_hash.py corpus2/apache/incubator-skywalking/summary.json > corpus2/apache/incubator-skywalking/hash.json
./get_hash.py corpus2/apache/incubator-heron/summary.json > corpus2/apache/incubator-heron/hash.json
./get_hash.py corpus2/apache/jmeter/summary.json > corpus2/apache/jmeter/hash.json
./get_hash.py corpus2/apache/shiro/summary.json > corpus2/apache/shiro/hash.json
./get_hash.py corpus2/apache/tomcat/summary.json > corpus2/apache/tomcat/hash.json
./get_hash.py corpus2/apache/cordova-android/summary.json > corpus2/apache/cordova-android/hash.json
./get_hash.py corpus2/apache/incubator-pinot/summary.json > corpus2/apache/incubator-pinot/hash.json
./get_hash.py corpus2/apache/incubator-dubbo-spring-boot-project/summary.json > corpus2/apache/incubator-dubbo-spring-boot-project/hash.json
./get_hash.py corpus2/apache/nutch/summary.json > corpus2/apache/nutch/hash.json
./get_hash.py corpus2/apache/zeppelin/summary.json > corpus2/apache/zeppelin/hash.json
./get_hash.py corpus2/fyhertz/libstreaming/summary.json > corpus2/fyhertz/libstreaming/hash.json
./get_hash.py corpus2/commonsguy/cw-omnibus/summary.json > corpus2/commonsguy/cw-omnibus/hash.json
./get_hash.py corpus2/clojure/clojure/summary.json > corpus2/clojure/clojure/hash.json
./get_hash.py corpus2/guardianproject/haven/summary.json > corpus2/guardianproject/haven/hash.json
./get_hash.py corpus2/h6ah4i/android-advancedrecyclerview/summary.json > corpus2/h6ah4i/android-advancedrecyclerview/hash.json
./get_hash.py corpus2/luontola/retrolambda/summary.json > corpus2/luontola/retrolambda/hash.json
./get_hash.py corpus2/googlemaps/android-maps-utils/summary.json > corpus2/googlemaps/android-maps-utils/hash.json
./get_hash.py corpus2/lihengming/spring-boot-api-project-seed/summary.json > corpus2/lihengming/spring-boot-api-project-seed/hash.json
./get_hash.py corpus2/react-community/react-native-image-picker/summary.json > corpus2/react-community/react-native-image-picker/hash.json
./get_hash.py corpus2/tyzlmjj/PagerBottomTabStrip/summary.json > corpus2/tyzlmjj/PagerBottomTabStrip/hash.json
./get_hash.py corpus2/dmilicic/Android-Clean-Boilerplate/summary.json > corpus2/dmilicic/Android-Clean-Boilerplate/hash.json
./get_hash.py corpus2/fanrunqi/MaterialLogin/summary.json > corpus2/fanrunqi/MaterialLogin/hash.json
./get_hash.py corpus2/Qihoo360/RePlugin/summary.json > corpus2/Qihoo360/RePlugin/hash.json
./get_hash.py corpus2/koral--/android-gif-drawable/summary.json > corpus2/koral--/android-gif-drawable/hash.json
./get_hash.py corpus2/vavr-io/vavr/summary.json > corpus2/vavr-io/vavr/hash.json
./get_hash.py corpus2/abel533/Mapper/summary.json > corpus2/abel533/Mapper/hash.json
./get_hash.py corpus2/abel533/MyBatis-Spring-Boot/summary.json > corpus2/abel533/MyBatis-Spring-Boot/hash.json
./get_hash.py corpus2/square/moshi/summary.json > corpus2/square/moshi/hash.json
./get_hash.py corpus2/square/android-times-square/summary.json > corpus2/square/android-times-square/hash.json
./get_hash.py corpus2/square/flow/summary.json > corpus2/square/flow/hash.json
./get_hash.py corpus2/square/tape/summary.json > corpus2/square/tape/hash.json
./get_hash.py corpus2/square/wire/summary.json > corpus2/square/wire/hash.json
./get_hash.py corpus2/square/javapoet/summary.json > corpus2/square/javapoet/hash.json
./get_hash.py corpus2/square/dagger/summary.json > corpus2/square/dagger/hash.json
./get_hash.py corpus2/square/mortar/summary.json > corpus2/square/mortar/hash.json
./get_hash.py corpus2/square/sqlbrite/summary.json > corpus2/square/sqlbrite/hash.json
./get_hash.py corpus2/square/otto/summary.json > corpus2/square/otto/hash.json
./get_hash.py corpus2/nutzam/nutz/summary.json > corpus2/nutzam/nutz/hash.json
./get_hash.py corpus2/ImmortalZ/StereoView/summary.json > corpus2/ImmortalZ/StereoView/hash.json
./get_hash.py corpus2/puniverse/quasar/summary.json > corpus2/puniverse/quasar/hash.json
./get_hash.py corpus2/shwenzhang/AndResGuard/summary.json > corpus2/shwenzhang/AndResGuard/hash.json
./get_hash.py corpus2/codecentric/spring-boot-admin/summary.json > corpus2/codecentric/spring-boot-admin/hash.json
./get_hash.py corpus2/thinkaurelius/titan/summary.json > corpus2/thinkaurelius/titan/hash.json
