./get_mrg_hash.sh repo100/java-design-patterns > corpus/iluwatar/java-design-patterns/mrg_hash.txt
./get_mrg_hash.sh repo100/RxJava > corpus/ReactiveX/RxJava/mrg_hash.txt
./get_mrg_hash.sh repo100/elasticsearch > corpus/elastic/elasticsearch/mrg_hash.txt
./get_mrg_hash.sh repo100/retrofit > corpus/square/retrofit/mrg_hash.txt
./get_mrg_hash.sh repo100/okhttp > corpus/square/okhttp/mrg_hash.txt
./get_mrg_hash.sh repo100/spring-boot > corpus/spring-projects/spring-boot/mrg_hash.txt
./get_mrg_hash.sh repo100/guava > corpus/google/guava/mrg_hash.txt
./get_mrg_hash.sh repo100/interviews > corpus/kdn251/interviews/mrg_hash.txt
./get_mrg_hash.sh repo100/MPAndroidChart > corpus/PhilJay/MPAndroidChart/mrg_hash.txt
./get_mrg_hash.sh repo100/glide > corpus/bumptech/glide/mrg_hash.txt
./get_mrg_hash.sh repo100/spring-framework > corpus/spring-projects/spring-framework/mrg_hash.txt
./get_mrg_hash.sh repo100/lottie-android > corpus/airbnb/lottie-android/mrg_hash.txt
./get_mrg_hash.sh repo100/butterknife > corpus/JakeWharton/butterknife/mrg_hash.txt
./get_mrg_hash.sh repo100/incubator-dubbo > corpus/apache/incubator-dubbo/mrg_hash.txt
./get_mrg_hash.sh repo100/leakcanary > corpus/square/leakcanary/mrg_hash.txt
./get_mrg_hash.sh repo100/zxing > corpus/zxing/zxing/mrg_hash.txt
./get_mrg_hash.sh repo100/AndroidUtilCode > corpus/Blankj/AndroidUtilCode/mrg_hash.txt
./get_mrg_hash.sh repo100/EventBus > corpus/greenrobot/EventBus/mrg_hash.txt
./get_mrg_hash.sh repo100/RxAndroid > corpus/ReactiveX/RxAndroid/mrg_hash.txt
./get_mrg_hash.sh repo100/Android-Universal-Image-Loader > corpus/nostra13/Android-Universal-Image-Loader/mrg_hash.txt
./get_mrg_hash.sh repo100/picasso > corpus/square/picasso/mrg_hash.txt
./get_mrg_hash.sh repo100/iosched > corpus/google/iosched/mrg_hash.txt
./get_mrg_hash.sh repo100/jadx > corpus/skylot/jadx/mrg_hash.txt
./get_mrg_hash.sh repo100/netty > corpus/netty/netty/mrg_hash.txt
./get_mrg_hash.sh repo100/fresco > corpus/facebook/fresco/mrg_hash.txt
./get_mrg_hash.sh repo100/fastjson > corpus/alibaba/fastjson/mrg_hash.txt
./get_mrg_hash.sh repo100/BaseRecyclerViewAdapterHelper > corpus/CymChad/BaseRecyclerViewAdapterHelper/mrg_hash.txt
./get_mrg_hash.sh repo100/Hystrix > corpus/Netflix/Hystrix/mrg_hash.txt
./get_mrg_hash.sh repo100/libgdx > corpus/libgdx/libgdx/mrg_hash.txt
./get_mrg_hash.sh repo100/material-dialogs > corpus/afollestad/material-dialogs/mrg_hash.txt
./get_mrg_hash.sh repo100/PhotoView > corpus/chrisbanes/PhotoView/mrg_hash.txt
./get_mrg_hash.sh repo100/SmartRefreshLayout > corpus/scwang90/SmartRefreshLayout/mrg_hash.txt
./get_mrg_hash.sh repo100/gson > corpus/google/gson/mrg_hash.txt
./get_mrg_hash.sh repo100/druid > corpus/alibaba/druid/mrg_hash.txt
./get_mrg_hash.sh repo100/tinker > corpus/Tencent/tinker/mrg_hash.txt
./get_mrg_hash.sh repo100/proxyee-down > corpus/proxyee-down-org/proxyee-down/mrg_hash.txt
./get_mrg_hash.sh repo100/Android-CleanArchitecture > corpus/android10/Android-CleanArchitecture/mrg_hash.txt
./get_mrg_hash.sh repo100/Material-Animations > corpus/lgvalle/Material-Animations/mrg_hash.txt
./get_mrg_hash.sh repo100/plaid > corpus/nickbutcher/plaid/mrg_hash.txt
./get_mrg_hash.sh repo100/selenium > corpus/SeleniumHQ/selenium/mrg_hash.txt
./get_mrg_hash.sh repo100/SlidingMenu > corpus/jfeinstein10/SlidingMenu/mrg_hash.txt
./get_mrg_hash.sh repo100/zheng > corpus/shuzheng/zheng/mrg_hash.txt
./get_mrg_hash.sh repo100/jenkins > corpus/jenkinsci/jenkins/mrg_hash.txt
./get_mrg_hash.sh repo100/ExoPlayer > corpus/google/ExoPlayer/mrg_hash.txt
./get_mrg_hash.sh repo100/androidannotations > corpus/androidannotations/androidannotations/mrg_hash.txt
./get_mrg_hash.sh repo100/greenDAO > corpus/greenrobot/greenDAO/mrg_hash.txt
./get_mrg_hash.sh repo100/AndroidSwipeLayout > corpus/daimajia/AndroidSwipeLayout/mrg_hash.txt
./get_mrg_hash.sh repo100/android-async-http > corpus/loopj/android-async-http/mrg_hash.txt
./get_mrg_hash.sh repo100/Telegram > corpus/DrKLO/Telegram/mrg_hash.txt
./get_mrg_hash.sh repo100/CircleImageView > corpus/hdodenhof/CircleImageView/mrg_hash.txt
./get_mrg_hash.sh repo100/incubator-weex > corpus/apache/incubator-weex/mrg_hash.txt
./get_mrg_hash.sh repo100/stetho > corpus/facebook/stetho/mrg_hash.txt
./get_mrg_hash.sh repo100/Signal-Android > corpus/signalapp/Signal-Android/mrg_hash.txt
./get_mrg_hash.sh repo100/ViewPagerIndicator > corpus/JakeWharton/ViewPagerIndicator/mrg_hash.txt
./get_mrg_hash.sh repo100/realm-java > corpus/realm/realm-java/mrg_hash.txt
./get_mrg_hash.sh repo100/AndroidViewAnimations > corpus/daimajia/AndroidViewAnimations/mrg_hash.txt
./get_mrg_hash.sh repo100/java8-tutorial > corpus/winterbe/java8-tutorial/mrg_hash.txt
./get_mrg_hash.sh repo100/bazel > corpus/bazelbuild/bazel/mrg_hash.txt
./get_mrg_hash.sh repo100/logger > corpus/orhanobut/logger/mrg_hash.txt
./get_mrg_hash.sh repo100/bytecode-viewer > corpus/Konloch/bytecode-viewer/mrg_hash.txt
./get_mrg_hash.sh repo100/MaterialDrawer > corpus/mikepenz/MaterialDrawer/mrg_hash.txt
./get_mrg_hash.sh repo100/FizzBuzzEnterpriseEdition > corpus/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/mrg_hash.txt
./get_mrg_hash.sh repo100/deeplearning4j > corpus/deeplearning4j/deeplearning4j/mrg_hash.txt
./get_mrg_hash.sh repo100/PocketHub > corpus/pockethub/PocketHub/mrg_hash.txt
./get_mrg_hash.sh repo100/android-Ultra-Pull-To-Refresh > corpus/liaohuqiu/android-Ultra-Pull-To-Refresh/mrg_hash.txt
./get_mrg_hash.sh repo100/zipkin > corpus/openzipkin/zipkin/mrg_hash.txt
./get_mrg_hash.sh repo100/storm > corpus/nathanmarz/storm/mrg_hash.txt
./get_mrg_hash.sh repo100/kafka > corpus/apache/kafka/mrg_hash.txt
./get_mrg_hash.sh repo100/Android-ObservableScrollView > corpus/ksoichiro/Android-ObservableScrollView/mrg_hash.txt
./get_mrg_hash.sh repo100/MaterialDesignLibrary > corpus/navasmdc/MaterialDesignLibrary/mrg_hash.txt
./get_mrg_hash.sh repo100/Android-PullToRefresh > corpus/chrisbanes/Android-PullToRefresh/mrg_hash.txt
./get_mrg_hash.sh repo100/vlayout > corpus/alibaba/vlayout/mrg_hash.txt
./get_mrg_hash.sh repo100/recyclerview-animators > corpus/wasabeef/recyclerview-animators/mrg_hash.txt
./get_mrg_hash.sh repo100/VasSonic > corpus/Tencent/VasSonic/mrg_hash.txt
./get_mrg_hash.sh repo100/vert.x > corpus/eclipse/vert.x/mrg_hash.txt
./get_mrg_hash.sh repo100/HanLP > corpus/hankcs/HanLP/mrg_hash.txt
./get_mrg_hash.sh repo100/react-native-navigation > corpus/wix/react-native-navigation/mrg_hash.txt
./get_mrg_hash.sh repo100/disruptor > corpus/LMAX-Exchange/disruptor/mrg_hash.txt
./get_mrg_hash.sh repo100/Luban > corpus/Curzibn/Luban/mrg_hash.txt
./get_mrg_hash.sh repo100/mybatis-3 > corpus/mybatis/mybatis-3/mrg_hash.txt
./get_mrg_hash.sh repo100/Java-Interview > corpus/crossoverJie/Java-Interview/mrg_hash.txt
./get_mrg_hash.sh repo100/BottomBar > corpus/roughike/BottomBar/mrg_hash.txt
./get_mrg_hash.sh repo100/okhttp-OkGo > corpus/jeasonlzy/okhttp-OkGo/mrg_hash.txt
./get_mrg_hash.sh repo100/Android-PickerView > corpus/Bigkoo/Android-PickerView/mrg_hash.txt
./get_mrg_hash.sh repo100/AppIntro > corpus/apl-devs/AppIntro/mrg_hash.txt
./get_mrg_hash.sh repo100/Calligraphy > corpus/chrisjenx/Calligraphy/mrg_hash.txt
./get_mrg_hash.sh repo100/presto > corpus/prestodb/presto/mrg_hash.txt
./get_mrg_hash.sh repo100/HomeMirror > corpus/HannahMitt/HomeMirror/mrg_hash.txt
./get_mrg_hash.sh repo100/AndroidSlidingUpPanel > corpus/umano/AndroidSlidingUpPanel/mrg_hash.txt
./get_mrg_hash.sh repo100/platform_frameworks_base > corpus/aosp-mirror/platform_frameworks_base/mrg_hash.txt
./get_mrg_hash.sh repo100/RxBinding > corpus/JakeWharton/RxBinding/mrg_hash.txt
./get_mrg_hash.sh repo100/hadoop > corpus/apache/hadoop/mrg_hash.txt
./get_mrg_hash.sh repo100/AVLoadingIndicatorView > corpus/81813780/AVLoadingIndicatorView/mrg_hash.txt
./get_mrg_hash.sh repo100/PermissionsDispatcher > corpus/permissions-dispatcher/PermissionsDispatcher/mrg_hash.txt
./get_mrg_hash.sh repo100/spark > corpus/perwendel/spark/mrg_hash.txt
./get_mrg_hash.sh repo100/cheesesquare > corpus/chrisbanes/cheesesquare/mrg_hash.txt
./get_mrg_hash.sh repo100/MaterialViewPager > corpus/florent37/MaterialViewPager/mrg_hash.txt
./get_mrg_hash.sh repo100/Matisse > corpus/zhihu/Matisse/mrg_hash.txt
./get_mrg_hash.sh repo100/HikariCP > corpus/brettwooldridge/HikariCP/mrg_hash.txt
./get_mrg_hash.sh repo100/uCrop > corpus/Yalantis/uCrop/mrg_hash.txt
