date
./get_hash.py corpus/chrisbanes/cheesesquare/summary.json > corpus/chrisbanes/cheesesquare/hash.json ; echo 'chrisbanes/cheesesquare' ; sleep 360
./get_hash.py corpus/winterbe/java8-tutorial/summary.json > corpus/winterbe/java8-tutorial/hash.json ; echo 'winterbe/java8-tutorial' ; sleep 360
./get_hash.py corpus/HannahMitt/HomeMirror/summary.json > corpus/HannahMitt/HomeMirror/hash.json ; echo 'HannahMitt/HomeMirror' ; sleep 360
./get_hash.py corpus/lgvalle/Material-Animations/summary.json > corpus/lgvalle/Material-Animations/hash.json ; echo 'lgvalle/Material-Animations' ; sleep 360
./get_hash.py corpus/81813780/AVLoadingIndicatorView/summary.json > corpus/81813780/AVLoadingIndicatorView/hash.json ; echo '81813780/AVLoadingIndicatorView' ; sleep 360
./get_hash.py corpus/kdn251/interviews/summary.json > corpus/kdn251/interviews/hash.json ; echo 'kdn251/interviews' ; sleep 360
./get_hash.py corpus/chrisbanes/Android-PullToRefresh/summary.json > corpus/chrisbanes/Android-PullToRefresh/hash.json ; echo 'chrisbanes/Android-PullToRefresh' ; sleep 360
./get_hash.py corpus/wasabeef/recyclerview-animators/summary.json > corpus/wasabeef/recyclerview-animators/hash.json ; echo 'wasabeef/recyclerview-animators' ; sleep 360
./get_hash.py corpus/aosp-mirror/platform_frameworks_base/summary.json > corpus/aosp-mirror/platform_frameworks_base/hash.json ; echo 'aosp-mirror/platform_frameworks_base' ; sleep 360
./get_hash.py corpus/daimajia/AndroidViewAnimations/summary.json > corpus/daimajia/AndroidViewAnimations/hash.json ; echo 'daimajia/AndroidViewAnimations' ; sleep 360
./get_hash.py corpus/crossoverJie/Java-Interview/summary.json > corpus/crossoverJie/Java-Interview/hash.json ; echo 'crossoverJie/Java-Interview' ; sleep 360
./get_hash.py corpus/Konloch/bytecode-viewer/summary.json > corpus/Konloch/bytecode-viewer/hash.json ; echo 'Konloch/bytecode-viewer' ; sleep 360
./get_hash.py corpus/ksoichiro/Android-ObservableScrollView/summary.json > corpus/ksoichiro/Android-ObservableScrollView/hash.json ; echo 'ksoichiro/Android-ObservableScrollView' ; sleep 360
./get_hash.py corpus/shuzheng/zheng/summary.json > corpus/shuzheng/zheng/hash.json ; echo 'shuzheng/zheng' ; sleep 360
./get_hash.py corpus/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/summary.json > corpus/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/hash.json ; echo 'EnterpriseQualityCoding/FizzBuzzEnterpriseEdition' ; sleep 360
./get_hash.py corpus/orhanobut/logger/summary.json > corpus/orhanobut/logger/hash.json ; echo 'orhanobut/logger' ; sleep 360
./get_hash.py corpus/navasmdc/MaterialDesignLibrary/summary.json > corpus/navasmdc/MaterialDesignLibrary/hash.json ; echo 'navasmdc/MaterialDesignLibrary' ; sleep 360
./get_hash.py corpus/android10/Android-CleanArchitecture/summary.json > corpus/android10/Android-CleanArchitecture/hash.json ; echo 'android10/Android-CleanArchitecture' ; sleep 360
./get_hash.py corpus/florent37/MaterialViewPager/summary.json > corpus/florent37/MaterialViewPager/hash.json ; echo 'florent37/MaterialViewPager' ; sleep 360
./get_hash.py corpus/DrKLO/Telegram/summary.json > corpus/DrKLO/Telegram/hash.json ; echo 'DrKLO/Telegram' ; sleep 360
./get_hash.py corpus/daimajia/AndroidSwipeLayout/summary.json > corpus/daimajia/AndroidSwipeLayout/hash.json ; echo 'daimajia/AndroidSwipeLayout' ; sleep 360
./get_hash.py corpus/apache/hadoop/summary.json > corpus/apache/hadoop/hash.json ; echo 'apache/hadoop' ; sleep 360
./get_hash.py corpus/skylot/jadx/summary.json > corpus/skylot/jadx/hash.json ; echo 'skylot/jadx' ; sleep 360
./get_hash.py corpus/liaohuqiu/android-Ultra-Pull-To-Refresh/summary.json > corpus/liaohuqiu/android-Ultra-Pull-To-Refresh/hash.json ; echo 'liaohuqiu/android-Ultra-Pull-To-Refresh' ; sleep 360
./get_hash.py corpus/JakeWharton/ViewPagerIndicator/summary.json > corpus/JakeWharton/ViewPagerIndicator/hash.json ; echo 'JakeWharton/ViewPagerIndicator' ; sleep 360
./get_hash.py corpus/nathanmarz/storm/summary.json > corpus/nathanmarz/storm/hash.json ; echo 'nathanmarz/storm' ; sleep 360
./get_hash.py corpus/LMAX-Exchange/disruptor/summary.json > corpus/LMAX-Exchange/disruptor/hash.json ; echo 'LMAX-Exchange/disruptor' ; sleep 360
./get_hash.py corpus/google/iosched/summary.json > corpus/google/iosched/hash.json ; echo 'google/iosched' ; sleep 360
./get_hash.py corpus/Curzibn/Luban/summary.json > corpus/Curzibn/Luban/hash.json ; echo 'Curzibn/Luban' ; sleep 360
./get_hash.py corpus/Tencent/VasSonic/summary.json > corpus/Tencent/VasSonic/hash.json ; echo 'Tencent/VasSonic' ; sleep 360
./get_hash.py corpus/hdodenhof/CircleImageView/summary.json > corpus/hdodenhof/CircleImageView/hash.json ; echo 'hdodenhof/CircleImageView' ; sleep 360
./get_hash.py corpus/chrisjenx/Calligraphy/summary.json > corpus/chrisjenx/Calligraphy/hash.json ; echo 'chrisjenx/Calligraphy' ; sleep 360
./get_hash.py corpus/zhihu/Matisse/summary.json > corpus/zhihu/Matisse/hash.json ; echo 'zhihu/Matisse' ; sleep 360
./get_hash.py corpus/Yalantis/uCrop/summary.json > corpus/Yalantis/uCrop/hash.json ; echo 'Yalantis/uCrop' ; sleep 360
./get_hash.py corpus/alibaba/vlayout/summary.json > corpus/alibaba/vlayout/hash.json ; echo 'alibaba/vlayout' ; sleep 360
./get_hash.py corpus/ReactiveX/RxAndroid/summary.json > corpus/ReactiveX/RxAndroid/hash.json ; echo 'ReactiveX/RxAndroid' ; sleep 360
./get_hash.py corpus/JakeWharton/RxBinding/summary.json > corpus/JakeWharton/RxBinding/hash.json ; echo 'JakeWharton/RxBinding' ; sleep 360
./get_hash.py corpus/nickbutcher/plaid/summary.json > corpus/nickbutcher/plaid/hash.json ; echo 'nickbutcher/plaid' ; sleep 360
./get_hash.py corpus/greenrobot/EventBus/summary.json > corpus/greenrobot/EventBus/hash.json ; echo 'greenrobot/EventBus' ; sleep 360
./get_hash.py corpus/jfeinstein10/SlidingMenu/summary.json > corpus/jfeinstein10/SlidingMenu/hash.json ; echo 'jfeinstein10/SlidingMenu' ; sleep 360
./get_hash.py corpus/apl-devs/AppIntro/summary.json > corpus/apl-devs/AppIntro/hash.json ; echo 'apl-devs/AppIntro' ; sleep 360
./get_hash.py corpus/facebook/stetho/summary.json > corpus/facebook/stetho/hash.json ; echo 'facebook/stetho' ; sleep 360
./get_hash.py corpus/chrisbanes/PhotoView/summary.json > corpus/chrisbanes/PhotoView/hash.json ; echo 'chrisbanes/PhotoView' ; sleep 360
./get_hash.py corpus/roughike/BottomBar/summary.json > corpus/roughike/BottomBar/hash.json ; echo 'roughike/BottomBar' ; sleep 360
./get_hash.py corpus/permissions-dispatcher/PermissionsDispatcher/summary.json > corpus/permissions-dispatcher/PermissionsDispatcher/hash.json ; echo 'permissions-dispatcher/PermissionsDispatcher' ; sleep 360
./get_hash.py corpus/iluwatar/java-design-patterns/summary.json > corpus/iluwatar/java-design-patterns/hash.json ; echo 'iluwatar/java-design-patterns' ; sleep 360
./get_hash.py corpus/jeasonlzy/okhttp-OkGo/summary.json > corpus/jeasonlzy/okhttp-OkGo/hash.json ; echo 'jeasonlzy/okhttp-OkGo' ; sleep 360
./get_hash.py corpus/umano/AndroidSlidingUpPanel/summary.json > corpus/umano/AndroidSlidingUpPanel/hash.json ; echo 'umano/AndroidSlidingUpPanel' ; sleep 360
./get_hash.py corpus/Bigkoo/Android-PickerView/summary.json > corpus/Bigkoo/Android-PickerView/hash.json ; echo 'Bigkoo/Android-PickerView' ; sleep 360
./get_hash.py corpus/hankcs/HanLP/summary.json > corpus/hankcs/HanLP/hash.json ; echo 'hankcs/HanLP' ; sleep 360
./get_hash.py corpus/greenrobot/greenDAO/summary.json > corpus/greenrobot/greenDAO/hash.json ; echo 'greenrobot/greenDAO' ; sleep 360
./get_hash.py corpus/perwendel/spark/summary.json > corpus/perwendel/spark/hash.json ; echo 'perwendel/spark' ; sleep 360
./get_hash.py corpus/Blankj/AndroidUtilCode/summary.json > corpus/Blankj/AndroidUtilCode/hash.json ; echo 'Blankj/AndroidUtilCode' ; sleep 360
./get_hash.py corpus/airbnb/lottie-android/summary.json > corpus/airbnb/lottie-android/hash.json ; echo 'airbnb/lottie-android' ; sleep 360
./get_hash.py corpus/pockethub/PocketHub/summary.json > corpus/pockethub/PocketHub/hash.json ; echo 'pockethub/PocketHub' ; sleep 360
./get_hash.py corpus/scwang90/SmartRefreshLayout/summary.json > corpus/scwang90/SmartRefreshLayout/hash.json ; echo 'scwang90/SmartRefreshLayout' ; sleep 360
./get_hash.py corpus/google/gson/summary.json > corpus/google/gson/hash.json ; echo 'google/gson' ; sleep 360
./get_hash.py corpus/zxing/zxing/summary.json > corpus/zxing/zxing/hash.json ; echo 'zxing/zxing' ; sleep 360
./get_hash.py corpus/nostra13/Android-Universal-Image-Loader/summary.json > corpus/nostra13/Android-Universal-Image-Loader/hash.json ; echo 'nostra13/Android-Universal-Image-Loader' ; sleep 360
./get_hash.py corpus/square/leakcanary/summary.json > corpus/square/leakcanary/hash.json ; echo 'square/leakcanary' ; sleep 360
./get_hash.py corpus/loopj/android-async-http/summary.json > corpus/loopj/android-async-http/hash.json ; echo 'loopj/android-async-http' ; sleep 360
./get_hash.py corpus/Tencent/tinker/summary.json > corpus/Tencent/tinker/hash.json ; echo 'Tencent/tinker' ; sleep 360
./get_hash.py corpus/mybatis/mybatis-3/summary.json > corpus/mybatis/mybatis-3/hash.json ; echo 'mybatis/mybatis-3' ; sleep 360
./get_hash.py corpus/oxyee-down-org/proxyee-down/summary.json > corpus/oxyee-down-org/proxyee-down/hash.json ; echo 'oxyee-down-org/proxyee-down' ; sleep 360
./get_hash.py corpus/JakeWharton/butterknife/summary.json > corpus/JakeWharton/butterknife/hash.json ; echo 'JakeWharton/butterknife' ; sleep 360
./get_hash.py corpus/Netflix/Hystrix/summary.json > corpus/Netflix/Hystrix/hash.json ; echo 'Netflix/Hystrix' ; sleep 360
./get_hash.py corpus/apache/incubator-weex/summary.json > corpus/apache/incubator-weex/hash.json ; echo 'apache/incubator-weex' ; sleep 360
./get_hash.py corpus/alibaba/fastjson/summary.json > corpus/alibaba/fastjson/hash.json ; echo 'alibaba/fastjson' ; sleep 360
./get_hash.py corpus/square/picasso/summary.json > corpus/square/picasso/hash.json ; echo 'square/picasso' ; sleep 360
./get_hash.py corpus/afollestad/material-dialogs/summary.json > corpus/afollestad/material-dialogs/hash.json ; echo 'afollestad/material-dialogs' ; sleep 360
./get_hash.py corpus/spring-projects/spring-framework/summary.json > corpus/spring-projects/spring-framework/hash.json ; echo 'spring-projects/spring-framework' ; sleep 360
./get_hash.py corpus/alibaba/druid/summary.json > corpus/alibaba/druid/hash.json ; echo 'alibaba/druid' ; sleep 360
./get_hash.py corpus/openzipkin/zipkin/summary.json > corpus/openzipkin/zipkin/hash.json ; echo 'openzipkin/zipkin' ; sleep 360
./get_hash.py corpus/facebook/fresco/summary.json > corpus/facebook/fresco/hash.json ; echo 'facebook/fresco' ; sleep 360
./get_hash.py corpus/google/guava/summary.json > corpus/google/guava/hash.json ; echo 'google/guava' ; sleep 360
./get_hash.py corpus/androidannotations/androidannotations/summary.json > corpus/androidannotations/androidannotations/hash.json ; echo 'androidannotations/androidannotations' ; sleep 360
./get_hash.py corpus/mikepenz/MaterialDrawer/summary.json > corpus/mikepenz/MaterialDrawer/hash.json ; echo 'mikepenz/MaterialDrawer' ; sleep 360
./get_hash.py corpus/eclipse/vert.x/summary.json > corpus/eclipse/vert.x/hash.json ; echo 'eclipse/vert.x' ; sleep 360
./get_hash.py corpus/square/retrofit/summary.json > corpus/square/retrofit/hash.json ; echo 'square/retrofit' ; sleep 360
./get_hash.py corpus/PhilJay/MPAndroidChart/summary.json > corpus/PhilJay/MPAndroidChart/hash.json ; echo 'PhilJay/MPAndroidChart' ; sleep 360
./get_hash.py corpus/jenkinsci/jenkins/summary.json > corpus/jenkinsci/jenkins/hash.json ; echo 'jenkinsci/jenkins' ; sleep 360
./get_hash.py corpus/CymChad/BaseRecyclerViewAdapterHelper/summary.json > corpus/CymChad/BaseRecyclerViewAdapterHelper/hash.json ; echo 'CymChad/BaseRecyclerViewAdapterHelper' ; sleep 360
./get_hash.py corpus/wix/react-native-navigation/summary.json > corpus/wix/react-native-navigation/hash.json ; echo 'wix/react-native-navigation' ; sleep 360
./get_hash.py corpus/libgdx/libgdx/summary.json > corpus/libgdx/libgdx/hash.json ; echo 'libgdx/libgdx' ; sleep 360
./get_hash.py corpus/apache/kafka/summary.json > corpus/apache/kafka/hash.json ; echo 'apache/kafka' ; sleep 360
./get_hash.py corpus/ReactiveX/RxJava/summary.json > corpus/ReactiveX/RxJava/hash.json ; echo 'ReactiveX/RxJava' ; sleep 360
./get_hash.py corpus/realm/realm-java/summary.json > corpus/realm/realm-java/hash.json ; echo 'realm/realm-java' ; sleep 360
./get_hash.py corpus/netty/netty/summary.json > corpus/netty/netty/hash.json ; echo 'netty/netty' ; sleep 360
./get_hash.py corpus/signalapp/Signal-Android/summary.json > corpus/signalapp/Signal-Android/hash.json ; echo 'signalapp/Signal-Android' ; sleep 360
./get_hash.py corpus/prestodb/presto/summary.json > corpus/prestodb/presto/hash.json ; echo 'prestodb/presto' ; sleep 360
date 
/home/iwanaga/slack_noti.sh "end hash job"
