python3 make_direct_corpus.py wix/react-native-navigationg
python3 make_direct_corpus.py HannahMitt/HomeMirrorg
python3 make_direct_corpus.py iluwatar/java-design-patternsg
python3 make_direct_corpus.py spring-projects/spring-bootg
python3 make_direct_corpus.py spring-projects/spring-frameworkg
python3 make_direct_corpus.py navasmdc/MaterialDesignLibraryg
python3 make_direct_corpus.py DrKLO/Telegramg
python3 make_direct_corpus.py florent37/MaterialViewPagerg
python3 make_direct_corpus.py Konloch/bytecode-viewerg
python3 make_direct_corpus.py nostra13/Android-Universal-Image-Loaderg
python3 make_direct_corpus.py brettwooldridge/HikariCPg
python3 make_direct_corpus.py bazelbuild/bazelg
python3 make_direct_corpus.py scwang90/SmartRefreshLayoutg
python3 make_direct_corpus.py zxing/zxingg
python3 make_direct_corpus.py wasabeef/recyclerview-animatorsg
python3 make_direct_corpus.py signalapp/Signal-Androidg
python3 make_direct_corpus.py ReactiveX/RxAndroidg
python3 make_direct_corpus.py ReactiveX/RxJavag
python3 make_direct_corpus.py permissions-dispatcher/PermissionsDispatcherg
python3 make_direct_corpus.py prestodb/prestog
python3 make_direct_corpus.py Tencent/tinkerg
python3 make_direct_corpus.py Tencent/VasSonicg
python3 make_direct_corpus.py elastic/elasticsearchg
python3 make_direct_corpus.py android10/Android-CleanArchitectureg
python3 make_direct_corpus.py PhilJay/MPAndroidChartg
python3 make_direct_corpus.py crossoverJie/Java-Interviewg
python3 make_direct_corpus.py jenkinsci/jenkinsg
python3 make_direct_corpus.py deeplearning4j/deeplearning4jg
python3 make_direct_corpus.py afollestad/material-dialogsg
python3 make_direct_corpus.py Bigkoo/Android-PickerViewg
python3 make_direct_corpus.py eclipse/vert.xg
python3 make_direct_corpus.py winterbe/java8-tutorialg
python3 make_direct_corpus.py netty/nettyg
python3 make_direct_corpus.py airbnb/lottie-androidg
python3 make_direct_corpus.py libgdx/libgdxg
python3 make_direct_corpus.py hdodenhof/CircleImageViewg
python3 make_direct_corpus.py chrisbanes/cheesesquareg
python3 make_direct_corpus.py chrisbanes/Android-PullToRefreshg
python3 make_direct_corpus.py chrisbanes/PhotoViewg
python3 make_direct_corpus.py alibaba/fastjsong
python3 make_direct_corpus.py alibaba/druidg
python3 make_direct_corpus.py alibaba/vlayoutg
python3 make_direct_corpus.py SeleniumHQ/seleniumg
python3 make_direct_corpus.py LMAX-Exchange/disruptorg
python3 make_direct_corpus.py shuzheng/zhengg
python3 make_direct_corpus.py pockethub/PocketHubg
python3 make_direct_corpus.py perwendel/sparkg
python3 make_direct_corpus.py apl-devs/AppIntrog
python3 make_direct_corpus.py lgvalle/Material-Animationsg
python3 make_direct_corpus.py Netflix/Hystrixg
python3 make_direct_corpus.py hankcs/HanLPg
python3 make_direct_corpus.py google/guavag
python3 make_direct_corpus.py google/ioschedg
python3 make_direct_corpus.py google/ExoPlayerg
python3 make_direct_corpus.py google/gsong
python3 make_direct_corpus.py 81813780/AVLoadingIndicatorViewg
python3 make_direct_corpus.py mikepenz/MaterialDrawerg
python3 make_direct_corpus.py daimajia/AndroidViewAnimationsg
python3 make_direct_corpus.py daimajia/AndroidSwipeLayoutg
python3 make_direct_corpus.py skylot/jadxg
python3 make_direct_corpus.py CymChad/BaseRecyclerViewAdapterHelperg
python3 make_direct_corpus.py chrisjenx/Calligraphyg
python3 make_direct_corpus.py nathanmarz/stormg
python3 make_direct_corpus.py Curzibn/Lubang
python3 make_direct_corpus.py Blankj/AndroidUtilCodeg
python3 make_direct_corpus.py umano/AndroidSlidingUpPanelg
python3 make_direct_corpus.py Yalantis/uCropg
python3 make_direct_corpus.py JakeWharton/butterknifeg
python3 make_direct_corpus.py JakeWharton/RxBindingg
python3 make_direct_corpus.py JakeWharton/ViewPagerIndicatorg
python3 make_direct_corpus.py bumptech/glideg
python3 make_direct_corpus.py jfeinstein10/SlidingMenug
python3 make_direct_corpus.py zhihu/Matisseg
python3 make_direct_corpus.py ksoichiro/Android-ObservableScrollViewg
python3 make_direct_corpus.py androidannotations/androidannotationsg
python3 make_direct_corpus.py roughike/BottomBarg
python3 make_direct_corpus.py jeasonlzy/okhttp-OkGog
python3 make_direct_corpus.py orhanobut/loggerg
python3 make_direct_corpus.py nickbutcher/plaidg
python3 make_direct_corpus.py liaohuqiu/android-Ultra-Pull-To-Refreshg
python3 make_direct_corpus.py realm/realm-javag
python3 make_direct_corpus.py openzipkin/zipking
python3 make_direct_corpus.py EnterpriseQualityCoding/FizzBuzzEnterpriseEditiong
python3 make_direct_corpus.py kdn251/interviewsg
python3 make_direct_corpus.py loopj/android-async-httpg
python3 make_direct_corpus.py facebook/frescog
python3 make_direct_corpus.py facebook/stethog
python3 make_direct_corpus.py proxyee-down-org/proxyee-downg
python3 make_direct_corpus.py aosp-mirror/platform_frameworks_baseg
python3 make_direct_corpus.py greenrobot/EventBusg
python3 make_direct_corpus.py greenrobot/greenDAOg
python3 make_direct_corpus.py mybatis/mybatis-3g
python3 make_direct_corpus.py apache/incubator-dubbog
python3 make_direct_corpus.py apache/kafkag
python3 make_direct_corpus.py apache/incubator-weexg
python3 make_direct_corpus.py apache/hadoopg
python3 make_direct_corpus.py square/retrofitg
python3 make_direct_corpus.py square/leakcanaryg
python3 make_direct_corpus.py square/okhttpg
python3 make_direct_corpus.py square/picassog
