corpus2/chrisjenx/Calligraphy/api.json
corpus2/vondear/RxTool/api.json
corpus2/mockito/mockito/api.json
corpus2/perwendel/spark/api.json
corpus2/Yalantis/uCrop/api.json
corpus2/HannahMitt/HomeMirror/api.json
corpus2/YoKeyword/Fragmentation/api.json
corpus2/H07000223/FlycoTabLayout/api.json
corpus2/florent37/MaterialViewPager/api.json
corpus2/lingochamp/FileDownloader/api.json
corpus2/naver/pinpoint/api.json
corpus2/chrisbanes/cheesesquare/api.json
corpus2/tbruyelle/RxPermissions/api.json
corpus2/Freelander/Android_Data/api.json
corpus2/clojure/clojure/api.json
corpus2/google/guice/api.json
corpus2/youth5201314/banner/api.json
corpus2/Bilibili/DanmakuFlameMaster/api.json
corpus2/xetorthio/jedis/api.json
corpus2/code4craft/webmagic/api.json
corpus2/apache/incubator-druid/api.json
corpus2/JeffLi1993/springboot-learning-example/api.json
corpus2/google/agera/api.json
corpus2/JakeWharton/ActionBarSherlock/api.json
corpus2/google/auto/api.json
corpus2/junit-team/junit4/api.json
corpus2/oracle/graal/api.json
corpus2/iBotPeaches/Apktool/api.json
corpus2/JessYanCoding/MVPArms/api.json
corpus2/redisson/redisson/api.json
corpus2/wasabeef/glide-transformations/api.json
corpus2/rzwitserloot/lombok/api.json
corpus2/square/dagger/api.json
corpus2/dropwizard/dropwizard/api.json
corpus2/Netflix/SimianArmy/api.json
corpus2/alibaba/arthas/api.json
corpus2/cymcsg/UltimateRecyclerView/api.json
corpus2/Bearded-Hen/Android-Bootstrap/api.json
corpus2/koral--/android-gif-drawable/api.json
corpus2/ityouknow/spring-boot-examples/api.json
corpus2/kaushikgopal/RxJava-Android-Samples/api.json
corpus2/Netflix/eureka/api.json
corpus2/dbeaver/dbeaver/api.json
corpus2/google/tink/api.json
corpus2/googlesamples/easypermissions/api.json
corpus2/astuetz/PagerSlidingTabStrip/api.json
corpus2/alibaba/canal/api.json
corpus2/alibaba/atlas/api.json
corpus2/jhy/jsoup/api.json
corpus2/laobie/StatusBarUtil/api.json
corpus2/ChrisRM/material-theme-jetbrains/api.json
corpus2/Netflix/zuul/api.json
corpus2/GcsSloop/AndroidNote/api.json
corpus2/hongyangAndroid/okhttputils/api.json
corpus2/hongyangAndroid/AndroidAutoLayout/api.json
corpus2/aritraroy/UltimateAndroidReference/api.json
corpus2/didi/VirtualAPK/api.json
corpus2/JakeWharton/hugo/api.json
corpus2/trello/RxLifecycle/api.json
corpus2/react-native-community/react-native-camera/api.json
corpus2/JakeWharton/timber/api.json
corpus2/geeeeeeeeek/WeChatLuckyMoney/api.json
corpus2/facebook/buck/api.json
corpus2/pedant/sweet-alert-dialog/api.json
corpus2/lecho/hellocharts-android/api.json
corpus2/square/javapoet/api.json
corpus2/dropwizard/metrics/api.json
corpus2/xuxueli/xxl-job/api.json
corpus2/google/physical-web/api.json
corpus2/sharding-sphere/sharding-sphere/api.json
corpus2/apache/rocketmq/api.json
corpus2/daniulive/SmarterStreaming/api.json
corpus2/codecentric/spring-boot-admin/api.json
corpus2/DroidPluginTeam/DroidPlugin/api.json
corpus2/googlesamples/android-testing/api.json
corpus2/mission-peace/interview/api.json
corpus2/QMUI/QMUI_Android/api.json
corpus2/koush/ion/api.json
corpus2/pedrovgs/EffectiveAndroidUI/api.json
corpus2/pagehelper/Mybatis-PageHelper/api.json
corpus2/futuresimple/android-floating-action-button/api.json
corpus2/nhaarman/ListViewAnimations/api.json
corpus2/rey5137/material/api.json
corpus2/medcl/elasticsearch-analysis-ik/api.json
corpus2/LitePalFramework/LitePal/api.json
corpus2/material-components/material-components-android/api.json
corpus2/cats-oss/android-gpuimage/api.json
corpus2/stanfordnlp/CoreNLP/api.json
corpus2/JakeWharton/u2020/api.json
corpus2/antoniolg/androidmvp/api.json
corpus2/singwhatiwanna/dynamic-load-apk/api.json
corpus2/ybq/Android-SpinKit/api.json
corpus2/facebook/litho/api.json
corpus2/springside/springside4/api.json
corpus2/ikew0ng/SwipeBackLayout/api.json
corpus2/rengwuxian/MaterialEditText/api.json
corpus2/apache/zookeeper/api.json
corpus2/amitshekhariitbhu/Android-Debug-Database/api.json
corpus2/apache/storm/api.json
corpus2/leolin310148/ShortcutBadger/api.json
corpus2/forezp/SpringCloudLearning/api.json
corpus2/amlcurran/ShowcaseView/api.json
corpus2/swagger-api/swagger-core/api.json
corpus2/MyCATApache/Mycat-Server/api.json
corpus2/emilsjolander/StickyListHeaders/api.json
corpus2/pxb1988/dex2jar/api.json
corpus2/hackware1993/MagicIndicator/api.json
corpus2/naman14/Timber/api.json
corpus2/evant/gradle-retrolambda/api.json
corpus2/google/j2objc/api.json
corpus2/MyCATApache/Mycat-Server/api.json
corpus2/emilsjolander/StickyListHeaders/api.json
corpus2/pxb1988/dex2jar/api.json
corpus2/hackware1993/MagicIndicator/api.json
corpus2/naman14/Timber/api.json
corpus2/evant/gradle-retrolambda/api.json
corpus2/google/j2objc/api.json
corpus2/google/android-classyshark/api.json
corpus2/shwenzhang/AndResGuard/api.json
corpus2/LuckSiege/PictureSelector/api.json
corpus2/daimajia/AndroidImageSlider/api.json
corpus2/lucasr/twoway-view/api.json
corpus2/daimajia/NumberProgressBar/api.json
corpus2/Qihoo360/RePlugin/api.json
corpus2/facebook/rebound/api.json
corpus2/wyouflf/xUtils3/api.json
corpus2/apereo/cas/api.json
corpus2/square/otto/api.json
corpus2/eclipse/che/api.json
corpus2/vinc3m1/RoundedImageView/api.json
corpus2/apache/flink/api.json
corpus2/grpc/grpc-java/api.json
corpus2/Devlight/InfiniteCycleViewPager/api.json
corpus2/dyc87112/SpringBoot-Learning/api.json
corpus2/android-hacker/VirtualXposed/api.json
corpus2/apache/incubator-skywalking/api.json
corpus2/Nightonke/BoomMenu/api.json
corpus2/jgilfelt/SystemBarTint/api.json
corpus2/dmytrodanylyk/circular-progress-button/api.json
corpus2/GoogleContainerTools/jib/api.json
corpus2/kickstarter/android-oss/api.json
corpus2/wyouflf/xUtils/api.json
corpus2/asLody/VirtualApp/api.json
corpus2/sparklemotion/nokogiri/api.json
corpus2/sockeqwe/mosby/api.json
corpus2/JessYanCoding/AndroidAutoSize/api.json
corpus2/Justson/AgentWeb/api.json
corpus2/ben-manes/caffeine/api.json
corpus2/airbnb/epoxy/api.json
corpus2/evernote/android-job/api.json
corpus2/frogermcs/InstaMaterial/api.json
corpus2/davemorrissey/subsampling-scale-image-view/api.json
corpus2/Blankj/awesome-java-leetcode/api.json
corpus2/gyf-dev/ImmersionBar/api.json
corpus2/claritylab/lucida/api.json
corpus2/firebase/quickstart-android/api.json
corpus2/Trinea/android-common/api.json
corpus2/yixia/VitamioBundle/api.json
corpus2/hs-web/hsweb-framework/api.json
corpus2/GrenderG/Toasty/api.json
corpus2/aa112901/remusic/api.json
corpus2/zaproxy/zaproxy/api.json
corpus2/thinkaurelius/titan/api.json
corpus2/apache/cassandra/api.json
corpus2/alibaba/freeline/api.json
corpus2/vipshop/vjtools/api.json
corpus2/Yalantis/Side-Menu.Android/api.json
corpus2/antlr/antlr4/api.json
corpus2/izzyleung/ZhihuDailyPurify/api.json
corpus2/gabrielemariotti/cardslib/api.json
corpus2/traex/RippleEffect/api.json
corpus2/prolificinteractive/material-calendarview/api.json
corpus2/yanzhenjie/AndPermission/api.json
corpus2/AsyncHttpClient/async-http-client/api.json
corpus2/weibocom/motan/api.json
corpus2/JakeWharton/DiskLruCache/api.json
corpus2/commonsguy/cw-omnibus/api.json
corpus2/etsy/AndroidStaggeredGrid/api.json
corpus2/TooTallNate/Java-WebSocket/api.json
corpus2/smuyyh/BookReader/api.json
corpus2/square/sqlbrite/api.json
corpus2/TeamNewPipe/NewPipe/api.json
corpus2/gitpitch/gitpitch/api.json
corpus2/ACRA/acra/api.json
corpus2/facebook/facebook-android-sdk/api.json
corpus2/guardianproject/haven/api.json
corpus2/scribejava/scribejava/api.json
corpus2/react-community/react-native-image-picker/api.json
corpus2/pardom-zz/ActiveAndroid/api.json
corpus2/NLPchina/ansj_seg/api.json
corpus2/motianhuo/wechat/api.json
corpus2/markzhai/AndroidPerformanceMonitor/api.json
corpus2/XRecyclerView/XRecyclerView/api.json
corpus2/square/moshi/api.json
corpus2/Graylog2/graylog2-server/api.json
corpus2/MindorksOpenSource/android-interview-questions/api.json
corpus2/sqshq/PiggyMetrics/api.json
corpus2/google/closure-compiler/api.json
corpus2/janishar/mit-deep-learning-book-pdf/api.json
corpus2/processing/processing/api.json
corpus2/go-lang-plugin-org/go-lang-idea-plugin/api.json
corpus2/wequick/Small/api.json
corpus2/gocd/gocd/api.json
corpus2/Clans/FloatingActionButton/api.json
corpus2/hongyangAndroid/FlowLayout/api.json
corpus2/chentao0707/SimplifyReader/api.json
corpus2/mcxiaoke/android-volley/api.json
corpus2/JakeWharton/NineOldAndroids/api.json
corpus2/java-native-access/jna/api.json
corpus2/danielzeller/Depth-LIB-Android-/api.json
corpus2/knightliao/disconf/api.json
corpus2/careercup/ctci/api.json
corpus2/elasticjob/elastic-job-lite/api.json
corpus2/Devlight/NavigationTabBar/api.json
corpus2/dm77/barcodescanner/api.json
corpus2/Activiti/Activiti/api.json
corpus2/lets-blade/blade/api.json
corpus2/aporter/coursera-android/api.json
corpus2/NLPchina/elasticsearch-sql/api.json
corpus2/square/android-times-square/api.json
corpus2/AndroidBootstrap/android-bootstrap/api.json
corpus2/robolectric/robolectric/api.json
corpus2/hanks-zyh/HTextView/api.json
corpus2/h6ah4i/android-advancedrecyclerview/api.json
corpus2/wasabeef/richeditor-android/api.json
corpus2/yarolegovich/DiscreteScrollView/api.json
corpus2/NanoHttpd/nanohttpd/api.json
corpus2/Ramotion/folding-cell-android/api.json
corpus2/google/error-prone/api.json
corpus2/andkulikov/Transitions-Everywhere/api.json
corpus2/jdamcd/android-crop/api.json
corpus2/spring-projects/spring-mvc-showcase/api.json
corpus2/orhanobut/dialogplus/api.json
corpus2/joelittlejohn/jsonschema2pojo/api.json
corpus2/gzu-liyujiang/AndroidPicker/api.json
corpus2/castorflex/SmoothProgressBar/api.json
corpus2/KeepSafe/TapTargetView/api.json
corpus2/alibaba/UltraViewPager/api.json
corpus2/careercup/CtCI-6th-Edition/api.json
corpus2/barteksc/AndroidPdfViewer/api.json
corpus2/k9mail/k-9/api.json
corpus2/Vedenin/useful-java-links/api.json
corpus2/hongyangAndroid/baseAdapter/api.json
corpus2/haifengl/smile/api.json
corpus2/checkstyle/checkstyle/api.json
corpus2/Flipboard/bottomsheet/api.json
corpus2/google/cameraview/api.json
corpus2/DreaminginCodeZH/Douya/api.json
corpus2/uber/RIBs/api.json
corpus2/mikepenz/Android-Iconics/api.json
corpus2/Bigkoo/Android-ConvenientBanner/api.json
corpus2/ArthurHub/Android-Image-Cropper/api.json
corpus2/TommyLemon/APIJSON/api.json
corpus2/makovkastar/FloatingActionButton/api.json
corpus2/alibaba/dexposed/api.json
corpus2/diogobernardino/WilliamChart/api.json
corpus2/jpush/aurora-imui/api.json
corpus2/jwtk/jjwt/api.json
corpus2/zetbaitsu/Compressor/api.json
corpus2/amitshekhariitbhu/RxJava2-Android-Samples/api.json
corpus2/amitshekhariitbhu/Fast-Android-Networking/api.json
corpus2/real-logic/aeron/api.json
corpus2/lightbend/config/api.json
corpus2/mcxiaoke/packer-ng-plugin/api.json
corpus2/Meituan-Dianping/walle/api.json
corpus2/Yalantis/Phoenix/api.json
corpus2/lihengming/spring-boot-api-project-seed/api.json
corpus2/kyleduo/SwitchButton/api.json
corpus2/apache/zeppelin/api.json
corpus2/roboguice/roboguice/api.json
corpus2/alibaba/otter/api.json
corpus2/JodaOrg/joda-time/api.json
corpus2/HotBitmapGG/bilibili-android-client/api.json
corpus2/huanghaibin-dev/CalendarView/api.json
corpus2/Angel-ML/angel/api.json
corpus2/bingoogolapple/BGARefreshLayout-Android/api.json
corpus2/pedrovgs/AndroidWiFiADB/api.json
corpus2/k0shk0sh/FastHub/api.json
corpus2/rubensousa/RecyclerViewSnap/api.json
corpus2/alibaba/Sentinel/api.json
corpus2/wuhaoyu1990/MagicCamera/api.json
corpus2/wdullaer/MaterialDateTimePicker/api.json
corpus2/Alluxio/alluxio/api.json
corpus2/drakeet/MultiType/api.json
corpus2/MindorksOpenSource/from-java-to-kotlin/api.json
corpus2/liyifeng1994/ssm/api.json
corpus2/yipianfengye/android-zxingLibrary/api.json
corpus2/OpenFeign/feign/api.json
corpus2/grantland/android-autofittextview/api.json
corpus2/nisrulz/android-tips-tricks/api.json
corpus2/orientechnologies/orientdb/api.json
corpus2/rengwuxian/RxJavaSamples/api.json
corpus2/wasabeef/Blurry/api.json
corpus2/JoanZapata/android-iconify/api.json
corpus2/alibaba/jstorm/api.json
corpus2/h2oai/h2o-3/api.json
corpus2/yanzhenjie/SwipeRecyclerView/api.json
corpus2/pili-engineering/PLDroidPlayer/api.json
corpus2/BoltsFramework/Bolts-Android/api.json
corpus2/sohutv/cachecloud/api.json
corpus2/Ashok-Varma/BottomNavigation/api.json
corpus2/JetBrains/ideavim/api.json
corpus2/flyway/flyway/api.json
corpus2/hugeterry/CoordinatorTabLayout/api.json
corpus2/Karumi/Dexter/api.json
corpus2/react-native-community/react-native-video/api.json
corpus2/yanzhenjie/NoHttp/api.json
corpus2/ximsfei/Android-skin-support/api.json
corpus2/jgilfelt/chuck/api.json
corpus2/baoyachi/StepView/api.json
corpus2/zo0r/react-native-push-notification/api.json
corpus2/hibernate/hibernate-orm/api.json
corpus2/kevin-wayne/algs4/api.json
corpus2/rubensousa/ViewPagerCards/api.json
corpus2/rest-assured/rest-assured/api.json
corpus2/dinuscxj/LoadingDrawable/api.json
corpus2/ChadCSong/ShineButton/api.json
corpus2/openhab/openhab1-addons/api.json
corpus2/luontola/retrolambda/api.json
corpus2/Yalantis/Context-Menu.Android/api.json
corpus2/aurelhubert/ahbottomnavigation/api.json
corpus2/lcodecorex/TwinklingRefreshLayout/api.json
corpus2/romandanylyk/PageIndicatorView/api.json
corpus2/NYTimes/Store/api.json
corpus2/socketio/socket.io-client-java/api.json
corpus2/topjohnwu/Magisk/api.json
corpus2/baoyongzhang/SwipeMenuListView/api.json
corpus2/amirzaidi/Launcher3/api.json
corpus2/avast/android-butterknife-zelezny/api.json
corpus2/PipelineAI/pipeline/api.json
corpus2/OpenTSDB/opentsdb/api.json
corpus2/puniverse/quasar/api.json
corpus2/baomidou/mybatis-plus/api.json
corpus2/CellularPrivacy/Android-IMSI-Catcher-Detector/api.json
corpus2/google/google-authenticator/api.json
corpus2/mrniko/netty-socketio/api.json
corpus2/MiguelCatalan/MaterialSearchView/api.json
corpus2/xcc3641/SeeWeather/api.json
corpus2/youlookwhat/CloudReader/api.json
corpus2/Manabu-GT/ExpandableTextView/api.json
corpus2/ryanhoo/StylishMusicPlayer/api.json
corpus2/jfoenixadmin/JFoenix/api.json
corpus2/tyrantgit/ExplosionField/api.json
corpus2/apache/incubator-heron/api.json
corpus2/yigit/android-priority-jobqueue/api.json
corpus2/bluelinelabs/Conductor/api.json
corpus2/chrisbanes/ActionBar-PullToRefresh/api.json
corpus2/TommyLemon/Android-ZBLibrary/api.json
corpus2/actorapp/actor-platform/api.json
corpus2/kikoso/android-stackblur/api.json
corpus2/tyrantgit/ExplosionField/api.json
corpus2/apache/incubator-heron/api.json
corpus2/yigit/android-priority-jobqueue/api.json
corpus2/bluelinelabs/Conductor/api.json
corpus2/chrisbanes/ActionBar-PullToRefresh/api.json
corpus2/TommyLemon/Android-ZBLibrary/api.json
corpus2/actorapp/actor-platform/api.json
corpus2/kikoso/android-stackblur/api.json
corpus2/json-path/JsonPath/api.json
corpus2/robinhood/ticker/api.json
corpus2/Atmosphere/atmosphere/api.json
corpus2/ivacf/archi/api.json
corpus2/Jacksgong/JKeyboardPanelSwitch/api.json
corpus2/yasserg/crawler4j/api.json
corpus2/yangfuhai/ASimpleCache/api.json
corpus2/rabbitmq/rabbitmq-tutorials/api.json
corpus2/lsjwzh/RecyclerViewPager/api.json
corpus2/airbnb/DeepLinkDispatch/api.json
corpus2/litesuits/android-common/api.json
corpus2/xcltapestry/XCL-Charts/api.json
corpus2/dropbox/hackpad/api.json
corpus2/journeyapps/zxing-android-embedded/api.json
corpus2/codeestX/GeekNews/api.json
corpus2/ongakuer/CircleIndicator/api.json
corpus2/bauerca/drag-sort-listview/api.json
corpus2/lzyzsd/CircleProgress/api.json
corpus2/zouzg/mybatis-generator-gui/api.json
corpus2/springfox/springfox/api.json
corpus2/JesusFreke/smali/api.json
corpus2/yangfuhai/afinal/api.json
corpus2/bluelinelabs/LoganSquare/api.json
corpus2/SonarSource/sonarqube/api.json
corpus2/orhanobut/hawk/api.json
corpus2/pengjianbo/GalleryFinal/api.json
corpus2/spring-projects/spring-security-oauth/api.json
corpus2/firebase/FirebaseUI-Android/api.json
corpus2/facebook/shimmer-android/api.json
corpus2/dyc87112/SpringCloud-Learning/api.json
corpus2/react-native-community/react-native-svg/api.json
corpus2/tangqi92/Android-Tips/api.json
corpus2/dongjunkun/DropDownMenu/api.json
corpus2/stleary/JSON-java/api.json
corpus2/bitcoinj/bitcoinj/api.json
corpus2/siacs/Conversations/api.json
corpus2/arimorty/floatingsearchview/api.json
corpus2/Microsoft/malmo/api.json
corpus2/airbnb/native-navigation/api.json
corpus2/keycloak/keycloak/api.json
corpus2/bingoogolapple/BGABanner-Android/api.json
corpus2/keyboardsurfer/Crouton/api.json
corpus2/andremion/Music-Player/api.json
corpus2/termux/termux-app/api.json
corpus2/stephanenicolas/robospice/api.json
corpus2/udacity/Sunshine-Version-2/api.json
corpus2/DingMouRen/LayoutManagerGroup/api.json
corpus2/hitherejoe/animate/api.json
corpus2/mybatis/generator/api.json
corpus2/spring-projects/spring-security/api.json
corpus2/Bilibili/MagicaSakura/api.json
corpus2/nicolasgramlich/AndEngine/api.json
corpus2/jgilfelt/android-viewbadger/api.json
corpus2/gabrielemariotti/RecyclerViewItemAnimators/api.json
corpus2/daimajia/AndroidViewHover/api.json
corpus2/alamkanak/Android-Week-View/api.json
corpus2/Meituan-Dianping/Robust/api.json
corpus2/cjlin1/libsvm/api.json
corpus2/gephi/gephi/api.json
corpus2/qstumn/BadgeView/api.json
corpus2/DuGuQiuBai/Java/api.json
corpus2/willowtreeapps/spruce-android/api.json
corpus2/spring-cloud/spring-cloud-netflix/api.json
corpus2/ManuelPeinado/FadingActionBar/api.json
corpus2/ragunathjawahar/android-saripaar/api.json
corpus2/yahoo/anthelion/api.json
corpus2/apache/groovy/api.json
corpus2/pedrovgs/DraggablePanel/api.json
corpus2/Piasy/BigImageViewer/api.json
corpus2/saulmm/Android-Material-Examples/api.json
corpus2/danikula/AndroidVideoCache/api.json
corpus2/race604/FlyRefresh/api.json
corpus2/davideas/FlexibleAdapter/api.json
corpus2/shekhargulati/99-problems/api.json
corpus2/jasonross/Nuwa/api.json
corpus2/Exrick/xmall/api.json
corpus2/bytedeco/javacv/api.json
corpus2/hazelcast/hazelcast/api.json
corpus2/psaravan/JamsMusicPlayer/api.json
corpus2/Skykai521/StickerCamera/api.json
corpus2/abel533/Mapper/api.json
corpus2/dmytrodanylyk/android-process-button/api.json
corpus2/sherxon/AlgoDS/api.json
corpus2/lovetuzitong/MultiImageSelector/api.json
corpus2/jersey/jersey/api.json
corpus2/amulyakhare/TextDrawable/api.json
corpus2/changmingxie/tcc-transaction/api.json
corpus2/JulienGenoud/android-percent-support-lib-sample/api.json
corpus2/huangyanbin/smartTable/api.json
corpus2/vavr-io/vavr/api.json
corpus2/facebook/network-connection-class/api.json
corpus2/paascloud/paascloud-master/api.json
corpus2/rubensousa/PreviewSeekBar/api.json
corpus2/objectbox/objectbox-java/api.json
corpus2/kevinsawicki/http-request/api.json
corpus2/zzz40500/GsonFormat/api.json
corpus2/donglua/PhotoPicker/api.json
corpus2/crazycodeboy/react-native-splash-screen/api.json
corpus2/graphql-java/graphql-java/api.json
corpus2/aws/aws-sdk-java/api.json
corpus2/spring-projects/spring-petclinic/api.json
corpus2/reactive-streams/reactive-streams-jvm/api.json
corpus2/iammert/ScalingLayout/api.json
corpus2/openaphid/android-flip/api.json
corpus2/SpecialCyCi/AndroidResideMenu/api.json
corpus2/apache/tomcat/api.json
corpus2/dragonflyoss/Dragonfly/api.json
corpus2/alipay/sofa-jarslink/api.json
corpus2/oblac/jodd/api.json
corpus2/linlinjava/litemall/api.json
corpus2/yipianfengye/android-adDialog/api.json
corpus2/code-troopers/android-betterpickers/api.json
corpus2/jOOQ/jOOQ/api.json
corpus2/HoraApps/LeafPic/api.json
corpus2/sunfusheng/MarqueeView/api.json
corpus2/apache/pulsar/api.json
corpus2/seven332/EhViewer/api.json
corpus2/databricks/learning-spark/api.json
corpus2/square/flow/api.json
corpus2/Bilibili/boxing/api.json
corpus2/binIoter/GuideView/api.json
corpus2/jiangqqlmj/FastDev4Android/api.json
corpus2/danylovolokh/VideoPlayerManager/api.json
corpus2/yui/yuicompressor/api.json
corpus2/CalebFenton/simplify/api.json
corpus2/CameraKit/blurkit-android/api.json
corpus2/qii/weiciyuan/api.json
corpus2/jfinal/jfinal/api.json
corpus2/SimonVT/android-menudrawer/api.json
corpus2/edmodo/cropper/api.json
corpus2/owncloud/android/api.json
corpus2/hmkcode/Android/api.json
corpus2/luojilab/DDComponentForAndroid/api.json
corpus2/jfeinstein10/JazzyViewPager/api.json
corpus2/requery/requery/api.json
corpus2/googlemaps/android-maps-utils/api.json
corpus2/junit-team/junit5/api.json
corpus2/Yalantis/GuillotineMenu-Android/api.json
corpus2/lygttpod/SuperTextView/api.json
corpus2/vespa-engine/vespa/api.json
corpus2/sharish/ShimmerRecyclerView/api.json
corpus2/Ereza/CustomActivityOnCrash/api.json
corpus2/hongyangAndroid/Highlight/api.json
corpus2/eirslett/frontend-maven-plugin/api.json
corpus2/pushtorefresh/storio/api.json
corpus2/Malinskiy/SuperRecyclerView/api.json
corpus2/cyrilmottier/GreenDroid/api.json
corpus2/brianway/java-learning/api.json
corpus2/xmuSistone/ViewpagerTransition/api.json
corpus2/MinecraftForge/MinecraftForge/api.json
corpus2/bytedeco/javacpp/api.json
corpus2/JakeWharton/scalpel/api.json
corpus2/knowm/XChange/api.json
corpus2/mzule/ActivityRouter/api.json
corpus2/beworker/pinned-section-listview/api.json
corpus2/zzhoujay/RichText/api.json
corpus2/sunfusheng/StickyHeaderListView/api.json
corpus2/square/wire/api.json
corpus2/Tencent/MSEC/api.json
corpus2/LyndonChin/MasteringAndroidDataBinding/api.json
corpus2/awangdev/LintCode/api.json
corpus2/zwwill/yanxuan-weex-demo/api.json
corpus2/JohnPersano/SuperToasts/api.json
corpus2/florent37/ExpectAnim/api.json
corpus2/Marswin/MarsDaemon/api.json
corpus2/north2016/T-MVP/api.json
corpus2/pqpo/SmartCropper/api.json
corpus2/chennaione/sugar/api.json
corpus2/w446108264/XhsEmoticonsKeyboard/api.json
corpus2/bisq-network/bisq/api.json
corpus2/Teevity/ice/api.json
corpus2/Jasonchenlijian/FastBle/api.json
corpus2/Nightonke/WoWoViewPager/api.json
corpus2/Todd-Davies/ProgressWheel/api.json
corpus2/yusugomori/DeepLearning/api.json
corpus2/saulmm/CoordinatorBehaviorExample/api.json
corpus2/Netflix/ribbon/api.json
corpus2/Freeyourgadget/Gadgetbridge/api.json
corpus2/oldmanpushcart/greys-anatomy/api.json
corpus2/mcxtzhang/SwipeDelMenuLayout/api.json
corpus2/jprante/elasticsearch-jdbc/api.json
corpus2/johannilsson/android-pulltorefresh/api.json
corpus2/rstudio/rstudio/api.json
corpus2/geftimov/android-pathview/api.json
corpus2/BelooS/ChipsLayoutManager/api.json
corpus2/GitLqr/LQRWeChat/api.json
corpus2/eishay/jvm-serializers/api.json
corpus2/kbastani/spring-cloud-microservice-example/api.json
corpus2/JakeWharton/ThreeTenABP/api.json
corpus2/mihaip/dex-method-counts/api.json
corpus2/cryptomator/cryptomator/api.json
corpus2/saulmm/Material-Movies/api.json
corpus2/crossoverJie/SSM/api.json
corpus2/apache/cordova-android/api.json
corpus2/JoanZapata/android-pdfview/api.json
corpus2/RobotiumTech/robotium/api.json
corpus2/oguzbilgener/CircularFloatingActionMenu/api.json
corpus2/alibaba/easyexcel/api.json
corpus2/ming1016/study/api.json
corpus2/yhaolpz/FloatWindow/api.json
corpus2/mikepenz/FastAdapter/api.json
corpus2/spring-projects/spring-data-examples/api.json
corpus2/phishman3579/java-algorithms-implementation/api.json
corpus2/Comcast/FreeFlow/api.json
corpus2/TangoAgency/material-intro-screen/api.json
corpus2/googlesamples/android-vision/api.json
corpus2/pedrovgs/Algorithms/api.json
corpus2/MovingBlocks/Terasology/api.json
corpus2/path/android-priority-jobqueue/api.json
corpus2/alibaba/cobar/api.json
corpus2/jd-alexander/LikeButton/api.json
corpus2/yarolegovich/SlidingRootNav/api.json
corpus2/balysv/material-menu/api.json
corpus2/apache/jmeter/api.json
corpus2/cglib/cglib/api.json
corpus2/google/hover/api.json
corpus2/google/binnavi/api.json
corpus2/airbnb/airpal/api.json
corpus2/jhalterman/failsafe/api.json
corpus2/raphw/byte-buddy/api.json
corpus2/romainguy/ViewServer/api.json
corpus2/languagetool-org/languagetool/api.json
corpus2/apache/hbase/api.json
corpus2/florent37/DiagonalLayout/api.json
corpus2/DylanVann/react-native-fast-image/api.json
corpus2/sd6352051/NiftyDialogEffects/api.json
corpus2/bmelnychuk/AndroidTreeView/api.json
corpus2/MagicMashRoom/SuperCalendar/api.json
corpus2/ozodrukh/CircularReveal/api.json
corpus2/harjot-oberai/MusicDNA/api.json
corpus2/fyhertz/libstreaming/api.json
corpus2/glomadrian/Grav/api.json
corpus2/wenmingvs/AndroidProcess/api.json
corpus2/chewiebug/GCViewer/api.json
corpus2/pchmn/MaterialChipsInput/api.json
corpus2/stfalcon-studio/ChatKit/api.json
corpus2/uber/NullAway/api.json
corpus2/dreamhead/moco/api.json
corpus2/pnikosis/materialish-progress/api.json
corpus2/500px/500px-android-blur/api.json
corpus2/Screetsec/TheFatRat/api.json
corpus2/nisrulz/sensey/api.json
corpus2/apache/beam/api.json
corpus2/flavioarfaria/KenBurnsView/api.json
corpus2/youtube/api-samples/api.json
corpus2/ityouknow/spring-cloud-examples/api.json
corpus2/JakeWharton/Telecine/api.json
corpus2/githubwing/ZoomHeader/api.json
corpus2/LawnchairLauncher/Lawnchair/api.json
corpus2/googlesamples/google-services/api.json
corpus2/goldze/MVVMHabit/api.json
corpus2/looly/hutool/api.json
corpus2/iwgang/CountdownView/api.json
corpus2/spring-cloud-incubator/spring-cloud-alibaba/api.json
corpus2/konifar/android-material-design-icon-generator-plugin/api.json
corpus2/auth0/java-jwt/api.json
corpus2/ronmamo/reflections/api.json
corpus2/iPaulPro/Android-ItemTouchHelper-Demo/api.json
corpus2/abel533/MyBatis-Spring-Boot/api.json
corpus2/luckybilly/CC/api.json
corpus2/hussien89aa/AndroidTutorialForBeginners/api.json
corpus2/rovo89/XposedInstaller/api.json
corpus2/simple-android-framework/android_design_patterns_analysis/api.json
corpus2/dlew/joda-time-android/api.json
corpus2/siyamed/android-shape-imageview/api.json
corpus2/mpusher/mpush/api.json
corpus2/brianfrankcooper/YCSB/api.json
corpus2/ffay/lanproxy/api.json
corpus2/Nightonke/CoCoin/api.json
corpus2/Twitter4J/Twitter4J/api.json
corpus2/btraceio/btrace/api.json
corpus2/JackyAndroid/AndroidChromium/api.json
corpus2/oracle/opengrok/api.json
corpus2/thingsboard/thingsboard/api.json
corpus2/ZieIony/Carbon/api.json
corpus2/h2oai/h2o-2/api.json
corpus2/eclipse/jetty.project/api.json
corpus2/aritraroy/PatternLockView/api.json
corpus2/theDazzler/droidicon/api.json
corpus2/apache/incubator-dubbo-spring-boot-project/api.json
corpus2/apache/camel/api.json
corpus2/google/google-java-format/api.json
corpus2/vipulasri/Timeline-View/api.json
corpus2/AriaLyy/Aria/api.json
corpus2/TeamAmaze/AmazeFileManager/api.json
corpus2/android-cjj/JJSearchViewAnim/api.json
corpus2/markushi/android-ui/api.json
corpus2/powermock/powermock/api.json
corpus2/twitter/distributedlog/api.json
corpus2/quartz-scheduler/quartz/api.json
corpus2/qiujuer/Genius-Android/api.json
corpus2/Prototik/HoloEverywhere/api.json
corpus2/bigbluebutton/bigbluebutton/api.json
corpus2/javaee-samples/javaee7-samples/api.json
corpus2/deano2390/MaterialShowcaseView/api.json
corpus2/zhanglei-workspace/shopping-management-system/api.json
corpus2/xinghongfei/LookLook/api.json
corpus2/apache/hive/api.json
corpus2/mxn21/FlowingDrawer/api.json
corpus2/Frank-Zhu/PullZoomView/api.json
corpus2/LuckyJayce/ViewPagerIndicator/api.json
corpus2/JackyAndroid/AndroidTVLauncher/api.json
corpus2/mikepenz/AboutLibraries/api.json
corpus2/square/tape/api.json
corpus2/chanjarster/weixin-java-tools/api.json
corpus2/alibaba/Tangram-Android/api.json
corpus2/react-native-community/react-native-blur/api.json
corpus2/huazhiyuan2008/RecyclerViewCardGallery/api.json
corpus2/2dxgujun/AndroidTagGroup/api.json
corpus2/chenupt/SpringIndicator/api.json
corpus2/stormzhang/9GAG/api.json
corpus2/WritingMinds/ffmpeg-android-java/api.json
corpus2/ata4/disunity/api.json
corpus2/r0adkll/Slidr/api.json
corpus2/linkedin/databus/api.json
corpus2/immutables/immutables/api.json
corpus2/ldoublem/LoadingView/api.json
corpus2/moezbhatti/qksms/api.json
corpus2/facebook/react-native-fbsdk/api.json
corpus2/esoxjem/MovieGuide/api.json
corpus2/voldemort/voldemort/api.json
corpus2/google/data-transfer-project/api.json
corpus2/jjoe64/GraphView/api.json
corpus2/mybatis/spring-boot-starter/api.json
corpus2/Yalantis/Euclid/api.json
corpus2/pentaho/pentaho-kettle/api.json
corpus2/daimajia/AnimationEasingFunctions/api.json
corpus2/xmuSistone/CardSlidePanel/api.json
corpus2/FinalTeam/RxGalleryFinal/api.json
corpus2/bingoogolapple/BGABadgeView-Android/api.json
corpus2/undertow-io/undertow/api.json
corpus2/bin456789/Unblock163MusicClient-Xposed/api.json
corpus2/balysv/material-ripple/api.json
corpus2/square/mortar/api.json
corpus2/code-mc/material-icon-lib/api.json
corpus2/iammert/MaterialIntroView/api.json
corpus2/wildfly/wildfly/api.json
corpus2/android-cjj/BeautifulRefreshLayout/api.json
corpus2/web3j/web3j/api.json
corpus2/iSoron/uhabits/api.json
corpus2/avast/android-styled-dialogs/api.json
corpus2/azkaban/azkaban/api.json
corpus2/xfumihiro/ViewInspector/api.json
corpus2/woxingxiao/BubbleSeekBar/api.json
corpus2/spockframework/spock/api.json
corpus2/eleme/UETool/api.json
corpus2/crate/crate/api.json
corpus2/ittianyu/BottomNavigationViewEx/api.json
corpus2/spring-projects/spring-loaded/api.json
corpus2/zhouchaoyuan/excelPanel/api.json
corpus2/vikramkakkar/SublimePicker/api.json
corpus2/jaydenxiao2016/AndroidFire/api.json
corpus2/aragozin/jvm-tools/api.json
corpus2/CrawlScript/WebCollector/api.json
corpus2/alipay/sofa-boot/api.json
corpus2/code4craft/netty-learning/api.json
corpus2/amitshekhariitbhu/awesome-android-complete-reference/api.json
corpus2/AntennaPod/AntennaPod/api.json
corpus2/watabou/pixel-dungeon/api.json
corpus2/soarcn/BottomSheet/api.json
corpus2/chrisbanes/philm/api.json
corpus2/apache/lucene-solr/api.json
corpus2/VictorAlbertos/RxCache/api.json
corpus2/apache/ignite/api.json
corpus2/reark/reark/api.json
corpus2/resilience4j/resilience4j/api.json
corpus2/bm-x/PhotoView/api.json
corpus2/nanchen2251/RxJava2Examples/api.json
corpus2/florent37/ViewAnimator/api.json
corpus2/yqritc/RecyclerView-FlexibleDivider/api.json
corpus2/JZ-Darkal/AndroidHttpCapture/api.json
corpus2/javaparser/javaparser/api.json
corpus2/jdsjlzx/LRecyclerView/api.json
corpus2/mongodb/mongo-java-driver/api.json
corpus2/zaaach/CityPicker/api.json
corpus2/zagum/Android-SwitchIcon/api.json
corpus2/oasisfeng/condom/api.json
corpus2/Diolor/Swipecards/api.json
corpus2/katzer/cordova-plugin-local-notifications/api.json
corpus2/AbrahamCaiJin/CommonUtilLibrary/api.json
corpus2/AltBeacon/android-beacon-library/api.json
corpus2/android-cjj/Android-MaterialRefreshLayout/api.json
corpus2/igreenwood/SimpleCropView/api.json
corpus2/Zomato/AndroidPhotoFilters/api.json
corpus2/grandcentrix/tray/api.json
corpus2/hefuyicoder/ListenerMusicPlayer/api.json
corpus2/androidquery/androidquery/api.json
corpus2/facebook/device-year-class/api.json
corpus2/skavanagh/KeyBox/api.json
corpus2/zhou-you/RxEasyHttp/api.json
corpus2/querydsl/querydsl/api.json
corpus2/Dimezis/BlurView/api.json
corpus2/Rukey7/MvpApp/api.json
corpus2/AigeStudio/WheelPicker/api.json
corpus2/elye/loaderviewlibrary/api.json
corpus2/ltsopensource/light-task-scheduler/api.json
corpus2/ToxicBakery/ViewPagerTransforms/api.json
corpus2/apache/incubator-pinot/api.json
corpus2/dmilicic/Android-Clean-Boilerplate/api.json
corpus2/sockeqwe/AdapterDelegates/api.json
corpus2/mcharmas/Android-ReactiveLocation/api.json
corpus2/florent37/CameraFragment/api.json
corpus2/confluentinc/ksql/api.json
corpus2/cymcsg/UltimateAndroid/api.json
corpus2/tronprotocol/java-tron/api.json
corpus2/tyzlmjj/PagerBottomTabStrip/api.json
corpus2/google/volley/api.json
corpus2/fengjundev/Android-Skin-Loader/api.json
corpus2/H07000223/FlycoDialog_Master/api.json
corpus2/jgilfelt/android-sqlite-asset-helper/api.json
corpus2/lingochamp/okdownload/api.json
corpus2/apache/shiro/api.json
corpus2/twosigma/beakerx/api.json
corpus2/pmd/pmd/api.json
corpus2/yingLanNull/ShadowImageView/api.json
corpus2/Netflix/curator/api.json
corpus2/baoyongzhang/android-PullRefreshLayout/api.json
corpus2/JanusGraph/janusgraph/api.json
corpus2/jiajunhui/PlayerBase/api.json
corpus2/guoxiaoxing/android-open-source-project-analysis/api.json
corpus2/lapism/MaterialSearchView/api.json
corpus2/AweiLoveAndroid/CommonDevKnowledge/api.json
corpus2/googlesamples/android-Camera2Basic/api.json
corpus2/evrencoskun/TableView/api.json
corpus2/promeG/TinyPinyin/api.json
corpus2/ApmeM/android-flowlayout/api.json
corpus2/fqrouter/fqrouter/api.json
corpus2/wordpress-mobile/WordPress-Android/api.json
corpus2/skyfishjy/android-ripple-background/api.json
corpus2/tiann/understand-plugin-framework/api.json
corpus2/EverythingMe/overscroll-decor/api.json
corpus2/Wizcorp/phonegap-facebook-plugin/api.json
corpus2/white-cat/ThinkAndroid/api.json
corpus2/rmtheis/android-ocr/api.json
corpus2/KieronQuinn/PersistentSearch/api.json
corpus2/Red5/red5-server/api.json
corpus2/elevenetc/TextSurface/api.json
corpus2/lisawray/groupie/api.json
corpus2/Yalantis/Horizon/api.json
corpus2/jjdxmashl/jjdxm_ijkplayer/api.json
corpus2/yanzhenjie/Album/api.json
corpus2/jMonkeyEngine/jmonkeyengine/api.json
corpus2/lettuce-io/lettuce-core/api.json
corpus2/MikeOrtiz/TouchImageView/api.json
corpus2/zhangkaitao/es/api.json
corpus2/Jude95/EasyRecyclerView/api.json
corpus2/steelkiwi/cropiwa/api.json
corpus2/zzz40500/AndroidSweetSheet/api.json
corpus2/LWJGL/lwjgl3/api.json
corpus2/prontera/spring-cloud-rest-tcc/api.json
corpus2/kabouzeid/Phonograph/api.json
corpus2/nutzam/nutz/api.json
corpus2/kymjs/KJFrameForAndroid/api.json
corpus2/spotify/helios/api.json
corpus2/mcxtzhang/ZLayoutManager/api.json
corpus2/Devlight/NavigationTabStrip/api.json
corpus2/Krupen/FabulousFilter/api.json
corpus2/fython/MaterialStepperView/api.json
corpus2/twosigma/beakerx/api.json
corpus2/pmd/pmd/api.json
corpus2/yingLanNull/ShadowImageView/api.json
corpus2/Netflix/curator/api.json
corpus2/baoyongzhang/android-PullRefreshLayout/api.json
corpus2/JanusGraph/janusgraph/api.json
corpus2/jiajunhui/PlayerBase/api.json
corpus2/guoxiaoxing/android-open-source-project-analysis/api.json
corpus2/lapism/MaterialSearchView/api.json
corpus2/AweiLoveAndroid/CommonDevKnowledge/api.json
corpus2/googlesamples/android-Camera2Basic/api.json
corpus2/evrencoskun/TableView/api.json
corpus2/promeG/TinyPinyin/api.json
corpus2/ApmeM/android-flowlayout/api.json
corpus2/fqrouter/fqrouter/api.json
corpus2/wordpress-mobile/WordPress-Android/api.json
corpus2/skyfishjy/android-ripple-background/api.json
corpus2/tiann/understand-plugin-framework/api.json
corpus2/EverythingMe/overscroll-decor/api.json
corpus2/Wizcorp/phonegap-facebook-plugin/api.json
corpus2/white-cat/ThinkAndroid/api.json
corpus2/rmtheis/android-ocr/api.json
corpus2/KieronQuinn/PersistentSearch/api.json
corpus2/Red5/red5-server/api.json
corpus2/elevenetc/TextSurface/api.json
corpus2/lisawray/groupie/api.json
corpus2/Yalantis/Horizon/api.json
corpus2/jjdxmashl/jjdxm_ijkplayer/api.json
corpus2/yanzhenjie/Album/api.json
corpus2/jMonkeyEngine/jmonkeyengine/api.json
corpus2/JingYeoh/FragmentRigger/api.json
corpus2/reactor/reactor-core/api.json
corpus2/nanchen2251/CompressHelper/api.json
corpus2/addthis/stream-lib/api.json
corpus2/jboss-javassist/javassist/api.json
corpus2/novoda/android-demos/api.json
corpus2/FasterXML/jackson-databind/api.json
corpus2/flavienlaurent/datetimepicker/api.json
corpus2/fanrunqi/MaterialLogin/api.json
corpus2/MindorksOpenSource/PRDownloader/api.json
corpus2/RomainPiel/Shimmer-android/api.json
corpus2/seaswalker/Spring/api.json
corpus2/gongwen/MarqueeViewLibrary/api.json
corpus2/ethereum/ethereumj/api.json
corpus2/AlexLiuSheng/CheckVersionLib/api.json
corpus2/bingoogolapple/BGASwipeBackLayout-Android/api.json
corpus2/KingJA/LoadSir/api.json
corpus2/jcoleman/tomcat-redis-session-manager/api.json
corpus2/googlesamples/android-play-location/api.json
corpus2/traccar/traccar/api.json
corpus2/ImmortalZ/StereoView/api.json
corpus2/alibaba/DataX/api.json
corpus2/apache/mahout/api.json
corpus2/Athou/commafeed/api.json
corpus2/MiCode/Notes/api.json
corpus2/codingXiaxw/seckill/api.json
corpus2/anjlab/android-inapp-billing-v3/api.json
corpus2/Jungerr/GridPasswordView/api.json
corpus2/mancj/SlideUp-Android/api.json
corpus2/medyo/Fancybuttons/api.json
corpus2/liyiorg/weixin-popular/api.json
corpus2/nispok/snackbar/api.json
corpus2/jokermonn/permissions4m/api.json
corpus2/qdrzwd/VideoRecorder/api.json
corpus2/liuguangqiang/SwipeBack/api.json
corpus2/harism/android-pagecurl/api.json
corpus2/xmuSistone/VerticalSlideFragment/api.json
corpus2/dingjikerbo/BluetoothKit/api.json
corpus2/speedment/speedment/api.json
corpus2/google/truth/api.json
corpus2/stephentuso/welcome-android/api.json
corpus2/parse-community/Parse-SDK-Android/api.json
corpus2/avjinder/Minimal-Todo/api.json
corpus2/mancj/MaterialSearchBar/api.json
corpus2/alibaba/jvm-sandbox/api.json
corpus2/Froussios/Intro-To-RxJava/api.json
corpus2/mthli/Knife/api.json
corpus2/pilgr/Paper/api.json
corpus2/libgdx/packr/api.json
corpus2/java8/Java8InAction/api.json
corpus2/apache/nutch/api.json
corpus2/testcontainers/testcontainers-java/api.json
corpus2/Netflix/archaius/api.json
corpus2/FudanNLP/fnlp/api.json
