python3 mrg_and.py corpus/wix/react-native-navigation > corpus/wix/react-native-navigation/mrg_and.txt
python3 mrg_and.py corpus/HannahMitt/HomeMirror > corpus/HannahMitt/HomeMirror/mrg_and.txt
python3 mrg_and.py corpus/iluwatar/java-design-patterns > corpus/iluwatar/java-design-patterns/mrg_and.txt
python3 mrg_and.py corpus/spring-projects/spring-boot > corpus/spring-projects/spring-boot/mrg_and.txt
python3 mrg_and.py corpus/spring-projects/spring-framework > corpus/spring-projects/spring-framework/mrg_and.txt
python3 mrg_and.py corpus/navasmdc/MaterialDesignLibrary > corpus/navasmdc/MaterialDesignLibrary/mrg_and.txt
python3 mrg_and.py corpus/DrKLO/Telegram > corpus/DrKLO/Telegram/mrg_and.txt
python3 mrg_and.py corpus/florent37/MaterialViewPager > corpus/florent37/MaterialViewPager/mrg_and.txt
python3 mrg_and.py corpus/Konloch/bytecode-viewer > corpus/Konloch/bytecode-viewer/mrg_and.txt
python3 mrg_and.py corpus/nostra13/Android-Universal-Image-Loader > corpus/nostra13/Android-Universal-Image-Loader/mrg_and.txt
python3 mrg_and.py corpus/brettwooldridge/HikariCP > corpus/brettwooldridge/HikariCP/mrg_and.txt
python3 mrg_and.py corpus/bazelbuild/bazel > corpus/bazelbuild/bazel/mrg_and.txt
python3 mrg_and.py corpus/scwang90/SmartRefreshLayout > corpus/scwang90/SmartRefreshLayout/mrg_and.txt
python3 mrg_and.py corpus/zxing/zxing > corpus/zxing/zxing/mrg_and.txt
python3 mrg_and.py corpus/wasabeef/recyclerview-animators > corpus/wasabeef/recyclerview-animators/mrg_and.txt
python3 mrg_and.py corpus/signalapp/Signal-Android > corpus/signalapp/Signal-Android/mrg_and.txt
python3 mrg_and.py corpus/ReactiveX/RxAndroid > corpus/ReactiveX/RxAndroid/mrg_and.txt
python3 mrg_and.py corpus/ReactiveX/RxJava > corpus/ReactiveX/RxJava/mrg_and.txt
python3 mrg_and.py corpus/permissions-dispatcher/PermissionsDispatcher > corpus/permissions-dispatcher/PermissionsDispatcher/mrg_and.txt
python3 mrg_and.py corpus/prestodb/presto > corpus/prestodb/presto/mrg_and.txt
python3 mrg_and.py corpus/Tencent/tinker > corpus/Tencent/tinker/mrg_and.txt
python3 mrg_and.py corpus/Tencent/VasSonic > corpus/Tencent/VasSonic/mrg_and.txt
python3 mrg_and.py corpus/elastic/elasticsearch > corpus/elastic/elasticsearch/mrg_and.txt
python3 mrg_and.py corpus/android10/Android-CleanArchitecture > corpus/android10/Android-CleanArchitecture/mrg_and.txt
python3 mrg_and.py corpus/PhilJay/MPAndroidChart > corpus/PhilJay/MPAndroidChart/mrg_and.txt
python3 mrg_and.py corpus/crossoverJie/Java-Interview > corpus/crossoverJie/Java-Interview/mrg_and.txt
python3 mrg_and.py corpus/jenkinsci/jenkins > corpus/jenkinsci/jenkins/mrg_and.txt
python3 mrg_and.py corpus/deeplearning4j/deeplearning4j > corpus/deeplearning4j/deeplearning4j/mrg_and.txt
python3 mrg_and.py corpus/afollestad/material-dialogs > corpus/afollestad/material-dialogs/mrg_and.txt
python3 mrg_and.py corpus/Bigkoo/Android-PickerView > corpus/Bigkoo/Android-PickerView/mrg_and.txt
python3 mrg_and.py corpus/eclipse/vert.x > corpus/eclipse/vert.x/mrg_and.txt
python3 mrg_and.py corpus/winterbe/java8-tutorial > corpus/winterbe/java8-tutorial/mrg_and.txt
python3 mrg_and.py corpus/netty/netty > corpus/netty/netty/mrg_and.txt
python3 mrg_and.py corpus/airbnb/lottie-android > corpus/airbnb/lottie-android/mrg_and.txt
python3 mrg_and.py corpus/libgdx/libgdx > corpus/libgdx/libgdx/mrg_and.txt
python3 mrg_and.py corpus/hdodenhof/CircleImageView > corpus/hdodenhof/CircleImageView/mrg_and.txt
python3 mrg_and.py corpus/chrisbanes/cheesesquare > corpus/chrisbanes/cheesesquare/mrg_and.txt
python3 mrg_and.py corpus/chrisbanes/Android-PullToRefresh > corpus/chrisbanes/Android-PullToRefresh/mrg_and.txt
python3 mrg_and.py corpus/chrisbanes/PhotoView > corpus/chrisbanes/PhotoView/mrg_and.txt
python3 mrg_and.py corpus/alibaba/fastjson > corpus/alibaba/fastjson/mrg_and.txt
python3 mrg_and.py corpus/alibaba/druid > corpus/alibaba/druid/mrg_and.txt
python3 mrg_and.py corpus/alibaba/vlayout > corpus/alibaba/vlayout/mrg_and.txt
python3 mrg_and.py corpus/SeleniumHQ/selenium > corpus/SeleniumHQ/selenium/mrg_and.txt
python3 mrg_and.py corpus/LMAX-Exchange/disruptor > corpus/LMAX-Exchange/disruptor/mrg_and.txt
python3 mrg_and.py corpus/shuzheng/zheng > corpus/shuzheng/zheng/mrg_and.txt
python3 mrg_and.py corpus/pockethub/PocketHub > corpus/pockethub/PocketHub/mrg_and.txt
python3 mrg_and.py corpus/perwendel/spark > corpus/perwendel/spark/mrg_and.txt
python3 mrg_and.py corpus/apl-devs/AppIntro > corpus/apl-devs/AppIntro/mrg_and.txt
python3 mrg_and.py corpus/lgvalle/Material-Animations > corpus/lgvalle/Material-Animations/mrg_and.txt
python3 mrg_and.py corpus/Netflix/Hystrix > corpus/Netflix/Hystrix/mrg_and.txt
python3 mrg_and.py corpus/hankcs/HanLP > corpus/hankcs/HanLP/mrg_and.txt
python3 mrg_and.py corpus/google/guava > corpus/google/guava/mrg_and.txt
python3 mrg_and.py corpus/google/iosched > corpus/google/iosched/mrg_and.txt
python3 mrg_and.py corpus/google/ExoPlayer > corpus/google/ExoPlayer/mrg_and.txt
python3 mrg_and.py corpus/google/gson > corpus/google/gson/mrg_and.txt
python3 mrg_and.py corpus/81813780/AVLoadingIndicatorView > corpus/81813780/AVLoadingIndicatorView/mrg_and.txt
python3 mrg_and.py corpus/mikepenz/MaterialDrawer > corpus/mikepenz/MaterialDrawer/mrg_and.txt
python3 mrg_and.py corpus/daimajia/AndroidViewAnimations > corpus/daimajia/AndroidViewAnimations/mrg_and.txt
python3 mrg_and.py corpus/daimajia/AndroidSwipeLayout > corpus/daimajia/AndroidSwipeLayout/mrg_and.txt
python3 mrg_and.py corpus/skylot/jadx > corpus/skylot/jadx/mrg_and.txt
python3 mrg_and.py corpus/CymChad/BaseRecyclerViewAdapterHelper > corpus/CymChad/BaseRecyclerViewAdapterHelper/mrg_and.txt
python3 mrg_and.py corpus/chrisjenx/Calligraphy > corpus/chrisjenx/Calligraphy/mrg_and.txt
python3 mrg_and.py corpus/nathanmarz/storm > corpus/nathanmarz/storm/mrg_and.txt
python3 mrg_and.py corpus/Curzibn/Luban > corpus/Curzibn/Luban/mrg_and.txt
python3 mrg_and.py corpus/Blankj/AndroidUtilCode > corpus/Blankj/AndroidUtilCode/mrg_and.txt
python3 mrg_and.py corpus/umano/AndroidSlidingUpPanel > corpus/umano/AndroidSlidingUpPanel/mrg_and.txt
python3 mrg_and.py corpus/Yalantis/uCrop > corpus/Yalantis/uCrop/mrg_and.txt
python3 mrg_and.py corpus/JakeWharton/butterknife > corpus/JakeWharton/butterknife/mrg_and.txt
python3 mrg_and.py corpus/JakeWharton/RxBinding > corpus/JakeWharton/RxBinding/mrg_and.txt
python3 mrg_and.py corpus/JakeWharton/ViewPagerIndicator > corpus/JakeWharton/ViewPagerIndicator/mrg_and.txt
python3 mrg_and.py corpus/bumptech/glide > corpus/bumptech/glide/mrg_and.txt
python3 mrg_and.py corpus/jfeinstein10/SlidingMenu > corpus/jfeinstein10/SlidingMenu/mrg_and.txt
python3 mrg_and.py corpus/zhihu/Matisse > corpus/zhihu/Matisse/mrg_and.txt
python3 mrg_and.py corpus/ksoichiro/Android-ObservableScrollView > corpus/ksoichiro/Android-ObservableScrollView/mrg_and.txt
python3 mrg_and.py corpus/androidannotations/androidannotations > corpus/androidannotations/androidannotations/mrg_and.txt
python3 mrg_and.py corpus/roughike/BottomBar > corpus/roughike/BottomBar/mrg_and.txt
python3 mrg_and.py corpus/jeasonlzy/okhttp-OkGo > corpus/jeasonlzy/okhttp-OkGo/mrg_and.txt
python3 mrg_and.py corpus/orhanobut/logger > corpus/orhanobut/logger/mrg_and.txt
python3 mrg_and.py corpus/nickbutcher/plaid > corpus/nickbutcher/plaid/mrg_and.txt
python3 mrg_and.py corpus/liaohuqiu/android-Ultra-Pull-To-Refresh > corpus/liaohuqiu/android-Ultra-Pull-To-Refresh/mrg_and.txt
python3 mrg_and.py corpus/realm/realm-java > corpus/realm/realm-java/mrg_and.txt
python3 mrg_and.py corpus/openzipkin/zipkin > corpus/openzipkin/zipkin/mrg_and.txt
python3 mrg_and.py corpus/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition > corpus/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/mrg_and.txt
python3 mrg_and.py corpus/kdn251/interviews > corpus/kdn251/interviews/mrg_and.txt
python3 mrg_and.py corpus/loopj/android-async-http > corpus/loopj/android-async-http/mrg_and.txt
python3 mrg_and.py corpus/facebook/fresco > corpus/facebook/fresco/mrg_and.txt
python3 mrg_and.py corpus/facebook/stetho > corpus/facebook/stetho/mrg_and.txt
python3 mrg_and.py corpus/proxyee-down-org/proxyee-down > corpus/proxyee-down-org/proxyee-down/mrg_and.txt
python3 mrg_and.py corpus/aosp-mirror/platform_frameworks_base > corpus/aosp-mirror/platform_frameworks_base/mrg_and.txt
python3 mrg_and.py corpus/greenrobot/EventBus > corpus/greenrobot/EventBus/mrg_and.txt
python3 mrg_and.py corpus/greenrobot/greenDAO > corpus/greenrobot/greenDAO/mrg_and.txt
python3 mrg_and.py corpus/mybatis/mybatis-3 > corpus/mybatis/mybatis-3/mrg_and.txt
python3 mrg_and.py corpus/apache/incubator-dubbo > corpus/apache/incubator-dubbo/mrg_and.txt
python3 mrg_and.py corpus/apache/kafka > corpus/apache/kafka/mrg_and.txt
python3 mrg_and.py corpus/apache/incubator-weex > corpus/apache/incubator-weex/mrg_and.txt
python3 mrg_and.py corpus/apache/hadoop > corpus/apache/hadoop/mrg_and.txt
python3 mrg_and.py corpus/square/retrofit > corpus/square/retrofit/mrg_and.txt
python3 mrg_and.py corpus/square/leakcanary > corpus/square/leakcanary/mrg_and.txt
python3 mrg_and.py corpus/square/okhttp > corpus/square/okhttp/mrg_and.txt
python3 mrg_and.py corpus/square/picasso > corpus/square/picasso/mrg_and.txt
