python3 msg2issue_nom.py corpus/wix/react-native-navigation |jq . > corpus/wix/react-native-navigation/msg2issue_nom.json
python3 msg2issue_nom.py corpus/HannahMitt/HomeMirror |jq . > corpus/HannahMitt/HomeMirror/msg2issue_nom.json
python3 msg2issue_nom.py corpus/iluwatar/java-design-patterns |jq . > corpus/iluwatar/java-design-patterns/msg2issue_nom.json
python3 msg2issue_nom.py corpus/spring-projects/spring-boot |jq . > corpus/spring-projects/spring-boot/msg2issue_nom.json
python3 msg2issue_nom.py corpus/spring-projects/spring-framework |jq . > corpus/spring-projects/spring-framework/msg2issue_nom.json
python3 msg2issue_nom.py corpus/navasmdc/MaterialDesignLibrary |jq . > corpus/navasmdc/MaterialDesignLibrary/msg2issue_nom.json
python3 msg2issue_nom.py corpus/DrKLO/Telegram |jq . > corpus/DrKLO/Telegram/msg2issue_nom.json
python3 msg2issue_nom.py corpus/florent37/MaterialViewPager |jq . > corpus/florent37/MaterialViewPager/msg2issue_nom.json
python3 msg2issue_nom.py corpus/Konloch/bytecode-viewer |jq . > corpus/Konloch/bytecode-viewer/msg2issue_nom.json
python3 msg2issue_nom.py corpus/nostra13/Android-Universal-Image-Loader |jq . > corpus/nostra13/Android-Universal-Image-Loader/msg2issue_nom.json
python3 msg2issue_nom.py corpus/brettwooldridge/HikariCP |jq . > corpus/brettwooldridge/HikariCP/msg2issue_nom.json
python3 msg2issue_nom.py corpus/bazelbuild/bazel |jq . > corpus/bazelbuild/bazel/msg2issue_nom.json
python3 msg2issue_nom.py corpus/scwang90/SmartRefreshLayout |jq . > corpus/scwang90/SmartRefreshLayout/msg2issue_nom.json
python3 msg2issue_nom.py corpus/zxing/zxing |jq . > corpus/zxing/zxing/msg2issue_nom.json
python3 msg2issue_nom.py corpus/wasabeef/recyclerview-animators |jq . > corpus/wasabeef/recyclerview-animators/msg2issue_nom.json
python3 msg2issue_nom.py corpus/signalapp/Signal-Android |jq . > corpus/signalapp/Signal-Android/msg2issue_nom.json
python3 msg2issue_nom.py corpus/ReactiveX/RxAndroid |jq . > corpus/ReactiveX/RxAndroid/msg2issue_nom.json
python3 msg2issue_nom.py corpus/ReactiveX/RxJava |jq . > corpus/ReactiveX/RxJava/msg2issue_nom.json
python3 msg2issue_nom.py corpus/permissions-dispatcher/PermissionsDispatcher |jq . > corpus/permissions-dispatcher/PermissionsDispatcher/msg2issue_nom.json
python3 msg2issue_nom.py corpus/prestodb/presto |jq . > corpus/prestodb/presto/msg2issue_nom.json
python3 msg2issue_nom.py corpus/Tencent/tinker |jq . > corpus/Tencent/tinker/msg2issue_nom.json
python3 msg2issue_nom.py corpus/Tencent/VasSonic |jq . > corpus/Tencent/VasSonic/msg2issue_nom.json
python3 msg2issue_nom.py corpus/elastic/elasticsearch |jq . > corpus/elastic/elasticsearch/msg2issue_nom.json
python3 msg2issue_nom.py corpus/android10/Android-CleanArchitecture |jq . > corpus/android10/Android-CleanArchitecture/msg2issue_nom.json
python3 msg2issue_nom.py corpus/PhilJay/MPAndroidChart |jq . > corpus/PhilJay/MPAndroidChart/msg2issue_nom.json
python3 msg2issue_nom.py corpus/crossoverJie/Java-Interview |jq . > corpus/crossoverJie/Java-Interview/msg2issue_nom.json
python3 msg2issue_nom.py corpus/jenkinsci/jenkins |jq . > corpus/jenkinsci/jenkins/msg2issue_nom.json
python3 msg2issue_nom.py corpus/deeplearning4j/deeplearning4j |jq . > corpus/deeplearning4j/deeplearning4j/msg2issue_nom.json
python3 msg2issue_nom.py corpus/afollestad/material-dialogs |jq . > corpus/afollestad/material-dialogs/msg2issue_nom.json
python3 msg2issue_nom.py corpus/Bigkoo/Android-PickerView |jq . > corpus/Bigkoo/Android-PickerView/msg2issue_nom.json
python3 msg2issue_nom.py corpus/eclipse/vert.x |jq . > corpus/eclipse/vert.x/msg2issue_nom.json
python3 msg2issue_nom.py corpus/winterbe/java8-tutorial |jq . > corpus/winterbe/java8-tutorial/msg2issue_nom.json
python3 msg2issue_nom.py corpus/netty/netty |jq . > corpus/netty/netty/msg2issue_nom.json
python3 msg2issue_nom.py corpus/airbnb/lottie-android |jq . > corpus/airbnb/lottie-android/msg2issue_nom.json
python3 msg2issue_nom.py corpus/libgdx/libgdx |jq . > corpus/libgdx/libgdx/msg2issue_nom.json
python3 msg2issue_nom.py corpus/hdodenhof/CircleImageView |jq . > corpus/hdodenhof/CircleImageView/msg2issue_nom.json
python3 msg2issue_nom.py corpus/chrisbanes/cheesesquare |jq . > corpus/chrisbanes/cheesesquare/msg2issue_nom.json
python3 msg2issue_nom.py corpus/chrisbanes/Android-PullToRefresh |jq . > corpus/chrisbanes/Android-PullToRefresh/msg2issue_nom.json
python3 msg2issue_nom.py corpus/chrisbanes/PhotoView |jq . > corpus/chrisbanes/PhotoView/msg2issue_nom.json
python3 msg2issue_nom.py corpus/alibaba/fastjson |jq . > corpus/alibaba/fastjson/msg2issue_nom.json
python3 msg2issue_nom.py corpus/alibaba/druid |jq . > corpus/alibaba/druid/msg2issue_nom.json
python3 msg2issue_nom.py corpus/alibaba/vlayout |jq . > corpus/alibaba/vlayout/msg2issue_nom.json
python3 msg2issue_nom.py corpus/SeleniumHQ/selenium |jq . > corpus/SeleniumHQ/selenium/msg2issue_nom.json
python3 msg2issue_nom.py corpus/LMAX-Exchange/disruptor |jq . > corpus/LMAX-Exchange/disruptor/msg2issue_nom.json
python3 msg2issue_nom.py corpus/shuzheng/zheng |jq . > corpus/shuzheng/zheng/msg2issue_nom.json
python3 msg2issue_nom.py corpus/pockethub/PocketHub |jq . > corpus/pockethub/PocketHub/msg2issue_nom.json
python3 msg2issue_nom.py corpus/perwendel/spark |jq . > corpus/perwendel/spark/msg2issue_nom.json
python3 msg2issue_nom.py corpus/apl-devs/AppIntro |jq . > corpus/apl-devs/AppIntro/msg2issue_nom.json
python3 msg2issue_nom.py corpus/lgvalle/Material-Animations |jq . > corpus/lgvalle/Material-Animations/msg2issue_nom.json
python3 msg2issue_nom.py corpus/Netflix/Hystrix |jq . > corpus/Netflix/Hystrix/msg2issue_nom.json
python3 msg2issue_nom.py corpus/hankcs/HanLP |jq . > corpus/hankcs/HanLP/msg2issue_nom.json
python3 msg2issue_nom.py corpus/google/guava |jq . > corpus/google/guava/msg2issue_nom.json
python3 msg2issue_nom.py corpus/google/iosched |jq . > corpus/google/iosched/msg2issue_nom.json
python3 msg2issue_nom.py corpus/google/ExoPlayer |jq . > corpus/google/ExoPlayer/msg2issue_nom.json
python3 msg2issue_nom.py corpus/google/gson |jq . > corpus/google/gson/msg2issue_nom.json
python3 msg2issue_nom.py corpus/81813780/AVLoadingIndicatorView |jq . > corpus/81813780/AVLoadingIndicatorView/msg2issue_nom.json
python3 msg2issue_nom.py corpus/mikepenz/MaterialDrawer |jq . > corpus/mikepenz/MaterialDrawer/msg2issue_nom.json
python3 msg2issue_nom.py corpus/daimajia/AndroidViewAnimations |jq . > corpus/daimajia/AndroidViewAnimations/msg2issue_nom.json
python3 msg2issue_nom.py corpus/daimajia/AndroidSwipeLayout |jq . > corpus/daimajia/AndroidSwipeLayout/msg2issue_nom.json
python3 msg2issue_nom.py corpus/skylot/jadx |jq . > corpus/skylot/jadx/msg2issue_nom.json
python3 msg2issue_nom.py corpus/CymChad/BaseRecyclerViewAdapterHelper |jq . > corpus/CymChad/BaseRecyclerViewAdapterHelper/msg2issue_nom.json
python3 msg2issue_nom.py corpus/chrisjenx/Calligraphy |jq . > corpus/chrisjenx/Calligraphy/msg2issue_nom.json
python3 msg2issue_nom.py corpus/nathanmarz/storm |jq . > corpus/nathanmarz/storm/msg2issue_nom.json
python3 msg2issue_nom.py corpus/Curzibn/Luban |jq . > corpus/Curzibn/Luban/msg2issue_nom.json
python3 msg2issue_nom.py corpus/Blankj/AndroidUtilCode |jq . > corpus/Blankj/AndroidUtilCode/msg2issue_nom.json
python3 msg2issue_nom.py corpus/umano/AndroidSlidingUpPanel |jq . > corpus/umano/AndroidSlidingUpPanel/msg2issue_nom.json
python3 msg2issue_nom.py corpus/Yalantis/uCrop |jq . > corpus/Yalantis/uCrop/msg2issue_nom.json
python3 msg2issue_nom.py corpus/JakeWharton/butterknife |jq . > corpus/JakeWharton/butterknife/msg2issue_nom.json
python3 msg2issue_nom.py corpus/JakeWharton/RxBinding |jq . > corpus/JakeWharton/RxBinding/msg2issue_nom.json
python3 msg2issue_nom.py corpus/JakeWharton/ViewPagerIndicator |jq . > corpus/JakeWharton/ViewPagerIndicator/msg2issue_nom.json
python3 msg2issue_nom.py corpus/bumptech/glide |jq . > corpus/bumptech/glide/msg2issue_nom.json
python3 msg2issue_nom.py corpus/jfeinstein10/SlidingMenu |jq . > corpus/jfeinstein10/SlidingMenu/msg2issue_nom.json
python3 msg2issue_nom.py corpus/zhihu/Matisse |jq . > corpus/zhihu/Matisse/msg2issue_nom.json
python3 msg2issue_nom.py corpus/ksoichiro/Android-ObservableScrollView |jq . > corpus/ksoichiro/Android-ObservableScrollView/msg2issue_nom.json
python3 msg2issue_nom.py corpus/androidannotations/androidannotations |jq . > corpus/androidannotations/androidannotations/msg2issue_nom.json
python3 msg2issue_nom.py corpus/roughike/BottomBar |jq . > corpus/roughike/BottomBar/msg2issue_nom.json
python3 msg2issue_nom.py corpus/jeasonlzy/okhttp-OkGo |jq . > corpus/jeasonlzy/okhttp-OkGo/msg2issue_nom.json
python3 msg2issue_nom.py corpus/orhanobut/logger |jq . > corpus/orhanobut/logger/msg2issue_nom.json
python3 msg2issue_nom.py corpus/nickbutcher/plaid |jq . > corpus/nickbutcher/plaid/msg2issue_nom.json
python3 msg2issue_nom.py corpus/liaohuqiu/android-Ultra-Pull-To-Refresh |jq . > corpus/liaohuqiu/android-Ultra-Pull-To-Refresh/msg2issue_nom.json
python3 msg2issue_nom.py corpus/realm/realm-java |jq . > corpus/realm/realm-java/msg2issue_nom.json
python3 msg2issue_nom.py corpus/openzipkin/zipkin |jq . > corpus/openzipkin/zipkin/msg2issue_nom.json
python3 msg2issue_nom.py corpus/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition |jq . > corpus/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/msg2issue_nom.json
python3 msg2issue_nom.py corpus/kdn251/interviews |jq . > corpus/kdn251/interviews/msg2issue_nom.json
python3 msg2issue_nom.py corpus/loopj/android-async-http |jq . > corpus/loopj/android-async-http/msg2issue_nom.json
python3 msg2issue_nom.py corpus/facebook/fresco |jq . > corpus/facebook/fresco/msg2issue_nom.json
python3 msg2issue_nom.py corpus/facebook/stetho |jq . > corpus/facebook/stetho/msg2issue_nom.json
python3 msg2issue_nom.py corpus/proxyee-down-org/proxyee-down |jq . > corpus/proxyee-down-org/proxyee-down/msg2issue_nom.json
python3 msg2issue_nom.py corpus/aosp-mirror/platform_frameworks_base |jq . > corpus/aosp-mirror/platform_frameworks_base/msg2issue_nom.json
python3 msg2issue_nom.py corpus/greenrobot/EventBus |jq . > corpus/greenrobot/EventBus/msg2issue_nom.json
python3 msg2issue_nom.py corpus/greenrobot/greenDAO |jq . > corpus/greenrobot/greenDAO/msg2issue_nom.json
python3 msg2issue_nom.py corpus/mybatis/mybatis-3 |jq . > corpus/mybatis/mybatis-3/msg2issue_nom.json
python3 msg2issue_nom.py corpus/apache/incubator-dubbo |jq . > corpus/apache/incubator-dubbo/msg2issue_nom.json
python3 msg2issue_nom.py corpus/apache/kafka |jq . > corpus/apache/kafka/msg2issue_nom.json
python3 msg2issue_nom.py corpus/apache/incubator-weex |jq . > corpus/apache/incubator-weex/msg2issue_nom.json
python3 msg2issue_nom.py corpus/apache/hadoop |jq . > corpus/apache/hadoop/msg2issue_nom.json
python3 msg2issue_nom.py corpus/square/retrofit |jq . > corpus/square/retrofit/msg2issue_nom.json
python3 msg2issue_nom.py corpus/square/leakcanary |jq . > corpus/square/leakcanary/msg2issue_nom.json
python3 msg2issue_nom.py corpus/square/okhttp |jq . > corpus/square/okhttp/msg2issue_nom.json
python3 msg2issue_nom.py corpus/square/picasso |jq . > corpus/square/picasso/msg2issue_nom.json
