python3 rm_merge.py  corpus/wix/react-native-navigationg/msg2issue.json > corpus/wix/react-native-navigationg/msg2issue.json 
python3 rm_merge.py  corpus/HannahMitt/HomeMirrorg/msg2issue.json > corpus/HannahMitt/HomeMirrorg/msg2issue.json 
python3 rm_merge.py  corpus/iluwatar/java-design-patternsg/msg2issue.json > corpus/iluwatar/java-design-patternsg/msg2issue.json 
python3 rm_merge.py  corpus/spring-projects/spring-bootg/msg2issue.json > corpus/spring-projects/spring-bootg/msg2issue.json 
python3 rm_merge.py  corpus/spring-projects/spring-frameworkg/msg2issue.json > corpus/spring-projects/spring-frameworkg/msg2issue.json 
python3 rm_merge.py  corpus/navasmdc/MaterialDesignLibraryg/msg2issue.json > corpus/navasmdc/MaterialDesignLibraryg/msg2issue.json 
python3 rm_merge.py  corpus/DrKLO/Telegramg/msg2issue.json > corpus/DrKLO/Telegramg/msg2issue.json 
python3 rm_merge.py  corpus/florent37/MaterialViewPagerg/msg2issue.json > corpus/florent37/MaterialViewPagerg/msg2issue.json 
python3 rm_merge.py  corpus/Konloch/bytecode-viewerg/msg2issue.json > corpus/Konloch/bytecode-viewerg/msg2issue.json 
python3 rm_merge.py  corpus/nostra13/Android-Universal-Image-Loaderg/msg2issue.json > corpus/nostra13/Android-Universal-Image-Loaderg/msg2issue.json 
python3 rm_merge.py  corpus/brettwooldridge/HikariCPg/msg2issue.json > corpus/brettwooldridge/HikariCPg/msg2issue.json 
python3 rm_merge.py  corpus/bazelbuild/bazelg/msg2issue.json > corpus/bazelbuild/bazelg/msg2issue.json 
python3 rm_merge.py  corpus/scwang90/SmartRefreshLayoutg/msg2issue.json > corpus/scwang90/SmartRefreshLayoutg/msg2issue.json 
python3 rm_merge.py  corpus/zxing/zxingg/msg2issue.json > corpus/zxing/zxingg/msg2issue.json 
python3 rm_merge.py  corpus/wasabeef/recyclerview-animatorsg/msg2issue.json > corpus/wasabeef/recyclerview-animatorsg/msg2issue.json 
python3 rm_merge.py  corpus/signalapp/Signal-Androidg/msg2issue.json > corpus/signalapp/Signal-Androidg/msg2issue.json 
python3 rm_merge.py  corpus/ReactiveX/RxAndroidg/msg2issue.json > corpus/ReactiveX/RxAndroidg/msg2issue.json 
python3 rm_merge.py  corpus/ReactiveX/RxJavag/msg2issue.json > corpus/ReactiveX/RxJavag/msg2issue.json 
python3 rm_merge.py  corpus/permissions-dispatcher/PermissionsDispatcherg/msg2issue.json > corpus/permissions-dispatcher/PermissionsDispatcherg/msg2issue.json 
python3 rm_merge.py  corpus/prestodb/prestog/msg2issue.json > corpus/prestodb/prestog/msg2issue.json 
python3 rm_merge.py  corpus/Tencent/tinkerg/msg2issue.json > corpus/Tencent/tinkerg/msg2issue.json 
python3 rm_merge.py  corpus/Tencent/VasSonicg/msg2issue.json > corpus/Tencent/VasSonicg/msg2issue.json 
python3 rm_merge.py  corpus/elastic/elasticsearchg/msg2issue.json > corpus/elastic/elasticsearchg/msg2issue.json 
python3 rm_merge.py  corpus/android10/Android-CleanArchitectureg/msg2issue.json > corpus/android10/Android-CleanArchitectureg/msg2issue.json 
python3 rm_merge.py  corpus/PhilJay/MPAndroidChartg/msg2issue.json > corpus/PhilJay/MPAndroidChartg/msg2issue.json 
python3 rm_merge.py  corpus/crossoverJie/Java-Interviewg/msg2issue.json > corpus/crossoverJie/Java-Interviewg/msg2issue.json 
python3 rm_merge.py  corpus/jenkinsci/jenkinsg/msg2issue.json > corpus/jenkinsci/jenkinsg/msg2issue.json 
python3 rm_merge.py  corpus/deeplearning4j/deeplearning4jg/msg2issue.json > corpus/deeplearning4j/deeplearning4jg/msg2issue.json 
python3 rm_merge.py  corpus/afollestad/material-dialogsg/msg2issue.json > corpus/afollestad/material-dialogsg/msg2issue.json 
python3 rm_merge.py  corpus/Bigkoo/Android-PickerViewg/msg2issue.json > corpus/Bigkoo/Android-PickerViewg/msg2issue.json 
python3 rm_merge.py  corpus/eclipse/vert.xg/msg2issue.json > corpus/eclipse/vert.xg/msg2issue.json 
python3 rm_merge.py  corpus/winterbe/java8-tutorialg/msg2issue.json > corpus/winterbe/java8-tutorialg/msg2issue.json 
python3 rm_merge.py  corpus/netty/nettyg/msg2issue.json > corpus/netty/nettyg/msg2issue.json 
python3 rm_merge.py  corpus/airbnb/lottie-androidg/msg2issue.json > corpus/airbnb/lottie-androidg/msg2issue.json 
python3 rm_merge.py  corpus/libgdx/libgdxg/msg2issue.json > corpus/libgdx/libgdxg/msg2issue.json 
python3 rm_merge.py  corpus/hdodenhof/CircleImageViewg/msg2issue.json > corpus/hdodenhof/CircleImageViewg/msg2issue.json 
python3 rm_merge.py  corpus/chrisbanes/cheesesquareg/msg2issue.json > corpus/chrisbanes/cheesesquareg/msg2issue.json 
python3 rm_merge.py  corpus/chrisbanes/Android-PullToRefreshg/msg2issue.json > corpus/chrisbanes/Android-PullToRefreshg/msg2issue.json 
python3 rm_merge.py  corpus/chrisbanes/PhotoViewg/msg2issue.json > corpus/chrisbanes/PhotoViewg/msg2issue.json 
python3 rm_merge.py  corpus/alibaba/fastjsong/msg2issue.json > corpus/alibaba/fastjsong/msg2issue.json 
python3 rm_merge.py  corpus/alibaba/druidg/msg2issue.json > corpus/alibaba/druidg/msg2issue.json 
python3 rm_merge.py  corpus/alibaba/vlayoutg/msg2issue.json > corpus/alibaba/vlayoutg/msg2issue.json 
python3 rm_merge.py  corpus/SeleniumHQ/seleniumg/msg2issue.json > corpus/SeleniumHQ/seleniumg/msg2issue.json 
python3 rm_merge.py  corpus/LMAX-Exchange/disruptorg/msg2issue.json > corpus/LMAX-Exchange/disruptorg/msg2issue.json 
python3 rm_merge.py  corpus/shuzheng/zhengg/msg2issue.json > corpus/shuzheng/zhengg/msg2issue.json 
python3 rm_merge.py  corpus/pockethub/PocketHubg/msg2issue.json > corpus/pockethub/PocketHubg/msg2issue.json 
python3 rm_merge.py  corpus/perwendel/sparkg/msg2issue.json > corpus/perwendel/sparkg/msg2issue.json 
python3 rm_merge.py  corpus/apl-devs/AppIntrog/msg2issue.json > corpus/apl-devs/AppIntrog/msg2issue.json 
python3 rm_merge.py  corpus/lgvalle/Material-Animationsg/msg2issue.json > corpus/lgvalle/Material-Animationsg/msg2issue.json 
python3 rm_merge.py  corpus/Netflix/Hystrixg/msg2issue.json > corpus/Netflix/Hystrixg/msg2issue.json 
python3 rm_merge.py  corpus/hankcs/HanLPg/msg2issue.json > corpus/hankcs/HanLPg/msg2issue.json 
python3 rm_merge.py  corpus/google/guavag/msg2issue.json > corpus/google/guavag/msg2issue.json 
python3 rm_merge.py  corpus/google/ioschedg/msg2issue.json > corpus/google/ioschedg/msg2issue.json 
python3 rm_merge.py  corpus/google/ExoPlayerg/msg2issue.json > corpus/google/ExoPlayerg/msg2issue.json 
python3 rm_merge.py  corpus/google/gsong/msg2issue.json > corpus/google/gsong/msg2issue.json 
python3 rm_merge.py  corpus/81813780/AVLoadingIndicatorViewg/msg2issue.json > corpus/81813780/AVLoadingIndicatorViewg/msg2issue.json 
python3 rm_merge.py  corpus/mikepenz/MaterialDrawerg/msg2issue.json > corpus/mikepenz/MaterialDrawerg/msg2issue.json 
python3 rm_merge.py  corpus/daimajia/AndroidViewAnimationsg/msg2issue.json > corpus/daimajia/AndroidViewAnimationsg/msg2issue.json 
python3 rm_merge.py  corpus/daimajia/AndroidSwipeLayoutg/msg2issue.json > corpus/daimajia/AndroidSwipeLayoutg/msg2issue.json 
python3 rm_merge.py  corpus/skylot/jadxg/msg2issue.json > corpus/skylot/jadxg/msg2issue.json 
python3 rm_merge.py  corpus/CymChad/BaseRecyclerViewAdapterHelperg/msg2issue.json > corpus/CymChad/BaseRecyclerViewAdapterHelperg/msg2issue.json 
python3 rm_merge.py  corpus/chrisjenx/Calligraphyg/msg2issue.json > corpus/chrisjenx/Calligraphyg/msg2issue.json 
python3 rm_merge.py  corpus/nathanmarz/stormg/msg2issue.json > corpus/nathanmarz/stormg/msg2issue.json 
python3 rm_merge.py  corpus/Curzibn/Lubang/msg2issue.json > corpus/Curzibn/Lubang/msg2issue.json 
python3 rm_merge.py  corpus/Blankj/AndroidUtilCodeg/msg2issue.json > corpus/Blankj/AndroidUtilCodeg/msg2issue.json 
python3 rm_merge.py  corpus/umano/AndroidSlidingUpPanelg/msg2issue.json > corpus/umano/AndroidSlidingUpPanelg/msg2issue.json 
python3 rm_merge.py  corpus/Yalantis/uCropg/msg2issue.json > corpus/Yalantis/uCropg/msg2issue.json 
python3 rm_merge.py  corpus/JakeWharton/butterknifeg/msg2issue.json > corpus/JakeWharton/butterknifeg/msg2issue.json 
python3 rm_merge.py  corpus/JakeWharton/RxBindingg/msg2issue.json > corpus/JakeWharton/RxBindingg/msg2issue.json 
python3 rm_merge.py  corpus/JakeWharton/ViewPagerIndicatorg/msg2issue.json > corpus/JakeWharton/ViewPagerIndicatorg/msg2issue.json 
python3 rm_merge.py  corpus/bumptech/glideg/msg2issue.json > corpus/bumptech/glideg/msg2issue.json 
python3 rm_merge.py  corpus/jfeinstein10/SlidingMenug/msg2issue.json > corpus/jfeinstein10/SlidingMenug/msg2issue.json 
python3 rm_merge.py  corpus/zhihu/Matisseg/msg2issue.json > corpus/zhihu/Matisseg/msg2issue.json 
python3 rm_merge.py  corpus/ksoichiro/Android-ObservableScrollViewg/msg2issue.json > corpus/ksoichiro/Android-ObservableScrollViewg/msg2issue.json 
python3 rm_merge.py  corpus/androidannotations/androidannotationsg/msg2issue.json > corpus/androidannotations/androidannotationsg/msg2issue.json 
python3 rm_merge.py  corpus/roughike/BottomBarg/msg2issue.json > corpus/roughike/BottomBarg/msg2issue.json 
python3 rm_merge.py  corpus/jeasonlzy/okhttp-OkGog/msg2issue.json > corpus/jeasonlzy/okhttp-OkGog/msg2issue.json 
python3 rm_merge.py  corpus/orhanobut/loggerg/msg2issue.json > corpus/orhanobut/loggerg/msg2issue.json 
python3 rm_merge.py  corpus/nickbutcher/plaidg/msg2issue.json > corpus/nickbutcher/plaidg/msg2issue.json 
python3 rm_merge.py  corpus/liaohuqiu/android-Ultra-Pull-To-Refreshg/msg2issue.json > corpus/liaohuqiu/android-Ultra-Pull-To-Refreshg/msg2issue.json 
python3 rm_merge.py  corpus/realm/realm-javag/msg2issue.json > corpus/realm/realm-javag/msg2issue.json 
python3 rm_merge.py  corpus/openzipkin/zipking/msg2issue.json > corpus/openzipkin/zipking/msg2issue.json 
python3 rm_merge.py  corpus/EnterpriseQualityCoding/FizzBuzzEnterpriseEditiong/msg2issue.json > corpus/EnterpriseQualityCoding/FizzBuzzEnterpriseEditiong/msg2issue.json 
python3 rm_merge.py  corpus/kdn251/interviewsg/msg2issue.json > corpus/kdn251/interviewsg/msg2issue.json 
python3 rm_merge.py  corpus/loopj/android-async-httpg/msg2issue.json > corpus/loopj/android-async-httpg/msg2issue.json 
python3 rm_merge.py  corpus/facebook/frescog/msg2issue.json > corpus/facebook/frescog/msg2issue.json 
python3 rm_merge.py  corpus/facebook/stethog/msg2issue.json > corpus/facebook/stethog/msg2issue.json 
python3 rm_merge.py  corpus/proxyee-down-org/proxyee-downg/msg2issue.json > corpus/proxyee-down-org/proxyee-downg/msg2issue.json 
python3 rm_merge.py  corpus/aosp-mirror/platform_frameworks_baseg/msg2issue.json > corpus/aosp-mirror/platform_frameworks_baseg/msg2issue.json 
python3 rm_merge.py  corpus/greenrobot/EventBusg/msg2issue.json > corpus/greenrobot/EventBusg/msg2issue.json 
python3 rm_merge.py  corpus/greenrobot/greenDAOg/msg2issue.json > corpus/greenrobot/greenDAOg/msg2issue.json 
python3 rm_merge.py  corpus/mybatis/mybatis-3g/msg2issue.json > corpus/mybatis/mybatis-3g/msg2issue.json 
python3 rm_merge.py  corpus/apache/incubator-dubbog/msg2issue.json > corpus/apache/incubator-dubbog/msg2issue.json 
python3 rm_merge.py  corpus/apache/kafkag/msg2issue.json > corpus/apache/kafkag/msg2issue.json 
python3 rm_merge.py  corpus/apache/incubator-weexg/msg2issue.json > corpus/apache/incubator-weexg/msg2issue.json 
python3 rm_merge.py  corpus/apache/hadoopg/msg2issue.json > corpus/apache/hadoopg/msg2issue.json 
python3 rm_merge.py  corpus/square/retrofitg/msg2issue.json > corpus/square/retrofitg/msg2issue.json 
python3 rm_merge.py  corpus/square/leakcanaryg/msg2issue.json > corpus/square/leakcanaryg/msg2issue.json 
python3 rm_merge.py  corpus/square/okhttpg/msg2issue.json > corpus/square/okhttpg/msg2issue.json 
python3 rm_merge.py  corpus/square/picassog/msg2issue.json > corpus/square/picassog/msg2issue.json 
