python3 url2body.py corpus2/eleme/UETool/api.json | jq . > corpus2/eleme/UETool/url2body.json
python3 url2body.py corpus2/FudanNLP/fnlp/api.json | jq . > corpus2/FudanNLP/fnlp/url2body.json
python3 url2body.py corpus2/google/binnavi/api.json | jq . > corpus2/google/binnavi/url2body.json
python3 url2body.py corpus2/Comcast/FreeFlow/api.json | jq . > corpus2/Comcast/FreeFlow/url2body.json
python3 url2body.py corpus2/facebook/rebound/api.json | jq . > corpus2/facebook/rebound/url2body.json
python3 url2body.py corpus2/linkedin/databus/api.json | jq . > corpus2/linkedin/databus/url2body.json
python3 url2body.py corpus2/vipshop/vjtools/api.json | jq . > corpus2/vipshop/vjtools/url2body.json
python3 url2body.py corpus2/wyouflf/xUtils3/api.json | jq . > corpus2/wyouflf/xUtils3/url2body.json
python3 url2body.py corpus2/Justson/AgentWeb/api.json | jq . > corpus2/Justson/AgentWeb/url2body.json
python3 url2body.py corpus2/Red5/red5-server/api.json | jq . > corpus2/Red5/red5-server/url2body.json
python3 url2body.py corpus2/smuyyh/BookReader/api.json | jq . > corpus2/smuyyh/BookReader/url2body.json
python3 url2body.py corpus2/sohutv/cachecloud/api.json | jq . > corpus2/sohutv/cachecloud/url2body.json
python3 url2body.py corpus2/yanzhenjie/NoHttp/api.json | jq . > corpus2/yanzhenjie/NoHttp/url2body.json
python3 url2body.py corpus2/alibaba/easyexcel/api.json | jq . > corpus2/alibaba/easyexcel/url2body.json
python3 url2body.py corpus2/seven332/EhViewer/api.json | jq . > corpus2/seven332/EhViewer/url2body.json
python3 url2body.py corpus2/JakeWharton/scalpel/api.json | jq . > corpus2/JakeWharton/scalpel/url2body.json
python3 url2body.py corpus2/dm77/barcodescanner/api.json | jq . > corpus2/dm77/barcodescanner/url2body.json
python3 url2body.py corpus2/youth5201314/banner/api.json | jq . > corpus2/youth5201314/banner/url2body.json
python3 url2body.py corpus2/zzz40500/GsonFormat/api.json | jq . > corpus2/zzz40500/GsonFormat/url2body.json
python3 url2body.py corpus2/jdsjlzx/LRecyclerView/api.json | jq . > corpus2/jdsjlzx/LRecyclerView/url2body.json
python3 url2body.py corpus2/laobie/StatusBarUtil/api.json | jq . > corpus2/laobie/StatusBarUtil/url2body.json
python3 url2body.py corpus2/Trinea/android-common/api.json | jq . > corpus2/Trinea/android-common/url2body.json
python3 url2body.py corpus2/alibaba/UltraViewPager/api.json | jq . > corpus2/alibaba/UltraViewPager/url2body.json
python3 url2body.py corpus2/florent37/DiagonalLayout/api.json | jq . > corpus2/florent37/DiagonalLayout/url2body.json
python3 url2body.py corpus2/kikoso/android-stackblur/api.json | jq . > corpus2/kikoso/android-stackblur/url2body.json
python3 url2body.py corpus2/Jude95/EasyRecyclerView/api.json | jq . > corpus2/Jude95/EasyRecyclerView/url2body.json
python3 url2body.py corpus2/florent37/CameraFragment/api.json | jq . > corpus2/florent37/CameraFragment/url2body.json
python3 url2body.py corpus2/mihaip/dex-method-counts/api.json | jq . > corpus2/mihaip/dex-method-counts/url2body.json
python3 url2body.py corpus2/pchmn/MaterialChipsInput/api.json | jq . > corpus2/pchmn/MaterialChipsInput/url2body.json
python3 url2body.py corpus2/zagum/Android-SwitchIcon/api.json | jq . > corpus2/zagum/Android-SwitchIcon/url2body.json
python3 url2body.py corpus2/SimonVT/android-menudrawer/api.json | jq . > corpus2/SimonVT/android-menudrawer/url2body.json
python3 url2body.py corpus2/Vedenin/useful-java-links/api.json | jq . > corpus2/Vedenin/useful-java-links/url2body.json
python3 url2body.py corpus2/Yalantis/Side-Menu.Android/api.json | jq . > corpus2/Yalantis/Side-Menu.Android/url2body.json
python3 url2body.py corpus2/DroidPluginTeam/DroidPlugin/api.json | jq . > corpus2/DroidPluginTeam/DroidPlugin/url2body.json
python3 url2body.py corpus2/LuckSiege/PictureSelector/api.json | jq . > corpus2/LuckSiege/PictureSelector/url2body.json
python3 url2body.py corpus2/daniulive/SmarterStreaming/api.json | jq . > corpus2/daniulive/SmarterStreaming/url2body.json
python3 url2body.py corpus2/hongyangAndroid/FlowLayout/api.json | jq . > corpus2/hongyangAndroid/FlowLayout/url2body.json
python3 url2body.py corpus2/JakeWharton/NineOldAndroids/api.json | jq . > corpus2/JakeWharton/NineOldAndroids/url2body.json
python3 url2body.py corpus2/JackyAndroid/AndroidChromium/api.json | jq . > corpus2/JackyAndroid/AndroidChromium/url2body.json
python3 url2body.py corpus2/TommyLemon/Android-ZBLibrary/api.json | jq . > corpus2/TommyLemon/Android-ZBLibrary/url2body.json
python3 url2body.py corpus2/florent37/MaterialViewPager/api.json | jq . > corpus2/florent37/MaterialViewPager/url2body.json
python3 url2body.py corpus2/google/google-authenticator/api.json | jq . > corpus2/google/google-authenticator/url2body.json
python3 url2body.py corpus2/pagehelper/Mybatis-PageHelper/api.json | jq . > corpus2/pagehelper/Mybatis-PageHelper/url2body.json
python3 url2body.py corpus2/yanzhenjie/SwipeRecyclerView/api.json | jq . > corpus2/yanzhenjie/SwipeRecyclerView/url2body.json
python3 url2body.py corpus2/zouzg/mybatis-generator-gui/api.json | jq . > corpus2/zouzg/mybatis-generator-gui/url2body.json
python3 url2body.py corpus2/DingMouRen/LayoutManagerGroup/api.json | jq . > corpus2/DingMouRen/LayoutManagerGroup/url2body.json
python3 url2body.py corpus2/luojilab/DDComponentForAndroid/api.json | jq . > corpus2/luojilab/DDComponentForAndroid/url2body.json
python3 url2body.py corpus2/pnikosis/materialish-progress/api.json | jq . > corpus2/pnikosis/materialish-progress/url2body.json
python3 url2body.py corpus2/Jacksgong/JKeyboardPanelSwitch/api.json | jq . > corpus2/Jacksgong/JKeyboardPanelSwitch/url2body.json
python3 url2body.py corpus2/JackyAndroid/AndroidTVLauncher/api.json | jq . > corpus2/JackyAndroid/AndroidTVLauncher/url2body.json
python3 url2body.py corpus2/ityouknow/spring-boot-examples/api.json | jq . > corpus2/ityouknow/spring-boot-examples/url2body.json
python3 url2body.py corpus2/prontera/spring-cloud-rest-tcc/api.json | jq . > corpus2/prontera/spring-cloud-rest-tcc/url2body.json
python3 url2body.py corpus2/Bigkoo/Android-ConvenientBanner/api.json | jq . > corpus2/Bigkoo/Android-ConvenientBanner/url2body.json
python3 url2body.py corpus2/anjlab/android-inapp-billing-v3/api.json | jq . > corpus2/anjlab/android-inapp-billing-v3/url2body.json
python3 url2body.py corpus2/grantland/android-autofittextview/api.json | jq . > corpus2/grantland/android-autofittextview/url2body.json
python3 url2body.py corpus2/spring-projects/spring-mvc-showcase/api.json | jq . > corpus2/spring-projects/spring-mvc-showcase/url2body.json
python3 url2body.py corpus2/zo0r/react-native-push-notification/api.json | jq . > corpus2/zo0r/react-native-push-notification/url2body.json
python3 url2body.py corpus2/MindorksOpenSource/from-java-to-kotlin/api.json | jq . > corpus2/MindorksOpenSource/from-java-to-kotlin/url2body.json
python3 url2body.py corpus2/phishman3579/java-algorithms-implementation/api.json | jq . > corpus2/phishman3579/java-algorithms-implementation/url2body.json
python3 url2body.py corpus2/JulienGenoud/android-percent-support-lib-sample/api.json | jq . > corpus2/JulienGenoud/android-percent-support-lib-sample/url2body.json
python3 url2body.py corpus2/r0adkll/Slidr/api.json | jq . > corpus2/r0adkll/Slidr/url2body.json
python3 url2body.py corpus2/CalebFenton/simplify/api.json | jq . > corpus2/CalebFenton/simplify/url2body.json
python3 url2body.py corpus2/gyf-dev/ImmersionBar/api.json | jq . > corpus2/gyf-dev/ImmersionBar/url2body.json
python3 url2body.py corpus2/AigeStudio/WheelPicker/api.json | jq . > corpus2/AigeStudio/WheelPicker/url2body.json
python3 url2body.py corpus2/harism/android-pagecurl/api.json | jq . > corpus2/harism/android-pagecurl/url2body.json
python3 url2body.py corpus2/JakeWharton/ThreeTenABP/api.json | jq . > corpus2/JakeWharton/ThreeTenABP/url2body.json
python3 url2body.py corpus2/ApmeM/android-flowlayout/api.json | jq . > corpus2/ApmeM/android-flowlayout/url2body.json
python3 url2body.py corpus2/fython/MaterialStepperView/api.json | jq . > corpus2/fython/MaterialStepperView/url2body.json
python3 url2body.py corpus2/Ramotion/folding-cell-android/api.json | jq . > corpus2/Ramotion/folding-cell-android/url2body.json
python3 url2body.py corpus2/saulmm/Android-Material-Examples/api.json | jq . > corpus2/saulmm/Android-Material-Examples/url2body.json
python3 url2body.py corpus2/yipianfengye/android-zxingLibrary/api.json | jq . > corpus2/yipianfengye/android-zxingLibrary/url2body.json
python3 url2body.py corpus2/google/tink/api.json | jq . > corpus2/google/tink/url2body.json
python3 url2body.py corpus2/jgilfelt/chuck/api.json | jq . > corpus2/jgilfelt/chuck/url2body.json
python3 url2body.py corpus2/vondear/RxTool/api.json | jq . > corpus2/vondear/RxTool/url2body.json
python3 url2body.py corpus2/zhangkaitao/es/api.json | jq . > corpus2/zhangkaitao/es/url2body.json
python3 url2body.py corpus2/GrenderG/Toasty/api.json | jq . > corpus2/GrenderG/Toasty/url2body.json
python3 url2body.py corpus2/abel533/Mapper/api.json | jq . > corpus2/abel533/Mapper/url2body.json
python3 url2body.py corpus2/dropbox/hackpad/api.json | jq . > corpus2/dropbox/hackpad/url2body.json
python3 url2body.py corpus2/Dimezis/BlurView/api.json | jq . > corpus2/Dimezis/BlurView/url2body.json
python3 url2body.py corpus2/grandcentrix/tray/api.json | jq . > corpus2/grandcentrix/tray/url2body.json
python3 url2body.py corpus2/jpush/aurora-imui/api.json | jq . > corpus2/jpush/aurora-imui/url2body.json
python3 url2body.py corpus2/gitpitch/gitpitch/api.json | jq . > corpus2/gitpitch/gitpitch/url2body.json
python3 url2body.py corpus2/QMUI/QMUI_Android/api.json | jq . > corpus2/QMUI/QMUI_Android/url2body.json
python3 url2body.py corpus2/mancj/SlideUp-Android/api.json | jq . > corpus2/mancj/SlideUp-Android/url2body.json
python3 url2body.py corpus2/baomidou/mybatis-plus/api.json | jq . > corpus2/baomidou/mybatis-plus/url2body.json
python3 url2body.py corpus2/shwenzhang/AndResGuard/api.json | jq . > corpus2/shwenzhang/AndResGuard/url2body.json
python3 url2body.py corpus2/frogermcs/InstaMaterial/api.json | jq . > corpus2/frogermcs/InstaMaterial/url2body.json
python3 url2body.py corpus2/liyiorg/weixin-popular/api.json | jq . > corpus2/liyiorg/weixin-popular/url2body.json
python3 url2body.py corpus2/objectbox/objectbox-java/api.json | jq . > corpus2/objectbox/objectbox-java/url2body.json
python3 url2body.py corpus2/iammert/MaterialIntroView/api.json | jq . > corpus2/iammert/MaterialIntroView/url2body.json
python3 url2body.py corpus2/Clans/FloatingActionButton/api.json | jq . > corpus2/Clans/FloatingActionButton/url2body.json
python3 url2body.py corpus2/gzu-liyujiang/AndroidPicker/api.json | jq . > corpus2/gzu-liyujiang/AndroidPicker/url2body.json
python3 url2body.py corpus2/avast/android-styled-dialogs/api.json | jq . > corpus2/avast/android-styled-dialogs/url2body.json
python3 url2body.py corpus2/castorflex/SmoothProgressBar/api.json | jq . > corpus2/castorflex/SmoothProgressBar/url2body.json
python3 url2body.py corpus2/leolin310148/ShortcutBadger/api.json | jq . > corpus2/leolin310148/ShortcutBadger/url2body.json
python3 url2body.py corpus2/medcl/elasticsearch-analysis-ik/api.json | jq . > corpus2/medcl/elasticsearch-analysis-ik/url2body.json
python3 url2body.py corpus2/MiguelCatalan/MaterialSearchView/api.json | jq . > corpus2/MiguelCatalan/MaterialSearchView/url2body.json
python3 url2body.py corpus2/dmytrodanylyk/android-process-button/api.json | jq . > corpus2/dmytrodanylyk/android-process-button/url2body.json
python3 url2body.py corpus2/konifar/android-material-design-icon-generator-plugin/api.json | jq . > corpus2/konifar/android-material-design-icon-generator-plugin/url2body.json
python3 url2body.py corpus2/edmodo/cropper/api.json | jq . > corpus2/edmodo/cropper/url2body.json
python3 url2body.py corpus2/alipay/sofa-jarslink/api.json | jq . > corpus2/alipay/sofa-jarslink/url2body.json
python3 url2body.py corpus2/antoniolg/androidmvp/api.json | jq . > corpus2/antoniolg/androidmvp/url2body.json
python3 url2body.py corpus2/hongyangAndroid/Highlight/api.json | jq . > corpus2/hongyangAndroid/Highlight/url2body.json
python3 url2body.py corpus2/Yalantis/Context-Menu.Android/api.json | jq . > corpus2/Yalantis/Context-Menu.Android/url2body.json
python3 url2body.py corpus2/LWJGL/lwjgl3/api.json | jq . > corpus2/LWJGL/lwjgl3/url2body.json
python3 url2body.py corpus2/naman14/Timber/api.json | jq . > corpus2/naman14/Timber/url2body.json
python3 url2body.py corpus2/Yalantis/Phoenix/api.json | jq . > corpus2/Yalantis/Phoenix/url2body.json
python3 url2body.py corpus2/steelkiwi/cropiwa/api.json | jq . > corpus2/steelkiwi/cropiwa/url2body.json
python3 url2body.py corpus2/jjoe64/GraphView/api.json | jq . > corpus2/jjoe64/GraphView/url2body.json
python3 url2body.py corpus2/yanzhenjie/Album/api.json | jq . > corpus2/yanzhenjie/Album/url2body.json
python3 url2body.py corpus2/PipelineAI/pipeline/api.json | jq . > corpus2/PipelineAI/pipeline/url2body.json
python3 url2body.py corpus2/ozodrukh/CircularReveal/api.json | jq . > corpus2/ozodrukh/CircularReveal/url2body.json
python3 url2body.py corpus2/airbnb/native-navigation/api.json | jq . > corpus2/airbnb/native-navigation/url2body.json
python3 url2body.py corpus2/sockeqwe/AdapterDelegates/api.json | jq . > corpus2/sockeqwe/AdapterDelegates/url2body.json
python3 url2body.py corpus2/JessYanCoding/AndroidAutoSize/api.json | jq . > corpus2/JessYanCoding/AndroidAutoSize/url2body.json
python3 url2body.py corpus2/ragunathjawahar/android-saripaar/api.json | jq . > corpus2/ragunathjawahar/android-saripaar/url2body.json
python3 url2body.py corpus2/bingoogolapple/BGABadgeView-Android/api.json | jq . > corpus2/bingoogolapple/BGABadgeView-Android/url2body.json
python3 url2body.py corpus2/lihengming/spring-boot-api-project-seed/api.json | jq . > corpus2/lihengming/spring-boot-api-project-seed/url2body.json
python3 url2body.py corpus2/android-cjj/Android-MaterialRefreshLayout/api.json | jq . > corpus2/android-cjj/Android-MaterialRefreshLayout/url2body.json
python3 url2body.py corpus2/kyleduo/SwitchButton/api.json | jq . > corpus2/kyleduo/SwitchButton/url2body.json
python3 url2body.py corpus2/hongyangAndroid/baseAdapter/api.json | jq . > corpus2/hongyangAndroid/baseAdapter/url2body.json
python3 url2body.py corpus2/codeestX/GeekNews/api.json | jq . > corpus2/codeestX/GeekNews/url2body.json
python3 url2body.py corpus2/kevin-wayne/algs4/api.json | jq . > corpus2/kevin-wayne/algs4/url2body.json
python3 url2body.py corpus2/zetbaitsu/Compressor/api.json | jq . > corpus2/zetbaitsu/Compressor/url2body.json
python3 url2body.py corpus2/harjot-oberai/MusicDNA/api.json | jq . > corpus2/harjot-oberai/MusicDNA/url2body.json
python3 url2body.py corpus2/aporter/coursera-android/api.json | jq . > corpus2/aporter/coursera-android/url2body.json
python3 url2body.py corpus2/CameraKit/blurkit-android/api.json | jq . > corpus2/CameraKit/blurkit-android/url2body.json
python3 url2body.py corpus2/pedant/sweet-alert-dialog/api.json | jq . > corpus2/pedant/sweet-alert-dialog/url2body.json
python3 url2body.py corpus2/wasabeef/richeditor-android/api.json | jq . > corpus2/wasabeef/richeditor-android/url2body.json
python3 url2body.py corpus2/googlesamples/google-services/api.json | jq . > corpus2/googlesamples/google-services/url2body.json
python3 url2body.py corpus2/beworker/pinned-section-listview/api.json | jq . > corpus2/beworker/pinned-section-listview/url2body.json
python3 url2body.py corpus2/kbastani/spring-cloud-microservice-example/api.json | jq . > corpus2/kbastani/spring-cloud-microservice-example/url2body.json
python3 url2body.py corpus2/luckybilly/CC/api.json | jq . > corpus2/luckybilly/CC/url2body.json
python3 url2body.py corpus2/ybq/Android-SpinKit/api.json | jq . > corpus2/ybq/Android-SpinKit/url2body.json
python3 url2body.py corpus2/novoda/android-demos/api.json | jq . > corpus2/novoda/android-demos/url2body.json
python3 url2body.py corpus2/iammert/ScalingLayout/api.json | jq . > corpus2/iammert/ScalingLayout/url2body.json
python3 url2body.py corpus2/openaphid/android-flip/api.json | jq . > corpus2/openaphid/android-flip/url2body.json
python3 url2body.py corpus2/Todd-Davies/ProgressWheel/api.json | jq . > corpus2/Todd-Davies/ProgressWheel/url2body.json
python3 url2body.py corpus2/androidquery/androidquery/api.json | jq . > corpus2/androidquery/androidquery/url2body.json
python3 url2body.py corpus2/Zomato/AndroidPhotoFilters/api.json | jq . > corpus2/Zomato/AndroidPhotoFilters/url2body.json
python3 url2body.py corpus2/daimajia/NumberProgressBar/api.json | jq . > corpus2/daimajia/NumberProgressBar/url2body.json
python3 url2body.py corpus2/huanghaibin-dev/CalendarView/api.json | jq . > corpus2/huanghaibin-dev/CalendarView/url2body.json
python3 url2body.py corpus2/AndroidBootstrap/android-bootstrap/api.json | jq . > corpus2/AndroidBootstrap/android-bootstrap/url2body.json
python3 url2body.py corpus2/LyndonChin/MasteringAndroidDataBinding/api.json | jq . > corpus2/LyndonChin/MasteringAndroidDataBinding/url2body.json
python3 url2body.py corpus2/knightliao/disconf/api.json | jq . > corpus2/knightliao/disconf/url2body.json
python3 url2body.py corpus2/Bilibili/MagicaSakura/api.json | jq . > corpus2/Bilibili/MagicaSakura/url2body.json
python3 url2body.py corpus2/balysv/material-ripple/api.json | jq . > corpus2/balysv/material-ripple/url2body.json
python3 url2body.py corpus2/xfumihiro/ViewInspector/api.json | jq . > corpus2/xfumihiro/ViewInspector/url2body.json
python3 url2body.py corpus2/JakeWharton/DiskLruCache/api.json | jq . > corpus2/JakeWharton/DiskLruCache/url2body.json
python3 url2body.py corpus2/flavioarfaria/KenBurnsView/api.json | jq . > corpus2/flavioarfaria/KenBurnsView/url2body.json
python3 url2body.py corpus2/diogobernardino/WilliamChart/api.json | jq . > corpus2/diogobernardino/WilliamChart/url2body.json
python3 url2body.py corpus2/WritingMinds/ffmpeg-android-java/api.json | jq . > corpus2/WritingMinds/ffmpeg-android-java/url2body.json
python3 url2body.py corpus2/orhanobut/hawk/api.json | jq . > corpus2/orhanobut/hawk/url2body.json
python3 url2body.py corpus2/aragozin/jvm-tools/api.json | jq . > corpus2/aragozin/jvm-tools/url2body.json
python3 url2body.py corpus2/elye/loaderviewlibrary/api.json | jq . > corpus2/elye/loaderviewlibrary/url2body.json
python3 url2body.py corpus2/pedrovgs/EffectiveAndroidUI/api.json | jq . > corpus2/pedrovgs/EffectiveAndroidUI/url2body.json
python3 url2body.py corpus2/EverythingMe/overscroll-decor/api.json | jq . > corpus2/EverythingMe/overscroll-decor/url2body.json
python3 url2body.py corpus2/yarolegovich/DiscreteScrollView/api.json | jq . > corpus2/yarolegovich/DiscreteScrollView/url2body.json
python3 url2body.py corpus2/ltsopensource/light-task-scheduler/api.json | jq . > corpus2/ltsopensource/light-task-scheduler/url2body.json
python3 url2body.py corpus2/alibaba/atlas/api.json | jq . > corpus2/alibaba/atlas/url2body.json
python3 url2body.py corpus2/traex/RippleEffect/api.json | jq . > corpus2/traex/RippleEffect/url2body.json
python3 url2body.py corpus2/alibaba/jvm-sandbox/api.json | jq . > corpus2/alibaba/jvm-sandbox/url2body.json
python3 url2body.py corpus2/lsjwzh/RecyclerViewPager/api.json | jq . > corpus2/lsjwzh/RecyclerViewPager/url2body.json
python3 url2body.py corpus2/googlesamples/android-vision/api.json | jq . > corpus2/googlesamples/android-vision/url2body.json
python3 url2body.py corpus2/changmingxie/tcc-transaction/api.json | jq . > corpus2/changmingxie/tcc-transaction/url2body.json
python3 url2body.py corpus2/SpecialCyCi/AndroidResideMenu/api.json | jq . > corpus2/SpecialCyCi/AndroidResideMenu/url2body.json
python3 url2body.py corpus2/johannilsson/android-pulltorefresh/api.json | jq . > corpus2/johannilsson/android-pulltorefresh/url2body.json
python3 url2body.py corpus2/MikeOrtiz/TouchImageView/api.json | jq . > corpus2/MikeOrtiz/TouchImageView/url2body.json
python3 url2body.py corpus2/dlew/joda-time-android/api.json | jq . > corpus2/dlew/joda-time-android/url2body.json
python3 url2body.py corpus2/sharish/ShimmerRecyclerView/api.json | jq . > corpus2/sharish/ShimmerRecyclerView/url2body.json
python3 url2body.py corpus2/googlesamples/android-play-location/api.json | jq . > corpus2/googlesamples/android-play-location/url2body.json
python3 url2body.py corpus2/yangfuhai/afinal/api.json | jq . > corpus2/yangfuhai/afinal/url2body.json
python3 url2body.py corpus2/watabou/pixel-dungeon/api.json | jq . > corpus2/watabou/pixel-dungeon/url2body.json
python3 url2body.py corpus2/koush/ion/api.json | jq . > corpus2/koush/ion/url2body.json
python3 url2body.py corpus2/auth0/java-jwt/api.json | jq . > corpus2/auth0/java-jwt/url2body.json
python3 url2body.py corpus2/MindorksOpenSource/android-interview-questions/api.json | jq . > corpus2/MindorksOpenSource/android-interview-questions/url2body.json
python3 url2body.py corpus2/igreenwood/SimpleCropView/api.json | jq . > corpus2/igreenwood/SimpleCropView/url2body.json
python3 url2body.py corpus2/material-components/material-components-android/api.json | jq . > corpus2/material-components/material-components-android/url2body.json
python3 url2body.py corpus2/google/hover/api.json | jq . > corpus2/google/hover/url2body.json
python3 url2body.py corpus2/jd-alexander/LikeButton/api.json | jq . > corpus2/jd-alexander/LikeButton/url2body.json
python3 url2body.py corpus2/kevinsawicki/http-request/api.json | jq . > corpus2/kevinsawicki/http-request/url2body.json
python3 url2body.py corpus2/ittianyu/BottomNavigationViewEx/api.json | jq . > corpus2/ittianyu/BottomNavigationViewEx/url2body.json
python3 url2body.py corpus2/ZieIony/Carbon/api.json | jq . > corpus2/ZieIony/Carbon/url2body.json
python3 url2body.py corpus2/square/sqlbrite/api.json | jq . > corpus2/square/sqlbrite/url2body.json
python3 url2body.py corpus2/jfinal/jfinal/api.json | jq . > corpus2/jfinal/jfinal/url2body.json
python3 url2body.py corpus2/medyo/Fancybuttons/api.json | jq . > corpus2/medyo/Fancybuttons/url2body.json
python3 url2body.py corpus2/orhanobut/dialogplus/api.json | jq . > corpus2/orhanobut/dialogplus/url2body.json
python3 url2body.py corpus2/pilgr/Paper/api.json | jq . > corpus2/pilgr/Paper/url2body.json
python3 url2body.py corpus2/speedment/speedment/api.json | jq . > corpus2/speedment/speedment/url2body.json
python3 url2body.py corpus2/alibaba/Tangram-Android/api.json | jq . > corpus2/alibaba/Tangram-Android/url2body.json
python3 url2body.py corpus2/vinc3m1/RoundedImageView/api.json | jq . > corpus2/vinc3m1/RoundedImageView/url2body.json
python3 url2body.py corpus2/pedrovgs/AndroidWiFiADB/api.json | jq . > corpus2/pedrovgs/AndroidWiFiADB/url2body.json
python3 url2body.py corpus2/astuetz/PagerSlidingTabStrip/api.json | jq . > corpus2/astuetz/PagerSlidingTabStrip/url2body.json
python3 url2body.py corpus2/avjinder/Minimal-Todo/api.json | jq . > corpus2/avjinder/Minimal-Todo/url2body.json
python3 url2body.py corpus2/alibaba/otter/api.json | jq . > corpus2/alibaba/otter/url2body.json
python3 url2body.py corpus2/wildfly/wildfly/api.json | jq . > corpus2/wildfly/wildfly/url2body.json
python3 url2body.py corpus2/RobotiumTech/robotium/api.json | jq . > corpus2/RobotiumTech/robotium/url2body.json
python3 url2body.py corpus2/JoanZapata/android-iconify/api.json | jq . > corpus2/JoanZapata/android-iconify/url2body.json
python3 url2body.py corpus2/pedrovgs/Algorithms/api.json | jq . > corpus2/pedrovgs/Algorithms/url2body.json
python3 url2body.py corpus2/flavienlaurent/datetimepicker/api.json | jq . > corpus2/flavienlaurent/datetimepicker/url2body.json
python3 url2body.py corpus2/singwhatiwanna/dynamic-load-apk/api.json | jq . > corpus2/singwhatiwanna/dynamic-load-apk/url2body.json
python3 url2body.py corpus2/xuxueli/xxl-job/api.json | jq . > corpus2/xuxueli/xxl-job/url2body.json
python3 url2body.py corpus2/ongakuer/CircleIndicator/api.json | jq . > corpus2/ongakuer/CircleIndicator/url2body.json
python3 url2body.py corpus2/nicolasgramlich/AndEngine/api.json | jq . > corpus2/nicolasgramlich/AndEngine/url2body.json
python3 url2body.py corpus2/Ereza/CustomActivityOnCrash/api.json | jq . > corpus2/Ereza/CustomActivityOnCrash/url2body.json
python3 url2body.py corpus2/skavanagh/KeyBox/api.json | jq . > corpus2/skavanagh/KeyBox/url2body.json
python3 url2body.py corpus2/amitshekhariitbhu/Android-Debug-Database/api.json | jq . > corpus2/amitshekhariitbhu/Android-Debug-Database/url2body.json
python3 url2body.py corpus2/qii/weiciyuan/api.json | jq . > corpus2/qii/weiciyuan/url2body.json
python3 url2body.py corpus2/mcxiaoke/android-volley/api.json | jq . > corpus2/mcxiaoke/android-volley/url2body.json
python3 url2body.py corpus2/HannahMitt/HomeMirror/api.json | jq . > corpus2/HannahMitt/HomeMirror/url2body.json
python3 url2body.py corpus2/rey5137/material/api.json | jq . > corpus2/rey5137/material/url2body.json
python3 url2body.py corpus2/google/agera/api.json | jq . > corpus2/google/agera/url2body.json
python3 url2body.py corpus2/wasabeef/glide-transformations/api.json | jq . > corpus2/wasabeef/glide-transformations/url2body.json
python3 url2body.py corpus2/YoKeyword/Fragmentation/api.json | jq . > corpus2/YoKeyword/Fragmentation/url2body.json
python3 url2body.py corpus2/oldmanpushcart/greys-anatomy/api.json | jq . > corpus2/oldmanpushcart/greys-anatomy/url2body.json
python3 url2body.py corpus2/didi/VirtualAPK/api.json | jq . > corpus2/didi/VirtualAPK/url2body.json
python3 url2body.py corpus2/lucasr/twoway-view/api.json | jq . > corpus2/lucasr/twoway-view/url2body.json
python3 url2body.py corpus2/stanfordnlp/CoreNLP/api.json | jq . > corpus2/stanfordnlp/CoreNLP/url2body.json
python3 url2body.py corpus2/libgdx/packr/api.json | jq . > corpus2/libgdx/packr/url2body.json
python3 url2body.py corpus2/Meituan-Dianping/Robust/api.json | jq . > corpus2/Meituan-Dianping/Robust/url2body.json
python3 url2body.py corpus2/Bilibili/boxing/api.json | jq . > corpus2/Bilibili/boxing/url2body.json
python3 url2body.py corpus2/aurelhubert/ahbottomnavigation/api.json | jq . > corpus2/aurelhubert/ahbottomnavigation/url2body.json
python3 url2body.py corpus2/raphw/byte-buddy/api.json | jq . > corpus2/raphw/byte-buddy/url2body.json
python3 url2body.py corpus2/avast/android-butterknife-zelezny/api.json | jq . > corpus2/avast/android-butterknife-zelezny/url2body.json
python3 url2body.py corpus2/JoanZapata/android-pdfview/api.json | jq . > corpus2/JoanZapata/android-pdfview/url2body.json
python3 url2body.py corpus2/sockeqwe/mosby/api.json | jq . > corpus2/sockeqwe/mosby/url2body.json
python3 url2body.py corpus2/soarcn/BottomSheet/api.json | jq . > corpus2/soarcn/BottomSheet/url2body.json
python3 url2body.py corpus2/facebook/shimmer-android/api.json | jq . > corpus2/facebook/shimmer-android/url2body.json
python3 url2body.py corpus2/lecho/hellocharts-android/api.json | jq . > corpus2/lecho/hellocharts-android/url2body.json
python3 url2body.py corpus2/JohnPersano/SuperToasts/api.json | jq . > corpus2/JohnPersano/SuperToasts/url2body.json
python3 url2body.py corpus2/ArthurHub/Android-Image-Cropper/api.json | jq . > corpus2/ArthurHub/Android-Image-Cropper/url2body.json
python3 url2body.py corpus2/bingoogolapple/BGABanner-Android/api.json | jq . > corpus2/bingoogolapple/BGABanner-Android/url2body.json
python3 url2body.py corpus2/donglua/PhotoPicker/api.json | jq . > corpus2/donglua/PhotoPicker/url2body.json
python3 url2body.py corpus2/crazycodeboy/react-native-splash-screen/api.json | jq . > corpus2/crazycodeboy/react-native-splash-screen/url2body.json
python3 url2body.py corpus2/jhalterman/failsafe/api.json | jq . > corpus2/jhalterman/failsafe/url2body.json
python3 url2body.py corpus2/hanks-zyh/HTextView/api.json | jq . > corpus2/hanks-zyh/HTextView/url2body.json
python3 url2body.py corpus2/mikepenz/AboutLibraries/api.json | jq . > corpus2/mikepenz/AboutLibraries/url2body.json
python3 url2body.py corpus2/google/j2objc/api.json | jq . > corpus2/google/j2objc/url2body.json
python3 url2body.py corpus2/rabbitmq/rabbitmq-tutorials/api.json | jq . > corpus2/rabbitmq/rabbitmq-tutorials/url2body.json
python3 url2body.py corpus2/ToxicBakery/ViewPagerTransforms/api.json | jq . > corpus2/ToxicBakery/ViewPagerTransforms/url2body.json
python3 url2body.py corpus2/BoltsFramework/Bolts-Android/api.json | jq . > corpus2/BoltsFramework/Bolts-Android/url2body.json
python3 url2body.py corpus2/lingochamp/okdownload/api.json | jq . > corpus2/lingochamp/okdownload/url2body.json
python3 url2body.py corpus2/Diolor/Swipecards/api.json | jq . > corpus2/Diolor/Swipecards/url2body.json
python3 url2body.py corpus2/socketio/socket.io-client-java/api.json | jq . > corpus2/socketio/socket.io-client-java/url2body.json
python3 url2body.py corpus2/willowtreeapps/spruce-android/api.json | jq . > corpus2/willowtreeapps/spruce-android/url2body.json
python3 url2body.py corpus2/gabrielemariotti/cardslib/api.json | jq . > corpus2/gabrielemariotti/cardslib/url2body.json
python3 url2body.py corpus2/NLPchina/ansj_seg/api.json | jq . > corpus2/NLPchina/ansj_seg/url2body.json
python3 url2body.py corpus2/dragonflyoss/Dragonfly/api.json | jq . > corpus2/dragonflyoss/Dragonfly/url2body.json
python3 url2body.py corpus2/android-hacker/VirtualXposed/api.json | jq . > corpus2/android-hacker/VirtualXposed/url2body.json
python3 url2body.py corpus2/robinhood/ticker/api.json | jq . > corpus2/robinhood/ticker/url2body.json
python3 url2body.py corpus2/linlinjava/litemall/api.json | jq . > corpus2/linlinjava/litemall/url2body.json
python3 url2body.py corpus2/daimajia/AndroidImageSlider/api.json | jq . > corpus2/daimajia/AndroidImageSlider/url2body.json
python3 url2body.py corpus2/code4craft/webmagic/api.json | jq . > corpus2/code4craft/webmagic/url2body.json
python3 url2body.py corpus2/h6ah4i/android-advancedrecyclerview/api.json | jq . > corpus2/h6ah4i/android-advancedrecyclerview/url2body.json
python3 url2body.py corpus2/googlesamples/android-testing/api.json | jq . > corpus2/googlesamples/android-testing/url2body.json
python3 url2body.py corpus2/Flipboard/bottomsheet/api.json | jq . > corpus2/Flipboard/bottomsheet/url2body.json
python3 url2body.py corpus2/JesusFreke/smali/api.json | jq . > corpus2/JesusFreke/smali/url2body.json
python3 url2body.py corpus2/yasserg/crawler4j/api.json | jq . > corpus2/yasserg/crawler4j/url2body.json
python3 url2body.py corpus2/danikula/AndroidVideoCache/api.json | jq . > corpus2/danikula/AndroidVideoCache/url2body.json
python3 url2body.py corpus2/qiujuer/Genius-Android/api.json | jq . > corpus2/qiujuer/Genius-Android/url2body.json
python3 url2body.py corpus2/square/tape/api.json | jq . > corpus2/square/tape/url2body.json
python3 url2body.py corpus2/evrencoskun/TableView/api.json | jq . > corpus2/evrencoskun/TableView/url2body.json
python3 url2body.py corpus2/mikepenz/Android-Iconics/api.json | jq . > corpus2/mikepenz/Android-Iconics/url2body.json
python3 url2body.py corpus2/bluelinelabs/LoganSquare/api.json | jq . > corpus2/bluelinelabs/LoganSquare/url2body.json
python3 url2body.py corpus2/JakeWharton/hugo/api.json | jq . > corpus2/JakeWharton/hugo/url2body.json
python3 url2body.py corpus2/jboss-javassist/javassist/api.json | jq . > corpus2/jboss-javassist/javassist/url2body.json
python3 url2body.py corpus2/square/flow/api.json | jq . > corpus2/square/flow/url2body.json
python3 url2body.py corpus2/rengwuxian/MaterialEditText/api.json | jq . > corpus2/rengwuxian/MaterialEditText/url2body.json
python3 url2body.py corpus2/evant/gradle-retrolambda/api.json | jq . > corpus2/evant/gradle-retrolambda/url2body.json
python3 url2body.py corpus2/lzyzsd/CircleProgress/api.json | jq . > corpus2/lzyzsd/CircleProgress/url2body.json
python3 url2body.py corpus2/stfalcon-studio/ChatKit/api.json | jq . > corpus2/stfalcon-studio/ChatKit/url2body.json
python3 url2body.py corpus2/bauerca/drag-sort-listview/api.json | jq . > corpus2/bauerca/drag-sort-listview/url2body.json
python3 url2body.py corpus2/Meituan-Dianping/walle/api.json | jq . > corpus2/Meituan-Dianping/walle/url2body.json
python3 url2body.py corpus2/springside/springside4/api.json | jq . > corpus2/springside/springside4/url2body.json
python3 url2body.py corpus2/pili-engineering/PLDroidPlayer/api.json | jq . > corpus2/pili-engineering/PLDroidPlayer/url2body.json
python3 url2body.py corpus2/FinalTeam/RxGalleryFinal/api.json | jq . > corpus2/FinalTeam/RxGalleryFinal/url2body.json
python3 url2body.py corpus2/mrniko/netty-socketio/api.json | jq . > corpus2/mrniko/netty-socketio/url2body.json
python3 url2body.py corpus2/davideas/FlexibleAdapter/api.json | jq . > corpus2/davideas/FlexibleAdapter/url2body.json
python3 url2body.py corpus2/nispok/snackbar/api.json | jq . > corpus2/nispok/snackbar/url2body.json
python3 url2body.py corpus2/JakeWharton/Telecine/api.json | jq . > corpus2/JakeWharton/Telecine/url2body.json
python3 url2body.py corpus2/spring-projects/spring-loaded/api.json | jq . > corpus2/spring-projects/spring-loaded/url2body.json
python3 url2body.py corpus2/google/cameraview/api.json | jq . > corpus2/google/cameraview/url2body.json
python3 url2body.py corpus2/ben-manes/caffeine/api.json | jq . > corpus2/ben-manes/caffeine/url2body.json
python3 url2body.py corpus2/ximsfei/Android-skin-support/api.json | jq . > corpus2/ximsfei/Android-skin-support/url2body.json
python3 url2body.py corpus2/amitshekhariitbhu/Fast-Android-Networking/api.json | jq . > corpus2/amitshekhariitbhu/Fast-Android-Networking/url2body.json
python3 url2body.py corpus2/mcharmas/Android-ReactiveLocation/api.json | jq . > corpus2/mcharmas/Android-ReactiveLocation/url2body.json
python3 url2body.py corpus2/ronmamo/reflections/api.json | jq . > corpus2/ronmamo/reflections/url2body.json
python3 url2body.py corpus2/markzhai/AndroidPerformanceMonitor/api.json | jq . > corpus2/markzhai/AndroidPerformanceMonitor/url2body.json
python3 url2body.py corpus2/Graylog2/graylog2-server/api.json | jq . > corpus2/Graylog2/graylog2-server/url2body.json
python3 url2body.py corpus2/addthis/stream-lib/api.json | jq . > corpus2/addthis/stream-lib/url2body.json
python3 url2body.py corpus2/Ashok-Varma/BottomNavigation/api.json | jq . > corpus2/Ashok-Varma/BottomNavigation/url2body.json
python3 url2body.py corpus2/voldemort/voldemort/api.json | jq . > corpus2/voldemort/voldemort/url2body.json
python3 url2body.py corpus2/Teevity/ice/api.json | jq . > corpus2/Teevity/ice/url2body.json
python3 url2body.py corpus2/square/mortar/api.json | jq . > corpus2/square/mortar/url2body.json
python3 url2body.py corpus2/cryptomator/cryptomator/api.json | jq . > corpus2/cryptomator/cryptomator/url2body.json
python3 url2body.py corpus2/lingochamp/FileDownloader/api.json | jq . > corpus2/lingochamp/FileDownloader/url2body.json
python3 url2body.py corpus2/emilsjolander/StickyListHeaders/api.json | jq . > corpus2/emilsjolander/StickyListHeaders/url2body.json
python3 url2body.py corpus2/Netflix/zuul/api.json | jq . > corpus2/Netflix/zuul/url2body.json
python3 url2body.py corpus2/makovkastar/FloatingActionButton/api.json | jq . > corpus2/makovkastar/FloatingActionButton/url2body.json
python3 url2body.py corpus2/alibaba/jstorm/api.json | jq . > corpus2/alibaba/jstorm/url2body.json
python3 url2body.py corpus2/Yalantis/uCrop/api.json | jq . > corpus2/Yalantis/uCrop/url2body.json
python3 url2body.py corpus2/keyboardsurfer/Crouton/api.json | jq . > corpus2/keyboardsurfer/Crouton/url2body.json
python3 url2body.py corpus2/bytedeco/javacpp/api.json | jq . > corpus2/bytedeco/javacpp/url2body.json
python3 url2body.py corpus2/davemorrissey/subsampling-scale-image-view/api.json | jq . > corpus2/davemorrissey/subsampling-scale-image-view/url2body.json
python3 url2body.py corpus2/barteksc/AndroidPdfViewer/api.json | jq . > corpus2/barteksc/AndroidPdfViewer/url2body.json
python3 url2body.py corpus2/etsy/AndroidStaggeredGrid/api.json | jq . > corpus2/etsy/AndroidStaggeredGrid/url2body.json
python3 url2body.py corpus2/trello/RxLifecycle/api.json | jq . > corpus2/trello/RxLifecycle/url2body.json
python3 url2body.py corpus2/journeyapps/zxing-android-embedded/api.json | jq . > corpus2/journeyapps/zxing-android-embedded/url2body.json
python3 url2body.py corpus2/javaee-samples/javaee7-samples/api.json | jq . > corpus2/javaee-samples/javaee7-samples/url2body.json
python3 url2body.py corpus2/nisrulz/sensey/api.json | jq . > corpus2/nisrulz/sensey/url2body.json
python3 url2body.py corpus2/google/android-classyshark/api.json | jq . > corpus2/google/android-classyshark/url2body.json
python3 url2body.py corpus2/topjohnwu/Magisk/api.json | jq . > corpus2/topjohnwu/Magisk/url2body.json
python3 url2body.py corpus2/Bearded-Hen/Android-Bootstrap/api.json | jq . > corpus2/Bearded-Hen/Android-Bootstrap/url2body.json
python3 url2body.py corpus2/quartz-scheduler/quartz/api.json | jq . > corpus2/quartz-scheduler/quartz/url2body.json
python3 url2body.py corpus2/eishay/jvm-serializers/api.json | jq . > corpus2/eishay/jvm-serializers/url2body.json
python3 url2body.py corpus2/Netflix/curator/api.json | jq . > corpus2/Netflix/curator/url2body.json
python3 url2body.py corpus2/square/otto/api.json | jq . > corpus2/square/otto/url2body.json
python3 url2body.py corpus2/Athou/commafeed/api.json | jq . > corpus2/Athou/commafeed/url2body.json
python3 url2body.py corpus2/google/google-java-format/api.json | jq . > corpus2/google/google-java-format/url2body.json
python3 url2body.py corpus2/real-logic/aeron/api.json | jq . > corpus2/real-logic/aeron/url2body.json
python3 url2body.py corpus2/jdamcd/android-crop/api.json | jq . > corpus2/jdamcd/android-crop/url2body.json
python3 url2body.py corpus2/pardom-zz/ActiveAndroid/api.json | jq . > corpus2/pardom-zz/ActiveAndroid/url2body.json
python3 url2body.py corpus2/facebook/react-native-fbsdk/api.json | jq . > corpus2/facebook/react-native-fbsdk/url2body.json
python3 url2body.py corpus2/puniverse/quasar/api.json | jq . > corpus2/puniverse/quasar/url2body.json
python3 url2body.py corpus2/wdullaer/MaterialDateTimePicker/api.json | jq . > corpus2/wdullaer/MaterialDateTimePicker/url2body.json
python3 url2body.py corpus2/alamkanak/Android-Week-View/api.json | jq . > corpus2/alamkanak/Android-Week-View/url2body.json
python3 url2body.py corpus2/lapism/MaterialSearchView/api.json | jq . > corpus2/lapism/MaterialSearchView/url2body.json
python3 url2body.py corpus2/lets-blade/blade/api.json | jq . > corpus2/lets-blade/blade/url2body.json
python3 url2body.py corpus2/arimorty/floatingsearchview/api.json | jq . > corpus2/arimorty/floatingsearchview/url2body.json
python3 url2body.py corpus2/react-native-community/react-native-blur/api.json | jq . > corpus2/react-native-community/react-native-blur/url2body.json
python3 url2body.py corpus2/romandanylyk/PageIndicatorView/api.json | jq . > corpus2/romandanylyk/PageIndicatorView/url2body.json
python3 url2body.py corpus2/spring-cloud-incubator/spring-cloud-alibaba/api.json | jq . > corpus2/spring-cloud-incubator/spring-cloud-alibaba/url2body.json
python3 url2body.py corpus2/futuresimple/android-floating-action-button/api.json | jq . > corpus2/futuresimple/android-floating-action-button/url2body.json
python3 url2body.py corpus2/pedrovgs/DraggablePanel/api.json | jq . > corpus2/pedrovgs/DraggablePanel/url2body.json
python3 url2body.py corpus2/JessYanCoding/MVPArms/api.json | jq . > corpus2/JessYanCoding/MVPArms/url2body.json
python3 url2body.py corpus2/claritylab/lucida/api.json | jq . > corpus2/claritylab/lucida/url2body.json
python3 url2body.py corpus2/JakeWharton/timber/api.json | jq . > corpus2/JakeWharton/timber/url2body.json
python3 url2body.py corpus2/evernote/android-job/api.json | jq . > corpus2/evernote/android-job/url2body.json
python3 url2body.py corpus2/jfoenixadmin/JFoenix/api.json | jq . > corpus2/jfoenixadmin/JFoenix/url2body.json
python3 url2body.py corpus2/thingsboard/thingsboard/api.json | jq . > corpus2/thingsboard/thingsboard/url2body.json
python3 url2body.py corpus2/JodaOrg/joda-time/api.json | jq . > corpus2/JodaOrg/joda-time/url2body.json
python3 url2body.py corpus2/joelittlejohn/jsonschema2pojo/api.json | jq . > corpus2/joelittlejohn/jsonschema2pojo/url2body.json
python3 url2body.py corpus2/Screetsec/TheFatRat/api.json | jq . > corpus2/Screetsec/TheFatRat/url2body.json
python3 url2body.py corpus2/jprante/elasticsearch-jdbc/api.json | jq . > corpus2/jprante/elasticsearch-jdbc/url2body.json
python3 url2body.py corpus2/uber/RIBs/api.json | jq . > corpus2/uber/RIBs/url2body.json
python3 url2body.py corpus2/junit-team/junit5/api.json | jq . > corpus2/junit-team/junit5/url2body.json
python3 url2body.py corpus2/esoxjem/MovieGuide/api.json | jq . > corpus2/esoxjem/MovieGuide/url2body.json
python3 url2body.py corpus2/Piasy/BigImageViewer/api.json | jq . > corpus2/Piasy/BigImageViewer/url2body.json
python3 url2body.py corpus2/ChrisRM/material-theme-jetbrains/api.json | jq . > corpus2/ChrisRM/material-theme-jetbrains/url2body.json
python3 url2body.py corpus2/roboguice/roboguice/api.json | jq . > corpus2/roboguice/roboguice/url2body.json
python3 url2body.py corpus2/wequick/Small/api.json | jq . > corpus2/wequick/Small/url2body.json
python3 url2body.py corpus2/nutzam/nutz/api.json | jq . > corpus2/nutzam/nutz/url2body.json
python3 url2body.py corpus2/Netflix/SimianArmy/api.json | jq . > corpus2/Netflix/SimianArmy/url2body.json
python3 url2body.py corpus2/Angel-ML/angel/api.json | jq . > corpus2/Angel-ML/angel/url2body.json
python3 url2body.py corpus2/google/guice/api.json | jq . > corpus2/google/guice/url2body.json
python3 url2body.py corpus2/googlemaps/android-maps-utils/api.json | jq . > corpus2/googlemaps/android-maps-utils/url2body.json
python3 url2body.py corpus2/kaushikgopal/RxJava-Android-Samples/api.json | jq . > corpus2/kaushikgopal/RxJava-Android-Samples/url2body.json
python3 url2body.py corpus2/cglib/cglib/api.json | jq . > corpus2/cglib/cglib/url2body.json
python3 url2body.py corpus2/mybatis/spring-boot-starter/api.json | jq . > corpus2/mybatis/spring-boot-starter/url2body.json
python3 url2body.py corpus2/iSoron/uhabits/api.json | jq . > corpus2/iSoron/uhabits/url2body.json
python3 url2body.py corpus2/luontola/retrolambda/api.json | jq . > corpus2/luontola/retrolambda/url2body.json
python3 url2body.py corpus2/airbnb/DeepLinkDispatch/api.json | jq . > corpus2/airbnb/DeepLinkDispatch/url2body.json
python3 url2body.py corpus2/looly/hutool/api.json | jq . > corpus2/looly/hutool/url2body.json
python3 url2body.py corpus2/chewiebug/GCViewer/api.json | jq . > corpus2/chewiebug/GCViewer/url2body.json
python3 url2body.py corpus2/NLPchina/elasticsearch-sql/api.json | jq . > corpus2/NLPchina/elasticsearch-sql/url2body.json
python3 url2body.py corpus2/haifengl/smile/api.json | jq . > corpus2/haifengl/smile/url2body.json
python3 url2body.py corpus2/Prototik/HoloEverywhere/api.json | jq . > corpus2/Prototik/HoloEverywhere/url2body.json
python3 url2body.py corpus2/drakeet/MultiType/api.json | jq . > corpus2/drakeet/MultiType/url2body.json
python3 url2body.py corpus2/Karumi/Dexter/api.json | jq . > corpus2/Karumi/Dexter/url2body.json
python3 url2body.py corpus2/requery/requery/api.json | jq . > corpus2/requery/requery/url2body.json
python3 url2body.py corpus2/code-troopers/android-betterpickers/api.json | jq . > corpus2/code-troopers/android-betterpickers/url2body.json
python3 url2body.py corpus2/KeepSafe/TapTargetView/api.json | jq . > corpus2/KeepSafe/TapTargetView/url2body.json
python3 url2body.py corpus2/yui/yuicompressor/api.json | jq . > corpus2/yui/yuicompressor/url2body.json
python3 url2body.py corpus2/kickstarter/android-oss/api.json | jq . > corpus2/kickstarter/android-oss/url2body.json
python3 url2body.py corpus2/yigit/android-priority-jobqueue/api.json | jq . > corpus2/yigit/android-priority-jobqueue/url2body.json
python3 url2body.py corpus2/google/error-prone/api.json | jq . > corpus2/google/error-prone/url2body.json
python3 url2body.py corpus2/mybatis/generator/api.json | jq . > corpus2/mybatis/generator/url2body.json
python3 url2body.py corpus2/cymcsg/UltimateRecyclerView/api.json | jq . > corpus2/cymcsg/UltimateRecyclerView/url2body.json
python3 url2body.py corpus2/bingoogolapple/BGASwipeBackLayout-Android/api.json | jq . > corpus2/bingoogolapple/BGASwipeBackLayout-Android/url2body.json
python3 url2body.py corpus2/square/dagger/api.json | jq . > corpus2/square/dagger/url2body.json
python3 url2body.py corpus2/google/truth/api.json | jq . > corpus2/google/truth/url2body.json
python3 url2body.py corpus2/koral--/android-gif-drawable/api.json | jq . > corpus2/koral--/android-gif-drawable/url2body.json
python3 url2body.py corpus2/termux/termux-app/api.json | jq . > corpus2/termux/termux-app/url2body.json
python3 url2body.py corpus2/mcxiaoke/packer-ng-plugin/api.json | jq . > corpus2/mcxiaoke/packer-ng-plugin/url2body.json
python3 url2body.py corpus2/amlcurran/ShowcaseView/api.json | jq . > corpus2/amlcurran/ShowcaseView/url2body.json
python3 url2body.py corpus2/react-community/react-native-image-picker/api.json | jq . > corpus2/react-community/react-native-image-picker/url2body.json
python3 url2body.py corpus2/weibocom/motan/api.json | jq . > corpus2/weibocom/motan/url2body.json
python3 url2body.py corpus2/alibaba/freeline/api.json | jq . > corpus2/alibaba/freeline/url2body.json
python3 url2body.py corpus2/oblac/jodd/api.json | jq . > corpus2/oblac/jodd/url2body.json
python3 url2body.py corpus2/tbruyelle/RxPermissions/api.json | jq . > corpus2/tbruyelle/RxPermissions/url2body.json
python3 url2body.py corpus2/alipay/sofa-boot/api.json | jq . > corpus2/alipay/sofa-boot/url2body.json
python3 url2body.py corpus2/apache/incubator-dubbo-spring-boot-project/api.json | jq . > corpus2/apache/incubator-dubbo-spring-boot-project/url2body.json
python3 url2body.py corpus2/vespa-engine/vespa/api.json | jq . > corpus2/vespa-engine/vespa/url2body.json
python3 url2body.py corpus2/bluelinelabs/Conductor/api.json | jq . > corpus2/bluelinelabs/Conductor/url2body.json
python3 url2body.py corpus2/square/android-times-square/api.json | jq . > corpus2/square/android-times-square/url2body.json
python3 url2body.py corpus2/Bilibili/DanmakuFlameMaster/api.json | jq . > corpus2/Bilibili/DanmakuFlameMaster/url2body.json
python3 url2body.py corpus2/facebook/litho/api.json | jq . > corpus2/facebook/litho/url2body.json
python3 url2body.py corpus2/square/moshi/api.json | jq . > corpus2/square/moshi/url2body.json
python3 url2body.py corpus2/lisawray/groupie/api.json | jq . > corpus2/lisawray/groupie/url2body.json
python3 url2body.py corpus2/JakeWharton/ActionBarSherlock/api.json | jq . > corpus2/JakeWharton/ActionBarSherlock/url2body.json
python3 url2body.py corpus2/rest-assured/rest-assured/api.json | jq . > corpus2/rest-assured/rest-assured/url2body.json
python3 url2body.py corpus2/lettuce-io/lettuce-core/api.json | jq . > corpus2/lettuce-io/lettuce-core/url2body.json
python3 url2body.py corpus2/Netflix/ribbon/api.json | jq . > corpus2/Netflix/ribbon/url2body.json
python3 url2body.py corpus2/google/volley/api.json | jq . > corpus2/google/volley/url2body.json
python3 url2body.py corpus2/LawnchairLauncher/Lawnchair/api.json | jq . > corpus2/LawnchairLauncher/Lawnchair/url2body.json
python3 url2body.py corpus2/NanoHttpd/nanohttpd/api.json | jq . > corpus2/NanoHttpd/nanohttpd/url2body.json
python3 url2body.py corpus2/alibaba/arthas/api.json | jq . > corpus2/alibaba/arthas/url2body.json
python3 url2body.py corpus2/gephi/gephi/api.json | jq . > corpus2/gephi/gephi/url2body.json
python3 url2body.py corpus2/DylanVann/react-native-fast-image/api.json | jq . > corpus2/DylanVann/react-native-fast-image/url2body.json
python3 url2body.py corpus2/firebase/quickstart-android/api.json | jq . > corpus2/firebase/quickstart-android/url2body.json
python3 url2body.py corpus2/json-path/JsonPath/api.json | jq . > corpus2/json-path/JsonPath/url2body.json
python3 url2body.py corpus2/google/physical-web/api.json | jq . > corpus2/google/physical-web/url2body.json
python3 url2body.py corpus2/lightbend/config/api.json | jq . > corpus2/lightbend/config/url2body.json
python3 url2body.py corpus2/spring-projects/spring-security-oauth/api.json | jq . > corpus2/spring-projects/spring-security-oauth/url2body.json
python3 url2body.py corpus2/iBotPeaches/Apktool/api.json | jq . > corpus2/iBotPeaches/Apktool/url2body.json
python3 url2body.py corpus2/reark/reark/api.json | jq . > corpus2/reark/reark/url2body.json
python3 url2body.py corpus2/spring-projects/spring-petclinic/api.json | jq . > corpus2/spring-projects/spring-petclinic/url2body.json
python3 url2body.py corpus2/square/javapoet/api.json | jq . > corpus2/square/javapoet/url2body.json
python3 url2body.py corpus2/cats-oss/android-gpuimage/api.json | jq . > corpus2/cats-oss/android-gpuimage/url2body.json
python3 url2body.py corpus2/moezbhatti/qksms/api.json | jq . > corpus2/moezbhatti/qksms/url2body.json
python3 url2body.py corpus2/jwtk/jjwt/api.json | jq . > corpus2/jwtk/jjwt/url2body.json
python3 url2body.py corpus2/chrisjenx/Calligraphy/api.json | jq . > corpus2/chrisjenx/Calligraphy/url2body.json
python3 url2body.py corpus2/codecentric/spring-boot-admin/api.json | jq . > corpus2/codecentric/spring-boot-admin/url2body.json
python3 url2body.py corpus2/eirslett/frontend-maven-plugin/api.json | jq . > corpus2/eirslett/frontend-maven-plugin/url2body.json
python3 url2body.py corpus2/spring-projects/spring-data-examples/api.json | jq . > corpus2/spring-projects/spring-data-examples/url2body.json
python3 url2body.py corpus2/bytedeco/javacv/api.json | jq . > corpus2/bytedeco/javacv/url2body.json
python3 url2body.py corpus2/guardianproject/haven/api.json | jq . > corpus2/guardianproject/haven/url2body.json
python3 url2body.py corpus2/alibaba/Sentinel/api.json | jq . > corpus2/alibaba/Sentinel/url2body.json
python3 url2body.py corpus2/MyCATApache/Mycat-Server/api.json | jq . > corpus2/MyCATApache/Mycat-Server/url2body.json
python3 url2body.py corpus2/scribejava/scribejava/api.json | jq . > corpus2/scribejava/scribejava/url2body.json
python3 url2body.py corpus2/parse-community/Parse-SDK-Android/api.json | jq . > corpus2/parse-community/Parse-SDK-Android/url2body.json
python3 url2body.py corpus2/Netflix/archaius/api.json | jq . > corpus2/Netflix/archaius/url2body.json
python3 url2body.py corpus2/prolificinteractive/material-calendarview/api.json | jq . > corpus2/prolificinteractive/material-calendarview/url2body.json
python3 url2body.py corpus2/web3j/web3j/api.json | jq . > corpus2/web3j/web3j/url2body.json
python3 url2body.py corpus2/Alluxio/alluxio/api.json | jq . > corpus2/Alluxio/alluxio/url2body.json
python3 url2body.py corpus2/k9mail/k-9/api.json | jq . > corpus2/k9mail/k-9/url2body.json
python3 url2body.py corpus2/uber/NullAway/api.json | jq . > corpus2/uber/NullAway/url2body.json
python3 url2body.py corpus2/rzwitserloot/lombok/api.json | jq . > corpus2/rzwitserloot/lombok/url2body.json
python3 url2body.py corpus2/elasticjob/elastic-job-lite/api.json | jq . > corpus2/elasticjob/elastic-job-lite/url2body.json
python3 url2body.py corpus2/languagetool-org/languagetool/api.json | jq . > corpus2/languagetool-org/languagetool/url2body.json
python3 url2body.py corpus2/TangoAgency/material-intro-screen/api.json | jq . > corpus2/TangoAgency/material-intro-screen/url2body.json
python3 url2body.py corpus2/alibaba/canal/api.json | jq . > corpus2/alibaba/canal/url2body.json
python3 url2body.py corpus2/Freeyourgadget/Gadgetbridge/api.json | jq . > corpus2/Freeyourgadget/Gadgetbridge/url2body.json
python3 url2body.py corpus2/chennaione/sugar/api.json | jq . > corpus2/chennaione/sugar/url2body.json
python3 url2body.py corpus2/katzer/cordova-plugin-local-notifications/api.json | jq . > corpus2/katzer/cordova-plugin-local-notifications/url2body.json
python3 url2body.py corpus2/apache/cordova-android/api.json | jq . > corpus2/apache/cordova-android/url2body.json
python3 url2body.py corpus2/k0shk0sh/FastHub/api.json | jq . > corpus2/k0shk0sh/FastHub/url2body.json
python3 url2body.py corpus2/redisson/redisson/api.json | jq . > corpus2/redisson/redisson/url2body.json
python3 url2body.py corpus2/tronprotocol/java-tron/api.json | jq . > corpus2/tronprotocol/java-tron/url2body.json
python3 url2body.py corpus2/spotify/helios/api.json | jq . > corpus2/spotify/helios/url2body.json
python3 url2body.py corpus2/apache/incubator-pinot/api.json | jq . > corpus2/apache/incubator-pinot/url2body.json
python3 url2body.py corpus2/asLody/VirtualApp/api.json | jq . > corpus2/asLody/VirtualApp/url2body.json
python3 url2body.py corpus2/stleary/JSON-java/api.json | jq . > corpus2/stleary/JSON-java/url2body.json
python3 url2body.py corpus2/powermock/powermock/api.json | jq . > corpus2/powermock/powermock/url2body.json
python3 url2body.py corpus2/resilience4j/resilience4j/api.json | jq . > corpus2/resilience4j/resilience4j/url2body.json
python3 url2body.py corpus2/traccar/traccar/api.json | jq . > corpus2/traccar/traccar/url2body.json
python3 url2body.py corpus2/bitcoinj/bitcoinj/api.json | jq . > corpus2/bitcoinj/bitcoinj/url2body.json
python3 url2body.py corpus2/oracle/graal/api.json | jq . > corpus2/oracle/graal/url2body.json
python3 url2body.py corpus2/google/auto/api.json | jq . > corpus2/google/auto/url2body.json
python3 url2body.py corpus2/jOOQ/jOOQ/api.json | jq . > corpus2/jOOQ/jOOQ/url2body.json
python3 url2body.py corpus2/google/data-transfer-project/api.json | jq . > corpus2/google/data-transfer-project/url2body.json
python3 url2body.py corpus2/antlr/antlr4/api.json | jq . > corpus2/antlr/antlr4/url2body.json
python3 url2body.py corpus2/crate/crate/api.json | jq . > corpus2/crate/crate/url2body.json
python3 url2body.py corpus2/pushtorefresh/storio/api.json | jq . > corpus2/pushtorefresh/storio/url2body.json
python3 url2body.py corpus2/jMonkeyEngine/jmonkeyengine/api.json | jq . > corpus2/jMonkeyEngine/jmonkeyengine/url2body.json
python3 url2body.py corpus2/Netflix/eureka/api.json | jq . > corpus2/Netflix/eureka/url2body.json
python3 url2body.py corpus2/square/wire/api.json | jq . > corpus2/square/wire/url2body.json
python3 url2body.py corpus2/querydsl/querydsl/api.json | jq . > corpus2/querydsl/querydsl/url2body.json
python3 url2body.py corpus2/aws/aws-sdk-java/api.json | jq . > corpus2/aws/aws-sdk-java/url2body.json
python3 url2body.py corpus2/dbeaver/dbeaver/api.json | jq . > corpus2/dbeaver/dbeaver/url2body.json
python3 url2body.py corpus2/Wizcorp/phonegap-facebook-plugin/api.json | jq . > corpus2/Wizcorp/phonegap-facebook-plugin/url2body.json
python3 url2body.py corpus2/NYTimes/Store/api.json | jq . > corpus2/NYTimes/Store/url2body.json
python3 url2body.py corpus2/facebook/buck/api.json | jq . > corpus2/facebook/buck/url2body.json
python3 url2body.py corpus2/reactive-streams/reactive-streams-jvm/api.json | jq . > corpus2/reactive-streams/reactive-streams-jvm/url2body.json
python3 url2body.py corpus2/TooTallNate/Java-WebSocket/api.json | jq . > corpus2/TooTallNate/Java-WebSocket/url2body.json
python3 url2body.py corpus2/AsyncHttpClient/async-http-client/api.json | jq . > corpus2/AsyncHttpClient/async-http-client/url2body.json
python3 url2body.py corpus2/java-native-access/jna/api.json | jq . > corpus2/java-native-access/jna/url2body.json
python3 url2body.py corpus2/airbnb/epoxy/api.json | jq . > corpus2/airbnb/epoxy/url2body.json
python3 url2body.py corpus2/Microsoft/malmo/api.json | jq . > corpus2/Microsoft/malmo/url2body.json
python3 url2body.py corpus2/FasterXML/jackson-databind/api.json | jq . > corpus2/FasterXML/jackson-databind/url2body.json
python3 url2body.py corpus2/sparklemotion/nokogiri/api.json | jq . > corpus2/sparklemotion/nokogiri/url2body.json
python3 url2body.py corpus2/mikepenz/FastAdapter/api.json | jq . > corpus2/mikepenz/FastAdapter/url2body.json
python3 url2body.py corpus2/perwendel/spark/api.json | jq . > corpus2/perwendel/spark/url2body.json
python3 url2body.py corpus2/OpenFeign/feign/api.json | jq . > corpus2/OpenFeign/feign/url2body.json
python3 url2body.py corpus2/dropwizard/metrics/api.json | jq . > corpus2/dropwizard/metrics/url2body.json
python3 url2body.py corpus2/thinkaurelius/titan/api.json | jq . > corpus2/thinkaurelius/titan/url2body.json
python3 url2body.py corpus2/stephanenicolas/robospice/api.json | jq . > corpus2/stephanenicolas/robospice/url2body.json
python3 url2body.py corpus2/zaproxy/zaproxy/api.json | jq . > corpus2/zaproxy/zaproxy/url2body.json
python3 url2body.py corpus2/bisq-network/bisq/api.json | jq . > corpus2/bisq-network/bisq/url2body.json
python3 url2body.py corpus2/JanusGraph/janusgraph/api.json | jq . > corpus2/JanusGraph/janusgraph/url2body.json
python3 url2body.py corpus2/react-native-community/react-native-video/api.json | jq . > corpus2/react-native-community/react-native-video/url2body.json
python3 url2body.py corpus2/AltBeacon/android-beacon-library/api.json | jq . > corpus2/AltBeacon/android-beacon-library/url2body.json
python3 url2body.py corpus2/Atmosphere/atmosphere/api.json | jq . > corpus2/Atmosphere/atmosphere/url2body.json
python3 url2body.py corpus2/apache/rocketmq/api.json | jq . > corpus2/apache/rocketmq/url2body.json
python3 url2body.py corpus2/kabouzeid/Phonograph/api.json | jq . > corpus2/kabouzeid/Phonograph/url2body.json
python3 url2body.py corpus2/OpenTSDB/opentsdb/api.json | jq . > corpus2/OpenTSDB/opentsdb/url2body.json
python3 url2body.py corpus2/react-native-community/react-native-svg/api.json | jq . > corpus2/react-native-community/react-native-svg/url2body.json
python3 url2body.py corpus2/TeamAmaze/AmazeFileManager/api.json | jq . > corpus2/TeamAmaze/AmazeFileManager/url2body.json
python3 url2body.py corpus2/junit-team/junit4/api.json | jq . > corpus2/junit-team/junit4/url2body.json
python3 url2body.py corpus2/CellularPrivacy/Android-IMSI-Catcher-Detector/api.json | jq . > corpus2/CellularPrivacy/Android-IMSI-Catcher-Detector/url2body.json
python3 url2body.py corpus2/react-native-community/react-native-camera/api.json | jq . > corpus2/react-native-community/react-native-camera/url2body.json
python3 url2body.py corpus2/azkaban/azkaban/api.json | jq . > corpus2/azkaban/azkaban/url2body.json
python3 url2body.py corpus2/spring-projects/spring-security/api.json | jq . > corpus2/spring-projects/spring-security/url2body.json
python3 url2body.py corpus2/rstudio/rstudio/api.json | jq . > corpus2/rstudio/rstudio/url2body.json
python3 url2body.py corpus2/Activiti/Activiti/api.json | jq . > corpus2/Activiti/Activiti/url2body.json
python3 url2body.py corpus2/flyway/flyway/api.json | jq . > corpus2/flyway/flyway/url2body.json
python3 url2body.py corpus2/siacs/Conversations/api.json | jq . > corpus2/siacs/Conversations/url2body.json
python3 url2body.py corpus2/go-lang-plugin-org/go-lang-idea-plugin/api.json | jq . > corpus2/go-lang-plugin-org/go-lang-idea-plugin/url2body.json
python3 url2body.py corpus2/openhab/openhab1-addons/api.json | jq . > corpus2/openhab/openhab1-addons/url2body.json
python3 url2body.py corpus2/spring-cloud/spring-cloud-netflix/api.json | jq . > corpus2/spring-cloud/spring-cloud-netflix/url2body.json
python3 url2body.py corpus2/spockframework/spock/api.json | jq . > corpus2/spockframework/spock/url2body.json
python3 url2body.py corpus2/testcontainers/testcontainers-java/api.json | jq . > corpus2/testcontainers/testcontainers-java/url2body.json
python3 url2body.py corpus2/AntennaPod/AntennaPod/api.json | jq . > corpus2/AntennaPod/AntennaPod/url2body.json
python3 url2body.py corpus2/ethereum/ethereumj/api.json | jq . > corpus2/ethereum/ethereumj/url2body.json
python3 url2body.py corpus2/graphql-java/graphql-java/api.json | jq . > corpus2/graphql-java/graphql-java/url2body.json
python3 url2body.py corpus2/xetorthio/jedis/api.json | jq . > corpus2/xetorthio/jedis/url2body.json
python3 url2body.py corpus2/dropwizard/dropwizard/api.json | jq . > corpus2/dropwizard/dropwizard/url2body.json
python3 url2body.py corpus2/robolectric/robolectric/api.json | jq . > corpus2/robolectric/robolectric/url2body.json
python3 url2body.py corpus2/springfox/springfox/api.json | jq . > corpus2/springfox/springfox/url2body.json
python3 url2body.py corpus2/TeamNewPipe/NewPipe/api.json | jq . > corpus2/TeamNewPipe/NewPipe/url2body.json
python3 url2body.py corpus2/pmd/pmd/api.json | jq . > corpus2/pmd/pmd/url2body.json
python3 url2body.py corpus2/processing/processing/api.json | jq . > corpus2/processing/processing/url2body.json
python3 url2body.py corpus2/confluentinc/ksql/api.json | jq . > corpus2/confluentinc/ksql/url2body.json
python3 url2body.py corpus2/knowm/XChange/api.json | jq . > corpus2/knowm/XChange/url2body.json
python3 url2body.py corpus2/swagger-api/swagger-core/api.json | jq . > corpus2/swagger-api/swagger-core/url2body.json
python3 url2body.py corpus2/mockito/mockito/api.json | jq . > corpus2/mockito/mockito/url2body.json
python3 url2body.py corpus2/reactor/reactor-core/api.json | jq . > corpus2/reactor/reactor-core/url2body.json
python3 url2body.py corpus2/grpc/grpc-java/api.json | jq . > corpus2/grpc/grpc-java/url2body.json
python3 url2body.py corpus2/apache/incubator-skywalking/api.json | jq . > corpus2/apache/incubator-skywalking/url2body.json
python3 url2body.py corpus2/jhy/jsoup/api.json | jq . > corpus2/jhy/jsoup/url2body.json
python3 url2body.py corpus2/sharding-sphere/sharding-sphere/api.json | jq . > corpus2/sharding-sphere/sharding-sphere/url2body.json
python3 url2body.py corpus2/javaparser/javaparser/api.json | jq . > corpus2/javaparser/javaparser/url2body.json
python3 url2body.py corpus2/vavr-io/vavr/api.json | jq . > corpus2/vavr-io/vavr/url2body.json
python3 url2body.py corpus2/firebase/FirebaseUI-Android/api.json | jq . > corpus2/firebase/FirebaseUI-Android/url2body.json
python3 url2body.py corpus2/MinecraftForge/MinecraftForge/api.json | jq . > corpus2/MinecraftForge/MinecraftForge/url2body.json
python3 url2body.py corpus2/apache/pulsar/api.json | jq . > corpus2/apache/pulsar/url2body.json
python3 url2body.py corpus2/brianfrankcooper/YCSB/api.json | jq . > corpus2/brianfrankcooper/YCSB/url2body.json
python3 url2body.py corpus2/bigbluebutton/bigbluebutton/api.json | jq . > corpus2/bigbluebutton/bigbluebutton/url2body.json
python3 url2body.py corpus2/apache/incubator-heron/api.json | jq . > corpus2/apache/incubator-heron/url2body.json
python3 url2body.py corpus2/GoogleContainerTools/jib/api.json | jq . > corpus2/GoogleContainerTools/jib/url2body.json
python3 url2body.py corpus2/gocd/gocd/api.json | jq . > corpus2/gocd/gocd/url2body.json
python3 url2body.py corpus2/eclipse/jetty.project/api.json | jq . > corpus2/eclipse/jetty.project/url2body.json
python3 url2body.py corpus2/naver/pinpoint/api.json | jq . > corpus2/naver/pinpoint/url2body.json
python3 url2body.py corpus2/owncloud/android/api.json | jq . > corpus2/owncloud/android/url2body.json
python3 url2body.py corpus2/hazelcast/hazelcast/api.json | jq . > corpus2/hazelcast/hazelcast/url2body.json
python3 url2body.py corpus2/checkstyle/checkstyle/api.json | jq . > corpus2/checkstyle/checkstyle/url2body.json
python3 url2body.py corpus2/eclipse/che/api.json | jq . > corpus2/eclipse/che/url2body.json
python3 url2body.py corpus2/twosigma/beakerx/api.json | jq . > corpus2/twosigma/beakerx/url2body.json
python3 url2body.py corpus2/wordpress-mobile/WordPress-Android/api.json | jq . > corpus2/wordpress-mobile/WordPress-Android/url2body.json
