python3 url2body.py corpus/wix/react-native-navigation/api.json | jq .> corpus/wix/react-native-navigation/url2body.json
python3 url2body.py corpus/HannahMitt/HomeMirror/api.json | jq .> corpus/HannahMitt/HomeMirror/url2body.json
python3 url2body.py corpus/iluwatar/java-design-patterns/api.json | jq .> corpus/iluwatar/java-design-patterns/url2body.json
python3 url2body.py corpus/spring-projects/spring-boot/api.json | jq .> corpus/spring-projects/spring-boot/url2body.json
python3 url2body.py corpus/spring-projects/spring-framework/api.json | jq .> corpus/spring-projects/spring-framework/url2body.json
python3 url2body.py corpus/navasmdc/MaterialDesignLibrary/api.json | jq .> corpus/navasmdc/MaterialDesignLibrary/url2body.json
python3 url2body.py corpus/DrKLO/Telegram/api.json | jq .> corpus/DrKLO/Telegram/url2body.json
python3 url2body.py corpus/florent37/MaterialViewPager/api.json | jq .> corpus/florent37/MaterialViewPager/url2body.json
python3 url2body.py corpus/Konloch/bytecode-viewer/api.json | jq .> corpus/Konloch/bytecode-viewer/url2body.json
python3 url2body.py corpus/nostra13/Android-Universal-Image-Loader/api.json | jq .> corpus/nostra13/Android-Universal-Image-Loader/url2body.json
python3 url2body.py corpus/scwang90/SmartRefreshLayout/api.json | jq .> corpus/scwang90/SmartRefreshLayout/url2body.json
python3 url2body.py corpus/zxing/zxing/api.json | jq .> corpus/zxing/zxing/url2body.json
python3 url2body.py corpus/wasabeef/recyclerview-animators/api.json | jq .> corpus/wasabeef/recyclerview-animators/url2body.json
python3 url2body.py corpus/signalapp/Signal-Android/api.json | jq .> corpus/signalapp/Signal-Android/url2body.json
python3 url2body.py corpus/ReactiveX/RxAndroid/api.json | jq .> corpus/ReactiveX/RxAndroid/url2body.json
python3 url2body.py corpus/ReactiveX/RxJava/api.json | jq .> corpus/ReactiveX/RxJava/url2body.json
python3 url2body.py corpus/permissions-dispatcher/PermissionsDispatcher/api.json | jq .> corpus/permissions-dispatcher/PermissionsDispatcher/url2body.json
python3 url2body.py corpus/prestodb/presto/api.json | jq .> corpus/prestodb/presto/url2body.json
python3 url2body.py corpus/Tencent/tinker/api.json | jq .> corpus/Tencent/tinker/url2body.json
python3 url2body.py corpus/Tencent/VasSonic/api.json | jq .> corpus/Tencent/VasSonic/url2body.json
python3 url2body.py corpus/elastic/elasticsearch/api.json | jq .> corpus/elastic/elasticsearch/url2body.json
python3 url2body.py corpus/android10/Android-CleanArchitecture/api.json | jq .> corpus/android10/Android-CleanArchitecture/url2body.json
python3 url2body.py corpus/PhilJay/MPAndroidChart/api.json | jq .> corpus/PhilJay/MPAndroidChart/url2body.json
python3 url2body.py corpus/crossoverJie/Java-Interview/api.json | jq .> corpus/crossoverJie/Java-Interview/url2body.json
python3 url2body.py corpus/jenkinsci/jenkins/api.json | jq .> corpus/jenkinsci/jenkins/url2body.json
python3 url2body.py corpus/afollestad/material-dialogs/api.json | jq .> corpus/afollestad/material-dialogs/url2body.json
python3 url2body.py corpus/Bigkoo/Android-PickerView/api.json | jq .> corpus/Bigkoo/Android-PickerView/url2body.json
python3 url2body.py corpus/eclipse/vert.x/api.json | jq .> corpus/eclipse/vert.x/url2body.json
python3 url2body.py corpus/winterbe/java8-tutorial/api.json | jq .> corpus/winterbe/java8-tutorial/url2body.json
python3 url2body.py corpus/netty/netty/api.json | jq .> corpus/netty/netty/url2body.json
python3 url2body.py corpus/airbnb/lottie-android/api.json | jq .> corpus/airbnb/lottie-android/url2body.json
python3 url2body.py corpus/libgdx/libgdx/api.json | jq .> corpus/libgdx/libgdx/url2body.json
python3 url2body.py corpus/hdodenhof/CircleImageView/api.json | jq .> corpus/hdodenhof/CircleImageView/url2body.json
python3 url2body.py corpus/chrisbanes/cheesesquare/api.json | jq .> corpus/chrisbanes/cheesesquare/url2body.json
python3 url2body.py corpus/chrisbanes/Android-PullToRefresh/api.json | jq .> corpus/chrisbanes/Android-PullToRefresh/url2body.json
python3 url2body.py corpus/chrisbanes/PhotoView/api.json | jq .> corpus/chrisbanes/PhotoView/url2body.json
python3 url2body.py corpus/alibaba/fastjson/api.json | jq .> corpus/alibaba/fastjson/url2body.json
python3 url2body.py corpus/alibaba/druid/api.json | jq .> corpus/alibaba/druid/url2body.json
python3 url2body.py corpus/alibaba/vlayout/api.json | jq .> corpus/alibaba/vlayout/url2body.json
python3 url2body.py corpus/LMAX-Exchange/disruptor/api.json | jq .> corpus/LMAX-Exchange/disruptor/url2body.json
python3 url2body.py corpus/shuzheng/zheng/api.json | jq .> corpus/shuzheng/zheng/url2body.json
python3 url2body.py corpus/pockethub/PocketHub/api.json | jq .> corpus/pockethub/PocketHub/url2body.json
python3 url2body.py corpus/perwendel/spark/api.json | jq .> corpus/perwendel/spark/url2body.json
python3 url2body.py corpus/apl-devs/AppIntro/api.json | jq .> corpus/apl-devs/AppIntro/url2body.json
python3 url2body.py corpus/lgvalle/Material-Animations/api.json | jq .> corpus/lgvalle/Material-Animations/url2body.json
python3 url2body.py corpus/Netflix/Hystrix/api.json | jq .> corpus/Netflix/Hystrix/url2body.json
python3 url2body.py corpus/hankcs/HanLP/api.json | jq .> corpus/hankcs/HanLP/url2body.json
python3 url2body.py corpus/google/guava/api.json | jq .> corpus/google/guava/url2body.json
python3 url2body.py corpus/google/iosched/api.json | jq .> corpus/google/iosched/url2body.json
python3 url2body.py corpus/google/gson/api.json | jq .> corpus/google/gson/url2body.json
python3 url2body.py corpus/81813780/AVLoadingIndicatorView/api.json | jq .> corpus/81813780/AVLoadingIndicatorView/url2body.json
python3 url2body.py corpus/mikepenz/MaterialDrawer/api.json | jq .> corpus/mikepenz/MaterialDrawer/url2body.json
python3 url2body.py corpus/daimajia/AndroidViewAnimations/api.json | jq .> corpus/daimajia/AndroidViewAnimations/url2body.json
python3 url2body.py corpus/daimajia/AndroidSwipeLayout/api.json | jq .> corpus/daimajia/AndroidSwipeLayout/url2body.json
python3 url2body.py corpus/skylot/jadx/api.json | jq .> corpus/skylot/jadx/url2body.json
python3 url2body.py corpus/CymChad/BaseRecyclerViewAdapterHelper/api.json | jq .> corpus/CymChad/BaseRecyclerViewAdapterHelper/url2body.json
python3 url2body.py corpus/chrisjenx/Calligraphy/api.json | jq .> corpus/chrisjenx/Calligraphy/url2body.json
python3 url2body.py corpus/nathanmarz/storm/api.json | jq .> corpus/nathanmarz/storm/url2body.json
python3 url2body.py corpus/Curzibn/Luban/api.json | jq .> corpus/Curzibn/Luban/url2body.json
python3 url2body.py corpus/Blankj/AndroidUtilCode/api.json | jq .> corpus/Blankj/AndroidUtilCode/url2body.json
python3 url2body.py corpus/umano/AndroidSlidingUpPanel/api.json | jq .> corpus/umano/AndroidSlidingUpPanel/url2body.json
python3 url2body.py corpus/Yalantis/uCrop/api.json | jq .> corpus/Yalantis/uCrop/url2body.json
python3 url2body.py corpus/JakeWharton/butterknife/api.json | jq .> corpus/JakeWharton/butterknife/url2body.json
python3 url2body.py corpus/JakeWharton/RxBinding/api.json | jq .> corpus/JakeWharton/RxBinding/url2body.json
python3 url2body.py corpus/JakeWharton/ViewPagerIndicator/api.json | jq .> corpus/JakeWharton/ViewPagerIndicator/url2body.json
python3 url2body.py corpus/bumptech/glide/api.json | jq .> corpus/bumptech/glide/url2body.json
python3 url2body.py corpus/jfeinstein10/SlidingMenu/api.json | jq .> corpus/jfeinstein10/SlidingMenu/url2body.json
python3 url2body.py corpus/zhihu/Matisse/api.json | jq .> corpus/zhihu/Matisse/url2body.json
python3 url2body.py corpus/ksoichiro/Android-ObservableScrollView/api.json | jq .> corpus/ksoichiro/Android-ObservableScrollView/url2body.json
python3 url2body.py corpus/androidannotations/androidannotations/api.json | jq .> corpus/androidannotations/androidannotations/url2body.json
python3 url2body.py corpus/roughike/BottomBar/api.json | jq .> corpus/roughike/BottomBar/url2body.json
python3 url2body.py corpus/jeasonlzy/okhttp-OkGo/api.json | jq .> corpus/jeasonlzy/okhttp-OkGo/url2body.json
python3 url2body.py corpus/orhanobut/logger/api.json | jq .> corpus/orhanobut/logger/url2body.json
python3 url2body.py corpus/nickbutcher/plaid/api.json | jq .> corpus/nickbutcher/plaid/url2body.json
python3 url2body.py corpus/liaohuqiu/android-Ultra-Pull-To-Refresh/api.json | jq .> corpus/liaohuqiu/android-Ultra-Pull-To-Refresh/url2body.json
python3 url2body.py corpus/realm/realm-java/api.json | jq .> corpus/realm/realm-java/url2body.json
python3 url2body.py corpus/openzipkin/zipkin/api.json | jq .> corpus/openzipkin/zipkin/url2body.json
python3 url2body.py corpus/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/api.json | jq .> corpus/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/url2body.json
python3 url2body.py corpus/kdn251/interviews/api.json | jq .> corpus/kdn251/interviews/url2body.json
python3 url2body.py corpus/loopj/android-async-http/api.json | jq .> corpus/loopj/android-async-http/url2body.json
python3 url2body.py corpus/facebook/fresco/api.json | jq .> corpus/facebook/fresco/url2body.json
python3 url2body.py corpus/facebook/stetho/api.json | jq .> corpus/facebook/stetho/url2body.json
python3 url2body.py corpus/aosp-mirror/platform_frameworks_base/api.json | jq .> corpus/aosp-mirror/platform_frameworks_base/url2body.json
python3 url2body.py corpus/greenrobot/EventBus/api.json | jq .> corpus/greenrobot/EventBus/url2body.json
python3 url2body.py corpus/greenrobot/greenDAO/api.json | jq .> corpus/greenrobot/greenDAO/url2body.json
python3 url2body.py corpus/mybatis/mybatis-3/api.json | jq .> corpus/mybatis/mybatis-3/url2body.json
python3 url2body.py corpus/apache/kafka/api.json | jq .> corpus/apache/kafka/url2body.json
python3 url2body.py corpus/apache/incubator-weex/api.json | jq .> corpus/apache/incubator-weex/url2body.json
python3 url2body.py corpus/apache/hadoop/api.json | jq .> corpus/apache/hadoop/url2body.json
python3 url2body.py corpus/square/retrofit/api.json | jq .> corpus/square/retrofit/url2body.json
python3 url2body.py corpus/square/leakcanary/api.json | jq .> corpus/square/leakcanary/url2body.json
python3 url2body.py corpus/square/okhttp/api.json | jq .> corpus/square/okhttp/url2body.json
python3 url2body.py corpus/square/picasso/api.json | jq .> corpus/square/picasso/url2body.json
